### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="qsar_oral_toxicity",
    dataset_year="2019",
    domain_str="biology & life sciences",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://archive.ics.uci.edu/dataset/508/qsar+oral+toxicity",
    download_description="""
We download the data from the UCI repository and uzip it to a predefined folder. 

mkdir -p local-data-warehouse/qsar_oral_toxicity && \
wget -P local-data-warehouse/qsar_oral_toxicity/ https://archive.ics.uci.edu/static/public/508/qsar+oral+toxicity.zip && \
unzip local-data-warehouse/qsar_oral_toxicity/qsar+oral+toxicity.zip -d local-data-warehouse/qsar_oral_toxicity/ && \
rm local-data-warehouse/qsar_oral_toxicity/qsar+oral+toxicity.zip
""",
    # References
academic_reference_bibtex="""@misc{uci2019qsaroral,
    title        = {QSAR oral toxicity},
    year         = {2019},
    author       = {Unknown},
    howpublished = {UCI Machine Learning Repository},
    url = {https://doi.org/10.24432/C5PS4J},
    }
""",
    academic_reference_bibtex_key="uci2019qsaroral",
    license="CC BY 4.0",
    data_tags=["IID"],
    curation_comments="""
    - We map the original target values to "Yes" and "No" for better readability.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="Toxic",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="Toxic",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_csv(dataset_mold.path / "qsar_oral_toxicity.csv", header=None, sep=";")

target_feature = "Toxic"
df.columns = [f"Attribute {i+1}" for i in range(len(df.columns) - 1)] + [target_feature]
df[target_feature] = df[target_feature].map({"positive": "Yes", "negative": "No"})

# convert to binary type
cat_features = [col for col in df.columns]
df[cat_features] = df[cat_features].astype("category")

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 8,992
Columns: 1025
Use sampling: False (sample size: 8,992)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['Attribute 1', 'Attribute 514', 'Attribute 676', 'Attribute 677', 'Attribute 678', 'Attribute 679', 'Attribute 680', 'Attribute 681', 'Attribute 682', 'Attribute 683']
Rows remaining as candidates after top-10 filter: 8,936 (of 8,992)

#### Duplicate Report
Total duplicate rows: 477 (5.30% of dataset)
Duplicate rows ignoring target: 488 (5.43% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,Attribute 1,Attribute 2,Attribute 3,Attribute 4,Attribute 5,Attribute 6,Attribute 7,Attribute 8,Attribute 9,Attribute 10,Attribute 11,Attribute 12,Attribute 13,Attribute 14,Attribute 15,Attribute 16,Attribute 17,Attribute 18,Attribute 19,Attribute 20,Attribute 21,Attribute 22,Attribute 23,Attribute 24,Attribute 25,Attribute 26,Attribute 27,Attribute 28,Attribute 29,Attribute 30,Attribute 31,Attribute 32,Attribute 33,Attribute 34,Attribute 35,Attribute 36,Attribute 37,Attribute 38,Attribute 39,Attribute 40,Attribute 41,Attribute 42,Attribute 43,Attribute 44,Attribute 45,Attribute 46,Attribute 47,Attribute 48,Attribute 49,Attribute 50,Attribute 51,Attribute 52,Attribute 53,Attribute 54,Attribute 55,Attribute 56,Attribute 57,Attribute 58,Attribute 59,Attribute 60,Attribute 61,Attribute 62,Attribute 63,Attribute 64,Attribute 65,Attribute 66,Attribute 67,Attribute 68,Attribute 69,Attribute 70,Attribute 71,Attribute 72,Attribute 73,Attribute 74,Attribute 75,Attribute 76,Attribute 77,Attribute 78,Attribute 79,Attribute 80,Attribute 81,Attribute 82,Attribute 83,Attribute 84,Attribute 85,Attribute 86,Attribute 87,Attribute 88,Attribute 89,Attribute 90,Attribute 91,Attribute 92,Attribute 93,Attribute 94,Attribute 95,Attribute 96,Attribute 97,Attribute 98,Attribute 99,Attribute 100,Attribute 101,Attribute 102,Attribute 103,Attribute 104,Attribute 105,Attribute 106,Attribute 107,Attribute 108,Attribute 109,Attribute 110,Attribute 111,Attribute 112,Attribute 113,Attribute 114,Attribute 115,Attribute 116,Attribute 117,Attribute 118,Attribute 119,Attribute 120,Attribute 121,Attribute 122,Attribute 123,Attribute 124,Attribute 125,Attribute 126,Attribute 127,Attribute 128,Attribute 129,Attribute 130,Attribute 131,Attribute 132,Attribute 133,Attribute 134,Attribute 135,Attribute 136,Attribute 137,Attribute 138,Attribute 139,Attribute 140,Attribute 141,Attribute 142,Attribute 143,Attribute 144,Attribute 145,Attribute 146,Attribute 147,Attribute 148,Attribute 149,Attribute 150,Attribute 151,Attribute 152,Attribute 153,Attribute 154,Attribute 155,Attribute 156,Attribute 157,Attribute 158,Attribute 159,Attribute 160,Attribute 161,Attribute 162,Attribute 163,Attribute 164,Attribute 165,Attribute 166,Attribute 167,Attribute 168,Attribute 169,Attribute 170,Attribute 171,Attribute 172,Attribute 173,Attribute 174,Attribute 175,Attribute 176,Attribute 177,Attribute 178,Attribute 179,Attribute 180,Attribute 181,Attribute 182,Attribute 183,Attribute 184,Attribute 185,Attribute 186,Attribute 187,Attribute 188,Attribute 189,Attribute 190,Attribute 191,Attribute 192,Attribute 193,Attribute 194,Attribute 195,Attribute 196,Attribute 197,Attribute 198,Attribute 199,Attribute 200,Attribute 201,Attribute 202,Attribute 203,Attribute 204,Attribute 205,Attribute 206,Attribute 207,Attribute 208,Attribute 209,Attribute 210,Attribute 211,Attribute 212,Attribute 213,Attribute 214,Attribute 215,Attribute 216,Attribute 217,Attribute 218,Attribute 219,Attribute 220,Attribute 221,Attribute 222,Attribute 223,Attribute 224,Attribute 225,Attribute 226,Attribute 227,Attribute 228,Attribute 229,Attribute 230,Attribute 231,Attribute 232,Attribute 233,Attribute 234,Attribute 235,Attribute 236,Attribute 237,Attribute 238,Attribute 239,Attribute 240,Attribute 241,Attribute 242,Attribute 243,Attribute 244,Attribute 245,Attribute 246,Attribute 247,Attribute 248,Attribute 249,Attribute 250,Attribute 251,Attribute 252,Attribute 253,Attribute 254,Attribute 255,Attribute 256,Attribute 257,Attribute 258,Attribute 259,Attribute 260,Attribute 261,Attribute 262,Attribute 263,Attribute 264,Attribute 265,Attribute 266,Attribute 267,Attribute 268,Attribute 269,Attribute 270,Attribute 271,Attribute 272,Attribute 273,Attribute 274,Attribute 275,Attribute 276,Attribute 277,Attribute 278,Attribute 279,Attribute 280,Attribute 281,Attribute 282,Attribute 283,Attribute 284,Attribute 285,Attribute 286,Attribute 287,Attribute 288,Attribute 289,Attribute 290,Attribute 291,Attribute 292,Attribute 293,Attribute 294,Attribute 295,Attribute 296,Attribute 297,Attribute 298,Attribute 299,Attribute 300,Attribute 301,Attribute 302,Attribute 303,Attribute 304,Attribute 305,Attribute 306,Attribute 307,Attribute 308,Attribute 309,Attribute 310,Attribute 311,Attribute 312,Attribute 313,Attribute 314,Attribute 315,Attribute 316,Attribute 317,Attribute 318,Attribute 319,Attribute 320,Attribute 321,Attribute 322,Attribute 323,Attribute 324,Attribute 325,Attribute 326,Attribute 327,Attribute 328,Attribute 329,Attribute 330,Attribute 331,Attribute 332,Attribute 333,Attribute 334,Attribute 335,Attribute 336,Attribute 337,Attribute 338,Attribute 339,Attribute 340,Attribute 341,Attribute 342,Attribute 343,Attribute 344,Attribute 345,Attribute 346,Attribute 347,Attribute 348,Attribute 349,Attribute 350,Attribute 351,Attribute 352,Attribute 353,Attribute 354,Attribute 355,Attribute 356,Attribute 357,Attribute 358,Attribute 359,Attribute 360,Attribute 361,Attribute 362,Attribute 363,Attribute 364,Attribute 365,Attribute 366,Attribute 367,Attribute 368,Attribute 369,Attribute 370,Attribute 371,Attribute 372,Attribute 373,Attribute 374,Attribute 375,Attribute 376,Attribute 377,Attribute 378,Attribute 379,Attribute 380,Attribute 381,Attribute 382,Attribute 383,Attribute 384,Attribute 385,Attribute 386,Attribute 387,Attribute 388,Attribute 389,Attribute 390,Attribute 391,Attribute 392,Attribute 393,Attribute 394,Attribute 395,Attribute 396,Attribute 397,Attribute 398,Attribute 399,Attribute 400,Attribute 401,Attribute 402,Attribute 403,Attribute 404,Attribute 405,Attribute 406,Attribute 407,Attribute 408,Attribute 409,Attribute 410,Attribute 411,Attribute 412,Attribute 413,Attribute 414,Attribute 415,Attribute 416,Attribute 417,Attribute 418,Attribute 419,Attribute 420,Attribute 421,Attribute 422,Attribute 423,Attribute 424,Attribute 425,Attribute 426,Attribute 427,Attribute 428,Attribute 429,Attribute 430,Attribute 431,Attribute 432,Attribute 433,Attribute 434,Attribute 435,Attribute 436,Attribute 437,Attribute 438,Attribute 439,Attribute 440,Attribute 441,Attribute 442,Attribute 443,Attribute 444,Attribute 445,Attribute 446,Attribute 447,Attribute 448,Attribute 449,Attribute 450,Attribute 451,Attribute 452,Attribute 453,Attribute 454,Attribute 455,Attribute 456,Attribute 457,Attribute 458,Attribute 459,Attribute 460,Attribute 461,Attribute 462,Attribute 463,Attribute 464,Attribute 465,Attribute 466,Attribute 467,Attribute 468,Attribute 469,Attribute 470,Attribute 471,Attribute 472,Attribute 473,Attribute 474,Attribute 475,Attribute 476,Attribute 477,Attribute 478,Attribute 479,Attribute 480,Attribute 481,Attribute 482,Attribute 483,Attribute 484,Attribute 485,Attribute 486,Attribute 487,Attribute 488,Attribute 489,Attribute 490,Attribute 491,Attribute 492,Attribute 493,Attribute 494,Attribute 495,Attribute 496,Attribute 497,Attribute 498,Attribute 499,Attribute 500,Attribute 501,Attribute 502,Attribute 503,Attribute 504,Attribute 505,Attribute 506,Attribute 507,Attribute 508,Attribute 509,Attribute 510,Attribute 511,Attribute 512,Attribute 513,Attribute 514,Attribute 515,Attribute 516,Attribute 517,Attribute 518,Attribute 519,Attribute 520,Attribute 521,Attribute 522,Attribute 523,Attribute 524,Attribute 525,Attribute 526,Attribute 527,Attribute 528,Attribute 529,Attribute 530,Attribute 531,Attribute 532,Attribute 533,Attribute 534,Attribute 535,Attribute 536,Attribute 537,Attribute 538,Attribute 539,Attribute 540,Attribute 541,Attribute 542,Attribute 543,Attribute 544,Attribute 545,Attribute 546,Attribute 547,Attribute 548,Attribute 549,Attribute 550,Attribute 551,Attribute 552,Attribute 553,Attribute 554,Attribute 555,Attribute 556,Attribute 557,Attribute 558,Attribute 559,Attribute 560,Attribute 561,Attribute 562,Attribute 563,Attribute 564,Attribute 565,Attribute 566,Attribute 567,Attribute 568,Attribute 569,Attribute 570,Attribute 571,Attribute 572,Attribute 573,Attribute 574,Attribute 575,Attribute 576,Attribute 577,Attribute 578,Attribute 579,Attribute 580,Attribute 581,Attribute 582,Attribute 583,Attribute 584,Attribute 585,Attribute 586,Attribute 587,Attribute 588,Attribute 589,Attribute 590,Attribute 591,Attribute 592,Attribute 593,Attribute 594,Attribute 595,Attribute 596,Attribute 597,Attribute 598,Attribute 599,Attribute 600,Attribute 601,Attribute 602,Attribute 603,Attribute 604,Attribute 605,Attribute 606,Attribute 607,Attribute 608,Attribute 609,Attribute 610,Attribute 611,Attribute 612,Attribute 613,Attribute 614,Attribute 615,Attribute 616,Attribute 617,Attribute 618,Attribute 619,Attribute 620,Attribute 621,Attribute 622,Attribute 623,Attribute 624,Attribute 625,Attribute 626,Attribute 627,Attribute 628,Attribute 629,Attribute 630,Attribute 631,Attribute 632,Attribute 633,Attribute 634,Attribute 635,Attribute 636,Attribute 637,Attribute 638,Attribute 639,Attribute 640,Attribute 641,Attribute 642,Attribute 643,Attribute 644,Attribute 645,Attribute 646,Attribute 647,Attribute 648,Attribute 649,Attribute 650,Attribute 651,Attribute 652,Attribute 653,Attribute 654,Attribute 655,Attribute 656,Attribute 657,Attribute 658,Attribute 659,Attribute 660,Attribute 661,Attribute 662,Attribute 663,Attribute 664,Attribute 665,Attribute 666,Attribute 667,Attribute 668,Attribute 669,Attribute 670,Attribute 671,Attribute 672,Attribute 673,Attribute 674,Attribute 675,Attribute 676,Attribute 677,Attribute 678,Attribute 679,Attribute 680,Attribute 681,Attribute 682,Attribute 683,Attribute 684,Attribute 685,Attribute 686,Attribute 687,Attribute 688,Attribute 689,Attribute 690,Attribute 691,Attribute 692,Attribute 693,Attribute 694,Attribute 695,Attribute 696,Attribute 697,Attribute 698,Attribute 699,Attribute 700,Attribute 701,Attribute 702,Attribute 703,Attribute 704,Attribute 705,Attribute 706,Attribute 707,Attribute 708,Attribute 709,Attribute 710,Attribute 711,Attribute 712,Attribute 713,Attribute 714,Attribute 715,Attribute 716,Attribute 717,Attribute 718,Attribute 719,Attribute 720,Attribute 721,Attribute 722,Attribute 723,Attribute 724,Attribute 725,Attribute 726,Attribute 727,Attribute 728,Attribute 729,Attribute 730,Attribute 731,Attribute 732,Attribute 733,Attribute 734,Attribute 735,Attribute 736,Attribute 737,Attribute 738,Attribute 739,Attribute 740,Attribute 741,Attribute 742,Attribute 743,Attribute 744,Attribute 745,Attribute 746,Attribute 747,Attribute 748,Attribute 749,Attribute 750,Attribute 751,Attribute 752,Attribute 753,Attribute 754,Attribute 755,Attribute 756,Attribute 757,Attribute 758,Attribute 759,Attribute 760,Attribute 761,Attribute 762,Attribute 763,Attribute 764,Attribute 765,Attribute 766,Attribute 767,Attribute 768,Attribute 769,Attribute 770,Attribute 771,Attribute 772,Attribute 773,Attribute 774,Attribute 775,Attribute 776,Attribute 777,Attribute 778,Attribute 779,Attribute 780,Attribute 781,Attribute 782,Attribute 783,Attribute 784,Attribute 785,Attribute 786,Attribute 787,Attribute 788,Attribute 789,Attribute 790,Attribute 791,Attribute 792,Attribute 793,Attribute 794,Attribute 795,Attribute 796,Attribute 797,Attribute 798,Attribute 799,Attribute 800,Attribute 801,Attribute 802,Attribute 803,Attribute 804,Attribute 805,Attribute 806,Attribute 807,Attribute 808,Attribute 809,Attribute 810,Attribute 811,Attribute 812,Attribute 813,Attribute 814,Attribute 815,Attribute 816,Attribute 817,Attribute 818,Attribute 819,Attribute 820,Attribute 821,Attribute 822,Attribute 823,Attribute 824,Attribute 825,Attribute 826,Attribute 827,Attribute 828,Attribute 829,Attribute 830,Attribute 831,Attribute 832,Attribute 833,Attribute 834,Attribute 835,Attribute 836,Attribute 837,Attribute 838,Attribute 839,Attribute 840,Attribute 841,Attribute 842,Attribute 843,Attribute 844,Attribute 845,Attribute 846,Attribute 847,Attribute 848,Attribute 849,Attribute 850,Attribute 851,Attribute 852,Attribute 853,Attribute 854,Attribute 855,Attribute 856,Attribute 857,Attribute 858,Attribute 859,Attribute 860,Attribute 861,Attribute 862,Attribute 863,Attribute 864,Attribute 865,Attribute 866,Attribute 867,Attribute 868,Attribute 869,Attribute 870,Attribute 871,Attribute 872,Attribute 873,Attribute 874,Attribute 875,Attribute 876,Attribute 877,Attribute 878,Attribute 879,Attribute 880,Attribute 881,Attribute 882,Attribute 883,Attribute 884,Attribute 885,Attribute 886,Attribute 887,Attribute 888,Attribute 889,Attribute 890,Attribute 891,Attribute 892,Attribute 893,Attribute 894,Attribute 895,Attribute 896,Attribute 897,Attribute 898,Attribute 899,Attribute 900,Attribute 901,Attribute 902,Attribute 903,Attribute 904,Attribute 905,Attribute 906,Attribute 907,Attribute 908,Attribute 909,Attribute 910,Attribute 911,Attribute 912,Attribute 913,Attribute 914,Attribute 915,Attribute 916,Attribute 917,Attribute 918,Attribute 919,Attribute 920,Attribute 921,Attribute 922,Attribute 923,Attribute 924,Attribute 925,Attribute 926,Attribute 927,Attribute 928,Attribute 929,Attribute 930,Attribute 931,Attribute 932,Attribute 933,Attribute 934,Attribute 935,Attribute 936,Attribute 937,Attribute 938,Attribute 939,Attribute 940,Attribute 941,Attribute 942,Attribute 943,Attribute 944,Attribute 945,Attribute 946,Attribute 947,Attribute 948,Attribute 949,Attribute 950,Attribute 951,Attribute 952,Attribute 953,Attribute 954,Attribute 955,Attribute 956,Attribute 957,Attribute 958,Attribute 959,Attribute 960,Attribute 961,Attribute 962,Attribute 963,Attribute 964,Attribute 965,Attribute 966,Attribute 967,Attribute 968,Attribute 969,Attribute 970,Attribute 971,Attribute 972,Attribute 973,Attribute 974,Attribute 975,Attribute 976,Attribute 977,Attribute 978,Attribute 979,Attribute 980,Attribute 981,Attribute 982,Attribute 983,Attribute 984,Attribute 985,Attribute 986,Attribute 987,Attribute 988,Attribute 989,Attribute 990,Attribute 991,Attribute 992,Attribute 993,Attribute 994,Attribute 995,Attribute 996,Attribute 997,Attribute 998,Attribute 999,Attribute 1000,Attribute 1001,Attribute 1002,Attribute 1003,Attribute 1004,Attribute 1005,Attribute 1006,Attribute 1007,Attribute 1008,Attribute 1009,Attribute 1010,Attribute 1011,Attribute 1012,Attribute 1013,Attribute 1014,Attribute 1015,Attribute 1016,Attribute 1017,Attribute 1018,Attribute 1019,Attribute 1020,Attribute 1021,Attribute 1022,Attribute 1023,Attribute 1024,Toxic
0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,No
1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,No

In [5]:
# Feature Summary
summary

               index     dtype  n_missing  pct_missing  n_unique examples
0        Attribute 1  category        0.0          0.0       2.0     0, 1
1        Attribute 2  category        0.0          0.0       2.0     0, 1
2        Attribute 3  category        0.0          0.0       2.0     0, 1
3        Attribute 4  category        0.0          0.0       2.0     0, 1
4        Attribute 5  category        0.0          0.0       2.0     0, 1
5        Attribute 6  category        0.0          0.0       2.0     0, 1
6        Attribute 7  category        0.0          0.0       2.0     0, 1
7        Attribute 8  category        0.0          0.0       2.0     0, 1
8        Attribute 9  category        0.0          0.0       2.0     0, 1
9       Attribute 10  category        0.0          0.0       2.0     0, 1
10      Attribute 11  category        0.0          0.0       2.0     0, 1
11      Attribute 12  category        0.0          0.0       2.0     0, 1
12      Attribute 13  category        0.0          0.0       2.0     0, 1
13      Attribute 14  category        0.0          0.0       2.0     0, 1
14      Attribute 15  category        0.0          0.0       2.0     0, 1
15      Attribute 16  category        0.0          0.0       2.0     0, 1
16      Attribute 17  category        0.0          0.0       2.0     1, 0
17      Attribute 18  category        0.0          0.0       2.0     0, 1
18      Attribute 19  category        0.0          0.0       2.0     0, 1
19      Attribute 20  category        0.0          0.0       2.0     0, 1
20      Attribute 21  category        0.0          0.0       2.0     0, 1
21      Attribute 22  category        0.0          0.0       2.0     0, 1
22      Attribute 23  category        0.0          0.0       2.0     0, 1
23      Attribute 24  category        0.0          0.0       2.0     0, 1
24      Attribute 25  category        0.0          0.0       2.0     0, 1
25      Attribute 26  category        0.0          0.0       2.0     0, 1
26      Attribute 27  category        0.0          0.0       2.0     0, 1
27      Attribute 28  category        0.0          0.0       2.0     0, 1
28      Attribute 29  category        0.0          0.0       2.0     0, 1
29      Attribute 30  category        0.0          0.0       2.0     0, 1
30      Attribute 31  category        0.0          0.0       2.0     0, 1
31      Attribute 32  category        0.0          0.0       2.0     0, 1
32      Attribute 33  category        0.0          0.0       2.0     0, 1
33      Attribute 34  category        0.0          0.0       2.0     0, 1
34      Attribute 35  category        0.0          0.0       2.0     0, 1
35      Attribute 36  category        0.0          0.0       2.0     0, 1
36      Attribute 37  category        0.0          0.0       2.0     0, 1
37      Attribute 38  category        0.0          0.0       2.0     0, 1
38      Attribute 39  category        0.0          0.0       2.0     0, 1
39      Attribute 40  category        0.0          0.0       2.0     0, 1
40      Attribute 41  category        0.0          0.0       2.0     0, 1
41      Attribute 42  category        0.0          0.0       2.0     0, 1
42      Attribute 43  category        0.0          0.0       2.0     0, 1
43      Attribute 44  category        0.0          0.0       2.0     0, 1
44      Attribute 45  category        0.0          0.0       2.0     0, 1
45      Attribute 46  category        0.0          0.0       2.0     0, 1
46      Attribute 47  category        0.0          0.0       2.0     0, 1
47      Attribute 48  category        0.0          0.0       2.0     0, 1
48      Attribute 49  category        0.0          0.0       2.0     0, 1
49      Attribute 50  category        0.0          0.0       2.0     0, 1
50      Attribute 51  category        0.0          0.0       2.0     0, 1
51      Attribute 52  category        0.0          0.0       2.0     0, 1
52      Attribute 53  category        0.0          0.0       2.0     0, 1
53      Attribute 54  category        0.0          0.0       2.0     0, 1
54      Attribute 55  category        0.0          0.0       2.0     0, 1
55      Attribute 56  category        0.0          0.0       2.0     0, 1
56      Attribute 57  category        0.0          0.0       2.0     0, 1
57      Attribute 58  category        0.0          0.0       2.0     0, 1
58      Attribute 59  category        0.0          0.0       2.0     0, 1
59      Attribute 60  category        0.0          0.0       2.0     0, 1
60      Attribute 61  category        0.0          0.0       2.0     0, 1
61      Attribute 62  category        0.0          0.0       2.0     0, 1
62      Attribute 63  category        0.0          0.0       2.0     0, 1
63      Attribute 64  category        0.0          0.0       2.0     0, 1
64      Attribute 65  category        0.0          0.0       2.0     0, 1
65      Attribute 66  category        0.0          0.0       2.0     0, 1
66      Attribute 67  category        0.0          0.0       2.0     0, 1
67      Attribute 68  category        0.0          0.0       2.0     0, 1
68      Attribute 69  category        0.0          0.0       2.0     0, 1
69      Attribute 70  category        0.0          0.0       2.0     0, 1
70      Attribute 71  category        0.0          0.0       2.0     0, 1
71      Attribute 72  category        0.0          0.0       2.0     0, 1
72      Attribute 73  category        0.0          0.0       2.0     0, 1
73      Attribute 74  category        0.0          0.0       2.0     0, 1
74      Attribute 75  category        0.0          0.0       2.0     0, 1
75      Attribute 76  category        0.0          0.0       2.0     0, 1
76      Attribute 77  category        0.0          0.0       2.0     0, 1
77      Attribute 78  category        0.0          0.0       2.0     0, 1
78      Attribute 79  category        0.0          0.0       2.0     1, 0
79      Attribute 80  category        0.0          0.0       2.0     0, 1
80      Attribute 81  category        0.0          0.0       2.0     0, 1
81      Attribute 82  category        0.0          0.0       2.0     0, 1
82      Attribute 83  category        0.0          0.0       2.0     0, 1
83      Attribute 84  category        0.0          0.0       2.0     0, 1
84      Attribute 85  category        0.0          0.0       2.0     0, 1
85      Attribute 86  category        0.0          0.0       2.0     0, 1
86      Attribute 87  category        0.0          0.0       2.0     0, 1
87      Attribute 88  category        0.0          0.0       2.0     0, 1
88      Attribute 89  category        0.0          0.0       2.0     0, 1
89      Attribute 90  category        0.0          0.0       2.0     0, 1
90      Attribute 91  category        0.0          0.0       2.0     0, 1
91      Attribute 92  category        0.0          0.0       2.0     0, 1
92      Attribute 93  category        0.0          0.0       2.0     1, 0
93      Attribute 94  category        0.0          0.0       2.0     0, 1
94      Attribute 95  category        0.0          0.0       2.0     0, 1
95      Attribute 96  category        0.0          0.0       2.0     0, 1
96      Attribute 97  category        0.0          0.0       2.0     0, 1
97      Attribute 98  category        0.0          0.0       2.0     0, 1
98      Attribute 99  category        0.0          0.0       2.0     0, 1
99     Attribute 100  category        0.0          0.0       2.0     0, 1
100    Attribute 101  category        0.0          0.0       2.0     0, 1
101    Attribute 102  category        0.0          0.0       2.0     0, 1
102    Attribute 103  category        0.0          0.0       2.0     0, 1
103    Attribute 104  category        0.0          0.0       2.0     0, 1
104    Attribute 105  category        0.0          0.0       2.0     0, 1
105    Attribute 106  category        0.0          0.0       2.0     0, 1
106    Attribute 107  category        0.0          0.0       2.0     0, 1
107    Attribute 108  category        0.0          0.0       2.0     0, 1
108    Attribute 109  category        0.0          0.0       2.0     0, 1
109    Attribute 110  category        0.0          0.0       2.0     0, 1
110    Attribute 111  category        0.0          0.0       2.0     0, 1
111    Attribute 112  category        0.0          0.0       2.0     0, 1
112    Attribute 113  category        0.0          0.0       2.0     0, 1
113    Attribute 114  category        0.0          0.0       2.0     0, 1
114    Attribute 115  category        0.0          0.0       2.0     0, 1
115    Attribute 116  category        0.0          0.0       2.0     0, 1
116    Attribute 117  category        0.0          0.0       2.0     1, 0
117    Attribute 118  category        0.0          0.0       2.0     0, 1
118    Attribute 119  category        0.0          0.0       2.0     0, 1
119    Attribute 120  category        0.0          0.0       2.0     0, 1
120    Attribute 121  category        0.0          0.0       2.0     0, 1
121    Attribute 122  category        0.0          0.0       2.0     0, 1
122    Attribute 123  category        0.0          0.0       2.0     0, 1
123    Attribute 124  category        0.0          0.0       2.0     0, 1
124    Attribute 125  category        0.0          0.0       2.0     0, 1
125    Attribute 126  category        0.0          0.0       2.0     0, 1
126    Attribute 127  category        0.0          0.0       2.0     0, 1
127    Attribute 128  category        0.0          0.0       2.0     0, 1
128    Attribute 129  category        0.0          0.0       2.0     0, 1
129    Attribute 130  category        0.0          0.0       2.0     0, 1
130    Attribute 131  category        0.0          0.0       2.0     0, 1
131    Attribute 132  category        0.0          0.0       2.0     1, 0
132    Attribute 133  category        0.0          0.0       2.0     0, 1
133    Attribute 134  category        0.0          0.0       2.0     0, 1
134    Attribute 135  category        0.0          0.0       2.0     0, 1
135    Attribute 136  category        0.0          0.0       2.0     0, 1
136    Attribute 137  category        0.0          0.0       2.0     0, 1
137    Attribute 138  category        0.0          0.0       2.0     0, 1
138    Attribute 139  category        0.0          0.0       2.0     0, 1
139    Attribute 140  category        0.0          0.0       2.0     0, 1
140    Attribute 141  category        0.0          0.0       2.0     0, 1
141    Attribute 142  category        0.0          0.0       2.0     0, 1
142    Attribute 143  category        0.0          0.0       2.0     0, 1
143    Attribute 144  category        0.0          0.0       2.0     0, 1
144    Attribute 145  category        0.0          0.0       2.0     0, 1
145    Attribute 146  category        0.0          0.0       2.0     0, 1
146    Attribute 147  category        0.0          0.0       2.0     0, 1
147    Attribute 148  category        0.0          0.0       2.0     0, 1
148    Attribute 149  category        0.0          0.0       2.0     0, 1
149    Attribute 150  category        0.0          0.0       2.0     0, 1
150    Attribute 151  category        0.0          0.0       2.0     0, 1
151    Attribute 152  category        0.0          0.0       2.0     0, 1
152    Attribute 153  category        0.0          0.0       2.0     0, 1
153    Attribute 154  category        0.0          0.0       2.0     0, 1
154    Attribute 155  category        0.0          0.0       2.0     0, 1
155    Attribute 156  category        0.0          0.0       2.0     0, 1
156    Attribute 157  category        0.0          0.0       2.0     0, 1
157    Attribute 158  category        0.0          0.0       2.0     0, 1
158    Attribute 159  category        0.0          0.0       2.0     0, 1
159    Attribute 160  category        0.0          0.0       2.0     0, 1
160    Attribute 161  category        0.0          0.0       2.0     0, 1
161    Attribute 162  category        0.0          0.0       2.0     0, 1
162    Attribute 163  category        0.0          0.0       2.0     0, 1
163    Attribute 164  category        0.0          0.0       2.0     0, 1
164    Attribute 165  category        0.0          0.0       2.0     0, 1
165    Attribute 166  category        0.0          0.0       2.0     0, 1
166    Attribute 167  category        0.0          0.0       2.0     0, 1
167    Attribute 168  category        0.0          0.0       2.0     0, 1
168    Attribute 169  category        0.0          0.0       2.0     0, 1
169    Attribute 170  category        0.0          0.0       2.0     0, 1
170    Attribute 171  category        0.0          0.0       2.0     0, 1
171    Attribute 172  category        0.0          0.0       2.0     0, 1
172    Attribute 173  category        0.0          0.0       2.0     0, 1
173    Attribute 174  category        0.0          0.0       2.0     0, 1
174    Attribute 175  category        0.0          0.0       2.0     0, 1
175    Attribute 176  category        0.0          0.0       2.0     0, 1
176    Attribute 177  category        0.0          0.0       2.0     0, 1
177    Attribute 178  category        0.0          0.0       2.0     0, 1
178    Attribute 179  category        0.0          0.0       2.0     1, 0
179    Attribute 180  category        0.0          0.0       2.0     0, 1
180    Attribute 181  category        0.0          0.0       2.0     0, 1
181    Attribute 182  category        0.0          0.0       2.0     0, 1
182    Attribute 183  category        0.0          0.0       2.0     0, 1
183    Attribute 184  category        0.0          0.0       2.0     0, 1
184    Attribute 185  category        0.0          0.0       2.0     0, 1
185    Attribute 186  category        0.0          0.0       2.0     0, 1
186    Attribute 187  category        0.0          0.0       2.0     0, 1
187    Attribute 188  category        0.0          0.0       2.0     0, 1
188    Attribute 189  category        0.0          0.0       2.0     0, 1
189    Attribute 190  category        0.0          0.0       2.0     0, 1
190    Attribute 191  category        0.0          0.0       2.0     0, 1
191    Attribute 192  category        0.0          0.0       2.0     0, 1
192    Attribute 193  category        0.0          0.0       2.0     0, 1
193    Attribute 194  category        0.0          0.0       2.0     0, 1
194    Attribute 195  category        0.0          0.0       2.0     0, 1
195    Attribute 196  category        0.0          0.0       2.0     0, 1
196    Attribute 197  category        0.0          0.0       2.0     0, 1
197    Attribute 198  category        0.0          0.0       2.0     0, 1
198    Attribute 199  category        0.0          0.0       2.0     0, 1
199    Attribute 200  category        0.0          0.0       2.0     0, 1
200    Attribute 201  category        0.0          0.0       2.0     0, 1
201    Attribute 202  category        0.0          0.0       2.0     0, 1
202    Attribute 203  category        0.0          0.0       2.0     0, 1
203    Attribute 204  category        0.0          0.0       2.0     0, 1
204    Attribute 205  category        0.0          0.0       2.0     0, 1
205    Attribute 206  category        0.0          0.0       2.0     0, 1
206    Attribute 207  category        0.0          0.0       2.0     0, 1
207    Attribute 208  category        0.0          0.0       2.0     0, 1
208    Attribute 209  category        0.0          0.0       2.0     0, 1
209    Attribute 210  category        0.0          0.0       2.0     0, 1
210    Attribute 211  category        0.0          0.0       2.0     0, 1
211    Attribute 212  category        0.0          0.0       2.0     0, 1
212    Attribute 213  category        0.0          0.0       2.0     0, 1
213    Attribute 214  category        0.0          0.0       2.0     0, 1
214    Attribute 215  category        0.0          0.0       2.0     0, 1
215    Attribute 216  category        0.0          0.0       2.0     0, 1
216    Attribute 217  category        0.0          0.0       2.0     0, 1
217    Attribute 218  category        0.0          0.0       2.0     0, 1
218    Attribute 219  category        0.0          0.0       2.0     0, 1
219    Attribute 220  category        0.0          0.0       2.0     0, 1
220    Attribute 221  category        0.0          0.0       2.0     0, 1
221    Attribute 222  category        0.0          0.0       2.0     0, 1
222    Attribute 223  category        0.0          0.0       2.0     1, 0
223    Attribute 224  category        0.0          0.0       2.0     0, 1
224    Attribute 225  category        0.0          0.0       2.0     0, 1
225    Attribute 226  category        0.0          0.0       2.0     0, 1
226    Attribute 227  category        0.0          0.0       2.0     0, 1
227    Attribute 228  category        0.0          0.0       2.0     0, 1
228    Attribute 229  category        0.0          0.0       2.0     0, 1
229    Attribute 230  category        0.0          0.0       2.0     0, 1
230    Attribute 231  category        0.0          0.0       2.0     0, 1
231    Attribute 232  category        0.0          0.0       2.0     0, 1
232    Attribute 233  category        0.0          0.0       2.0     0, 1
233    Attribute 234  category        0.0          0.0       2.0     0, 1
234    Attribute 235  category        0.0          0.0       2.0     0, 1
235    Attribute 236  category        0.0          0.0       2.0     0, 1
236    Attribute 237  category        0.0          0.0       2.0     0, 1
237    Attribute 238  category        0.0          0.0       2.0     0, 1
238    Attribute 239  category        0.0          0.0       2.0     0, 1
239    Attribute 240  category        0.0          0.0       2.0     0, 1
240    Attribute 241  category        0.0          0.0       2.0     0, 1
241    Attribute 242  category        0.0          0.0       2.0     0, 1
242    Attribute 243  category        0.0          0.0       2.0     0, 1
243    Attribute 244  category        0.0          0.0       2.0     0, 1
244    Attribute 245  category        0.0          0.0       2.0     0, 1
245    Attribute 246  category        0.0          0.0       2.0     0, 1
246    Attribute 247  category        0.0          0.0       2.0     0, 1
247    Attribute 248  category        0.0          0.0       2.0     0, 1
248    Attribute 249  category        0.0          0.0       2.0     0, 1
249    Attribute 250  category        0.0          0.0       2.0     1, 0
250    Attribute 251  category        0.0          0.0       2.0     0, 1
251    Attribute 252  category        0.0          0.0       2.0     0, 1
252    Attribute 253  category        0.0          0.0       2.0     0, 1
253    Attribute 254  category        0.0          0.0       2.0     0, 1
254    Attribute 255  category        0.0          0.0       2.0     0, 1
255    Attribute 256  category        0.0          0.0       2.0     0, 1
256    Attribute 257  category        0.0          0.0       2.0     0, 1
257    Attribute 258  category        0.0          0.0       2.0     0, 1
258    Attribute 259  category        0.0          0.0       2.0     0, 1
259    Attribute 260  category        0.0          0.0       2.0     0, 1
260    Attribute 261  category        0.0          0.0       2.0     1, 0
261    Attribute 262  category        0.0          0.0       2.0     0, 1
262    Attribute 263  category        0.0          0.0       2.0     0, 1
263    Attribute 264  category        0.0          0.0       2.0     0, 1
264    Attribute 265  category        0.0          0.0       2.0     0, 1
265    Attribute 266  category        0.0          0.0       2.0     0, 1
266    Attribute 267  category        0.0          0.0       2.0     0, 1
267    Attribute 268  category        0.0          0.0       2.0     0, 1
268    Attribute 269  category        0.0          0.0       2.0     0, 1

In [6]:
# Numeric Feature Statistics
numeric_stats

'No numeric features to summarize.'

In [7]:
# Categorical Feature Statistics
cat_stats

                    value  count    pct
column         rank
Attribute 1    1        0   7077  78.70
               2        1   1915  21.30
Attribute 10   1        0   8836  98.27
               2        1    156   1.73
Attribute 100  1        0   8809  97.96
               2        1    183   2.04
Attribute 1000 1        0   8711  96.88
               2        1    281   3.12
Attribute 1001 1        0   7865  87.47
               2        1   1127  12.53
Attribute 1002 1        0   8779  97.63
               2        1    213   2.37
Attribute 1003 1        0   8567  95.27
               2        1    425   4.73
Attribute 1004 1        0   8515  94.70
               2        1    477   5.30
Attribute 1005 1        0   8244  91.68
               2        1    748   8.32
Attribute 1006 1        0   8817  98.05
               2        1    175   1.95
Attribute 1007 1        0   8662  96.33
               2        1    330   3.67
Attribute 1008 1        0   6662  74.09
               2        1   2330  25.91
Attribute 1009 1        0   7428  82.61
               2        1   1564  17.39
Attribute 101  1        0   8159  90.74
               2        1    833   9.26
Attribute 1010 1        0   8485  94.36
               2        1    507   5.64
Attribute 1011 1        0   8292  92.22
               2        1    700   7.78
Attribute 1012 1        0   8672  96.44
               2        1    320   3.56
Attribute 1013 1        0   8606  95.71
               2        1    386   4.29
Attribute 1014 1        0   8587  95.50
               2        1    405   4.50
Attribute 1015 1        0   8642  96.11
               2        1    350   3.89
Attribute 1016 1        0   8441  93.87
               2        1    551   6.13
Attribute 1017 1        0   8842  98.33
               2        1    150   1.67
Attribute 1018 1        0   7514  83.56
               2        1   1478  16.44
Attribute 1019 1        0   6843  76.10
               2        1   2149  23.90
Attribute 102  1        0   5813  64.65
               2        1   3179  35.35
Attribute 1020 1        0   8790  97.75
               2        1    202   2.25
Attribute 1021 1        0   8794  97.80
               2        1    198   2.20
Attribute 1022 1        0   8796  97.82
               2        1    196   2.18
Attribute 1023 1        0   8791  97.76
               2        1    201   2.24
Attribute 1024 1        0   8826  98.15
               2        1    166   1.85
Attribute 103  1        0   8812  98.00
               2        1    180   2.00
Attribute 104  1        0   8660  96.31
               2        1    332   3.69
Attribute 105  1        0   8773  97.56
               2        1    219   2.44
Attribute 106  1        0   8752  97.33
               2        1    240   2.67
Attribute 107  1        0   8864  98.58
               2        1    128   1.42
Attribute 108  1        0   8661  96.32
               2        1    331   3.68
Attribute 109  1        0   8820  98.09
               2        1    172   1.91
Attribute 11   1        0   7603  84.55
               2        1   1389  15.45
Attribute 110  1        0   8343  92.78
               2        1    649   7.22
Attribute 111  1        0   8784  97.69
               2        1    208   2.31
Attribute 112  1        0   8821  98.10
               2        1    171   1.90
Attribute 113  1        0   8535  94.92
               2        1    457   5.08
Attribute 114  1        0   8450  93.97
               2        1    542   6.03
Attribute 115  1        0   8206  91.26
               2        1    786   8.74
Attribute 116  1        0   8755  97.36
               2        1    237   2.64
Attribute 117  1        1   5629  62.60
               2        0   3363  37.40
Attribute 118  1        0   8555  95.14
               2        1    437   4.86
Attribute 119  1        0   8609  95.74
               2        1    383   4.26
Attribute 12   1        0   8734  97.13
               2        1    258   2.87
Attribute 120  1        0   8702  96.77
               2        1    290   3.23
Attribute 121  1        0   8451  93.98
               2        1    541   6.02
Attribute 122  1        0   8929  99.30
               2        1     63   0.70
Attribute 123  1        0   8756  97.38
               2        1    236   2.62
Attribute 124  1        0   8849  98.41
               2        1    143   1.59
Attribute 125  1        0   8790  97.75
               2        1    202   2.25
Attribute 126  1        0   6644  73.89
               2        1   2348  26.11
Attribute 127  1        0   8207  91.27
               2        1    785   8.73
Attribute 128  1        0   8817  98.05
               2        1    175   1.95
Attribute 129  1        0   8848  98.40
               2        1    144   1.60
Attribute 13   1        0   8243  91.67
               2        1    749   8.33
Attribute 130  1        0   8724  97.02
               2        1    268   2.98
Attribute 131  1        0   8669  96.41
               2        1    323   3.59
Attribute 132  1        1   6227  69.25
               2        0   2765  30.75
Attribute 133  1        0   8666  96.37
               2        1    326   3.63
Attribute 134  1        0   8579  95.41
               2        1    413   4.59
Attribute 135  1        0   8552  95.11
               2        1    440   4.89
Attribute 136  1        0   8787  97.72
               2        1    205   2.28
Attribute 137  1        0   8366  93.04
               2        1    626   6.96
Attribute 138  1        0   8679  96.52
               2        1    313   3.48
Attribute 139  1        0   8691  96.65
               2        1    301   3.35
Attribute 14   1        0   6353  70.65
               2        1   2639  29.35
Attribute 140  1        0   8409  93.52
               2        1    583   6.48
Attribute 141  1        0   8856  98.49
               2        1    136   1.51
Attribute 142  1        0   8800  97.86
               2        1    192   2.14
Attribute 143  1        0   8368  93.06
               2        1    624   6.94
Attribute 144  1        0   8428  93.73
               2        1    564   6.27
Attribute 145  1        0   8763  97.45
               2        1    229   2.55
Attribute 146  1        0   8586  95.48
               2        1    406   4.52
Attribute 147  1        0   8808  97.95
               2        1    184   2.05
Attribute 148  1        0   8572  95.33
               2        1    420   4.67
Attribute 149  1        0   8888  98.84
               2        1    104   1.16
Attribute 15   1        0   8321  92.54
               2        1    671   7.46
Attribute 150  1        0   8687  96.61
               2        1    305   3.39
Attribute 151  1        0   8770  97.53
               2        1    222   2.47
Attribute 152  1        0   8869  98.63
               2        1    123   1.37
Attribute 153  1        0   8537  94.94
               2        1    455   5.06
Attribute 154  1        0   8743  97.23
               2        1    249   2.77
Attribute 155  1        0   8719  96.96
               2        1    273   3.04
Attribute 156  1        0   6327  70.36
               2        1   2665  29.64
Attribute 157  1        0   8830  98.20
               2        1    162   1.80
Attribute 158  1        0   8632  96.00
               2        1    360   4.00
Attribute 159  1        0   8701  96.76
               2        1    291   3.24
Attribute 16   1        0   6562  72.98
               2        1   2430  27.02
Attribute 160  1        0   8808  97.95
               2        1    184   2.05
Attribute 161  1        0   7753  86.22
               2        1   1239  13.78
Attribute 162  1        0   8796  97.82
               2        1    196   2.18
Attribute 163  1        0   8788  97.73
               2        1    204   2.27
Attribute 164  1        0   8396  93.37
               2        1    596   6.63
Attribute 165  1        0   8332  92.66
               2        1    660   7.34
Attribute 166  1        0   8759  97.41
               2        1    233   2.59
Attribute 167  1        0   8638  96.06
               2        1    354   3.94
Attribute 168  1        0   8288  92.17
               2        1    704   7.83
Attribute 169  1        0   6916  76.91
               2        1   2076  23.09
Attribute 17   1        1   5410  60.16
               2        0   3582  39.84
Attribute 170  1        0   8811  97.99
               2        1    181   2.01
Attribute 171  1        0   8276  92.04
               2        1    716   7.96
Attribute 172  1        0   8797  97.83
               2        1    195   2.17
Attribute 173  1        0   8026  89.26
               2        1    966  10.74
Attribute 174  1        0   8792  97.78
               2        1    200   2.22
Attribute 175  1        0   8739  97.19
               2        1    253   2.81
Attribute 176  1        0   8889  98.85
               2        1    103   1.15
Attribute 177  1        0   7731  85.98
               2        1   1261  14.02
Attribute 178  1        0   8857  98.50
               2        1    135   1.50
Attribute 179  1        1   4805  53.44
               2        0   4187  46.56
Attribute 18   1        0   8805  97.92
               2        1    187   2.08
Attribute 180  1        0   7608  84.61
               2        1   1384  15.39
Attribute 181  1        0   8150  90.64
               2        1    842   9.36
Attribute 182  1        0   4737  52.68
               2        1   4255  47.32
Attribute 183  1        0   8777  97.61
               2        1    215   2.39
Attribute 184  1        0   8630  95.97
               2        1    362   4.03
Attribute 185  1        0   8841  98.32
               2        1    151   1.68
Attribute 186  1        0   8075  89.80
               2        1    917  10.20
Attribute 187  1        0   8734  97.13
               2        1    258   2.87
Attribute 188  1        0   8811  97.99
               2        1    181   2.01
Attribute 189  1        0   8531  94.87
               2        1    461   5.13
Attribute 19   1        0   7983  88.78
               2        1   1009  11.22
Attribute 190  1        0   8555  95.14
               2        1    437   4.86
Attribute 191  1        0   8732  97.11
               2        1    260   2.89
Attribute 192  1        0   8830  98.20
               2        1    162   1.80
Attribute 193  1        0   8913  99.12
               2        1     79   0.88
Attribute 194  1        0   7665  85.24
               2        1   1327  14.76
Attribute 195  1        0   8254  91.79
               2        1    738   8.21
Attribute 196  1        0   7813  86.89
               2        1   1179  13.11
Attribute 197  1        0   8819  98.08
               2        1    173   1.92
Attribute 198  1        0   8487  94.38
               2        1    505   5.62
Attribute 199  1        0   8309  92.40
               2        1    683   7.60
Attribute 2    1        0   8671  96.43
               2        1    321   3.57
Attribute 20   1        0   8631  95.99
               2        1    361   4.01
Attribute 200  1        0   8806  97.93
               2        1    186   2.07
Attribute 201  1        0   8514  94.68
               2        1    478   5.32
Attribute 202  1        0   8758  97.40
               2        1    234   2.60
Attribute 203  1        0   7901  87.87
               2        1   1091  12.13
Attribute 204  1        0   5983  66.54
               2        1   3009  33.46
Attribute 205  1        0   8437  93.83
               2        1    555   6.17
Attribute 206  1        0   8667  96.39
               2        1    325   3.61
Attribute 207  1        0   8861  98.54
               2        1    131   1.46
Attribute 208  1        0   8713  96.90
               2        1    279   3.10
Attribute 209  1        0   6869  76.39
               2        1   2123  23.61
Attribute 21   1        0   8488  94.40
               2        1    504   5.60
Attribute 210  1        0   7714  85.79
               2        1   1278  14.21
Attribute 211  1        0   8875  98.70
               2        1    117   1.30
Attribute 212  1        0   8739  97.19
               2        1    253   2.81
Attribute 213  1        0   8684  96.57
               2        1    308   3.43
Attribute 214  1        0   8525  94.81
               2        1    467   5.19
Attribute 215  1        0   8643  96.12
               2        1    349   3.88
Attribute 216  1        0   8740  97.20
               2        1    252   2.80
Attribute 217  1        0   8801  97.88
               2        1    191   2.12
Attribute 218  1        0   8822  98.11
               2        1    170   1.89
Attribute 219  1        0   8662  96.33
               2        1    330   3.67
Attribute 22   1        0   8496  94.48
               2        1    496   5.52
Attribute 220  1        0   8796  97.82
               2        1    196   2.18
Attribute 221  1        0   8710  96.86
               2        1    282   3.14
Attribute 222  1        0   8742  97.22
               2        1    250   2.78
Attribute 223  1        1   5651  62.84
               2        0   3341  37.16
Attribute 224  1        0   8778  97.62
               2        1    214   2.38
Attribute 225  1        0   8688  96.62
               2        1    304   3.38
Attribute 226  1        0   7457  82.93
               2        1   1535  17.07
Attribute 227  1        0   8659  96.30
               2        1    333   3.70
Attribute 228  1        0   8898  98.95
               2        1     94   1.05
Attribute 229  1        0   8372  93.10
               2        1    620   6.90
Attribute 23   1        0   8581  95.43
               2        1    411   4.57
Attribute 230  1        0   8608  95.73
               2        1    384   4.27
Attribute 231  1        0   8234  91.57
               2        1    758   8.43
Attribute 232  1        0   8384  93.24
               2        1    608   6.76
Attribute 233  1        0   8762  97.44
               2        1    230   2.56
Attribute 234  1        0   7252  80.65
               2        1   1740  19.35
Attribute 235  1        0   8783  97.68
               2        1    209   2.32
Attribute 236  1        0   8722  97.00
               2        1    270   3.00
Attribute 237  1        0   7662  85.21
               2        1   1330  14.79
Attribute 238  1        0   7960  88.52
               2        1   1032  11.48
Attribute 239  1        0   8656  96.26
               2        1    336   3.74
Attribute 24   1        0   8592  95.55
               2        1    400   4.45
Attribute 240  1        0   8759  97.41
               2        1    233   2.59
Attribute 241  1        0   8745  97.25
               2        1    247   2.75
Attribute 242  1        0   8770  97.53
               2        1    222   2.47
Attribute 243  1        0   4561  50.72
               2        1   4431  49.28
Attribute 244  1        0   8462  94.11
               2        1    530   5.89
Attribute 245  1        0   8286  92.15
               2        1    706   7.85
Attribute 246  1        0   8301  92.32
               2        1    691   7.68
Attribute 247  1        0   8373  93.12
               2        1    619   6.88
Attribute 248  1        0   8824  98.13
               2        1    168   1.87
Attribute 249  1        0   8789  97.74
               2        1    203   2.26
Attribute 25   1        0   8704  96.80
               2        1    288   3.20
Attribute 250  1        1   5240  58.27
               2        0   3752  41.73
Attribute 251  1        0   8811  97.99
               2        1    181   2.01
Attribute 252  1        0   8869  98.63
               2        1    123   1.37
Attribute 253  1        0   8555  95.14
               2        1    437   4.86
Attribute 254  1        0   8186  91.04
               2        1    806   8.96
Attribute 255  1        0   8696  96.71
               2        1    296   3.29
Attribute 256  1        0   8601  95.65
               2        1    391   4.35
Attribute 257  1        0   8895  98.92
               2        1     97   1.08
Attribute 258  1        0   8580  95.42
               2        1    412   4.58
Attribute 259  1        0   8069  89.74
               2        1    923  10.26
Attribute 26   1        0   8623  95.90
               2        1    369   4.10
Attribute 260  1        0   8761  97.43
               2        1    231   2.57
Attribute 261  1        1   7340  81.63
               2        0   1652  18.37
Attribute 262  1        0   8732  97.11
               2        1    260   2.89
Attribute 263  1        0   8640  96.09
               2        1    352   3.91
Attribute 264  1        0   8806  97.93
               2        1    186   2.07
Attribute 265  1        0   8679  96.52
               2        1    313   3.48
Attribute 266  1        0   8287  92.16
               2        1    705   7.84
Attribute 267  1        0   7917  88.04
               2        1   1075  11.96
Attribute 268  1        0   7825  87.02
               2        1   1167  12.98
Attribute 269  1        0   7889  87.73
               2        1   1103  12.27
Attribute 27   1        0   8563  95.23
               2        1    429   4.77
Attribute 270  1        0   8096  90.04
               2        1    896   9.96
Attribute 271  1        0   8625  95.92
               2        1    367   4.08
Attribute 272  1        0   8375  93.14
               2        1    617   6.86
Attribute 273  1        0   8836  98.27
               2        1    156   1.73
Attribute 274  1        0   8785  97.70
               2        1    207   2.30
Attribute 275  1        0   8746  97.26
               2        1    246   2.74
Attribute 276  1        0   8752  97.33
               2        1    240   2.67
Attribute 277  1        0   8797  97.83
               2        1    195   2.17
Attribute 278  1        0   7132  79.31
               2        1   1860  20.69
Attribute 279  1        0   8899  98.97
               2        1     93   1.03
Attribute 28   1        0   8726  97.04
               2        1    266   2.96
Attribute 280  1        0   8818  98.06
               2        1    174   1.94
Attribute 281  1        0   8554  95.13
               2        1    438   4.87
Attribute 282  1        0   7656  85.14
               2        1   1336  14.86
Attribute 283  1        0   7526  83.70
               2        1   1466  16.30
Attribute 284  1        0   8701  96.76
               2        1    291   3.24
Attribute 285  1        0   8821  98.10
               2        1    171   1.90
Attribute 286  1        0   8519  94.74
               2        1    473   5.26
Attribute 287  1        0   8859  98.52
               2        1    133   1.48
Attribute 288  1        0   8783  97.68
               2        1    209   2.32
Attribute 289  1        1   5460  60.72
               2        0   3532  39.28
Attribute 29   1        0   8784  97.69
               2        1    208   2.31
Attribute 290  1        0   8750  97.31
               2        1    242   2.69
Attribute 291  1        0   8695  96.70
               2        1    297   3.30
Attribute 292  1        0   8825  98.14
               2        1    167   1.86
Attribute 293  1        0   8815  98.03
               2        1    177   1.97
Attribute 294  1        0   8836  98.27
               2        1    156   1.73
Attribute 295  1        0   8658  96.29
               2        1    334   3.71
Attribute 296  1        0   8765  97.48
               2        1    227   2.52
Attribute 297  1        0   6011  66.85
               2        1   2981  33.15
Attribute 298  1        0   8887  98.83
               2        1    105   1.17
Attribute 299  1        0   4827  53.68
               2        1   4165  46.32
Attribute 3    1        0   8374  93.13
               2        1    618   6.87
Attribute 30   1        0   8475  94.25
               2        1    517   5.75

In [8]:
# Target Distribution
target_df

       count    pct
Toxic
No      8251  91.76
Yes      741   8.24

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=3, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to qsar_oral_toxicity/019d9d33-cdb5-7c70-96f9-f921748b363a
019d9d33-cdb5-7c70-96f9-f921748b363a
4592a9ec97202ea218bb3f0cc7374a35328a5757aad2e2b878cde129ca73288b