### Dataset and Task Metadata

In [ ]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="mechanisms_of_action",
    dataset_year="2021",
    domain_str="biology & life sciences",
    # Data Source
    dataset_source="Kaggle",
    original_dataset_source_download_link="https://www.kaggle.com/competitions/lish-moa/data",
    download_description="""
We download the data from the UCI repository and uzip it to a predefined folder.

mkdir -p local-data-warehouse/mechanisms_of_action/ && cd local-data-warehouse/mechanisms_of_action/ && kaggle competitions download -c lish-moa && cd ../../ && unzip local-data-warehouse/mechanisms_of_action/lish-moa.zip -d local-data-warehouse/mechanisms_of_action/ && rm local-data-warehouse/mechanisms_of_action/lish-moa.zip && rm local-data-warehouse/mechanisms_of_action/sample_submission.csv
""",
    # References
    academic_reference_bibtex="""@misc{lish2021moa,
    author = {inversion and Jin Paik and Maggie and mrbhbs and Steven Randazzo  and tnat1031},
    title = {Mechanisms of Action (MoA) Prediction},
    year = {2020},
    howpublished = {url{https://kaggle.com/competitions/lish-moa}},
    note = {Kaggle}
}
""",
    academic_reference_bibtex_key="lish2021moa",
    license="Competition license",
    data_tags=["IID"],
    curation_comments="""
- We chose the train_features and the train_targets_scored as the full dataset, because for the rest of the data, there is no target
- There are 207 targets, we decide to use the nfkb_inhibitor as the target because of its high prevalence and because it is a central inflammation/immunomodulation target.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="nfkb_inhibitor",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="nfkb_inhibitor",
)

## Preprocessing

In [2]:
import pandas as pd

train_features = pd.read_csv(f"{dataset_mold.path}/train_features.csv", header=0)
train_targets_scored = pd.read_csv(f"{dataset_mold.path}/train_targets_scored.csv", header=0)

df = pd.concat([train_features, train_targets_scored], axis=1)

feature_names = df.columns

cat_features = [
    "cp_type",
    "cp_time",
    "cp_dose"
]

df.drop(columns=["sig_id"], inplace=True)

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

df[cat_features] = df[cat_features].astype("category")

In [3]:
# Use if needed to get see all cols of pandas dataframes
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
df.head()

,cp_type,cp_time,cp_dose,g-0,g-1,g-2,g-3,g-4,g-5,g-6,g-7,g-8,g-9,g-10,g-11,g-12,g-13,g-14,g-15,g-16,g-17,g-18,g-19,g-20,g-21,g-22,g-23,g-24,g-25,g-26,g-27,g-28,g-29,g-30,g-31,g-32,g-33,g-34,g-35,g-36,g-37,g-38,g-39,g-40,g-41,g-42,g-43,g-44,g-45,g-46,g-47,g-48,g-49,g-50,g-51,g-52,g-53,g-54,g-55,g-56,g-57,g-58,g-59,g-60,g-61,g-62,g-63,g-64,g-65,g-66,g-67,g-68,g-69,g-70,g-71,g-72,g-73,g-74,g-75,g-76,g-77,g-78,g-79,g-80,g-81,g-82,g-83,g-84,g-85,g-86,g-87,g-88,g-89,g-90,g-91,g-92,g-93,g-94,g-95,g-96,g-97,g-98,g-99,g-100,g-101,g-102,g-103,g-104,g-105,g-106,g-107,g-108,g-109,g-110,g-111,g-112,g-113,g-114,g-115,g-116,g-117,g-118,g-119,g-120,g-121,g-122,g-123,g-124,g-125,g-126,g-127,g-128,g-129,g-130,g-131,g-132,g-133,g-134,g-135,g-136,g-137,g-138,g-139,g-140,g-141,g-142,g-143,g-144,g-145,g-146,g-147,g-148,g-149,g-150,g-151,g-152,g-153,g-154,g-155,g-156,g-157,g-158,g-159,g-160,g-161,g-162,g-163,g-164,g-165,g-166,g-167,g-168,g-169,g-170,g-171,g-172,g-173,g-174,g-175,g-176,g-177,g-178,g-179,g-180,g-181,g-182,g-183,g-184,g-185,g-186,g-187,g-188,g-189,g-190,g-191,g-192,g-193,g-194,g-195,g-196,g-197,g-198,g-199,g-200,g-201,g-202,g-203,g-204,g-205,g-206,g-207,g-208,g-209,g-210,g-211,g-212,g-213,g-214,g-215,g-216,g-217,g-218,g-219,g-220,g-221,g-222,g-223,g-224,g-225,g-226,g-227,g-228,g-229,g-230,g-231,g-232,g-233,g-234,g-235,g-236,g-237,g-238,g-239,g-240,g-241,g-242,g-243,g-244,g-245,g-246,g-247,g-248,g-249,g-250,g-251,g-252,g-253,g-254,g-255,g-256,g-257,g-258,g-259,g-260,g-261,g-262,g-263,g-264,g-265,g-266,g-267,g-268,g-269,g-270,g-271,g-272,g-273,g-274,g-275,g-276,g-277,g-278,g-279,g-280,g-281,g-282,g-283,g-284,g-285,g-286,g-287,g-288,g-289,g-290,g-291,g-292,g-293,g-294,g-295,g-296,g-297,g-298,g-299,g-300,g-301,g-302,g-303,g-304,g-305,g-306,g-307,g-308,g-309,g-310,g-311,g-312,g-313,g-314,g-315,g-316,g-317,g-318,g-319,g-320,g-321,g-322,g-323,g-324,g-325,g-326,g-327,g-328,g-329,g-330,g-331,g-332,g-333,g-334,g-335,g-336,g-337,g-338,g-339,g-340,g-341,g-342,g-343,g-344,g-345,g-346,g-347,g-348,g-349,g-350,g-351,g-352,g-353,g-354,g-355,g-356,g-357,g-358,g-359,g-360,g-361,g-362,g-363,g-364,g-365,g-366,g-367,g-368,g-369,g-370,g-371,g-372,g-373,g-374,g-375,g-376,g-377,g-378,g-379,g-380,g-381,g-382,g-383,g-384,g-385,g-386,g-387,g-388,g-389,g-390,g-391,g-392,g-393,g-394,g-395,g-396,g-397,g-398,g-399,g-400,g-401,g-402,g-403,g-404,g-405,g-406,g-407,g-408,g-409,g-410,g-411,g-412,g-413,g-414,g-415,g-416,g-417,g-418,g-419,g-420,g-421,g-422,g-423,g-424,g-425,g-426,g-427,g-428,g-429,g-430,g-431,g-432,g-433,g-434,g-435,g-436,g-437,g-438,g-439,g-440,g-441,g-442,g-443,g-444,g-445,g-446,g-447,g-448,g-449,g-450,g-451,g-452,g-453,g-454,g-455,g-456,g-457,g-458,g-459,g-460,g-461,g-462,g-463,g-464,g-465,g-466,g-467,g-468,g-469,g-470,g-471,g-472,g-473,g-474,g-475,g-476,g-477,g-478,g-479,g-480,g-481,g-482,g-483,g-484,g-485,g-486,g-487,g-488,g-489,g-490,g-491,g-492,g-493,g-494,g-495,g-496,g-497,g-498,g-499,g-500,g-501,g-502,g-503,g-504,g-505,g-506,g-507,g-508,g-509,g-510,g-511,g-512,g-513,g-514,g-515,g-516,g-517,g-518,g-519,g-520,g-521,g-522,g-523,g-524,g-525,g-526,g-527,g-528,g-529,g-530,g-531,g-532,g-533,g-534,g-535,g-536,g-537,g-538,g-539,g-540,g-541,g-542,g-543,g-544,g-545,g-546,g-547,g-548,g-549,g-550,g-551,g-552,g-553,g-554,g-555,g-556,g-557,g-558,g-559,g-560,g-561,g-562,g-563,g-564,g-565,g-566,g-567,g-568,g-569,g-570,g-571,g-572,g-573,g-574,g-575,g-576,g-577,g-578,g-579,g-580,g-581,g-582,g-583,g-584,g-585,g-586,g-587,g-588,g-589,g-590,g-591,g-592,g-593,g-594,g-595,g-596,g-597,g-598,g-599,g-600,g-601,g-602,g-603,g-604,g-605,g-606,g-607,g-608,g-609,g-610,g-611,g-612,g-613,g-614,g-615,g-616,g-617,g-618,g-619,g-620,g-621,g-622,g-623,g-624,g-625,g-626,g-627,g-628,g-629,g-630,g-631,g-632,g-633,g-634,g-635,g-636,g-637,g-638,g-639,g-640,g-641,g-642,g-643,g-644,g-645,g-646,g-647,g-648,g-649,g-650,g-651,g-652,g-653,g-654,g-655,g-656,g-657,g-658,g-659,g-660,g-661,g-662,g-663,g-664,g-665,g-666,g-667,g-668,g-669,g-670,g-671,g-672,g-673,g-674,g-675,g-676,g-677,g-678,g-679,g-680,g-681,g-682,g-683,g-684,g-685,g-686,g-687,g-688,g-689,g-690,g-691,g-692,g-693,g-694,g-695,g-696,g-697,g-698,g-699,g-700,g-701,g-702,g-703,g-704,g-705,g-706,g-707,g-708,g-709,g-710,g-711,g-712,g-713,g-714,g-715,g-716,g-717,g-718,g-719,g-720,g-721,g-722,g-723,g-724,g-725,g-726,g-727,g-728,g-729,g-730,g-731,g-732,g-733,g-734,g-735,g-736,g-737,g-738,g-739,g-740,g-741,g-742,g-743,g-744,g-745,g-746,g-747,g-748,g-749,g-750,g-751,g-752,g-753,g-754,g-755,g-756,g-757,g-758,g-759,g-760,g-761,g-762,g-763,g-764,g-765,g-766,g-767,g-768,g-769,g-770,g-771,c-0,c-1,c-2,c-3,c-4,c-5,c-6,c-7,c-8,c-9,c-10,c-11,c-12,c-13,c-14,c-15,c-16,c-17,c-18,c-19,c-20,c-21,c-22,c-23,c-24,c-25,c-26,c-27,c-28,c-29,c-30,c-31,c-32,c-33,c-34,c-35,c-36,c-37,c-38,c-39,c-40,c-41,c-42,c-43,c-44,c-45,c-46,c-47,c-48,c-49,c-50,c-51,c-52,c-53,c-54,c-55,c-56,c-57,c-58,c-59,c-60,c-61,c-62,c-63,c-64,c-65,c-66,c-67,c-68,c-69,c-70,c-71,c-72,c-73,c-74,c-75,c-76,c-77,c-78,c-79,c-80,c-81,c-82,c-83,c-84,c-85,c-86,c-87,c-88,c-89,c-90,c-91,c-92,c-93,c-94,c-95,c-96,c-97,c-98,c-99,5-alpha_reductase_inhibitor,11-beta-hsd1_inhibitor,acat_inhibitor,acetylcholine_receptor_agonist,acetylcholine_receptor_antagonist,acetylcholinesterase_inhibitor,adenosine_receptor_agonist,adenosine_receptor_antagonist,adenylyl_cyclase_activator,adrenergic_receptor_agonist,adrenergic_receptor_antagonist,akt_inhibitor,aldehyde_dehydrogenase_inhibitor,alk_inhibitor,ampk_activator,analgesic,androgen_receptor_agonist,androgen_receptor_antagonist,anesthetic_-_local,angiogenesis_inhibitor,angiotensin_receptor_antagonist,anti-inflammatory,antiarrhythmic,antibiotic,anticonvulsant,antifungal,antihistamine,antimalarial,antioxidant,antiprotozoal,antiviral,apoptosis_stimulant,aromatase_inhibitor,atm_kinase_inhibitor,atp-sensitive_potassium_channel_antagonist,atp_synthase_inhibitor,atpase_inhibitor,atr_kinase_inhibitor,aurora_kinase_inhibitor,autotaxin_inhibitor,bacterial_30s_ribosomal_subunit_inhibitor,bacterial_50s_ribosomal_subunit_inhibitor,bacterial_antifolate,bacterial_cell_wall_synthesis_inhibitor,bacterial_dna_gyrase_inhibitor,bacterial_dna_inhibitor,bacterial_membrane_integrity_inhibitor,bcl_inhibitor,bcr-abl_inhibitor,benzodiazepine_receptor_agonist,beta_amyloid_inhibitor,bromodomain_inhibitor,btk_inhibitor,calcineurin_inhibitor,calcium_channel_blocker,cannabinoid_receptor_agonist,cannabinoid_receptor_antagonist,carbonic_anhydrase_inhibitor,casein_kinase_inhibitor,caspase_activator,catechol_o_methyltransferase_inhibitor,cc_chemokine_receptor_antagonist,cck_receptor_antagonist,cdk_inhibitor,chelating_agent,chk_inhibitor,chloride_channel_blocker,cholesterol_inhibitor,cholinergic_receptor_antagonist,coagulation_factor_inhibitor,corticosteroid_agonist,cyclooxygenase_inhibitor,cytochrome_p450_inhibitor,dihydrofolate_reductase_inhibitor,dipeptidyl_peptidase_inhibitor,diuretic,dna_alkylating_agent,dna_inhibitor,dopamine_receptor_agonist,dopamine_receptor_antagonist,egfr_inhibitor,elastase_inhibitor,erbb2_inhibitor,estrogen_receptor_agonist,estrogen_receptor_antagonist,faah_inhibitor,farnesyltransferase_inhibitor,fatty_acid_receptor_agonist,fgfr_inhibitor,flt3_inhibitor,focal_adhesion_kinase_inhibitor,free_radical_scavenger,fungal_squalene_epoxidase_inhibitor,gaba_receptor_agonist,gaba_receptor_antagonist,gamma_secretase_inhibitor,glucocorticoid_receptor_agonist,glutamate_inhibitor,glutamate_receptor_agonist,glutamate_receptor_antagonist,gonadotropin_receptor_agonist,gsk_inhibitor,hcv_inhibitor,hdac_inhibitor,histamine_receptor_agonist,histamine_receptor_antagonist,histone_lysine_demethylase_inhibitor,histone_lysine_methyltransferase_inhibitor,hiv_inhibitor,hmgcr_inhibitor,hsp_inhibitor,igf-1_inhibitor,ikk_inhibitor,imidazoline_receptor_agonist,immunosuppressant,insulin_secretagogue,insulin_sensitizer,integrin_inhibitor,jak_inhibitor,kit_inhibitor,laxative,leukotriene_inhibitor,leukotriene_receptor_antagonist,lipase_inhibitor,lipoxygenase_inhibitor,lxr_agonist,mdm_inhibitor,mek_inhibitor,membrane_integrity_inhibitor,mineralocorticoid_receptor_antagonist,monoacylglycerol_lipase_inhibitor,monoamine_oxidase_inhibitor,monopolar_spindle_1_kinase_inhibitor,mtor_inhibitor,mucolytic_agent,neuropeptide_receptor_antagonist,nfkb_inhibitor,nicotinic_receptor_agonist,nitric_oxide_donor,nitric_oxide_production_inhibitor,nitric_oxide_synthase_inhibitor,norepinephrine_reuptake_inhibitor,nrf2_activator,opioid_receptor_agonist,opioid_receptor_antagonist,orexin_receptor_antagonist,p38_mapk_inhibitor,p-glycoprotein_inhibitor,parp_inhibitor,pdgfr_inhibitor,pdk_inhibitor,phosphodiesterase_inhibitor,phospholipase_inhibitor,pi3k_inhibitor,pkc_inhibitor,potassium_channel_activator,potassium_channel_antagonist,ppar_receptor_agonist,ppar_receptor_antagonist,progesterone_receptor_agonist,progesterone_receptor_antagonist,prostaglandin_inhibitor,prostanoid_receptor_antagonist,proteasome_inhibitor,protein_kinase_inhibitor,protein_phosphatase_inhibitor,protein_synthesis_inhibitor,protein_tyrosine_kinase_inhibitor,radiopaque_medium,raf_inhibitor,ras_gtpase_inhibitor,retinoid_receptor_agonist,retinoid_receptor_antagonist,rho_associated_kinase_inhibitor,ribonucleoside_reductase_inhibitor,rna_polymerase_inhibitor,serotonin_receptor_agonist,serotonin_receptor_antagonist,serotonin_reuptake_inhibitor,sigma_receptor_agonist,sigma_receptor_antagonist,smoothened_receptor_antagonist,sodium_channel_inhibitor,sphingosine_receptor_agonist,src_inhibitor,steroid,syk_inhibitor,tachykinin_antagonist,tgf-beta_receptor_inhibitor,thrombin_inhibitor,thymidylate_synthase_inhibitor,tlr_agonist,tlr_antagonist,tnf_inhibitor,topoisomerase_inhibitor,transient_receptor_potential_channel_antagonist,tropomyosin_receptor_kinase_inhibitor,trpv_agonist,trpv_antagonist,tubulin_inhibitor,tyrosine_kinase_inhibitor,ubiquitin_specific_protease_inhibitor,vegfr_inhibitor,vitamin_b,vitamin_d_receptor_agonist,wnt_inhibitor
0,trt_cp,48,D2,-0.3555,0.3902,0.0050,0.0950,0.1351,-0.2835,-0.2565,-0.0532,0.2592,0.7135,0.4747,-0.6239,0.2018,-0.1420,-0.3456,-0.2961,-0.3488,0.1373,-0.2413,0.0734,-0.6593,0.3183,-0.2404,0.2014,1.5200,-0.0887,-0.6887,0.1626,0.1098,-0.0240,0.8374,0.1531,0.5290,-0.6963,0.9207,-0.2149,-0.8954,0.2526,-0.1183,0.1416,-0.6763,-0.5903,-0.3164,-0.5874,1.1140,-2.3500,-0.1887,-0.3254,-0.5482,0.6300,0.0626,0.1518,0.8537,0.5780,-0.7709,0.2591,-0.2620,-0.9450,0.1842,0.5286,0.1809,-0.2356,0.2918,-0.7138,-0.1708,-0.1672,-0.4373,0.2758,1.1210,1.5690,0.8734,-2.2590,-0.3070,0.6789,0.0111,-0.3880,-0.2808,-0.0963,-0.0193,0.5728,-0.9663,-0.5565,-1.0260,-0.6029,0.0754,0.0651,-0.4225,0.1869,0.4791,0.4584,-0.2731,-0.8058,-0.2124,-0.5031,0.0988,-1.4510,1.0210,-1.2380,1.2250,0.0565,-0.4796,-0.3923,0.3458,0.0652,0.0000,-0.6582,-0.1141,-0.0848,0.1475,-0.1804,-0.5957,0.3814,0.0528,-0.0001,0.6026,0.2501,-0.4053,0.3438,-0.0950,0.0259,-0.0284,0.2232,-0.1144,-0.1218,0.2352,0.5519,-0.8171,0.2914,-0.2021,-0.3307,-0.6862,0.4072,-0.1030,-0.6991,0.4457,-0.3372,-0.2034,-0.4600,-0.3185,-0.5920,-0.0274,0.0305,-0.9506,0.2910,0.0000,-0.0013,-0.2691,-0.5096,0.0075,-1.0360,0.4533,0.1531,-0.0454,0.6134,1.5180,-0.1440,0.4079,0.4017,0.2876,0.3030,0.8757,0.4940,-0.1075,-0.3880,0.4874,-0.1868,-0.5645,-0.2970,-0.6053,0.3837,-0.0816,-0.1555,-0.4263,0.5797,-0.5076,-0.2749,0.4535,-1.0550,0.2017,-0.0201,0.5193,-0.6331,3.8250,0.4185,-0.2279,-0.5598,0.4445,0.3929,0.4325,0.1752,-0.5342,-0.3736,-0.1206,0.4984,0.4036,0.9432,-0.4737,-0.4272,-0.2164,0.5288,-0.4795,0.1157,0.1129,0.5610,-0.9186,0.7495,0.0678,0.4199,-0.0335,-0.2376,-0.2479,-0.0488,-0.3946,0.0132,-0.8419,0.0572,0.8624,-1.0220,-0.2983,0.0209,-0.4528,-0.4664,-0.0296,-0.3726,1.3030,-0.0837,-0.2332,-0.3974,0.5073,0.0867,-0.6306,0.5625,0.5406,0.7968,1.1550,-0.5388,0.0481,0.2801,-0.6169,0.5789,-0.3661,-0.1869,-0.2226,-0.1426,-0.2040,-0.1247,-0.9869,-1.8960,-0.3989,-0.0658,-0.0879,0.6606,0.0798,0.3844,-0.9204,0.5044,-0.2748,-0.0336,-0.7053,0.0573,-0.5483,0.1521,-0.0372,1.0650,0.0152,-0.3146,-0.9401,0.0414,-0.6808,-0.5971,0.4609,-0.4424,-0.4441,0.8311,0.3052,0.3041,1.1250,0.2361,-0.1495,0.6155,0.1407,-0.7693,-0.6332,0.7084,-0.5222,-0.1477,-0.0036,-0.4236,-0.2796,0.1610,0.3141,0.0906,-0.1005,-0.0826,-0.7139,1.6180,-0.4011,0.2632,1.3140,-0.2790,0.4342,-0.2880,0.0731,-0.1851,-0.2742,-0.3670,0.6385,-0.2219,0.9304,0.5010,0.1516,-0.4286,-2.4270,-0.0095,-0.1278,-1.3100,0.3397,0.2868,-0.0952,0.3015,-0.3884,-0.0114,0.4304,-0.1433,0.1816,0.4147,0.0725,0.1188,-0.2128,0.796,-0.5943,0.2857,0.3929,-0.5444,-0.0488,-0.3119,0.0988,-0.4766,0.4941,-0.4734,-0.1534,0.1335,0.0800,-0.2772,-0.4426,1.1190,-0.4997,0.7593,0.3167,0.3067,-0.3591,0.2328,-0.2221,0.5468,-0.3835,0.3339,-0.6587,0.2229,0.4666,-0.1336,-0.3993,-0.1150,0.3516,-0.1490,-0.5021,-0.0277,-0.2170,0.1258,-0.3552,0.2208,-0.2146,-0.5280,0.0487,-0.0018,1.4990,-0.8145,0.0706,-0.1329,-0.9980,0.2157,1.1070,-0.3759,-0.1013,0.2819,-0.6896,0.2327,-0.0495,-0.1329,-0.0468,0.5021,-0.7889,-0.0864,-1.0930,0.4819,0.1524,0.1615,0.3866,0.5298,-0.4852,-0.0720,-0.2936,-0.0556,-0.6021,0.1196,-0.3352,0.3646,-0.7133,-0.0403,-0.3139,-0.3661,-0.4361,0.1632,0.4690,0.4612,0.1072,-0.1570,-0.7403,-0.9380,0.0593,0.2194,-0.1659,0.6683,0.0576,0.1155,0.5963,0.1812,-0.4123,-0.2009,0.2530,-0.1277,-0.5341,0.4209,0.3369,-0.0352,0.2234,-0.8235,0.1185,-0.4203,0.7717,-1.3300,0.1588,0.6037,0.1437,-0.6932,0.3012,0.0713,0.6593,0.6559,-0.8339,0.2664,0.6254,0.9844,0.3276,0.2609,-0.2532,0.4330,0.6795,-0.5997,-0.4709,0.3574,-0.2873,1.0180,-0.4067,0.6651,0.5796,0.6373,1.0340,-0.6833,-0.1954,-0.0143,-0.1224,0.4788,0.7437,0.3426,-5.0690,-1.9920,0.5181,-0.0939,-0.3919,0.2581,-0.3628,0.2621,-0.4010,-0.7948,0.2457,0.0326,0.0934,-0.2912,0.1899,-0.2798,0.0650,-0.0698,-0.1970,0.4384,0.3282,0.2953,0.4539,0.6274,-0.1230,0.5900,0.5310,0.1333,-0.1323,0.3044,-0.0068,0.1849,-0.5238,-0.2246,0.3629,0.1602,-0.2322,0.0467,-0.0026,0.3430,-0.2750,-0.1069,0.7898,0.6812,0.2593,0.6021,-0.2212,0.0092,-0.1770,-0.4929,0.1193,0.6374,-0.3857,0.6123,-0.6162,0.1276,0.1831,0.0781,-0.1772,-0.1968,0.6909,-0.3809,0.4030,-0.7316,0.3467,0.3772,0.3584,0.5212,-0.4981,-0.5059,-0.2383,0.1998,-0.4613,-0.3417,0.0175,-0.0582,-0.2522,0.6014,-0.6682,-0.0578,-0.6354,0.2910,0.5289,-0.0823,1.3250,-0.4256,0.1256,-0.1702,1.0530,-0.4649,-0.1086,-0.2387,0.2549,0.5959,0.1703,0.4714,0.0357,-0.1705,0.4720,-0.3373,0.1592,-1.2400,0.0197,0.3013,0.5362,-0.4105,-0.0734,0.2943,-0.2613,0.4377,0.2002,-1.4760,0.4067,-0.0806,0.1838,-0.1798,-0.3858,0.2029,0.4634,-0.2270,0.1287,1.3150,-0.3600,-0.0338,0.0871,0.1983,-1.1150,-0.0598,0.4409,0.4967,-0.3976,0.4020,0.7692,0.0774,-0.1862,-0.0599,0.4784,0.1430,0.1377,0.6322,1.0730,-0.0708,-0.0929,-0.0506,0.2957,0.0627,0.0558,-0.0638,0.0068,0.2121,-0.4599,-0.8507,0.0938,0.1542,-0.0468,-0.0203,0.2216,-0.0464,-0.1745,-0.0753,0.1488,0.1437,-0.1012,-0.9577,0.1161,0.4153,-0.2868,0.4384,-0.0731,-0.3038,-0.3079,0.0769,0.4154,-0.4166,0.2264,-0.9852,0.0221,-0.4625,0.7895,-0.7151,-0.2388,0.1439,0.5257,-0.2817,-0.0629,0.2248,-0.9178,0.5150,-0.1700,-0.1079,0.3522,-0.0907,-0.2978,-0.1550,0.6772,0.5515,-0.6141,-0.0986,-0.4367,-0.0827,-0.3929,-0.2762,0.0728,0.1013,-0.3155,0.0512,-0.6893,-0.1448,1.0440,0.0935,-0.9710,-0.1838,-0.2607,-0.3929,-0.4239,0.2709,0.2928,0.7596,0.0166,-0.6870,-0.2456,0.3119,0.5998,0.4845,-0.0081,-0.2144,0.0688,0.2609,0.3207,1.3050,2.7870,0.0936,-0.3120,-0.3372,-1.1000,1.4860,-0.6019,-0.6484,-1.0840,2.4980,-0.4222,0.7238,0.3165,-0.0664,0.0000,-1.3440,0.1557,-0.3018,0.5359,0.0063,-0.4096,-0.1320,0.4374,0.4829,0.0838,6.2970,0.2817,0.0462,0.0169,-0.3322,-0.0854,-0.9425,0.2813,0.8164,0.2215,0.3743,-0.0454,-0.1528,-0.3394,0.0746,-0.4733,0.3330,-0.8158,-0.5635,-0.0576,-0.4076,0.0656,0.1612,0.2512,0.3893,0.0321,0.3704,1.2740,0.1537,0.3476,-0.3169,-0.3015,0.2749,-0.0950,-1.1660,0.1581,0.2432,-0.1851,-0.2291,0.2380,0.2498,-0.0582,0.2888,-0.0821,-0.5701,0.0936,0.0154,0.3964,0.0084,0.0921,0.5716,0.1466,0.3960,0.1634,0.2322,1.2020,0.3369,-0.2218,0.5470,-0.3334,0.1261,-0.5852,-0.2508,0.7471,0.3260,0.4212,0.1325,-0.0486,0.6564,0.0524,0.0224,0.4575,0.7006,0.4444,0.0964,-0.1382,0.4514,-0.9959,0.9245,-0.1438,-0.5770,0.6305,-0.4197,-0.1645,0.0572,-0.1159,0.2904,-0.3969,0.5718,0.6256,0.2385,-0.3830,1.3920,0.8380,-0.9898,0.1703,0.4633,0.3427,0.4273,0.4686,0.2925,-0.7758,0.6909,-0.8665,0.0096,-0.0901,0.1288,-0.2346,0.6453,0.8311,0.7664,0.0129,0.6354,-0.0505,0.6970,-0.0036,0.3672,-0.5071,0.4762,0.7797,0.2960,0.3659,-0.3068,-0.2990,0.1808,0.1909,-0.9424,0.3796,0.4456,0.1268,0.2448,-0.0101,-0.6606,0.5282,0.1966,0.5799,0.7647,0.2427,-0.1676,-0.3130,-0.2610,0.6027,0.4509,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## Data Checks

In [4]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 23,814
Columns: 1081
Use sampling: False (sample size: 23,814)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['g-175', 'g-723', 'c-50', 'g-231', 'c-57', 'c-47', 'c-9', 'g-486', 'g-745', 'c-26']
Rows remaining as candidates after top-10 filter: 0 (of 23,814)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [5]:
# Sample Rows
df_head

,cp_type,cp_time,cp_dose,g-0,g-1,g-2,g-3,g-4,g-5,g-6,g-7,g-8,g-9,g-10,g-11,g-12,g-13,g-14,g-15,g-16,g-17,g-18,g-19,g-20,g-21,g-22,g-23,g-24,g-25,g-26,g-27,g-28,g-29,g-30,g-31,g-32,g-33,g-34,g-35,g-36,g-37,g-38,g-39,g-40,g-41,g-42,g-43,g-44,g-45,g-46,g-47,g-48,g-49,g-50,g-51,g-52,g-53,g-54,g-55,g-56,g-57,g-58,g-59,g-60,g-61,g-62,g-63,g-64,g-65,g-66,g-67,g-68,g-69,g-70,g-71,g-72,g-73,g-74,g-75,g-76,g-77,g-78,g-79,g-80,g-81,g-82,g-83,g-84,g-85,g-86,g-87,g-88,g-89,g-90,g-91,g-92,g-93,g-94,g-95,g-96,g-97,g-98,g-99,g-100,g-101,g-102,g-103,g-104,g-105,g-106,g-107,g-108,g-109,g-110,g-111,g-112,g-113,g-114,g-115,g-116,g-117,g-118,g-119,g-120,g-121,g-122,g-123,g-124,g-125,g-126,g-127,g-128,g-129,g-130,g-131,g-132,g-133,g-134,g-135,g-136,g-137,g-138,g-139,g-140,g-141,g-142,g-143,g-144,g-145,g-146,g-147,g-148,g-149,g-150,g-151,g-152,g-153,g-154,g-155,g-156,g-157,g-158,g-159,g-160,g-161,g-162,g-163,g-164,g-165,g-166,g-167,g-168,g-169,g-170,g-171,g-172,g-173,g-174,g-175,g-176,g-177,g-178,g-179,g-180,g-181,g-182,g-183,g-184,g-185,g-186,g-187,g-188,g-189,g-190,g-191,g-192,g-193,g-194,g-195,g-196,g-197,g-198,g-199,g-200,g-201,g-202,g-203,g-204,g-205,g-206,g-207,g-208,g-209,g-210,g-211,g-212,g-213,g-214,g-215,g-216,g-217,g-218,g-219,g-220,g-221,g-222,g-223,g-224,g-225,g-226,g-227,g-228,g-229,g-230,g-231,g-232,g-233,g-234,g-235,g-236,g-237,g-238,g-239,g-240,g-241,g-242,g-243,g-244,g-245,g-246,g-247,g-248,g-249,g-250,g-251,g-252,g-253,g-254,g-255,g-256,g-257,g-258,g-259,g-260,g-261,g-262,g-263,g-264,g-265,g-266,g-267,g-268,g-269,g-270,g-271,g-272,g-273,g-274,g-275,g-276,g-277,g-278,g-279,g-280,g-281,g-282,g-283,g-284,g-285,g-286,g-287,g-288,g-289,g-290,g-291,g-292,g-293,g-294,g-295,g-296,g-297,g-298,g-299,g-300,g-301,g-302,g-303,g-304,g-305,g-306,g-307,g-308,g-309,g-310,g-311,g-312,g-313,g-314,g-315,g-316,g-317,g-318,g-319,g-320,g-321,g-322,g-323,g-324,g-325,g-326,g-327,g-328,g-329,g-330,g-331,g-332,g-333,g-334,g-335,g-336,g-337,g-338,g-339,g-340,g-341,g-342,g-343,g-344,g-345,g-346,g-347,g-348,g-349,g-350,g-351,g-352,g-353,g-354,g-355,g-356,g-357,g-358,g-359,g-360,g-361,g-362,g-363,g-364,g-365,g-366,g-367,g-368,g-369,g-370,g-371,g-372,g-373,g-374,g-375,g-376,g-377,g-378,g-379,g-380,g-381,g-382,g-383,g-384,g-385,g-386,g-387,g-388,g-389,g-390,g-391,g-392,g-393,g-394,g-395,g-396,g-397,g-398,g-399,g-400,g-401,g-402,g-403,g-404,g-405,g-406,g-407,g-408,g-409,g-410,g-411,g-412,g-413,g-414,g-415,g-416,g-417,g-418,g-419,g-420,g-421,g-422,g-423,g-424,g-425,g-426,g-427,g-428,g-429,g-430,g-431,g-432,g-433,g-434,g-435,g-436,g-437,g-438,g-439,g-440,g-441,g-442,g-443,g-444,g-445,g-446,g-447,g-448,g-449,g-450,g-451,g-452,g-453,g-454,g-455,g-456,g-457,g-458,g-459,g-460,g-461,g-462,g-463,g-464,g-465,g-466,g-467,g-468,g-469,g-470,g-471,g-472,g-473,g-474,g-475,g-476,g-477,g-478,g-479,g-480,g-481,g-482,g-483,g-484,g-485,g-486,g-487,g-488,g-489,g-490,g-491,g-492,g-493,g-494,g-495,g-496,g-497,g-498,g-499,g-500,g-501,g-502,g-503,g-504,g-505,g-506,g-507,g-508,g-509,g-510,g-511,g-512,g-513,g-514,g-515,g-516,g-517,g-518,g-519,g-520,g-521,g-522,g-523,g-524,g-525,g-526,g-527,g-528,g-529,g-530,g-531,g-532,g-533,g-534,g-535,g-536,g-537,g-538,g-539,g-540,g-541,g-542,g-543,g-544,g-545,g-546,g-547,g-548,g-549,g-550,g-551,g-552,g-553,g-554,g-555,g-556,g-557,g-558,g-559,g-560,g-561,g-562,g-563,g-564,g-565,g-566,g-567,g-568,g-569,g-570,g-571,g-572,g-573,g-574,g-575,g-576,g-577,g-578,g-579,g-580,g-581,g-582,g-583,g-584,g-585,g-586,g-587,g-588,g-589,g-590,g-591,g-592,g-593,g-594,g-595,g-596,g-597,g-598,g-599,g-600,g-601,g-602,g-603,g-604,g-605,g-606,g-607,g-608,g-609,g-610,g-611,g-612,g-613,g-614,g-615,g-616,g-617,g-618,g-619,g-620,g-621,g-622,g-623,g-624,g-625,g-626,g-627,g-628,g-629,g-630,g-631,g-632,g-633,g-634,g-635,g-636,g-637,g-638,g-639,g-640,g-641,g-642,g-643,g-644,g-645,g-646,g-647,g-648,g-649,g-650,g-651,g-652,g-653,g-654,g-655,g-656,g-657,g-658,g-659,g-660,g-661,g-662,g-663,g-664,g-665,g-666,g-667,g-668,g-669,g-670,g-671,g-672,g-673,g-674,g-675,g-676,g-677,g-678,g-679,g-680,g-681,g-682,g-683,g-684,g-685,g-686,g-687,g-688,g-689,g-690,g-691,g-692,g-693,g-694,g-695,g-696,g-697,g-698,g-699,g-700,g-701,g-702,g-703,g-704,g-705,g-706,g-707,g-708,g-709,g-710,g-711,g-712,g-713,g-714,g-715,g-716,g-717,g-718,g-719,g-720,g-721,g-722,g-723,g-724,g-725,g-726,g-727,g-728,g-729,g-730,g-731,g-732,g-733,g-734,g-735,g-736,g-737,g-738,g-739,g-740,g-741,g-742,g-743,g-744,g-745,g-746,g-747,g-748,g-749,g-750,g-751,g-752,g-753,g-754,g-755,g-756,g-757,g-758,g-759,g-760,g-761,g-762,g-763,g-764,g-765,g-766,g-767,g-768,g-769,g-770,g-771,c-0,c-1,c-2,c-3,c-4,c-5,c-6,c-7,c-8,c-9,c-10,c-11,c-12,c-13,c-14,c-15,c-16,c-17,c-18,c-19,c-20,c-21,c-22,c-23,c-24,c-25,c-26,c-27,c-28,c-29,c-30,c-31,c-32,c-33,c-34,c-35,c-36,c-37,c-38,c-39,c-40,c-41,c-42,c-43,c-44,c-45,c-46,c-47,c-48,c-49,c-50,c-51,c-52,c-53,c-54,c-55,c-56,c-57,c-58,c-59,c-60,c-61,c-62,c-63,c-64,c-65,c-66,c-67,c-68,c-69,c-70,c-71,c-72,c-73,c-74,c-75,c-76,c-77,c-78,c-79,c-80,c-81,c-82,c-83,c-84,c-85,c-86,c-87,c-88,c-89,c-90,c-91,c-92,c-93,c-94,c-95,c-96,c-97,c-98,c-99,5-alpha_reductase_inhibitor,11-beta-hsd1_inhibitor,acat_inhibitor,acetylcholine_receptor_agonist,acetylcholine_receptor_antagonist,acetylcholinesterase_inhibitor,adenosine_receptor_agonist,adenosine_receptor_antagonist,adenylyl_cyclase_activator,adrenergic_receptor_agonist,adrenergic_receptor_antagonist,akt_inhibitor,aldehyde_dehydrogenase_inhibitor,alk_inhibitor,ampk_activator,analgesic,androgen_receptor_agonist,androgen_receptor_antagonist,anesthetic_-_local,angiogenesis_inhibitor,angiotensin_receptor_antagonist,anti-inflammatory,antiarrhythmic,antibiotic,anticonvulsant,antifungal,antihistamine,antimalarial,antioxidant,antiprotozoal,antiviral,apoptosis_stimulant,aromatase_inhibitor,atm_kinase_inhibitor,atp-sensitive_potassium_channel_antagonist,atp_synthase_inhibitor,atpase_inhibitor,atr_kinase_inhibitor,aurora_kinase_inhibitor,autotaxin_inhibitor,bacterial_30s_ribosomal_subunit_inhibitor,bacterial_50s_ribosomal_subunit_inhibitor,bacterial_antifolate,bacterial_cell_wall_synthesis_inhibitor,bacterial_dna_gyrase_inhibitor,bacterial_dna_inhibitor,bacterial_membrane_integrity_inhibitor,bcl_inhibitor,bcr-abl_inhibitor,benzodiazepine_receptor_agonist,beta_amyloid_inhibitor,bromodomain_inhibitor,btk_inhibitor,calcineurin_inhibitor,calcium_channel_blocker,cannabinoid_receptor_agonist,cannabinoid_receptor_antagonist,carbonic_anhydrase_inhibitor,casein_kinase_inhibitor,caspase_activator,catechol_o_methyltransferase_inhibitor,cc_chemokine_receptor_antagonist,cck_receptor_antagonist,cdk_inhibitor,chelating_agent,chk_inhibitor,chloride_channel_blocker,cholesterol_inhibitor,cholinergic_receptor_antagonist,coagulation_factor_inhibitor,corticosteroid_agonist,cyclooxygenase_inhibitor,cytochrome_p450_inhibitor,dihydrofolate_reductase_inhibitor,dipeptidyl_peptidase_inhibitor,diuretic,dna_alkylating_agent,dna_inhibitor,dopamine_receptor_agonist,dopamine_receptor_antagonist,egfr_inhibitor,elastase_inhibitor,erbb2_inhibitor,estrogen_receptor_agonist,estrogen_receptor_antagonist,faah_inhibitor,farnesyltransferase_inhibitor,fatty_acid_receptor_agonist,fgfr_inhibitor,flt3_inhibitor,focal_adhesion_kinase_inhibitor,free_radical_scavenger,fungal_squalene_epoxidase_inhibitor,gaba_receptor_agonist,gaba_receptor_antagonist,gamma_secretase_inhibitor,glucocorticoid_receptor_agonist,glutamate_inhibitor,glutamate_receptor_agonist,glutamate_receptor_antagonist,gonadotropin_receptor_agonist,gsk_inhibitor,hcv_inhibitor,hdac_inhibitor,histamine_receptor_agonist,histamine_receptor_antagonist,histone_lysine_demethylase_inhibitor,histone_lysine_methyltransferase_inhibitor,hiv_inhibitor,hmgcr_inhibitor,hsp_inhibitor,igf-1_inhibitor,ikk_inhibitor,imidazoline_receptor_agonist,immunosuppressant,insulin_secretagogue,insulin_sensitizer,integrin_inhibitor,jak_inhibitor,kit_inhibitor,laxative,leukotriene_inhibitor,leukotriene_receptor_antagonist,lipase_inhibitor,lipoxygenase_inhibitor,lxr_agonist,mdm_inhibitor,mek_inhibitor,membrane_integrity_inhibitor,mineralocorticoid_receptor_antagonist,monoacylglycerol_lipase_inhibitor,monoamine_oxidase_inhibitor,monopolar_spindle_1_kinase_inhibitor,mtor_inhibitor,mucolytic_agent,neuropeptide_receptor_antagonist,nfkb_inhibitor,nicotinic_receptor_agonist,nitric_oxide_donor,nitric_oxide_production_inhibitor,nitric_oxide_synthase_inhibitor,norepinephrine_reuptake_inhibitor,nrf2_activator,opioid_receptor_agonist,opioid_receptor_antagonist,orexin_receptor_antagonist,p38_mapk_inhibitor,p-glycoprotein_inhibitor,parp_inhibitor,pdgfr_inhibitor,pdk_inhibitor,phosphodiesterase_inhibitor,phospholipase_inhibitor,pi3k_inhibitor,pkc_inhibitor,potassium_channel_activator,potassium_channel_antagonist,ppar_receptor_agonist,ppar_receptor_antagonist,progesterone_receptor_agonist,progesterone_receptor_antagonist,prostaglandin_inhibitor,prostanoid_receptor_antagonist,proteasome_inhibitor,protein_kinase_inhibitor,protein_phosphatase_inhibitor,protein_synthesis_inhibitor,protein_tyrosine_kinase_inhibitor,radiopaque_medium,raf_inhibitor,ras_gtpase_inhibitor,retinoid_receptor_agonist,retinoid_receptor_antagonist,rho_associated_kinase_inhibitor,ribonucleoside_reductase_inhibitor,rna_polymerase_inhibitor,serotonin_receptor_agonist,serotonin_receptor_antagonist,serotonin_reuptake_inhibitor,sigma_receptor_agonist,sigma_receptor_antagonist,smoothened_receptor_antagonist,sodium_channel_inhibitor,sphingosine_receptor_agonist,src_inhibitor,steroid,syk_inhibitor,tachykinin_antagonist,tgf-beta_receptor_inhibitor,thrombin_inhibitor,thymidylate_synthase_inhibitor,tlr_agonist,tlr_antagonist,tnf_inhibitor,topoisomerase_inhibitor,transient_receptor_potential_channel_antagonist,tropomyosin_receptor_kinase_inhibitor,trpv_agonist,trpv_antagonist,tubulin_inhibitor,tyrosine_kinase_inhibitor,ubiquitin_specific_protease_inhibitor,vegfr_inhibitor,vitamin_b,vitamin_d_receptor_agonist,wnt_inhibitor
0,trt_cp,48,D2,-0.3555,0.3902,0.0050,0.0950,0.1351,-0.2835,-0.2565,-0.0532,0.2592,0.7135,0.4747,-0.6239,0.2018,-0.1420,-0.3456,-0.2961,-0.3488,0.1373,-0.2413,0.0734,-0.6593,0.3183,-0.2404,0.2014,1.5200,-0.0887,-0.6887,0.1626,0.1098,-0.0240,0.8374,0.1531,0.5290,-0.6963,0.9207,-0.2149,-0.8954,0.2526,-0.1183,0.1416,-0.6763,-0.5903,-0.3164,-0.5874,1.1140,-2.3500,-0.1887,-0.3254,-0.5482,0.6300,0.0626,0.1518,0.8537,0.5780,-0.7709,0.2591,-0.2620,-0.9450,0.1842,0.5286,0.1809,-0.2356,0.2918,-0.7138,-0.1708,-0.1672,-0.4373,0.2758,1.1210,1.5690,0.8734,-2.2590,-0.3070,0.6789,0.0111,-0.3880,-0.2808,-0.0963,-0.0193,0.5728,-0.9663,-0.5565,-1.0260,-0.6029,0.0754,0.0651,-0.4225,0.1869,0.4791,0.4584,-0.2731,-0.8058,-0.2124,-0.5031,0.0988,-1.4510,1.0210,-1.2380,1.2250,0.0565,-0.4796,-0.3923,0.3458,0.0652,0.0000,-0.6582,-0.1141,-0.0848,0.1475,-0.1804,-0.5957,0.3814,0.0528,-0.0001,0.6026,0.2501,-0.4053,0.3438,-0.0950,0.0259,-0.0284,0.2232,-0.1144,-0.1218,0.2352,0.5519,-0.8171,0.2914,-0.2021,-0.3307,-0.6862,0.4072,-0.1030,-0.6991,0.4457,-0.3372,-0.2034,-0.4600,-0.3185,-0.5920,-0.0274,0.0305,-0.9506,0.2910,0.0000,-0.0013,-0.2691,-0.5096,0.0075,-1.0360,0.4533,0.1531,-0.0454,0.6134,1.5180,-0.1440,0.4079,0.4017,0.2876,0.3030,0.8757,0.4940,-0.1075,-0.3880,0.4874,-0.1868,-0.5645,-0.2970,-0.6053,0.3837,-0.0816,-0.1555,-0.4263,0.5797,-0.5076,-0.2749,0.4535,-1.0550,0.2017,-0.0201,0.5193,-0.6331,3.8250,0.4185,-0.2279,-0.5598,0.4445,0.3929,0.4325,0.1752,-0.5342,-0.3736,-0.1206,0.4984,0.4036,0.9432,-0.4737,-0.4272,-0.2164,0.5288,-0.4795,0.1157,0.1129,0.5610,-0.9186,0.7495,0.0678,0.4199,-0.0335,-0.2376,-0.2479,-0.0488,-0.3946,0.0132,-0.8419,0.0572,0.8624,-1.0220,-0.2983,0.0209,-0.4528,-0.4664,-0.0296,-0.3726,1.3030,-0.0837,-0.2332,-0.3974,0.5073,0.0867,-0.6306,0.5625,0.5406,0.7968,1.1550,-0.5388,0.0481,0.2801,-0.6169,0.5789,-0.3661,-0.1869,-0.2226,-0.1426,-0.2040,-0.1247,-0.9869,-1.8960,-0.3989,-0.0658,-0.0879,0.6606,0.0798,0.3844,-0.9204,0.5044,-0.2748,-0.0336,-0.7053,0.0573,-0.5483,0.1521,-0.0372,1.0650,0.0152,-0.3146,-0.9401,0.0414,-0.6808,-0.5971,0.4609,-0.4424,-0.4441,0.8311,0.3052,0.3041,1.1250,0.2361,-0.1495,0.6155,0.1407,-0.7693,-0.6332,0.7084,-0.5222,-0.1477,-0.0036,-0.4236,-0.2796,0.1610,0.3141,0.0906,-0.1005,-0.0826,-0.7139,1.6180,-0.4011,0.2632,1.3140,-0.2790,0.4342,-0.2880,0.0731,-0.1851,-0.2742,-0.3670,0.6385,-0.2219,0.9304,0.5010,0.1516,-0.4286,-2.4270,-0.0095,-0.1278,-1.3100,0.3397,0.2868,-0.0952,0.3015,-0.3884,-0.0114,0.4304,-0.1433,0.1816,0.4147,0.0725,0.1188,-0.2128,0.796,-0.5943,0.2857,0.3929,-0.5444,-0.0488,-0.3119,0.0988,-0.4766,0.4941,-0.4734,-0.1534,0.1335,0.0800,-0.2772,-0.4426,1.1190,-0.4997,0.7593,0.3167,0.3067,-0.3591,0.2328,-0.2221,0.5468,-0.3835,0.3339,-0.6587,0.2229,0.4666,-0.1336,-0.3993,-0.1150,0.3516,-0.1490,-0.5021,-0.0277,-0.2170,0.1258,-0.3552,0.2208,-0.2146,-0.5280,0.0487,-0.0018,1.4990,-0.8145,0.0706,-0.1329,-0.9980,0.2157,1.1070,-0.3759,-0.1013,0.2819,-0.6896,0.2327,-0.0495,-0.1329,-0.0468,0.5021,-0.7889,-0.0864,-1.0930,0.4819,0.1524,0.1615,0.3866,0.5298,-0.4852,-0.0720,-0.2936,-0.0556,-0.6021,0.1196,-0.3352,0.3646,-0.7133,-0.0403,-0.3139,-0.3661,-0.4361,0.1632,0.4690,0.4612,0.1072,-0.1570,-0.7403,-0.9380,0.0593,0.2194,-0.1659,0.6683,0.0576,0.1155,0.5963,0.1812,-0.4123,-0.2009,0.2530,-0.1277,-0.5341,0.4209,0.3369,-0.0352,0.2234,-0.8235,0.1185,-0.4203,0.7717,-1.3300,0.1588,0.6037,0.1437,-0.6932,0.3012,0.0713,0.6593,0.6559,-0.8339,0.2664,0.6254,0.9844,0.3276,0.2609,-0.2532,0.4330,0.6795,-0.5997,-0.4709,0.3574,-0.2873,1.0180,-0.4067,0.6651,0.5796,0.6373,1.0340,-0.6833,-0.1954,-0.0143,-0.1224,0.4788,0.7437,0.3426,-5.0690,-1.9920,0.5181,-0.0939,-0.3919,0.2581,-0.3628,0.2621,-0.4010,-0.7948,0.2457,0.0326,0.0934,-0.2912,0.1899,-0.2798,0.0650,-0.0698,-0.1970,0.4384,0.3282,0.2953,0.4539,0.6274,-0.1230,0.5900,0.5310,0.1333,-0.1323,0.3044,-0.0068,0.1849,-0.5238,-0.2246,0.3629,0.1602,-0.2322,0.0467,-0.0026,0.3430,-0.2750,-0.1069,0.7898,0.6812,0.2593,0.6021,-0.2212,0.0092,-0.1770,-0.4929,0.1193,0.6374,-0.3857,0.6123,-0.6162,0.1276,0.1831,0.0781,-0.1772,-0.1968,0.6909,-0.3809,0.4030,-0.7316,0.3467,0.3772,0.3584,0.5212,-0.4981,-0.5059,-0.2383,0.1998,-0.4613,-0.3417,0.0175,-0.0582,-0.2522,0.6014,-0.6682,-0.0578,-0.6354,0.2910,0.5289,-0.0823,1.3250,-0.4256,0.1256,-0.1702,1.0530,-0.4649,-0.1086,-0.2387,0.2549,0.5959,0.1703,0.4714,0.0357,-0.1705,0.4720,-0.3373,0.1592,-1.2400,0.0197,0.3013,0.5362,-0.4105,-0.0734,0.2943,-0.2613,0.4377,0.2002,-1.4760,0.4067,-0.0806,0.1838,-0.1798,-0.3858,0.2029,0.4634,-0.2270,0.1287,1.3150,-0.3600,-0.0338,0.0871,0.1983,-1.1150,-0.0598,0.4409,0.4967,-0.3976,0.4020,0.7692,0.0774,-0.1862,-0.0599,0.4784,0.1430,0.1377,0.6322,1.0730,-0.0708,-0.0929,-0.0506,0.2957,0.0627,0.0558,-0.0638,0.0068,0.2121,-0.4599,-0.8507,0.0938,0.1542,-0.0468,-0.0203,0.2216,-0.0464,-0.1745,-0.0753,0.1488,0.1437,-0.1012,-0.9577,0.1161,0.4153,-0.2868,0.4384,-0.0731,-0.3038,-0.3079,0.0769,0.4154,-0.4166,0.2264,-0.9852,0.0221,-0.4625,0.7895,-0.7151,-0.2388,0.1439,0.5257,-0.2817,-0.0629,0.2248,-0.9178,0.5150,-0.1700,-0.1079,0.3522,-0.0907,-0.2978,-0.1550,0.6772,0.5515,-0.6141,-0.0986,-0.4367,-0.0827,-0.3929,-0.2762,0.0728,0.1013,-0.3155,0.0512,-0.6893,-0.1448,1.0440,0.0935,-0.9710,-0.1838,-0.2607,-0.3929,-0.4239,0.2709,0.2928,0.7596,0.0166,-0.6870,-0.2456,0.3119,0.5998,0.4845,-0.0081,-0.2144,0.0688,0.2609,0.3207,1.3050,2.7870,0.0936,-0.3120,-0.3372,-1.1000,1.4860,-0.6019,-0.6484,-1.0840,2.4980,-0.4222,0.7238,0.3165,-0.0664,0.0000,-1.3440,0.1557,-0.3018,0.5359,0.0063,-0.4096,-0.1320,0.4374,0.4829,0.0838,6.2970,0.2817,0.0462,0.0169,-0.3322,-0.0854,-0.9425,0.2813,0.8164,0.2215,0.3743,-0.0454,-0.1528,-0.3394,0.0746,-0.4733,0.3330,-0.8158,-0.5635,-0.0576,-0.4076,0.0656,0.1612,0.2512,0.3893,0.0321,0.3704,1.2740,0.1537,0.3476,-0.3169,-0.3015,0.2749,-0.0950,-1.1660,0.1581,0.2432,-0.1851,-0.2291,0.2380,0.2498,-0.0582,0.2888,-0.0821,-0.5701,0.0936,0.0154,0.3964,0.0084,0.0921,0.5716,0.1466,0.3960,0.1634,0.2322,1.2020,0.3369,-0.2218,0.5470,-0.3334,0.1261,-0.5852,-0.2508,0.7471,0.3260,0.4212,0.1325,-0.0486,0.6564,0.0524,0.0224,0.4575,0.7006,0.4444,0.0964,-0.1382,0.4514,-0.9959,0.9245,-0.1438,-0.5770,0.6305,-0.4197,-0.1645,0.0572,-0.1159,0.2904,-0.3969,0.5718,0.6256,0.2385,-0.3830,1.3920,0.8380,-0.9898,0.1703,0.4633,0.3427,0.4273,0.4686,0.2925,-0.7758,0.6909,-0.8665,0.0096,-0.0901,0.1288,-0.2346,0.6453,0.8311,0.7664,0.0129,0.6354,-0.0505,0.6970,-0.0036,0.3672,-0.5071,0.4762,0.7797,0.2960,0.3659,-0.3068,-0.2990,0.1808,0.1909,-0.9424,0.3796,0.4456,0.1268,0.2448,-0.0101,-0.6606,0.5282,0.1966,0.5799,0.7647,0.2427,-0.1676,-0.3130,-0.2610,0.6027,0.4509,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [6]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,cp_type,category,0.0,0.0,2.0,"trt_cp, ctl_vehicle"
1,cp_time,category,0.0,0.0,3.0,"48, 72, 24"
2,cp_dose,category,0.0,0.0,2.0,"D1, D2"
3,g-0,float64,0.0,0.0,14367.0,"0.0, -0.3372, 10.0, -1.004, -1.085, -1.086, -1.326, -0.6745, -0.3246, -1.041"
4,g-1,float64,0.0,0.0,13893.0,"-1.14, -1.145, -1.138, -1.013, -1.333, -1.026, -1.034, -1.12, -1.32, -1.05"
5,g-2,float64,0.0,0.0,14210.0,"1.1, 1.122, 1.018, 1.083, 1.095, -0.0192, 1.03, 0.0, 1.023, 1.047"
6,g-3,float64,0.0,0.0,12793.0,"0.0, 0.3372, -0.3372, -1.084, -0.0766, -0.0529, -0.0034, -0.1295, -0.0371, 0.0759"
7,g-4,float64,0.0,0.0,14038.0,"0.0, -1.018, -1.129, 1.017, -1.084, -0.0693, -0.0232, -1.151, -1.02, -1.135"
8,g-5,float64,0.0,0.0,14375.0,"0.0, -1.416, -1.207, 1.016, -1.108, 1.009, 1.042, 1.092, -1.074, 1.163"
9,g-6,float64,0.0,0.0,13741.0,"0.0, -0.3372, -1.013, 0.3372, -1.072, 1.069, -1.148, -1.109, 1.218, -0.6745"
10,g-7,float64,0.0,0.0,14106.0,"0.0, 1.062, 0.3372, -1.028, -1.007, -1.198, -1.149, -1.043, -1.09, -1.058"
11,g-8,float64,0.0,0.0,14583.0,"-10.0, 1.041, 1.023, 1.004, 1.084, 1.177, 1.13, -1.046, 1.17, 1.111"
12,g-9,float64,0.0,0.0,14081.0,"1.053, 1.052, 1.006, 1.204, 0.0, 1.022, 1.075, 1.01, 1.105, 1.232"
13,g-10,float64,0.0,0.0,14316.0,"0.0, 0.3372, 1.035, 1.054, -1.009, 1.164, -1.041, 1.015, 0.2803, 1.01"
14,g-11,float64,0.0,0.0,14385.0,"0.0, -1.204, -1.153, -1.027, -1.053, -1.142, 1.089, -1.037, 1.113, -1.01"
15,g-12,float64,0.0,0.0,14274.0,"0.0, -0.3372, 0.3372, -1.08, 1.232, 1.006, 1.058, 1.025, 1.086, 0.6745"
16,g-13,float64,0.0,0.0,14186.0,"0.0, 10.0, 0.3372, -0.3372, 0.6745, -1.044, -1.002, 1.086, 1.013, -1.184"
17,g-14,float64,0.0,0.0,14400.0,"0.0, -1.054, -1.234, 1.196, -1.097, 1.108, 1.002, -1.222, -1.023, -1.099"
18,g-15,float64,0.0,0.0,10757.0,"0.0, 0.3372, -0.3426, 0.2937, -0.0674, -0.3372, 0.0516, 0.029, -0.2138, 0.3575"
19,g-16,float64,0.0,0.0,14306.0,"0.0, 1.084, 1.064, 1.201, 1.32, 1.225, 1.347, 1.388, 1.065, 1.54"
20,g-17,float64,0.0,0.0,13868.0,"0.0, 0.3372, -0.3372, 1.048, 0.0421, 0.1878, 1.021, 1.023, 1.045, 0.7517"
21,g-18,float64,0.0,0.0,8055.0,"0.0, -0.3372, 0.3372, -0.1407, -0.0772, -0.2314, -0.0769, -0.1409, -0.3426, -0.1059"
22,g-19,float64,0.0,0.0,11075.0,"0.0, 0.3372, -0.3372, 0.2695, 0.6745, 0.4809, 0.4502, 0.2334, 0.1063, -0.235"
23,g-20,float64,0.0,0.0,14440.0,"0.0, -0.3372, -1.108, 1.099, 1.014, 1.022, 1.16, 1.405, -1.023, -1.117"
24,g-21,float64,0.0,0.0,13332.0,"0.0, -0.3372, -0.4137, 0.3372, 0.3022, -1.049, -1.024, -1.073, -1.025, 1.125"
25,g-22,float64,0.0,0.0,12380.0,"0.0, -0.0196, 0.0783, -0.0661, -0.1494, -0.2735, -0.3372, 0.3372, -1.095, 0.088"
26,g-23,float64,0.0,0.0,6079.0,"0.0, 0.3372, -0.3372, 0.3711, 0.2826, -0.915, 0.0003, -0.2873, 0.6745, 0.2195"
27,g-24,float64,0.0,0.0,14205.0,"0.0, 1.107, 1.086, 1.013, 1.039, -1.352, 1.068, 1.007, 1.002, -1.001"
28,g-25,float64,0.0,0.0,13960.0,"0.3372, 0.0, -1.028, -1.024, -1.056, -0.0411, 0.0338, 1.023, -1.049, -1.127"
29,g-26,float64,0.0,0.0,13838.0,"0.0, -0.3372, 0.3372, -1.133, 1.151, -1.043, -1.063, 1.08, 0.1582, 1.038"
30,g-27,float64,0.0,0.0,14018.0,"0.0, -1.123, -1.055, -1.107, 1.281, -1.154, 1.003, 1.172, 1.215, 1.191"
31,g-28,float64,0.0,0.0,11230.0,"0.0, -0.3372, 0.0624, -0.1376, 0.3372, -0.0992, 0.1066, -0.1784, -0.1137, -0.026"
32,g-29,float64,0.0,0.0,14174.0,"0.0, 0.3372, -0.3372, -1.003, -1.089, -1.072, 1.118, -1.233, 1.004, -1.013"
33,g-30,float64,0.0,0.0,13474.0,"0.0, -0.3372, 0.3372, 0.2668, 0.6745, 0.1089, -0.0611, 1.041, -0.6745, -0.1956"
34,g-31,float64,0.0,0.0,12104.0,"0.0, 10.0, -0.3372, -0.0732, -0.0263, 0.3372, 0.1804, -0.1734, -0.3285, -0.0192"
35,g-32,float64,0.0,0.0,13842.0,"-1.105, -1.103, 0.0, -1.014, -1.024, -1.128, -1.065, 1.039, -1.142, -1.185"
36,g-33,float64,0.0,0.0,14282.0,"0.0, 1.021, 1.035, 0.3372, 1.026, 1.019, 1.014, 1.384, -1.096, -1.037"
37,g-34,float64,0.0,0.0,14185.0,"1.05, -1.223, -1.062, 10.0, 0.0, 1.045, -1.083, -1.237, -1.066, 0.147"
38,g-35,float64,0.0,0.0,14232.0,"0.0, 1.1, 1.082, -1.072, 1.19, 1.255, 0.0215, -1.089, -1.028, 1.123"
39,g-36,float64,0.0,0.0,14387.0,"-10.0, 0.0, 1.027, 0.3372, -1.017, 1.066, 1.067, -1.145, 1.047, 1.132"
40,g-37,float64,0.0,0.0,14575.0,"-10.0, 0.0, 0.3372, -1.014, 1.065, -1.158, 1.027, 1.095, 1.204, 0.2867"
41,g-38,float64,0.0,0.0,14580.0,"10.0, 0.0, -1.003, -1.106, -1.01, -1.03, -1.059, 1.023, -1.099, 1.071"
42,g-39,float64,0.0,0.0,11388.0,"0.0, 0.3372, -0.2873, 0.0708, 0.2165, -0.0951, 0.1288, -0.0907, 0.2256, 0.0998"
43,g-40,float64,0.0,0.0,13153.0,"0.0, 0.3372, -10.0, -0.3372, 1.035, -1.062, -1.117, 0.6745, 0.511, 1.11"
44,g-41,float64,0.0,0.0,14392.0,"1.033, 1.219, 1.005, 1.331, 1.15, 1.072, 1.083, -1.059, 1.359, -1.047"
45,g-42,float64,0.0,0.0,13466.0,"0.0, 0.3372, -0.3372, 0.6745, 1.079, 0.3828, -1.041, -0.058, 1.087, -0.0741"
46,g-43,float64,0.0,0.0,13709.0,"0.0, -0.3372, -1.221, -1.025, 1.028, 1.178, 1.124, 1.219, 0.3372, 0.019"
47,g-44,float64,0.0,0.0,14226.0,"0.0901, -1.049, -1.03, -1.006, -1.101, -1.024, -1.036, 1.044, 1.042, -0.0488"
48,g-45,float64,0.0,0.0,14228.0,"-1.058, -1.197, -1.062, -1.02, -1.007, -1.039, -1.117, -0.1987, -1.022, 0.0"
49,g-46,float64,0.0,0.0,6674.0,"0.0, -0.3372, 0.3295, -0.1943, -0.1666, -0.1055, -0.1946, 0.1828, -0.0692, -0.1909"
50,g-47,float64,0.0,0.0,13657.0,"0.0, -1.036, 1.061, -1.057, -1.171, 0.2054, -1.058, -0.0442, -1.034, 0.1882"
51,g-48,float64,0.0,0.0,14284.0,"0.0, 10.0, 0.3372, 1.066, -1.115, -1.037, -1.249, -1.01, -1.11, -1.118"
52,g-49,float64,0.0,0.0,13867.0,"0.0, -1.022, -1.247, -1.042, -1.099, -1.008, -1.036, -1.005, -1.105, -1.178"
53,g-50,float64,0.0,0.0,14391.0,"-10.0, 0.0, 0.3372, 1.241, 1.048, 1.125, 1.022, 1.075, 1.06, 1.014"
54,g-51,float64,0.0,0.0,14091.0,"1.03, -1.051, 0.0, 1.064, -1.061, -1.031, -1.012, 1.086, 1.058, -1.053"
55,g-52,float64,0.0,0.0,13296.0,"0.0, 0.3372, -0.3372, 0.6745, 0.0556, 1.171, -0.2307, 1.008, 0.2617, 1.058"
56,g-53,float64,0.0,0.0,14137.0,"0.0, 0.6745, 0.3372, -0.3372, 1.067, 5.0, -1.039, -1.091, -1.065, 1.087"
57,g-54,float64,0.0,0.0,13038.0,"0.0, -0.3372, -0.6745, 5.0, 1.053, 1.16, 0.0833, -0.2277, 0.3372, -0.01"
58,g-55,float64,0.0,0.0,13670.0,"0.0, 0.3372, -0.3372, -10.0, 0.6745, -0.0493, -1.022, 1.002, -1.049, 1.033"
59,g-56,float64,0.0,0.0,14265.0,"0.0, 1.104, 0.3372, 1.149, 1.084, 1.1, -1.325, 1.312, 1.005, 1.07"
60,g-57,float64,0.0,0.0,14181.0,"10.0, -0.3372, 0.0, 1.157, 1.01, 1.197, 1.054, 1.152, 1.11, 0.6738"
61,g-58,float64,0.0,0.0,13571.0,"-10.0, 0.0, 0.3372, -0.3372, 0.2495, 0.6745, 1.025, -0.0576, 0.3544, 0.5145"
62,g-59,float64,0.0,0.0,14398.0,"0.0, 1.022, 0.0654, 1.028, -10.0, -1.112, 1.002, -1.048, -1.035, 1.077"
63,g-60,float64,0.0,0.0,14017.0,"0.0, -1.002, -1.06, -1.016, -1.04, 1.079, 1.094, -1.056, -1.219, -1.308"
64,g-61,float64,0.0,0.0,14129.0,"-10.0, -1.21, 1.048, -1.026, 1.161, -1.03, -0.3372, 1.238, 1.02, -1.277"
65,g-62,float64,0.0,0.0,14432.0,"-10.0, 0.0, 1.152, 1.131, 1.12, 0.3424, 0.3372, -1.106, 1.156, 1.13"
66,g-63,float64,0.0,0.0,14612.0,"-10.0, 0.0, -1.059, 1.067, 1.065, 0.1046, 1.086, 0.2962, 0.2404, 1.021"
67,g-64,float64,0.0,0.0,13790.0,"0.0, -0.3372, 1.15, 1.004, -1.037, 1.058, 1.261, 0.3372, -1.013, -1.113"
68,g-65,float64,0.0,0.0,14545.0,"-1.054, 0.0, -1.079, -1.067, -1.09, -1.186, 1.448, -0.2871, -1.009, -1.373"
69,g-66,float64,0.0,0.0,13637.0,"0.0, -1.02, -0.3372, -1.226, -1.088, 0.1933, 1.015, -1.067, -1.071, 1.036"
70,g-67,float64,0.0,0.0,14239.0,"-10.0, 0.0, 1.049, 1.141, 1.179, 1.062, 0.1461, 1.293, -1.141, 0.0112"
71,g-68,float64,0.0,0.0,13829.0,"0.0, -0.3372, 0.3372, -1.245, -1.027, -1.081, -1.194, -1.133, -1.232, -1.024"
72,g-69,float64,0.0,0.0,14027.0,"0.0, 1.044, 1.654, 1.63, 2.019, 1.157, 1.176, 1.01, 1.066, 1.106"
73,g-70,float64,0.0,0.0,14317.0,"1.145, 1.054, 1.004, 1.133, -1.025, 1.12, 1.1, 1.04, 1.075, 1.051"
74,g-71,float64,0.0,0.0,13999.0,"0.0, -1.108, -1.077, 0.3372, -1.043, -0.0233, -1.036, -1.188, -1.045, -1.046"
75,g-72,float64,0.0,0.0,14852.0,"-10.0, 0.0, 1.0, -1.145, 1.002, 1.039, 0.3589, 1.043, 1.011, 1.171"
76,g-73,float64,0.0,0.0,13991.0,"-1.231, -1.145, 0.0, -1.063, -1.061, 0.3372, -1.044, -1.032, -1.173, -1.1"
77,g-74,float64,0.0,0.0,14263.0,"10.0, 0.0, -0.3372, 1.094, -1.051, -1.095, -1.067, 1.554, 1.205, 1.171"
78,g-75,float64,0.0,0.0,14752.0,"-10.0, 0.0, 1.012, 1.078, -1.07, 1.007, 1.067, -1.114, 1.171, 1.2"
79,g-76,float64,0.0,0.0,13902.0,"0.0, 1.033, 1.055, 1.096, -1.048, 1.117, 0.3372, -1.049, -0.5375, -1.019"
80,g-77,float64,0.0,0.0,13786.0,"0.0, 0.3372, -1.018, -1.019, -1.086, 1.102, -1.016, -0.0221, -1.009, -1.055"
81,g-78,float64,0.0,0.0,13283.0,"0.0, -0.3372, 0.3372, 0.0702, 1.105, 0.1143, 0.0863, 1.079, 1.158, 1.374"
82,g-79,float64,0.0,0.0,14037.0,"0.0, 1.091, 1.155, -0.3372, -1.097, 1.061, -1.049, 1.027, 1.021, -1.158"
83,g-80,float64,0.0,0.0,14140.0,"0.0, 1.088, 1.026, -1.034, -1.138, 1.254, 1.121, 1.202, -1.061, 1.019"
84,g-81,float64,0.0,0.0,14105.0,"0.0, -1.037, -0.3372, 1.116, -1.052, 1.012, 1.024, 1.052, 1.05, -1.006"
85,g-82,float64,0.0,0.0,13897.0,"1.044, 1.153, 1.007, 1.039, 1.099, 1.258, 1.241, 1.112, 1.149, 1.052"
86,g-83,float64,0.0,0.0,14560.0,"-1.006, -1.196, -1.031, -1.1, -1.03, -1.119, -1.063, -1.132, 1.115, -1.038"
87,g-84,float64,0.0,0.0,14173.0,"0.0, 1.223, 1.27, -0.3372, 1.079, -1.012, 1.015, -1.06, -1.029, -1.229"
88,g-85,float64,0.0,0.0,13417.0,"0.0, -0.3372, 0.3372, 1.015, -0.0452, 0.2792, 1.062, -0.0509, 0.2381, 0.1116"
89,g-86,float64,0.0,0.0,14439.0,"10.0, 0.0, -1.056, -1.001, -1.042, -0.3372, 0.5738, 1.129, 1.019, -1.027"
90,g-87,float64,0.0,0.0,13901.0,"0.0, -1.031, -1.025, -0.3372, -1.245, -1.039, -1.006, -1.047, -1.068, -1.038"
91,g-88,float64,0.0,0.0,13690.0,"0.0, 0.3372, 0.0809, 1.053, -1.128, 1.046, 1.062, -1.028, -0.1497, -1.044"
92,g-89,float64,0.0,0.0,14061.0,"0.0, 0.0129, 1.088, 1.062, 1.05, 1.217, 1.13, 1.006, -1.248, -1.076"
93,g-90,float64,0.0,0.0,14022.0,"0.0, 0.3372, -0.2206, -0.3372, -1.026, -1.143, -0.6745, -1.003, -1.037, -1.01"
94,g-91,float64,0.0,0.0,14736.0,"10.0, 0.0, -1.006, -1.005, -1.069, -1.03, -1.096, -1.117, -1.013, -0.3372"
95,g-92,float64,0.0,0.0,14197.0,"0.0, -1.014, -0.3372, 0.3372, -1.013, 1.053, -1.056, -1.299, -1.138, 1.021"
96,g-93,float64,0.0,0.0,14165.0,"0.0, 1.056, -1.13, 1.089, 1.004, 1.14, 1.033, -1.047, 1.061, -1.056"
97,g-94,float64,0.0,0.0,12651.0,"0.0, 0.3372, -1.066, -0.1622, -1.058, -0.057, 0.2921, 0.3902, -1.059, -0.3659"
98,g-95,float64,0.0,0.0,14299.0,"-1.13, -1.015, -1.01, -1.001, -1.061, -1.025, 1.166, -1.123, -1.05, 0.6467"
99,g-96,float64,0.0,0.0,14227.0,"0.0, -10.0, 0.3372, -1.188, 1.018, 1.217, 1.065, 1.003, -1.013, 1.016"
100,g-97,float64,0.0,0.0,12522.0,"0.0, 10.0, -0.3372, -0.6745, -0.2084, -0.0348, -0.1511, -0.317, -0.2736, -1.067"
101,g-98,float64,0.0,0.0,14339.0,"-10.0, 0.0, -0.3372, 1.018, 0.3372, 1.025, 1.036, 0.1949, 1.247, 1.071"
102,g-99,float64,0.0,0.0,13577.0,"0.0, 0.3372, -1.095, -0.6745, 1.23, 1.036, -1.084, -1.144, -1.083, -0.1157"
103,g-100,float64,0.0,0.0,14700.0,"10.0, 0.0, -0.3372, -1.108, -1.036, -1.145, 0.0544, 0.1397, -1.201, -1.462"
104,g-101,float64,0.0,0.0,14011.0,"1.167, 1.047, 1.171, 1.023, 1.049, 1.226, 1.116, -1.016, 1.209, 1.145"
105,g-102,float64,0.0,0.0,14563.0,"10.0, -1.027, -1.034, -1.013, -1.023, -1.075, -1.048, -1.035, -1.185, -1.215"
106,g-103,float64,0.0,0.0,14102.0,"0.0, -1.017, 1.023, -1.024, -0.3372, -1.049, 1.111, 1.109, -1.077, -1.124"
107,g-104,float64,0.0,0.0,3110.0,"0.0, 0.3372, -0.3372, 0.1585, -0.1889, 0.1227, -0.0945, 0.2222, -0.1649, 0.1794"
108,g-105,float64,0.0,0.0,14182.0,"-1.04, 0.0, -0.3372, -1.067, -1.051, -1.02, -1.031, -1.229, -1.077, 1.026"
109,g-106,float64,0.0,0.0,14436.0,"10.0, 0.0, -0.6745, -1.121, 0.3372, -1.037, -1.178, 1.07, -1.09, 1.086"
110,g-107,float64,0.0,0.0,14604.0,"0.0, 0.203, 1.22, -1.197, 1.138, 1.067, 1.011, -0.7012, 1.012, -1.019"
111,g-108,float64,0.0,0.0,14050.0,"0.0, 0.3372, 1.049, -1.006, -1.102, -1.038, 0.2806, -1.051, -1.147, -1.238"
112,g-109,float64,0.0,0.0,14137.0,"-1.018, -1.052, 1.05, -1.128, 1.006, -1.041, -1.12, -1.112, 1.035, 1.005"
113,g-110,float64,0.0,0.0,10990.0,"0.0, 0.3372, -0.3372, 0.3217, 0.2988, 0.659, -0.4509, -0.4546, -0.1174, 0.7571"
114,g-111,float64,0.0,0.0,12043.0,"0.0, -0.3372, 0.3372, -0.0351, -0.1349, -0.1342, 0.3268, -0.2975, -0.1366, 0.145"
115,g-112,float64,0.0,0.0,14034.0,"0.0, 0.3372, 1.012, -0.3372, 1.014, 1.132, 0.4924, -1.086, -1.197, -0.0115"
116,g-113,float64,0.0,0.0,14691.0,"-10.0, 0.0, -1.011, -1.079, 1.04, 1.025, 1.02, 1.001, 1.01, 1.008"
117,g-114,float64,0.0,0.0,13794.0,"0.0, -0.3372, -1.047, 0.3372, 5.0, 1.148, -1.086, 1.1, 1.024, -1.016"
118,g-115,float64,0.0,0.0,14086.0,"0.0, 1.015, 0.3372, 1.177, 1.005, 1.105, -1.118, 1.08, -0.3625, -1.11"
119,g-116,float64,0.0,0.0,14220.0,"0.0, 1.008, 1.221, -0.3372, -1.087, 1.115, -1.121, 1.155, 1.215, -1.019"
120,g-117,float64,0.0,0.0,14197.0,"0.0, -1.043, 1.044, -1.239, -0.6745, 0.3372, 1.033, 1.039, -1.064, -1.053"
121,g-118,float64,0.0,0.0,14134.0,"0.0, 1.042, -1.066, 1.01, -1.086, -1.036, 1.083, 1.015, 1.005, -1.142"
122,g-119,float64,0.0,0.0,13897.0,"0.0, -0.3372, 1.113, 1.016, -0.179, 1.015, 1.156, 1.127, -1.303, -1.359"
123,g-120,float64,0.0,0.0,14125.0,"0.0, 1.125, -1.004, 1.013, -1.146, 1.094, -1.092, 1.08, 1.072, 1.011"
124,g-121,float64,0.0,0.0,14499.0,"-10.0, 0.0, 1.016, 1.021, 1.1, 1.142, 1.039, 1.036, -1.171, -1.042"
125,g-122,float64,0.0,0.0,13257.0,"0.0, 0.3372, -1.093, 0.0152, -0.6745, -1.013, -1.001, -1.041, -0.0469, 1.355"
126,g-123,float64,0.0,0.0,13686.0,"10.0, 0.0, -0.3372, -0.2988, -0.0853, 0.1214, 0.4627, 0.0439, 0.0823, 0.115"
127,g-124,float64,0.0,0.0,13884.0,"0.0, -0.3372, -1.094, -1.086, -1.128, -1.265, -1.008, -1.019, -1.217, -1.222"
128,g-125,float64,0.0,0.0,13821.0,"0.0, 0.3372, -0.3372, 0.6745, -1.011, -1.028, -1.03, -1.038, -0.1585, 1.005"
129,g-126,float64,0.0,0.0,14457.0,"10.0, -1.174, -1.106, 0.0, -1.089, -1.077, -1.023, -1.043, -1.013, -1.049"
130,g-127,float64,0.0,0.0,11360.0,"0.0, -0.3372, 0.0769, -0.0783, 0.3372, -0.0607, -0.0553, 0.1173, 0.202, -0.1588"
131,g-128,float64,0.0,0.0,13334.0,"-10.0, 0.0, -0.0398, 0.3372, 0.3706, -0.3372, 0.0479, -0.1902, 0.0732, 0.4141"
132,g-129,float64,0.0,0.0,14328.0,"0.0, -1.013, -1.197, 1.069, 1.037, 1.105, 0.0534, -1.107, -1.142, -1.027"
133,g-130,float64,0.0,0.0,13495.0,"5.0, 0.0, 10.0, 4.663, 0.0901, 5.337, 0.3372, -0.0135, -0.3372, -0.177"
134,g-131,float64,0.0,0.0,14706.0,"10.0, 1.03, 0.3372, 0.0, -1.03, 1.147, -1.168, -1.321, -1.034, -1.111"
135,g-132,float64,0.0,0.0,9497.0,"0.0, -0.1079, -0.0887, -0.3372, 0.0806, -0.1369, -0.1177, -0.1396, 0.1173, -0.2337"
136,g-133,float64,0.0,0.0,14474.0,"0.0, -1.123, 1.137, -1.001, 1.02, -10.0, -1.006, 1.405, 1.082, 0.5956"
137,g-134,float64,0.0,0.0,14148.0,"0.0, -1.168, -1.078, 1.043, 0.3372, -1.011, 1.009, 1.148, -1.082, 0.059"
138,g-135,float64,0.0,0.0,12336.0,"0.0, -0.3372, 0.3372, 0.0486, -0.0654, 0.0294, 0.0175, 0.7153, -0.2263, -0.0425"
139,g-136,float64,0.0,0.0,14213.0,"0.0, 0.3372, 1.024, 1.083, -1.044, -0.3372, 1.092, -0.6745, 1.035, 1.009"
140,g-137,float64,0.0,0.0,14325.0,"0.0, 1.086, 1.109, 0.3372, 1.031, -1.196, 1.103, 1.108, 1.135, 1.198"
141,g-138,float64,0.0,0.0,14241.0,"0.0, 1.207, 0.3372, 1.027, 1.01, 1.072, 1.07, 1.049, 1.365, -1.057"
142,g-139,float64,0.0,0.0,14296.0,"0.0, -1.143, -1.067, -1.081, 10.0, -1.104, -1.058, -1.1, -1.092, -1.049"
143,g-140,float64,0.0,0.0,14089.0,"0.3372, 0.0, 1.056, -1.079, 0.2431, 1.042, -1.04, -1.003, -1.044, 1.004"
144,g-141,float64,0.0,0.0,14069.0,"1.044, 0.0, 1.128, 1.056, 1.016, 1.051, 1.026, 1.063, 1.283, -1.002"
145,g-142,float64,0.0,0.0,14388.0,"0.0, -0.3372, 10.0, 0.3372, 0.6745, -1.026, -1.248, -1.006, -1.076, -1.051"
146,g-143,float64,0.0,0.0,13836.0,"0.0, 1.273, 1.112, 1.684, 1.463, 1.035, 1.616, 1.148, 1.4, 1.246"
147,g-144,float64,0.0,0.0,14250.0,"10.0, 0.0, -0.3372, -1.033, -1.072, -1.007, -1.023, -1.271, -1.045, -0.0165"
148,g-145,float64,0.0,0.0,14163.0,"0.0, 1.03, 1.39, 1.407, 1.048, 1.04, 1.097, 1.035, 1.036, 1.013"
149,g-146,float64,0.0,0.0,14480.0,"0.0, 10.0, -1.058, 1.064, -1.059, -1.047, -0.3372, -1.026, -1.258, -0.0394"
150,g-147,float64,0.0,0.0,13165.0,"10.0, 0.0, 0.3372, 0.0877, -0.3372, -0.0384, -0.2526, 0.1683, -0.116, -0.0398"
151,g-148,float64,0.0,0.0,14673.0,"10.0, -1.14, 1.016, 1.01, 1.135, -1.084, 0.0795, 1.153, 1.127, 0.0158"
152,g-149,float64,0.0,0.0,13977.0,"0.0, 1.074, -1.033, -1.087, 1.166, 1.107, 1.083, -1.023, 1.019, 1.015"
153,g-150,float64,0.0,0.0,13586.0,"0.0, 0.3372, 1.087, 1.024, 1.132, 1.067, 0.1305, -1.124, -1.029, 1.069"
154,g-151,float64,0.0,0.0,13876.0,"0.0, -1.002, -1.239, -1.095, -1.111, -1.044, 1.01, -1.056, -1.091, -1.02"
155,g-152,float64,0.0,0.0,14521.0,"-10.0, 0.0, 1.181, 0.3372, -0.0362, -0.0746, 1.019, 0.3792, 1.311, 1.062"
156,g-153,float64,0.0,0.0,6927.0,"0.0, 0.3372, 0.0003, -0.3372, 0.0611, 0.5531, 0.2333, 0.2425, 0.1403, 0.6745"
157,g-154,float64,0.0,0.0,14177.0,"0.0, 1.145, 1.204, 1.318, 0.3372, -1.005, 1.26, 1.253, 1.052, 1.192"
158,g-155,float64,0.0,0.0,13466.0,"0.0, 10.0, -0.3372, 0.3372, -0.6745, -0.0181, 1.08, 1.109, -0.4444, -1.037"
159,g-156,float64,0.0,0.0,14611.0,"0.0, -1.022, -1.604, -1.059, -1.076, -0.0377, -1.038, 1.036, 1.009, -1.228"
160,g-157,float64,0.0,0.0,12530.0,"0.0, 0.3372, -0.3372, 0.2216, 0.4609, 0.2189, 0.3791, -0.4378, 0.2424, 0.4905"
161,g-158,float64,0.0,0.0,14430.0,"10.0, 0.0, -1.055, 0.3372, -1.049, -1.02, -1.016, -0.6745, -1.184, -1.01"
162,g-159,float64,0.0,0.0,14032.0,"1.451, 1.02, 1.098, 1.23, 1.027, 1.292, 1.086, 1.056, -0.0707, 1.148"
163,g-160,float64,0.0,0.0,14630.0,"0.0, 1.032, -10.0, 1.132, 1.002, 1.165, 1.142, 1.26, 0.3372, 1.057"
164,g-161,float64,0.0,0.0,13871.0,"0.0, 0.3372, -0.1337, 1.159, 0.1845, -0.3372, -5.0, 0.272, 0.1763, 0.4035"
165,g-162,float64,0.0,0.0,14370.0,"0.0, 1.424, -1.057, -1.034, -1.007, -1.005, 1.018, 1.116, 1.079, -1.185"
166,g-163,float64,0.0,0.0,14396.0,"10.0, -1.036, 0.0, 1.016, -1.22, -1.151, 0.0872, -1.06, -1.053, 1.14"
167,g-164,float64,0.0,0.0,10557.0,"0.0, -0.3372, 0.3372, 0.0003, -0.6745, 10.0, 0.4367, -0.4418, -0.4421, 0.6745"
168,g-165,float64,0.0,0.0,13660.0,"0.0, 0.3372, 1.053, -0.3372, -0.6745, -0.1183, -1.146, 1.054, 0.2826, -0.3101"
169,g-166,float64,0.0,0.0,14282.0,"0.0, 1.145, -1.008, -1.015, 1.046, 1.043, -1.048, 1.095, 1.003, 1.13"
170,g-167,float64,0.0,0.0,14366.0,"0.0, 1.051, -1.025, -1.148, 1.023, -1.22, -1.012, -1.041, 1.033, -1.108"
171,g-168,float64,0.0,0.0,14167.0,"0.0, 0.3372, -1.025, -1.165, -1.081, -1.017, -1.089, -1.083, -1.016, -1.353"
172,g-169,float64,0.0,0.0,13769.0,"0.0, -0.3372, 0.3372, -1.029, 1.018, 1.007, 1.03, -1.127, -1.005, 0.6745"
173,g-170,float64,0.0,0.0,14489.0,"10.0, 0.0, 1.002, -1.027, -0.3372, -1.064, -1.049, -1.08, -1.076, -1.096"
174,g-171,float64,0.0,0.0,13148.0,"0.0, -0.3372, 0.3372, -0.6745, 1.038, 1.127, -1.185, -0.8374, -0.3251, -1.087"
175,g-172,float64,0.0,0.0,14174.0,"0.0, -1.243, 1.041, -1.037, 1.464, 1.062, -1.175, 1.045, 0.0978, -1.038"
176,g-173,float64,0.0,0.0,14145.0,"0.0, -1.046, -1.033, 1.012, -0.0307, 1.039, 1.105, -1.013, -1.199, -1.017"
177,g-174,float64,0.0,0.0,14286.0,"0.0, -1.008, -0.5135, -1.061, -1.026, 0.1975, -1.049, -1.096, -1.282, -1.271"
178,g-175,float64,0.0,0.0,15034.0,"-1.025, 1.016, 1.028, 1.072, 0.0, 1.162, 0.0362, -0.2282, -1.033, 1.131"
179,g-176,float64,0.0,0.0,14334.0,"0.0, -1.076, -1.283, -1.058, -1.022, -1.059, 1.023, -1.234, 1.109, 0.3539"
180,g-177,float64,0.0,0.0,14210.0,"10.0, 0.0, 1.032, -1.131, 1.181, -1.164, -1.01, -1.087, -1.224, -1.147"
181,g-178,float64,0.0,0.0,14802.0,"-10.0, 10.0, 0.0, 1.02, 0.2138, -0.0331, -1.156, -1.07, -1.032, -0.6745"
182,g-179,float64,0.0,0.0,13853.0,"1.179, 0.0, -1.021, -1.026, -1.059, 1.023, 1.059, 1.007, -1.054, -1.134"
183,g-180,float64,0.0,0.0,14274.0,"0.0, -1.005, 0.3372, -1.161, 1.041, 1.023, -0.3372, 1.074, -1.018, -1.083"
184,g-181,float64,0.0,0.0,14639.0,"10.0, 0.0, -1.017, 1.181, 0.3372, -1.04, -1.051, -1.041, -1.166, 1.018"
185,g-182,float64,0.0,0.0,14271.0,"-1.105, 1.222, 1.044, 1.175, 1.259, 0.6745, 1.39, 1.009, 1.126, 1.403"

In [7]:
# Numeric Feature Statistics
numeric_stats

,count,mean,std,min,max
g-0,23814.0,0.248366,1.393399,-5.513,10.000
g-1,23814.0,-0.095684,0.812363,-5.737,5.039
g-2,23814.0,0.152253,1.035731,-9.104,8.257
g-3,23814.0,0.081971,0.950012,-5.998,10.000
g-4,23814.0,0.057347,1.032091,-6.369,10.000
g-5,23814.0,-0.138836,1.179388,-10.000,7.282
g-6,23814.0,0.035961,0.882395,-10.000,7.333
g-7,23814.0,-0.202651,1.125494,-10.000,5.473
g-8,23814.0,-0.190083,1.749885,-10.000,8.887
g-9,23814.0,0.119905,1.087180,-8.337,6.433
g-10,23814.0,-0.123321,1.291501,-10.000,10.000
g-11,23814.0,0.182307,1.253604,-5.870,10.000
g-12,23814.0,0.143203,1.234590,-8.587,10.000
g-13,23814.0,0.209402,1.273068,-5.018,10.000
g-14,23814.0,-0.173884,1.247178,-10.000,10.000
g-15,23814.0,-0.024432,0.659839,-10.000,4.134
g-16,23814.0,0.126823,1.418997,-10.000,6.418
g-17,23814.0,-0.146663,1.179688,-10.000,4.750
g-18,23814.0,0.087687,0.743301,-4.226,8.872
g-19,23814.0,-0.082982,0.844796,-10.000,4.081
g-20,23814.0,-0.111908,1.219529,-10.000,9.842
g-21,23814.0,-0.087379,0.824401,-5.700,5.248
g-22,23814.0,0.047548,0.924838,-10.000,5.942
g-23,23814.0,-0.117474,0.760159,-10.000,5.201
g-24,23814.0,-0.113212,1.203186,-10.000,10.000
g-25,23814.0,-0.052746,0.866977,-8.272,8.494
g-26,23814.0,-0.091055,1.103765,-8.184,10.000
g-27,23814.0,0.112176,1.001687,-4.835,10.000
g-28,23814.0,-0.046458,1.027758,-7.913,10.000
g-29,23814.0,-0.076239,1.279399,-10.000,9.416
g-30,23814.0,-0.197699,1.302567,-10.000,10.000
g-31,23814.0,0.382177,1.559174,-2.956,10.000
g-32,23814.0,-0.189432,0.933514,-8.356,6.796
g-33,23814.0,0.078791,1.172270,-7.182,10.000
g-34,23814.0,-0.093312,1.174325,-10.000,10.000
g-35,23814.0,0.135729,1.061719,-9.261,10.000
g-36,23814.0,-0.188616,1.397677,-10.000,5.834
g-37,23814.0,-0.606710,2.200277,-10.000,5.602
g-38,23814.0,0.534425,2.003317,-10.000,10.000
g-39,23814.0,0.132026,0.990477,-4.223,10.000
g-40,23814.0,-0.192703,1.261415,-10.000,4.201
g-41,23814.0,-0.116715,1.259411,-9.575,5.912
g-42,23814.0,-0.130481,1.014167,-10.000,3.967
g-43,23814.0,0.041742,0.913359,-4.807,10.000
g-44,23814.0,-0.003400,0.996064,-7.362,10.000
g-45,23814.0,-0.145524,1.138590,-10.000,10.000
g-46,23814.0,0.198103,1.131534,-3.622,10.000
g-47,23814.0,0.044684,1.056562,-10.000,9.041
g-48,23814.0,0.190723,1.375734,-7.680,10.000
g-49,23814.0,-0.026252,0.966217,-6.577,10.000
g-50,23814.0,-0.588018,2.256983,-10.000,4.889
g-51,23814.0,0.084115,1.044536,-10.000,8.740
g-52,23814.0,-0.060244,0.988165,-6.913,10.000
g-53,23814.0,0.149425,1.224047,-5.465,10.000
g-54,23814.0,0.270067,1.119319,-5.072,10.000
g-55,23814.0,-0.210933,1.248058,-10.000,3.373
g-56,23814.0,-0.120079,1.234026,-10.000,4.911
g-57,23814.0,0.042565,1.213755,-10.000,10.000
g-58,23814.0,-0.419357,1.885048,-10.000,5.311
g-59,23814.0,-0.220125,1.379736,-10.000,10.000
g-60,23814.0,-0.044085,1.004798,-10.000,10.000
g-61,23814.0,-0.231587,1.192664,-10.000,3.563
g-62,23814.0,-0.220041,1.725091,-10.000,10.000
g-63,23814.0,-0.382150,1.760003,-10.000,4.886
g-64,23814.0,-0.021930,0.921277,-5.978,10.000
g-65,23814.0,0.295247,1.441082,-6.319,10.000
g-66,23814.0,-0.017459,0.936259,-10.000,5.521
g-67,23814.0,-0.494869,2.020121,-10.000,4.695
g-68,23814.0,0.140129,1.249608,-4.958,10.000
g-69,23814.0,0.403317,1.221999,-6.962,10.000
g-70,23814.0,0.004548,1.118795,-7.992,6.541
g-71,23814.0,-0.134467,0.893569,-10.000,4.584
g-72,23814.0,-0.423243,1.978893,-10.000,7.280
g-73,23814.0,-0.093386,0.892039,-5.270,6.940
g-74,23814.0,0.299319,1.431489,-5.479,10.000
g-75,23814.0,-0.445392,2.254701,-10.000,8.835
g-76,23814.0,-0.004895,0.914296,-10.000,8.209
g-77,23814.0,-0.089633,0.880041,-10.000,4.550
g-78,23814.0,0.009940,0.849408,-10.000,5.416
g-79,23814.0,-0.006237,1.055794,-8.610,9.725
g-80,23814.0,-0.083865,1.079820,-10.000,6.585
g-81,23814.0,0.023874,0.995769,-7.361,7.841
g-82,23814.0,0.216686,1.085011,-10.000,5.778
g-83,23814.0,0.245262,1.331346,-10.000,10.000
g-84,23814.0,0.240652,1.185213,-5.030,10.000
g-85,23814.0,0.046094,1.053281,-10.000,5.708
g-86,23814.0,0.323618,1.510464,-9.221,10.000
g-87,23814.0,-0.096629,0.898041,-6.930,5.838
g-88,23814.0,0.110119,1.001881,-8.732,10.000
g-89,23814.0,-0.012135,0.925411,-10.000,7.476
g-90,23814.0,0.191735,1.321554,-4.925,10.000
g-91,23814.0,0.407155,1.910301,-6.822,10.000
g-92,23814.0,0.049477,1.164653,-8.580,9.894
g-93,23814.0,0.094816,1.074901,-7.006,10.000
g-94,23814.0,-0.022741,0.829330,-5.963,10.000
g-95,23814.0,0.190986,1.317184,-3.905,10.000
g-96,23814.0,-0.419490,1.618852,-10.000,4.038
g-97,23814.0,0.219582,1.252505,-3.749,10.000
g-98,23814.0,-0.259191,1.490406,-10.000,7.311
g-99,23814.0,-0.026606,0.919208,-10.000,5.400
g-100,23814.0,0.553186,2.152067,-5.915,10.000
g-101,23814.0,0.149191,1.030329,-10.000,9.692
g-102,23814.0,0.181576,1.471078,-6.461,10.000
g-103,23814.0,0.044605,1.098941,-10.000,10.000
g-104,23814.0,0.079709,0.621391,-3.138,10.000
g-105,23814.0,0.122196,1.138324,-7.907,10.000
g-106,23814.0,0.372315,1.571284,-4.927,10.000
g-107,23814.0,0.017905,1.298779,-10.000,10.000
g-108,23814.0,-0.130118,1.114983,-8.781,8.018
g-109,23814.0,-0.045348,1.005339,-9.193,10.000
g-110,23814.0,-0.091741,0.903687,-10.000,4.489
g-111,23814.0,0.184092,0.993925,-3.317,10.000
g-112,23814.0,-0.133383,1.080577,-10.000,5.609
g-113,23814.0,-0.490342,1.843141,-10.000,3.926
g-114,23814.0,-0.006779,1.202515,-8.774,10.000
g-115,23814.0,-0.053366,1.023516,-10.000,4.952
g-116,23814.0,0.182516,1.204051,-6.753,10.000
g-117,23814.0,-0.002605,1.161487,-7.481,10.000
g-118,23814.0,0.091559,1.042106,-5.411,9.910
g-119,23814.0,-0.013088,0.911273,-7.284,7.908
g-120,23814.0,-0.080500,0.987804,-8.560,7.817
g-121,23814.0,-0.345632,1.656886,-10.000,3.780
g-122,23814.0,0.003580,0.906871,-7.890,10.000
g-123,23814.0,0.425806,1.780085,-4.254,10.000
g-124,23814.0,0.039368,0.922761,-10.000,7.640
g-125,23814.0,-0.105995,1.063146,-10.000,8.915
g-126,23814.0,0.212274,1.362637,-4.728,10.000
g-127,23814.0,0.062819,0.913929,-7.969,10.000
g-128,23814.0,-0.265743,1.690968,-10.000,6.117
g-129,23814.0,0.010379,1.035710,-10.000,9.389
g-130,23814.0,0.262663,1.447668,-8.923,10.000
g-131,23814.0,0.369558,2.084729,-9.931,10.000
g-132,23814.0,0.204949,1.143068,-2.849,10.000
g-133,23814.0,0.049921,1.489410,-10.000,10.000
g-134,23814.0,-0.095685,1.248209,-10.000,10.000
g-135,23814.0,0.181764,1.074660,-4.806,9.112
g-136,23814.0,-0.019320,1.127180,-9.163,10.000
g-137,23814.0,-0.031388,1.106040,-9.757,8.064
g-138,23814.0,-0.071636,1.283919,-10.000,10.000
g-139,23814.0,0.165484,1.261948,-10.000,10.000
g-140,23814.0,0.164184,1.124960,-5.583,7.832
g-141,23814.0,-0.122510,1.079769,-10.000,5.548
g-142,23814.0,0.222065,1.373094,-5.746,10.000
g-143,23814.0,0.288643,1.183380,-10.000,6.542
g-144,23814.0,0.274966,1.458870,-5.633,10.000
g-145,23814.0,0.360590,1.270184,-5.679,10.000
g-146,23814.0,0.320514,1.522666,-10.000,10.000
g-147,23814.0,0.340454,1.637079,-4.137,10.000
g-148,23814.0,0.274446,1.371357,-6.169,10.000
g-149,23814.0,0.033633,0.953237,-6.825,10.000
g-150,23814.0,-0.060082,0.915679,-6.535,6.009
g-151,23814.0,-0.165893,0.891298,-8.046,9.959
g-152,23814.0,-0.367541,1.618229,-10.000,7.382
g-153,23814.0,-0.131631,0.764111,-10.000,4.129
g-154,23814.0,0.088080,1.107515,-10.000,8.007
g-155,23814.0,0.282972,1.319818,-2.699,10.000
g-156,23814.0,-0.188911,1.325495,-9.385,10.000
g-157,23814.0,0.078601,1.404926,-10.000,10.000
g-158,23814.0,0.472131,1.954981,-5.113,10.000
g-159,23814.0,0.233131,1.021656,-8.249,7.759
g-160,23814.0,-0.049466,1.639475,-10.000,10.000
g-161,23814.0,-0.039718,1.349479,-10.000,7.134
g-162,23814.0,0.181594,1.258924,-8.971,9.964
g-163,23814.0,0.356694,1.538516,-7.069,10.000
g-164,23814.0,0.080781,1.348943,-10.000,10.000
g-165,23814.0,-0.124705,1.015509,-8.944,6.004
g-166,23814.0,-0.027440,1.230927,-10.000,10.000
g-167,23814.0,-0.018446,1.286735,-10.000,10.000
g-168,23814.0,-0.038914,1.160236,-6.565,10.000
g-169,23814.0,0.055477,1.083643,-7.621,10.000
g-170,23814.0,0.339697,1.656856,-4.910,10.000
g-171,23814.0,0.083943,0.934551,-5.059,10.000
g-172,23814.0,-0.158076,1.091421,-10.000,5.854
g-173,23814.0,0.048616,1.155354,-10.000,7.107
g-174,23814.0,0.187082,1.248905,-7.870,9.642
g-175,23814.0,-0.039062,1.616440,-10.000,9.201
g-176,23814.0,-0.091772,1.139079,-7.731,9.243
g-177,23814.0,0.245551,1.271860,-5.428,10.000
g-178,23814.0,-0.123382,1.988000,-10.000,10.000
g-179,23814.0,-0.059577,0.933761,-10.000,6.278
g-180,23814.0,0.190609,1.122586,-10.000,8.635
g-181,23814.0,0.323406,1.501394,-6.615,10.000
g-182,23814.0,0.251091,1.194793,-10.000,9.628
g-183,23814.0,-0.181816,1.490739,-10.000,9.648
g-184,23814.0,-0.036841,0.729980,-10.000,3.842
g-185,23814.0,-0.431850,1.820190,-10.000,8.486
g-186,23814.0,-0.267724,1.363034,-10.000,3.538
g-187,23814.0,0.028991,1.060757,-10.000,9.532
g-188,23814.0,0.153700,1.071579,-10.000,10.000
g-189,23814.0,0.001672,1.659294,-10.000,10.000
g-190,23814.0,0.141721,1.191004,-10.000,8.987
g-191,23814.0,0.258404,1.424484,-9.032,9.090
g-192,23814.0,0.156654,0.964431,-4.248,10.000
g-193,23814.0,-0.026994,0.844032,-10.000,4.570
g-194,23814.0,-0.228165,1.163079,-10.000,3.249
g-195,23814.0,-0.378534,1.737879,-10.000,4.945
g-196,23814.0,-0.263934,1.202973,-10.000,7.866
g-197,23814.0,0.223857,1.254302,-4.181,10.000
g-198,23814.0,0.182953,1.179621,-4.848,10.000
g-199,23814.0,-0.088170,1.019185,-10.000,5.198
g-200,23814.0,0.121417,1.020693,-7.602,7.267
g-201,23814.0,0.368972,1.680717,-5.717,10.000
g-202,23814.0,-0.230861,1.688577,-10.000,6.227
g-203,23814.0,-0.034724,1.242656,-10.000,10.000
g-204,23814.0,-0.192299,1.260946,-10.000,8.459
g-205,23814.0,0.131942,0.953080,-7.898,10.000
g-206,23814.0,-0.146795,1.393775,-10.000,10.000
g-207,23814.0,0.026069,1.100317,-7.708,10.000
g-208,23814.0,0.437445,1.774784,-5.726,10.000
g-209,23814.0,0.168788,1.048716,-6.193,10.000
g-210,23814.0,0.075845,1.150920,-9.057,10.000
g-211,23814.0,-0.072732,1.019254,-10.000,10.000
g-212,23814.0,-0.012826,0.919141,-7.827,10.000
g-213,23814.0,0.172382,1.047997,-3.638,10.000
g-214,23814.0,-0.111349,1.077159,-10.000,7.771
g-215,23814.0,0.293458,1.602694,-6.196,10.000
g-216,23814.0,0.068083,0.776268,-3.890,10.000
g-217,23814.0,-0.029711,0.960346,-8.417,10.000
g-218,23814.0,-0.043501,1.312465,-10.000,10.000
g-219,23814.0,0.046375,0.577300,-2.891,10.000
g-220,23814.0,0.251396,1.209575,-5.922,10.000
g-221,23814.0,0.028464,1.052924,-10.000,7.597
g-222,23814.0,-0.007041,1.057568,-8.370,10.000
g-223,23814.0,-0.155582,1.025350,-10.000,5.950
g-224,23814.0,0.000051,1.196507,-8.764,10.000
g-225,23814.0,0.044367,0.998377,-7.425,10.000
g-226,23814.0,0.268395,1.481310,-4.341,10.000
g-227,23814.0,-0.118700,0.983525,-10.000,6.391
g-228,23814.0,-0.475231,2.163439,-10.000,10.000
g-229,23814.0,0.145276,1.361261,-6.438,10.000
g-230,23814.0,0.023115,1.066590,-6.190,9.818
g-231,23814.0,-0.027720,1.689545,-10.000,10.000
g-232,23814.0,0.170473,1.171272,-5.493,10.000
g-233,23814.0,-0.000827,0.886915,-10.000,5.476
g-234,23814.0,-0.222871,1.285252,-10.000,9.509
g-235,23814.0,0.264450,1.372133,-4.582,10.000
g-236,23814.0,0.074245,0.934891,-10.000,7.878
g-237,23814.0,-0.041112,0.901657,-10.000,7.402
g-238,23814.0,-0.254441,1.117768,-9.056,3.852
g-239,23814.0,-0.275392,1.204756,-10.000,5.511
g-240,23814.0,0.042154,0.958786,-7.995,10.000
g-241,23814.0,-0.170449,1.296877,-10.000,7.759
g-242,23814.0,0.117622,1.091650,-5.126,10.000
g-243,23814.0,0.164056,1.511013,-5.051,10.000
g-244,23814.0,0.265041,1.106052,-2.806,10.000
g-245,23814.0,0.153300,1.306103,-6.483,10.000
g-246,23814.0,-0.009269,0.999196,-9.726,10.000
g-247,23814.0,-0.022225,1.102004,-10.000,6.354
g-248,23814.0,0.388632,1.815120,-5.866,10.000
g-249,23814.0,0.153214,1.156449,-6.768,10.000
g-250,23814.0,-0.374633,1.759713,-10.000,9.069
g-251,23814.0,0.222396,1.396399,-6.173,10.000
g-252,23814.0,0.038932,1.238792,-10.000,9.384
g-253,23814.0,0.023766,1.015557,-7.445,5.129
g-254,23814.0,0.093321,1.315312,-10.000,10.000
g-255,23814.0,0.164370,1.212813,-7.022,10.000
g-256,23814.0,-0.023268,0.981345,-10.000,9.013
g-257,23814.0,-0.472073,1.864766,-10.000,4.881
g-258,23814.0,-0.049739,1.101469,-10.000,10.000
g-259,23814.0,0.254160,1.355325,-3.597,10.000
g-260,23814.0,0.038577,0.970519,-7.294,10.000
g-261,23814.0,0.311212,1.635336,-5.616,10.000
g-262,23814.0,-0.074530,0.844241,-6.136,6.142
g-263,23814.0,0.044743,0.954678,-7.027,10.000
g-264,23814.0,0.157810,1.163346,-6.089,10.000
g-265,23814.0,-0.003230,1.008373,-6.485,10.000
g-266,23814.0,0.291709,1.360615,-3.985,10.000
g-267,23814.0,-0.268630,0.817990,-10.000,3.695
g-268,23814.0,-0.082307,0.859341,-5.261,8.457
g-269,23814.0,-0.031874,1.082770,-8.488,10.000
g-270,23814.0,0.321762,1.648393,-5.060,10.000
g-271,23814.0,-0.248234,1.516160,-10.000,7.698
g-272,23814.0,-0.101112,1.338176,-10.000,8.900
g-273,23814.0,-0.148110,0.977885,-9.332,5.518
g-274,23814.0,0.016953,0.849683,-10.000,6.816
g-275,23814.0,-0.073290,1.083478,-10.000,8.404
g-276,23814.0,-0.392451,1.365338,-10.000,3.355
g-277,23814.0,-0.135292,0.994930,-10.000,10.000
g-278,23814.0,0.142267,0.933240,-3.010,10.000
g-279,23814.0,0.000742,0.833731,-8.943,4.849
g-280,23814.0,-0.032489,1.046624,-6.605,10.000
g-281,23814.0,-0.039118,1.261285,-10.000,6.084
g-282,23814.0,-0.105057,1.114679,-9.180,6.889
g-283,23814.0,-0.124091,0.961099,-10.000,7.910
g-284,23814.0,-0.091918,1.051442,-10.000,8.588
g-285,23814.0,-0.215069,1.080072,-10.000,4.190
g-286,23814.0,0.193720,1.022554,-7.343,5.889
g-287,23814.0,-0.065849,1.118927,-10.000,8.208
g-288,23814.0,-0.023180,1.008338,-7.924,8.568
g-289,23814.0,0.181743,1.192771,-4.476,10.000
g-290,23814.0,0.172868,1.250949,-7.789,10.000
g-291,23814.0,-0.206315,1.530590,-10.000,9.065
g-292,23814.0,0.007374,0.832069,-10.000,5.384
g-293,23814.0,-0.110813,1.084464,-9.786,4.509
g-294,23814.0,-0.195061,1.339357,-10.000,5.296
g-295,23814.0,0.193706,1.155420,-8.086,10.000
g-296,23814.0,0.074015,1.039963,-7.113,10.000
g-297,23814.0,-0.095735,1.179552,-7.977,10.000
g-298,23814.0,-0.426909,1.662571,-10.000,5.479
g-299,23814.0,-0.192787,1.299974,-10.000,5.730
g-300,23814.0,-0.148016,1.949899,-10.000,10.000
g-301,23814.0,-0.111154,1.005412,-8.936,4.490
g-302,23814.0,0.250877,1.082847,-10.000,10.000
g-303,23814.0,-0.054572,0.779500,-10.000,3.801
g-304,23814.0,-0.226640,1.310098,-10.000,5.614
g-305,23814.0,-0.043025,0.957979,-7.997,10.000
g-306,23814.0,-0.157459,1.230002,-10.000,3.713
g-307,23814.0,-0.131650,0.602029,-10.000,5.584
g-308,23814.0,0.207138,1.230401,-5.439,10.000
g-309,23814.0,-0.057716,1.098640,-7.219,10.000
g-310,23814.0,0.367014,1.419396,-6.569,10.000
g-311,23814.0,0.017460,1.104527,-6.042,8.221
g-312,23814.0,-0.055813,0.900877,-7.064,5.373
g-313,23814.0,0.273357,1.138159,-8.450,10.000
g-314,23814.0,-0.186248,1.280322,-10.000,8.301
g-315,23814.0,-0.127431,1.074061,-10.000,6.398
g-316,23814.0,-0.119745,1.250242,-10.000,10.000
g-317,23814.0,0.212380,1.274073,-4.621,10.000
g-318,23814.0,0.029729,0.881331,-10.000,10.000
g-319,23814.0,0.023282,1.034077,-8.959,10.000
g-320,23814.0,0.159574,1.295550,-10.000,10.000
g-321,23814.0,-0.161792,1.114478,-10.000,3.963
g-322,23814.0,-0.119753,1.140883,-8.821,10.000
g-323,23814.0,-0.055577,1.091425,-9.372,6.597
g-324,23814.0,-0.046364,0.875300,-6.854,6.511
g-325,23814.0,-0.142826,1.069987,-10.000,4.902
g-326,23814.0,0.299260,1.186854,-10.000,10.000
g-327,23814.0,-0.201067,1.330702,-10.000,9.272
g-328,23814.0,0.378707,1.905435,-4.338,10.000
g-329,23814.0,-0.081514,1.164996,-10.000,5.172
g-330,23814.0,0.138658,1.108910,-9.429,10.000
g-331,23814.0,0.072841,0.630456,-2.996,10.000
g-332,23814.0,-0.433894,1.870617,-10.000,6.062
g-333,23814.0,0.102021,0.960868,-4.893,10.000
g-334,23814.0,0.308590,1.448106,-4.345,10.000
g-335,23814.0,0.204869,1.203323,-6.566,10.000
g-336,23814.0,0.057716,1.111162,-6.176,10.000
g-337,23814.0,0.194908,1.155131,-7.757,10.000
g-338,23814.0,-0.017019,1.411645,-10.000,10.000
g-339,23814.0,-0.090774,1.039531,-7.326,10.000
g-340,23814.0,0.024465,0.783395,-5.942,5.768
g-341,23814.0,-0.087233,1.091391,-7.554,5.834
g-342,23814.0,-0.043124,1.039986,-8.507,10.000
g-343,23814.0,0.134760,0.976433,-4.915,10.000
g-344,23814.0,0.354087,1.406757,-5.039,10.000
g-345,23814.0,0.086328,0.851439,-5.817,10.000
g-346,23814.0,0.087008,0.934288,-6.190,6.214
g-347,23814.0,-0.049679,1.014711,-10.000,5.609
g-348,23814.0,0.097380,0.927678,-4.615,10.000
g-349,23814.0,0.377734,1.771342,-3.602,10.000
g-350,23814.0,0.083233,1.086159,-8.140,7.289
g-351,23814.0,-0.117395,1.119672,-10.000,7.034
g-352,23814.0,0.130532,0.930901,-2.999,10.000
g-353,23814.0,-0.255226,1.563868,-10.000,7.191
g-354,23814.0,0.201478,1.082450,-5.039,10.000
g-355,23814.0,0.083577,0.988766,-5.358,8.569
g-356,23814.0,-0.003564,1.031534,-10.000,6.751
g-357,23814.0,-0.112663,1.223396,-10.000,10.000
g-358,23814.0,0.190017,1.151852,-10.000,7.899
g-359,23814.0,0.179458,1.317785,-10.000,10.000
g-360,23814.0,-0.264823,1.331794,-10.000,3.322
g-361,23814.0,0.097313,1.035179,-10.000,10.000
g-362,23814.0,0.183459,1.063264,-6.086,10.000
g-363,23814.0,-0.042124,0.878367,-10.000,5.602
g-364,23814.0,-0.280311,1.389991,-10.000,5.818
g-365,23814.0,0.195953,1.260111,-5.930,8.797
g-366,23814.0,0.093724,1.037647,-6.458,10.000
g-367,23814.0,0.147087,1.301622,-10.000,10.000
g-368,23814.0,0.326541,1.557454,-4.142,10.000
g-369,23814.0,-0.379800,1.730008,-10.000,10.000
g-370,23814.0,-0.648438,1.580592,-10.000,3.247
g-371,23814.0,-0.080322,1.070647,-10.000,10.000
g-372,23814.0,0.023319,1.141032,-9.129,9.986
g-373,23814.0,-0.089417,1.028255,-10.000,7.801
g-374,23814.0,0.256405,1.586628,-5.504,10.000
g-375,23814.0,-0.443521,1.583119,-10.000,5.791
g-376,23814.0,0.062147,1.311550,-10.000,7.665
g-377,23814.0,0.225972,1.248150,-4.581,10.000
g-378,23814.0,-0.048428,1.084442,-10.000,10.000
g-379,23814.0,-0.223153,1.468029,-10.000,6.444
g-380,23814.0,0.235658,1.107722,-10.000,10.000
g-381,23814.0,0.107254,1.060257,-7.912,10.000
g-382,23814.0,-0.040530,0.815795,-6.992,6.103
g-383,23814.0,-0.058963,0.906158,-10.000,6.533
g-384,23814.0,-0.061957,0.985407,-10.000,6.292
g-385,23814.0,-0.198694,1.831446,-10.000,10.000
g-386,23814.0,0.261760,1.665347,-10.000,10.000
g-387,23814.0,0.029325,1.004877,-10.000,7.740
g-388,23814.0,-0.120413,1.003969,-10.000,3.109
g-389,23814.0,0.097341,1.091622,-6.861,10.000
g-390,23814.0,-0.032896,1.201942,-10.000,5.321
g-391,23814.0,0.291440,1.079414,-10.000,6.731
g-392,23814.0,0.537320,1.989753,-4.156,10.000
g-393,23814.0,0.197379,1.161182,-3.350,10.000
g-394,23814.0,-0.049037,1.242774,-10.000,10.000
g-395,23814.0,0.009859,1.224826,-9.947,10.000
g-396,23814.0,-0.132121,0.869635,-6.866,9.997
g-397,23814.0,0.019025,0.990424,-6.995,10.000
g-398,23814.0,-0.003386,1.097328,-9.535,10.000
g-399,23814.0,-0.213570,1.219060,-9.334,7.781
g-400,23814.0,-0.137992,1.043429,-10.000,3.192
g-401,23814.0,-0.179270,1.137605,-8.475,6.303
g-402,23814.0,0.198680,1.348181,-9.505,10.000
g-403,23814.0,0.155349,1.011180,-6.483,10.000
g-404,23814.0,-0.025741,0.846599,-8.082,8.920
g-405,23814.0,-0.119222,1.156051,-10.000,9.466
g-406,23814.0,-0.422586,1.881884,-10.000,2.809
g-407,23814.0,-0.206382,1.217319,-10.000,3.804
g-408,23814.0,0.035467,0.944733,-5.670,7.503
g-409,23814.0,0.209384,1.214659,-5.077,10.000
g-410,23814.0,-0.246866,1.340314,-10.000,5.106
g-411,23814.0,-0.368640,1.741905,-10.000,6.382
g-412,23814.0,-0.160678,0.983163,-10.000,7.211
g-413,23814.0,0.378860,1.114941,-10.000,5.860
g-414,23814.0,-0.173947,1.288839,-10.000,10.000
g-415,23814.0,-0.034362,0.930717,-10.000,10.000
g-416,23814.0,0.133389,1.001127,-5.189,7.194
g-417,23814.0,0.441745,1.946993,-5.212,10.000
g-418,23814.0,0.235487,1.263888,-5.200,8.657
g-419,23814.0,0.018143,1.094539,-8.431,10.000
g-420,23814.0,-0.047821,0.813221,-10.000,5.152
g-421,23814.0,-0.366281,1.248636,-10.000,3.599
g-422,23814.0,0.144610,1.255798,-9.637,10.000
g-423,23814.0,-0.221267,1.477404,-10.000,6.913
g-424,23814.0,0.216495,1.397493,-6.434,10.000
g-425,23814.0,0.295024,1.149960,-6.070,9.932
g-426,23814.0,0.234333,1.193630,-4.604,10.000
g-427,23814.0,0.230264,1.399280,-4.614,10.000
g-428,23814.0,-0.176801,1.194915,-10.000,4.492
g-429,23814.0,-0.178642,1.213349,-10.000,5.439
g-430,23814.0,0.275108,0.912590,-7.536,6.491
g-431,23814.0,0.024118,1.099197,-10.000,7.776

In [8]:
# Categorical Feature Statistics
cat_stats

                    value  count    pct
column  rank
cp_dose 1              D1  12147  51.01
        2              D2  11667  48.99
cp_time 1              48   8250  34.64
        2              72   7792  32.72
        3              24   7772  32.64
cp_type 1          trt_cp  21948  92.16
        2     ctl_vehicle   1866   7.84

In [9]:
# Target Distribution
target_df

                count    pct
nfkb_inhibitor
0               22982  96.51
1                 832   3.49

## Task Curation

In [10]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=3, n_splits=3, test_size=None

In [11]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

## Export

In [12]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
019d25c0-2091-7039-b89b-19f5c3a34d66
3609ef9513808596502bb19ec21b5bd07158dc265c0df2e5801ee83c39036573