### Dataset and Task Metadata

In [12]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="leukemia_allaml",
    dataset_year="1999",
    domain_str="medical & healthcare",
    # Data Source
    dataset_source="OpenML",
    original_dataset_source_download_link="https://www.openml.org/d/1104",
    download_description="""
We download the dataset from OpenML to a predefined folder.

mkdir -p local-data-warehouse/leukemia_allaml/ && wget -P local-data-warehouse/leukemia_allaml/ https://www.openml.org/data/download/53987/leukemia.arff
""",
    # References
    academic_reference_bibtex="""@article{Golub1999MolecularCC,
  title={Molecular classification of cancer: class discovery and class prediction by gene expression monitoring},
  author={Todd R. Golub and Donna K. Slonim and Pablo Tamayo and Christine Huard and Michelle Gaasenbeek and Jill P. Mesirov and Hilary Coller and Mignon L. Loh and James R. Downing and Michael A. Caligiuri and Clara D. Bloomfield and Eric S. Lander},
  journal={Science},
  year={1999},
  volume={286},
  number={5439},
  pages={531-537},
  doi={10.1126/science.286.5439.531},
  url={https://doi.org/10.1126/science.286.5439.531}
}
""",
    academic_reference_bibtex_key="Golub1999MolecularCC",
    license="Public Domain",
    data_tags=["IID"],
    curation_comments="""
        - We use OpenML repository version as the raw data is not available. This dataset contains 7,129 features while the original reference mentions only 6,817 genes. This discrepancy is likely due to some gene filtering based on gene expression level that has not been disclosed in the paper. Hence, we treat OpenML version as the raw, untreated data.
        - We remove 57 columns corresponding to Affymetrix control probes that are not relevant for the prediction task.
        - We shuffle merged samples as the first 38 instances come from the training set.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="LeukemiaType",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="LeukemiaType",
)

## Preprocessing

In [13]:
import pandas as pd
import arff

with open(dataset_mold.path/"leukemia.arff") as f:
    data = arff.load(f)
df = pd.DataFrame(data["data"], columns=[x[0] for x in data["attributes"]])

# filter out affymetrix control probes
df.drop([col for col in df.columns if col.startswith('AFFX-')], axis=1, inplace=True)

target_feature = "LeukemiaType"
df = df.rename(columns={"CLASS": target_feature})
df[target_feature] = df[target_feature].astype("category")

df = df.sample(frac=1, random_state=453).reset_index(drop=True)

## Data Checks

In [14]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 72
Columns: 7072
Use sampling: False (sample size: 72)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['HG384-HT384_at', 'D50310_at', 'X04347_s_at', 'U21689_at', 'U72649_at', 'X71874_cds1_at', 'U17566_at', 'Y08765_s_at', 'L16842_at', 'U94832_at']
Rows remaining as candidates after top-10 filter: 0 (of 72)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [15]:
# Sample Rows
df_head

   hum_alu_at  A28102_at  AB000114_at  AB000115_at  AB000220_at  AB000409_at  \
0     18343.0      420.0        154.0       1559.0         32.0         70.0
1     11195.0      260.0         28.0        128.0         46.0          0.0
2     25673.0      485.0         87.0        178.0        162.0        -57.0
3     43084.0      267.0         12.0         84.0        -24.0       -184.0
4     23505.0       85.0         49.0        197.0         13.0         30.0

   AB000449_at  AB000450_at  AB000460_at  AB000462_at  AB000464_at  \
0        208.0         80.0       1404.0        134.0        481.0
1        833.0        390.0       2222.0        246.0        592.0
2        197.0        115.0       2325.0        161.0       1125.0
3         89.0        117.0       1333.0         57.0        347.0
4        165.0        166.0       1288.0        136.0        839.0

   AB000466_at  AB000467_at  AB000468_at  AB000584_at  AB000895_at  \
0       -418.0       -351.0       -112.0        106.0       -144.0
1      -1046.0      -1123.0       1766.0       -420.0       -637.0
2      -1693.0      -1871.0       -345.0       -190.0      -1157.0
3       -893.0       -464.0        314.0       -504.0          4.0
4       -397.0       -619.0        712.0       -288.0        172.0

   AB000896_at  AB000897_at  AB000905_at  AB001106_at  AB001325_at  \
0        -83.0        -92.0        138.0        169.0        847.0
1        -59.0        -57.0        138.0        863.0        872.0
2       -104.0       -181.0        262.0        309.0       1561.0
3        -69.0        -52.0          7.0        204.0        654.0
4         55.0        -86.0        118.0        182.0        605.0

   AB002314_at  AB002315_at  AB002318_at  AB002365_at  AB002366_at  \
0         50.0        145.0        606.0        -64.0        -39.0
1       -139.0        285.0       1652.0         -8.0         38.0
2        137.0         20.0       1891.0        208.0         46.0
3         92.0        159.0        828.0        -24.0        -39.0
4         46.0        179.0        434.0        -30.0        -17.0

   AB002380_at  AB002382_at  AB002409_at  AB002559_at  AB003102_at  \
0          4.0        430.0        121.0        667.0        388.0
1         35.0        583.0       -103.0        708.0       1263.0
2        106.0        414.0       -172.0       1187.0        627.0
3        -19.0        474.0         72.0        958.0        401.0
4         73.0        365.0          0.0        916.0        583.0

   AB003103_at  AB003177_at  AB003698_at  AB004884_at  AB006190_at  \
0         26.0        365.0         61.0        791.0        548.0
1        445.0       1019.0        705.0       1655.0        852.0
2        104.0        859.0        150.0       1297.0        921.0
3         79.0        361.0        154.0        396.0        474.0
4         52.0        342.0        178.0        611.0        643.0

   AC000061_cds2_at  AC000061_cds3_at  AC000062_at  AC000064_cds1_at  \
0             225.0            -107.0        -10.0             252.0
1             149.0            -149.0        -16.0             402.0
2             882.0            -190.0         42.0             874.0
3             366.0             -52.0         49.0             272.0
4             239.0            -143.0         13.0             289.0

   AC000064_cds2_at  AC000066_at  AC000099_at  AC000115_cds1_at  \
0              93.0        -21.0         33.0            -167.0
1             218.0        -39.0        186.0            -175.0
2             175.0        -23.0        336.0              81.0
3             204.0        -99.0        124.0               4.0
4              98.0        -76.0         97.0            -121.0

   AC002045_xpt1_at  AC002073_cds1_at  AC002077_at  AC002086_at  \
0             167.0             253.0       -157.0         59.0
1             257.0             191.0       -339.0         31.0
2             145.0             -62.0       -162.0          0.0
3             129.0             154.0        -19.0         49.0
4             -13.0             124.0       -229.0         11.0

   AC002115_cds1_at  AC002115_cds3_at  AC002115_cds4_at  AC002115_rna2_at  \
0            3634.0             527.0            -862.0             507.0
1            4192.0             689.0            -833.0             536.0
2            2960.0             884.0            -650.0              84.0
3            2596.0             501.0            -262.0             554.0
4            2585.0             404.0            -693.0             374.0

   AC002450_at  AC002464_at  AC002486_at  AD000092_cds1_at  AD000092_cds2_at  \
0        -37.0        -66.0        135.0              32.0            -540.0
1       -116.0         85.0        130.0             414.0           -1373.0
2        106.0         98.0        231.0              92.0            -420.0
3         29.0        -72.0        127.0              92.0            -681.0
4         17.0        -93.0        176.0            -235.0            -583.0

   AD000684_cds1_at  AD001527_cds1_at  AF000177_at  AF000231_at  AF000234_at  \
0             -81.0             100.0         82.0         17.0       -475.0
1              28.0               7.0        449.0        209.0       -445.0
2             -92.0             247.0        275.0          9.0       -132.0
3             -82.0             229.0         99.0         22.0        -62.0
4             -26.0             112.0        110.0         15.0        -93.0

   AF000430_at  AF000545_at  AF000560_at  AF000562_at  AF000573_rna1_at  \
0        -64.0          7.0          3.0       1314.0             -19.0
1         26.0       -186.0        206.0       1044.0             -76.0
2         -9.0       -344.0        -65.0       1034.0            -179.0
3         22.0        -57.0         92.0        951.0             -77.0
4         -4.0         24.0        342.0        817.0             -43.0

   AF000959_at  AF001294_at  AF001620_at  AF002020_at  AF002224_at  \
0       -185.0       -191.0         -7.0        194.0        144.0
1       -330.0        -77.0        -65.0        257.0        348.0
2      -1026.0        159.0         78.0        350.0        650.0
3       -252.0        189.0        -42.0        204.0        312.0
4        -22.0         30.0       -103.0        149.0        391.0

   AF002700_at  AF003743_at  AF005037_at  AF005043_at  AF005361_at  \
0        358.0        573.0        -17.0         24.0        -23.0
1        285.0          4.0         61.0        217.0        -11.0
2        974.0        747.0        -37.0         29.0         18.0
3        347.0        -72.0        -24.0         74.0         82.0
4        312.0        -78.0         23.0         95.0         10.0

   AF005775_at  AF005887_at  AF006041_at  AF006084_at  AF006087_at  \
0        328.0         78.0         69.0        551.0        168.0
1        325.0        304.0       1201.0       1249.0        485.0
2        791.0       -103.0        391.0        658.0        496.0
3        454.0         37.0        594.0        456.0        674.0
4       1242.0        110.0        837.0        688.0        450.0

   AF006609_at  AF007111_at  AF007551_at  AF007875_at  AF008445_at  \
0        -39.0        118.0        104.0        156.0        247.0
1       -256.0        121.0        180.0        942.0        175.0
2       -311.0         75.0          1.0        292.0       -168.0
3         69.0        224.0         94.0        167.0       -202.0
4       -117.0        209.0         62.0        269.0        -86.0

   AF008937_at  AF009301_at  AF009368_at  AF009426_at  AF009674_at  \
0        452.0         84.0        925.0        -35.0         90.0
1        224.0        435.0        804.0        154.0       -165.0
2        375.0         34.0       1395.0         20.0       -799.0
3        204.0         39.0        716.0         14.0        446.0
4        179.0        140.0        668.0         -5.0       -146.0

   AF010193_at  AF012270_at  AF014958_at  AF015910_at  AF015913_at  \
0        534.0         95.0        306.0        460.0        337.0
1        219.0         61.0        -62.0       1046.0       1432.0
2        680.0         34.0        424.0        843.0        536.0
3        112.0         79.0        199.0       1110.0        911.0
4        288.0        134.0        176.0       1140.0        369.0

   AF015950_at  AJ000480_at  AJ001047_at  AJ001421_at  AJ001487_at  D00017_at  \
0       -137.0        682.0       -173.0        486.0       -362.0      400.0
1       -365.0        772.0       -247.0       1472.0       -164.0     1065.0
2       -863.0       1391.0       -552.0        342.0       -242.0     2664.0
3         -7.0        644.0       -292.0        888.0        -84.0     2122.0
4        105.0        833.0       -256.0        574.0       -135.0      299.0

   D00591_at  D00596_at  D00632_at  D00654_at  D00723_at  D00726_at  \
0      117.0      991.0      105.0       20.0      -15.0      344.0
1      186.0     3359.0      329.0     -149.0      177.0      426.0
2      158.0      835.0       89.0       35.0       26.0      438.0
3      112.0     1892.0      239.0      -99.0       27.0      344.0
4       17.0     1721.0      172.0      -30.0       -9.0      349.0

   D00760_at  D00761_at  D00762_at  D00763_at  D10202_at  D10495_at  \
0      425.0      447.0      242.0      470.0       80.0      209.0
1     1487.0     2769.0     1687.0     4608.0       30.0     -135.0
2      434.0      500.0      574.0     1855.0       37.0     -517.0
3      401.0      806.0      504.0     1100.0      229.0       77.0
4      761.0      894.0      654.0      794.0       73.0     -182.0

   D10511_at  D10522_at  D10523_at  D10656_at  D10704_at  D10923_at  \
0      180.0       48.0      214.0      127.0     -101.0      196.0
1      846.0      592.0      287.0       40.0       24.0       26.0
2      194.0       42.0      250.0      350.0     -639.0     -140.0
3      309.0        7.0      499.0      144.0       89.0       94.0
4      199.0      408.0      389.0      141.0      -77.0        3.0

   D10995_at  D11086_at  D11094_at  D11139_at  D11151_at  D11428_at  \
0       65.0     1956.0       43.0       37.0       -5.0     -302.0
1      437.0     2343.0      423.0      -16.0       62.0     -229.0
2      511.0      891.0      -17.0     -195.0       97.0     -531.0
3      264.0      861.0       -4.0      -32.0       -4.0     -304.0
4      262.0      833.0      109.0      -61.0       45.0       19.0

   D12485_at  D12625_at  D12676_at  D12686_at  D12763_at  D13118_at  \
0     -127.0      -37.0      -42.0    -1166.0     -259.0     2271.0
1       79.0      -52.0      -18.0    -1062.0      -10.0     3561.0
2        1.0       37.0       -9.0    -3062.0       39.0     3683.0
3      -69.0      -62.0      -54.0     -743.0      -67.0     2793.0
4      -68.0       -9.0      -15.0     -866.0     -285.0     1794.0

   D13168_at  D13264_at  D13305_at  D13315_at  D13370_at  D13435_at  \
0      -19.0      -35.0     -225.0      367.0     1061.0       61.0
1        7.0      -51.0     -575.0     1955.0     3931.0      453.0
2      115.0      -34.0     -214.0      120.0     1699.0      223.0
3       47.0      -29.0       12.0       34.0     1767.0      189.0
4       40.0      -34.0     -140.0      827.0     1335.0      180.0

   D13540_at  D13626_at  D13627_at  D13628_at  D13630_at  D13633_at  \
0       73.0        3.0     1620.0      104.0      369.0       33.0
1       39.0      638.0     3895.0      106.0      866.0      475.0
2      145.0       45.0     1639.0      403.0      686.0      126.0
3       52.0      -77.0      556.0      127.0      274.0      107.0
4       80.0       27.0     1145.0      110.0      231.0      138.0

   D13634_at  D13635_at  D13636_at  D13637_at  D13639_at  D13640_at  \
0      101.0       -2.0     -176.0       56.0     2295.0      895.0
1      244.0       84.0      449.0      432.0     3575.0      932.0
2      164.0      -92.0       -3.0     -278.0      330.0      298.0
3      132.0      -24.0      264.0     -169.0      117.0      599.0
4       55.0       -1.0       10.0     -190.0      527.0      292.0

   D13641_at  D13642_at  D13643_at  D13644_at  D13645_at  D13748_at  \
0      532.0      170.0     -278.0       17.0      -78.0     5630.0
1      698.0      134.0     -558.0       78.0       91.0     6817.0
2      492.0       42.0    -1372.0       17.0      -46.0     3229.0
3      454.0     -227.0     -269.0       22.0        4.0     4586.0
4      406.0       47.0     -418.0       53.0      -49.0     3178.0

   D13789_at  D13897_rna2_at  D13900_at  D13969_at  D13988_at  D14043_at  \
0     -605.0           271.0     1076.0      131.0      676.0      960.0
1     -353.0           444.0     3233.0      -36.0     1261.0     3479.0
2    -1314.0           234.0     1896.0     -242.0      882.0      469.0
3     -741.0           222.0     1705.0     -197.0      981.0      456.0
4     -729.0           252.0     2295.0      -54.0     1251.0      441.0

   D14134_at  D14446_at  D14497_at  D14520_at  D14530_at  D14533_at  \
0      -54.0      150.0      -13.0      -39.0    15739.0     -110.0
1     -170.0      239.0      -11.0      -33.0    21519.0      -66.0
2     -134.0      129.0       37.0       82.0    20597.0     -594.0
3      -22.0      142.0      -17.0      -44.0    14861.0     -369.0
4      -61.0       83.0       48.0      121.0    16456.0     -267.0

   D14657_at  D14658_at  D14659_at  D14660_at  D14661_at  D14662_at  \
0      806.0      303.0       50.0       46.0      276.0      413.0
1     4514.0     2177.0      114.0      144.0      805.0     1553.0
2      453.0      766.0        3.0      -37.0      359.0      638.0
3      806.0      521.0       52.0      -14.0      157.0      621.0
4     1434.0      461.0       68.0       46.0      147.0      276.0

   D14663_at  D14664_at  D14678_at  D14686_at  D14689_at  D14694_at  \
0      264.0      -12.0       47.0      462.0      949.0     1240.0
1     1039.0      140.0      -59.0      465.0      925.0     1883.0
2      586.0       -4.0     -151.0      517.0      178.0     1334.0
3      414.0      112.0       59.0      242.0      766.0     1510.0
4      419.0       28.0       14.0      345.0      435.0     1685.0

   D14695_at  D14710_at  D14811_at  D14812_at  D14822_at  D14823_at  \
0      338.0     2097.0      215.0     2193.0       51.0       23.0
1      319.0     6462.0      422.0     6604.0      -13.0       -2.0
2      -92.0     4013.0      713.0     1841.0        6.0       29.0
3      152.0     4451.0      219.0     1283.0       42.0       39.0
4      939.0     4801.0      499.0     1844.0       51.0      -32.0

   D14827_at  D14838_at  D14874_at  D14878_at  D14889_at  D15049_at  \
0      -32.0      -39.0      327.0      368.0      313.0       69.0
1      170.0      -29.0       42.0     1026.0      398.0       82.0
2      219.0       76.0      170.0      740.0      491.0     -569.0
3      304.0      -47.0      142.0      634.0      337.0      -57.0
4       79.0      -33.0      100.0      401.0      324.0     -114.0

   D15050_at  D15057_at  D16181_at  D16217_at  D16227_at  D16294_at  \
0      811.0      229.0       25.0      488.0       27.0      123.0
1      630.0     2613.0       92.0      795.0     -219.0      618.0
2      819.0      391.0      161.0      614.0     -187.0      153.0
3      571.0      541.0       72.0      304.0      -34.0      262.0
4      394.0     1379.0       45.0      830.0      -45.0      286.0

   D16350_at  D16469_at  D16532_at  D16562_at  D16581_at  D16583_at  \
0       43.0      437.0      -17.0     2432.0      757.0     -748.0
1       33.0     2058.0      126.0     3794.0     2283.0     -884.0
2      -71.0      -46.0        6.0     2617.0     1236.0     -760.0
3      -27.0      748.0      -37.0     1263.0      644.0     -259.0
4      -29.0      251.0       60.0     1911.0      489.0     -540.0

   D16593_at  D16626_at  D16815_at  D17357_at  D17390_at  D17391_at  \
0      219.0      -42.0       -8.0       38.0    -1084.0      -47.0
1       54.0     -122.0       96.0       46.0    -1022.0      -65.0
2      818.0     -139.0      165.0      225.0    -2373.0     -129.0
3      374.0      -99.0      132.0       -7.0     -679.0     -124.0
4      304.0      -62.0       65.0       46.0     -627.0     -176.0

   D17400_at  D17461_at  D17516_at  D17525_at  D17716_at  D21063_at  \
0      134.0     -283.0       48.0      407.0      421.0      274.0
1      119.0      122.0      218.0      613.0      630.0     1692.0
2     -114.0     -699.0      -75.0      262.0      776.0      866.0
3     -154.0     -142.0      134.0      651.0      409.0     1700.0
4      -22.0     -254.0       72.0      490.0      502.0     1599.0

   D21089_at  D21090_at  D21163_at  D21205_at  D21239_at  D21255_at  \
0      343.0       76.0       82.0     -614.0     -186.0       -2.0
1      850.0      338.0       87.0     -703.0     -189.0       36.0
2      600.0      242.0     -175.0    -1046.0     -167.0      -75.0
3      514.0       79.0       57.0     -601.0       77.0      -12.0
4      662.0       87.0      179.0     -507.0      -81.0      -73.0

   D21260_at  D21261_at  D21262_at  D21267_at  D21337_at  D21851_at  \
0      207.0     3951.0       29.0       59.0       27.0       99.0
1     3784.0     3303.0      246.0       48.0        9.0      156.0
2     1669.0     6020.0      267.0       39.0      198.0      139.0
3      671.0     5522.0      177.0       -7.0        2.0      172.0
4     1254.0     4258.0       -1.0       91.0      116.0      108.0

   D21852_at  D21853_at  D21878_at  D23660_at  D23662_at  D23673_at  \
0      198.0      665.0     -208.0    14790.0     1438.0     2501.0
1      685.0     1514.0      -76.0    15324.0     3997.0     6308.0
2      441.0      826.0     -236.0    15657.0      721.0     2465.0
3      267.0      776.0      -94.0    14007.0     1550.0     1632.0
4      309.0      570.0     -153.0    15542.0     1221.0     1347.0

   D25215_at  D25216_at  D25217_at  D25218_at  D25248_at  D25274_at  \
0      -31.0      637.0      393.0      256.0      286.0      294.0
1      110.0     1027.0      392.0      449.0      330.0     1554.0
2     -336.0     1646.0       -3.0       26.0      650.0      427.0
3      -94.0     1722.0      948.0      524.0      424.0      599.0
4        7.0      647.0      399.0      332.0      402.0      268.0

   D25278_at  D25303_at  D25328_at  D25538_at  D25539_at  D25547_at  \
0      361.0      299.0      206.0      161.0       28.0      498.0
1      538.0       99.0     -286.0      421.0       75.0      812.0
2      602.0      398.0     -143.0       43.0       79.0      896.0
3      394.0      -24.0      329.0      149.0      109.0      334.0
4      435.0       30.0      302.0      124.0       21.0      295.0

   D26018_at  D26067_at  D26068_at  D26069_at  D26129_at  D26135_at  \
0      -40.0      100.0     2227.0      106.0      -21.0     -238.0
1      231.0      383.0     3943.0      659.0       73.0     -264.0
2      -97.0      370.0     2417.0      186.0     -145.0     -281.0
3      102.0      199.0     2466.0      122.0       72.0      -52.0
4       86.0      281.0     2861.0       92.0       47.0     -175.0

   D26308_at  D26350_at  D26361_at  D26362_at  D26443_at  D26528_at  \
0     1217.0       14.0       98.0      833.0       56.0      150.0
1     1295.0      -24.0      217.0      654.0       -2.0      100.0
2     1012.0     -153.0      203.0      430.0      -73.0       81.0
3      978.0       17.0      262.0      479.0       87.0      107.0
4      718.0      -58.0      230.0      399.0      -27.0       47.0

   D26561_cds1_at  D26561_cds2_at  D26561_cds3_at  D26579_at  D26598_at  \
0            10.0           -36.0           -28.0      275.0     1374.0
1            27.0           111.0            20.0      276.0     3141.0
2            23.0          -204.0             6.0      337.0     1924.0
3           -37.0            -2.0            12.0      112.0     1642.0
4            24.0            55.0            35.0      233.0     1404.0


In [16]:
# Feature Summary
summary

                   index     dtype  n_missing  pct_missing  n_unique  \
0           LeukemiaType  category        0.0          0.0       2.0
1             hum_alu_at   float64        0.0          0.0      72.0
2              A28102_at   float64        0.0          0.0      66.0
3            AB000114_at   float64        0.0          0.0      58.0
4            AB000115_at   float64        0.0          0.0      63.0
5            AB000220_at   float64        0.0          0.0      51.0
6            AB000409_at   float64        0.0          0.0      68.0
7            AB000449_at   float64        0.0          0.0      68.0
8            AB000450_at   float64        0.0          0.0      63.0
9            AB000460_at   float64        0.0          0.0      71.0
10           AB000462_at   float64        0.0          0.0      69.0
11           AB000464_at   float64        0.0          0.0      68.0
12           AB000466_at   float64        0.0          0.0      71.0
13           AB000467_at   float64        0.0          0.0      71.0
14           AB000468_at   float64        0.0          0.0      69.0
15           AB000584_at   float64        0.0          0.0      70.0
16           AB000895_at   float64        0.0          0.0      68.0
17           AB000896_at   float64        0.0          0.0      64.0
18           AB000897_at   float64        0.0          0.0      66.0
19           AB000905_at   float64        0.0          0.0      58.0
20           AB001106_at   float64        0.0          0.0      67.0
21           AB001325_at   float64        0.0          0.0      72.0
22           AB002314_at   float64        0.0          0.0      67.0
23           AB002315_at   float64        0.0          0.0      67.0
24           AB002318_at   float64        0.0          0.0      71.0
25           AB002365_at   float64        0.0          0.0      66.0
26           AB002366_at   float64        0.0          0.0      60.0
27           AB002380_at   float64        0.0          0.0      66.0
28           AB002382_at   float64        0.0          0.0      69.0
29           AB002409_at   float64        0.0          0.0      63.0
30           AB002559_at   float64        0.0          0.0      72.0
31           AB003102_at   float64        0.0          0.0      67.0
32           AB003103_at   float64        0.0          0.0      62.0
33           AB003177_at   float64        0.0          0.0      68.0
34           AB003698_at   float64        0.0          0.0      67.0
35           AB004884_at   float64        0.0          0.0      71.0
36           AB006190_at   float64        0.0          0.0      69.0
37      AC000061_cds2_at   float64        0.0          0.0      68.0
38      AC000061_cds3_at   float64        0.0          0.0      62.0
39           AC000062_at   float64        0.0          0.0      55.0
40      AC000064_cds1_at   float64        0.0          0.0      68.0
41      AC000064_cds2_at   float64        0.0          0.0      64.0
42           AC000066_at   float64        0.0          0.0      57.0
43           AC000099_at   float64        0.0          0.0      64.0
44      AC000115_cds1_at   float64        0.0          0.0      68.0
45      AC002045_xpt1_at   float64        0.0          0.0      59.0
46      AC002073_cds1_at   float64        0.0          0.0      68.0
47           AC002077_at   float64        0.0          0.0      69.0
48           AC002086_at   float64        0.0          0.0      53.0
49      AC002115_cds1_at   float64        0.0          0.0      72.0
50      AC002115_cds3_at   float64        0.0          0.0      68.0
51      AC002115_cds4_at   float64        0.0          0.0      68.0
52      AC002115_rna2_at   float64        0.0          0.0      67.0
53           AC002450_at   float64        0.0          0.0      65.0
54           AC002464_at   float64        0.0          0.0      66.0
55           AC002486_at   float64        0.0          0.0      59.0
56      AD000092_cds1_at   float64        0.0          0.0      69.0
57      AD000092_cds2_at   float64        0.0          0.0      68.0
58      AD000684_cds1_at   float64        0.0          0.0      66.0
59      AD001527_cds1_at   float64        0.0          0.0      62.0
60           AF000177_at   float64        0.0          0.0      68.0
61           AF000231_at   float64        0.0          0.0      61.0
62           AF000234_at   float64        0.0          0.0      71.0
63           AF000430_at   float64        0.0          0.0      64.0
64           AF000545_at   float64        0.0          0.0      68.0
65           AF000560_at   float64        0.0          0.0      71.0
66           AF000562_at   float64        0.0          0.0      70.0
67      AF000573_rna1_at   float64        0.0          0.0      65.0
68           AF000959_at   float64        0.0          0.0      70.0
69           AF001294_at   float64        0.0          0.0      71.0
70           AF001620_at   float64        0.0          0.0      62.0
71           AF002020_at   float64        0.0          0.0      64.0
72           AF002224_at   float64        0.0          0.0      70.0
73           AF002700_at   float64        0.0          0.0      68.0
74           AF003743_at   float64        0.0          0.0      70.0
75           AF005037_at   float64        0.0          0.0      60.0
76           AF005043_at   float64        0.0          0.0      61.0
77           AF005361_at   float64        0.0          0.0      63.0
78           AF005775_at   float64        0.0          0.0      71.0
79           AF005887_at   float64        0.0          0.0      66.0
80           AF006041_at   float64        0.0          0.0      71.0
81           AF006084_at   float64        0.0          0.0      70.0
82           AF006087_at   float64        0.0          0.0      72.0
83           AF006609_at   float64        0.0          0.0      68.0
84           AF007111_at   float64        0.0          0.0      71.0
85           AF007551_at   float64        0.0          0.0      68.0
86           AF007875_at   float64        0.0          0.0      66.0
87           AF008445_at   float64        0.0          0.0      66.0
88           AF008937_at   float64        0.0          0.0      68.0
89           AF009301_at   float64        0.0          0.0      67.0
90           AF009368_at   float64        0.0          0.0      72.0
91           AF009426_at   float64        0.0          0.0      67.0
92           AF009674_at   float64        0.0          0.0      70.0
93           AF010193_at   float64        0.0          0.0      69.0
94           AF012270_at   float64        0.0          0.0      64.0
95           AF014958_at   float64        0.0          0.0      63.0
96           AF015910_at   float64        0.0          0.0      71.0
97           AF015913_at   float64        0.0          0.0      69.0
98           AF015950_at   float64        0.0          0.0      70.0
99           AJ000480_at   float64        0.0          0.0      71.0
100          AJ001047_at   float64        0.0          0.0      70.0
101          AJ001421_at   float64        0.0          0.0      72.0
102          AJ001487_at   float64        0.0          0.0      66.0
103            D00017_at   float64        0.0          0.0      72.0
104            D00591_at   float64        0.0          0.0      67.0
105            D00596_at   float64        0.0          0.0      72.0
106            D00632_at   float64        0.0          0.0      69.0
107            D00654_at   float64        0.0          0.0      67.0
108            D00723_at   float64        0.0          0.0      60.0
109            D00726_at   float64        0.0          0.0      68.0
110            D00760_at   float64        0.0          0.0      71.0
111            D00761_at   float64        0.0          0.0      72.0
112            D00762_at   float64        0.0          0.0      70.0
113            D00763_at   float64        0.0          0.0      71.0
114            D10202_at   float64        0.0          0.0      68.0
115            D10495_at   float64        0.0          0.0      70.0
116            D10511_at   float64        0.0          0.0      69.0
117            D10522_at   float64        0.0          0.0      64.0
118            D10523_at   float64        0.0          0.0      68.0
119            D10656_at   float64        0.0          0.0      68.0
120            D10704_at   float64        0.0          0.0      67.0
121            D10923_at   float64        0.0          0.0      63.0
122            D10995_at   float64        0.0          0.0      68.0
123            D11086_at   float64        0.0          0.0      71.0
124            D11094_at   float64        0.0          0.0      69.0
125            D11139_at   float64        0.0          0.0      64.0
126            D11151_at   float64        0.0          0.0      61.0
127            D11428_at   float64        0.0          0.0      71.0
128            D12485_at   float64        0.0          0.0      60.0
129            D12625_at   float64        0.0          0.0      61.0
130            D12676_at   float64        0.0          0.0      63.0
131            D12686_at   float64        0.0          0.0      71.0
132            D12763_at   float64        0.0          0.0      65.0
133            D13118_at   float64        0.0          0.0      72.0
134            D13168_at   float64        0.0          0.0      50.0
135            D13264_at   float64        0.0          0.0      57.0
136            D13305_at   float64        0.0          0.0      67.0
137            D13315_at   float64        0.0          0.0      70.0
138            D13370_at   float64        0.0          0.0      69.0
139            D13435_at   float64        0.0          0.0      65.0
140            D13540_at   float64        0.0          0.0      66.0
141            D13626_at   float64        0.0          0.0      63.0
142            D13627_at   float64        0.0          0.0      69.0
143            D13628_at   float64        0.0          0.0      65.0
144            D13630_at   float64        0.0          0.0      68.0
145            D13633_at   float64        0.0          0.0      60.0
146            D13634_at   float64        0.0          0.0      62.0
147            D13635_at   float64        0.0          0.0      62.0
148            D13636_at   float64        0.0          0.0      69.0
149            D13637_at   float64        0.0          0.0      70.0
150            D13639_at   float64        0.0          0.0      72.0
151            D13640_at   float64        0.0          0.0      71.0
152            D13641_at   float64        0.0          0.0      72.0
153            D13642_at   float64        0.0          0.0      67.0
154            D13643_at   float64        0.0          0.0      69.0
155            D13644_at   float64        0.0          0.0      56.0
156            D13645_at   float64        0.0          0.0      67.0
157            D13748_at   float64        0.0          0.0      71.0
158            D13789_at   float64        0.0          0.0      71.0
159       D13897_rna2_at   float64        0.0          0.0      71.0
160            D13900_at   float64        0.0          0.0      71.0
161            D13969_at   float64        0.0          0.0      64.0
162            D13988_at   float64        0.0          0.0      70.0
163            D14043_at   float64        0.0          0.0      70.0
164            D14134_at   float64        0.0          0.0      61.0
165            D14446_at   float64        0.0          0.0      62.0
166            D14497_at   float64        0.0          0.0      56.0
167            D14520_at   float64        0.0          0.0      60.0
168            D14530_at   float64        0.0          0.0      72.0
169            D14533_at   float64        0.0          0.0      70.0
170            D14657_at   float64        0.0          0.0      71.0
171            D14658_at   float64        0.0          0.0      72.0
172            D14659_at   float64        0.0          0.0      59.0
173            D14660_at   float64        0.0          0.0      60.0
174            D14661_at   float64        0.0          0.0      66.0
175            D14662_at   float64        0.0          0.0      70.0
176            D14663_at   float64        0.0          0.0      68.0
177            D14664_at   float64        0.0          0.0      67.0
178            D14678_at   float64        0.0          0.0      68.0
179            D14686_at   float64        0.0          0.0      69.0
180            D14689_at   float64        0.0          0.0      71.0
181            D14694_at   float64        0.0          0.0      70.0
182            D14695_at   float64        0.0          0.0      68.0
183            D14710_at   float64        0.0          0.0      72.0
184            D14811_at   float64        0.0          0.0      70.0
185            D14812_at   float64        0.0          0.0      72.0
186            D14822_at   float64        0.0          0.0      52.0
187            D14823_at   float64        0.0          0.0      58.0
188            D14827_at   float64        0.0          0.0      67.0
189            D14838_at   float64        0.0          0.0      65.0
190            D14874_at   float64        0.0          0.0      66.0
191            D14878_at   float64        0.0          0.0      68.0
192            D14889_at   float64        0.0          0.0      63.0
193            D15049_at   float64        0.0          0.0      65.0
194            D15050_at   float64        0.0          0.0      71.0
195            D15057_at   float64        0.0          0.0      71.0
196            D16181_at   float64        0.0          0.0      60.0
197            D16217_at   float64        0.0          0.0      71.0
198            D16227_at   float64        0.0          0.0      69.0
199            D16294_at   float64        0.0          0.0      68.0
200            D16350_at   float64        0.0          0.0      62.0
201            D16469_at   float64        0.0          0.0      70.0
202            D16532_at   float64        0.0          0.0      61.0
203            D16562_at   float64        0.0          0.0      71.0
204            D16581_at   float64        0.0          0.0      72.0
205            D16583_at   float64        0.0          0.0      69.0
206            D16593_at   float64        0.0          0.0      70.0
207            D16626_at   float64        0.0          0.0      63.0
208            D16815_at   float64        0.0          0.0      64.0
209            D17357_at   float64        0.0          0.0      65.0
210            D17390_at   float64        0.0          0.0      72.0
211            D17391_at   float64        0.0          0.0      60.0
212            D17400_at   float64        0.0          0.0      68.0
213            D17461_at   float64        0.0          0.0      70.0
214            D17516_at   float64        0.0          0.0      65.0
215            D17525_at   float64        0.0          0.0      70.0
216            D17716_at   float64        0.0          0.0      70.0
217            D21063_at   float64        0.0          0.0      70.0
218            D21089_at   float64        0.0          0.0      70.0
219            D21090_at   float64        0.0          0.0      62.0
220            D21163_at   float64        0.0          0.0      68.0
221            D21205_at   float64        0.0          0.0      68.0
222            D21239_at   float64        0.0          0.0      66.0
223            D21255_at   float64        0.0          0.0      59.0
224            D21260_at   float64        0.0          0.0      71.0
225            D21261_at   float64        0.0          0.0      72.0
226            D21262_at   float64        0.0          0.0      69.0
227            D21267_at   float64        0.0          0.0      61.0
228            D21337_at   float64        0.0          0.0      64.0
229            D21851_at   float64        0.0          0.0      57.0
230            D21852_at   float64        0.0          0.0      69.0
231            D21853_at   float64        0.0          0.0      69.0
232            D21878_at   float64        0.0          0.0      61.0
233            D23660_at   float64        0.0          0.0      71.0
234            D23662_at   float64        0.0          0.0      71.0
235            D23673_at   float64        0.0          0.0      71.0
236            D25215_at   float64        0.0          0.0      58.0
237            D25216_at   float64        0.0          0.0      70.0
238            D25217_at   float64        0.0          0.0      70.0
239            D25218_at   float64        0.0          0.0      69.0
240            D25248_at   float64        0.0          0.0      70.0
241            D25274_at   float64        0.0          0.0      71.0
242            D25278_at   float64        0.0          0.0      65.0
243            D25303_at   float64        0.0          0.0      67.0
244            D25328_at   float64        0.0          0.0      69.0
245            D25538_at   float64        0.0          0.0      69.0
246            D25539_at   float64        0.0          0.0      69.0
247            D25547_at   float64        0.0          0.0      69.0
248            D26018_at   float64        0.0          0.0      68.0
249            D26067_at   float64        0.0          0.0      68.0
250            D26068_at   float64        0.0          0.0      71.0
251            D26069_at   float64        0.0          0.0      66.0
252            D26129_at   float64        0.0          0.0      63.0
253            D26135_at   float64        0.0          0.0      65.0
254            D26308_at   float64        0.0          0.0      70.0
255            D26350_at   float64        0.0          0.0      58.0
256            D26361_at   float64        0.0          0.0      64.0
257            D26362_at   float64        0.0          0.0      71.0
258            D26443_at   float64        0.0          0.0      59.0
259            D26528_at   float64        0.0          0.0      58.0
260       D26561_cds1_at   float64        0.0          0.0      61.0
261       D26561_cds2_at   float64        0.0          0.0      61.0
262       D26561_cds3_at   float64        0.0          0.0      55.0
263            D26579_at   float64        0.0          0.0      68.0
264            D26598_at   float64        0.0          0.0      69.0
265            D26599_at   float64        0.0          0.0      71.0
266            D26600_at   float64        0.0          0.0      71.0
267            D28114_at   float64        0.0          0.0      63.0
268            D28118_at   float64        0.0          0.0      66.0
269            D28124_at   float64        0.0          0.0      69.0
270            D28137_at   float64        0.0          0.0      70.0
271            D28364_at   float64        0.0          0.0      67.0
272            D28383_at   float64        0.0          0.0      64.0
273            D28416_at   float64        0.0          0.0      70.0
274            D28423_at   float64        0.0          0.0      72.0
275            D28476_at   float64        0.0          0.0      69.0
276            D28483_at   float64        0.0          0.0      64.0
277            D28532_at   float64        0.0          0.0      69.0
278            D28588_at   float64        0.0          0.0      67.0
279            D28589_at   float64        0.0          0.0      69.0
280            D28915_at   float64        0.0          0.0      69.0
281            D29012_at   float64        0.0          0.0      70.0
282            D29013_at   float64        0.0          0.0      70.0
283            D29641_at   float64        0.0          0.0      65.0
284            D29642_at   float64        0.0          0.0      70.0
285            D29643_at   float64        0.0          0.0      71.0
286            D29677_at   float64        0.0          0.0      68.0
287            D29810_at   float64        0.0          0.0      59.0

In [17]:
# Numeric Feature Statistics
numeric_stats

                    count          mean           std      min      max
hum_alu_at           72.0  25209.180556  10882.622106   6479.0  58203.0
A28102_at            72.0    278.013889    189.318979     20.0   1106.0
AB000114_at          72.0     30.805556     66.629655   -212.0    249.0
AB000115_at          72.0    296.250000    373.146414     65.0   2194.0
AB000220_at          72.0     44.444444     47.778506    -61.0    202.0
AB000409_at          72.0     24.722222    203.801286   -520.0    845.0
AB000449_at          72.0    214.208333    182.164756    -41.0    971.0
AB000450_at          72.0    179.222222    114.225404      2.0    556.0
AB000460_at          72.0   1824.083333    562.957826    714.0   3570.0
AB000462_at          72.0    143.666667    144.610502   -112.0    566.0
AB000464_at          72.0    753.013889    387.564606    180.0   2514.0
AB000466_at          72.0   -899.222222    417.422481  -1940.0   -322.0
AB000467_at          72.0   -735.152778    333.504341  -1871.0   -179.0
AB000468_at          72.0    469.819444    520.643273   -345.0   2503.0
AB000584_at          72.0   -140.736111    380.313918  -1200.0   1885.0
AB000895_at          72.0   -388.305556    381.057078  -1385.0    393.0
AB000896_at          72.0   -114.069444    126.872935   -633.0    148.0
AB000897_at          72.0   -100.222222     73.940445   -268.0    111.0
AB000905_at          72.0    116.625000     68.049575    -27.0    301.0
AB001106_at          72.0    349.861111    193.797433     88.0    921.0
AB001325_at          72.0    936.152778    396.665952    359.0   1968.0
AB002314_at          72.0      6.194444     78.287595   -202.0    145.0
AB002315_at          72.0    179.986111    135.479378    -92.0    660.0
AB002318_at          72.0    951.388889    434.162868     67.0   2356.0
AB002365_at          72.0     46.263889    101.598629   -140.0    551.0
AB002366_at          72.0    -10.250000     66.514162   -266.0    129.0
AB002380_at          72.0     45.819444     87.658802    -95.0    458.0
AB002382_at          72.0    464.138889    276.012059     60.0   1410.0
AB002409_at          72.0     17.180556    103.150147   -236.0    249.0
AB002559_at          72.0   1281.486111    664.441500    138.0   3601.0
AB003102_at          72.0    634.458333    277.049034    141.0   1571.0
AB003103_at          72.0    101.694444     90.275890    -40.0    453.0
AB003177_at          72.0    661.708333    270.772210    196.0   1321.0
AB003698_at          72.0    181.277778    129.827103     -7.0    705.0
AB004884_at          72.0    808.652778    337.685709    286.0   1882.0
AB006190_at          72.0    650.791667    216.901285    321.0   1558.0
AC000061_cds2_at     72.0    313.986111    210.123672     -1.0    982.0
AC000061_cds3_at     72.0   -107.402778     66.159572   -282.0     26.0
AC000062_at          72.0     -6.722222     28.504619    -81.0     65.0
AC000064_cds1_at     72.0    397.166667    198.337953    125.0   1068.0
AC000064_cds2_at     72.0    144.930556     80.327030   -163.0    305.0
AC000066_at          72.0    -15.847222     40.071998    -99.0     89.0
AC000099_at          72.0    124.555556     87.690700   -160.0    336.0
AC000115_cds1_at     72.0    -86.958333    110.298371   -351.0    155.0
AC002045_xpt1_at     72.0    142.750000     89.085929    -13.0    518.0
AC002073_cds1_at     72.0    141.000000    182.717746   -189.0    694.0
AC002077_at          72.0   -300.722222    241.088157  -1365.0    241.0
AC002086_at          72.0     34.930556     52.026355    -92.0    160.0
AC002115_cds1_at     72.0   3225.833333   1307.011999   1253.0   9268.0
AC002115_cds3_at     72.0    638.944444    193.804089    298.0   1007.0
AC002115_cds4_at     72.0   -945.666667    417.479459  -2070.0   -137.0
AC002115_rna2_at     72.0    419.583333    190.408512     -8.0   1000.0
AC002450_at          72.0    -15.888889     90.442037   -283.0    154.0
AC002464_at          72.0    -63.722222    142.831647   -403.0    277.0
AC002486_at          72.0    171.250000     79.644766     12.0    352.0
AD000092_cds1_at     72.0    160.402778    320.322842   -574.0   1539.0
AD000092_cds2_at     72.0   -796.569444    508.032377  -2802.0     51.0
AD000684_cds1_at     72.0    -87.875000    109.525087   -420.0    103.0
AD001527_cds1_at     72.0    138.500000     72.282895    -34.0    354.0
AF000177_at          72.0    111.597222    170.012813   -263.0    485.0
AF000231_at          72.0     72.055556    118.824511   -161.0    704.0
AF000234_at          72.0   -211.083333    254.208451  -1073.0    333.0
AF000430_at          72.0     -0.500000     48.447445   -103.0    117.0
AF000545_at          72.0   -159.986111    194.820140   -669.0    154.0
AF000560_at          72.0    228.888889    250.702874   -205.0    892.0
AF000562_at          72.0   1012.347222    437.181986    126.0   2446.0
AF000573_rna1_at     72.0    -67.486111     63.572071   -241.0     60.0
AF000959_at          72.0   -421.805556    212.752295  -1026.0     89.0
AF001294_at          72.0     72.111111    179.405321   -349.0    469.0
AF001620_at          72.0    -52.166667     79.777154   -343.0     96.0
AF002020_at          72.0    184.347222     86.383710     -9.0    439.0
AF002224_at          72.0    397.819444    209.219834     11.0    954.0
AF002700_at          72.0    429.527778    227.067215     37.0   1069.0
AF003743_at          72.0    202.597222    348.371732   -633.0   1013.0
AF005037_at          72.0     27.680556     69.811784   -166.0    240.0
AF005043_at          72.0     44.277778     62.009591    -76.0    217.0
AF005361_at          72.0     -9.722222     48.558727   -196.0     82.0
AF005775_at          72.0    612.138889    307.166712    131.0   1758.0
AF005887_at          72.0     87.194444    119.528491   -356.0    339.0
AF006041_at          72.0    773.055556    486.300692   -293.0   2126.0
AF006084_at          72.0   1004.597222    605.660288    126.0   3219.0
AF006087_at          72.0    587.666667    320.700949      3.0   1693.0
AF006609_at          72.0   -200.847222    275.908724  -1661.0    413.0
AF007111_at          72.0    197.597222    128.599352   -142.0    564.0
AF007551_at          72.0    134.722222    123.101266    -69.0    490.0
AF007875_at          72.0    307.125000    182.291821     82.0   1157.0
AF008445_at          72.0    134.902778    375.552969   -428.0   1829.0
AF008937_at          72.0    355.250000    166.405897     16.0    993.0
AF009301_at          72.0    181.055556    187.504508    -43.0   1007.0
AF009368_at          72.0    906.444444    333.380123    356.0   1793.0
AF009426_at          72.0     28.597222     83.651635   -139.0    268.0
AF009674_at          72.0    -39.402778    363.558146  -1076.0   1073.0
AF010193_at          72.0    300.555556    243.189944    -31.0   1757.0
AF012270_at          72.0    120.333333    106.487188    -95.0    485.0
AF014958_at          72.0    198.569444    188.161141    -71.0   1057.0
AF015910_at          72.0    967.069444    600.016228    119.0   2739.0
AF015913_at          72.0    615.569444    438.554406      0.0   2460.0
AF015950_at          72.0   -290.333333    307.699323  -1165.0    334.0
AJ000480_at          72.0    899.791667    569.079091    254.0   2912.0
AJ001047_at          72.0   -245.388889    144.218785   -620.0     89.0
AJ001421_at          72.0    879.847222    437.095331    141.0   1904.0
AJ001487_at          72.0   -344.041667    195.500473   -875.0    -37.0
D00017_at            72.0   2048.027778   2098.125192    -94.0   8752.0
D00591_at            72.0    185.958333    168.249767   -277.0    536.0
D00596_at            72.0   1472.263889   1158.236347    153.0   6284.0
D00632_at            72.0    289.305556    183.339801     41.0    894.0
D00654_at            72.0    -21.944444     94.660980   -265.0    348.0
D00723_at            72.0     56.222222    114.852535    -64.0    697.0
D00726_at            72.0    504.750000    543.252587     61.0   3048.0
D00760_at            72.0    612.402778    376.109538     78.0   2159.0
D00761_at            72.0   1133.083333    604.284369     27.0   2992.0
D00762_at            72.0    594.486111    307.458551     98.0   1694.0
D00763_at            72.0   1506.041667   1027.493003    470.0   6521.0
D10202_at            72.0     51.833333    205.296831   -393.0   1008.0
D10495_at            72.0    317.361111    627.955778   -517.0   2651.0
D10511_at            72.0    222.888889    207.183973    -87.0    986.0
D10522_at            72.0    287.138889    424.348459    -35.0   2719.0
D10523_at            72.0    429.222222    275.006695    -54.0   1409.0
D10656_at            72.0    163.180556    113.775332    -53.0    547.0
D10704_at            72.0    -40.125000    209.431957   -650.0    441.0
D10923_at            72.0     64.152778    205.489499   -140.0   1412.0
D10995_at            72.0    351.208333    185.707246    -34.0    818.0
D11086_at            72.0   1801.291667   1220.123942    225.0   7260.0
D11094_at            72.0    208.750000    283.537153   -292.0   1276.0
D11139_at            72.0    -42.111111    101.007259   -350.0    159.0
D11151_at            72.0     69.222222     54.339886    -88.0    201.0
D11428_at            72.0    -68.222222    492.040140   -612.0   3634.0
D12485_at            72.0     23.013889     72.413230   -192.0    171.0
D12625_at            72.0    -10.291667     48.441176   -110.0    166.0
D12676_at            72.0    -28.763889     63.069042   -292.0    105.0
D12686_at            72.0  -1095.111111    559.011717  -3062.0    178.0
D12763_at            72.0   -148.750000    148.513930   -632.0     78.0
D13118_at            72.0   3055.736111    960.418453   1605.0   7344.0
D13168_at            72.0     14.069444     32.856635    -44.0    115.0
D13264_at            72.0    -25.861111     43.657536   -128.0     76.0
D13305_at            72.0   -235.361111    231.808888  -1312.0    211.0
D13315_at            72.0    624.708333    434.997375   -168.0   1955.0
D13370_at            72.0   1818.611111    829.301616    676.0   5912.0
D13435_at            72.0    211.513889    142.228144      0.0    809.0
D13540_at            72.0    131.347222     91.575130     -7.0    474.0
D13626_at            72.0     36.263889    210.255043   -387.0   1238.0
D13627_at            72.0    939.263889    791.632597    129.0   4074.0
D13628_at            72.0    238.888889    316.530111    -17.0   2326.0
D13630_at            72.0    570.875000    342.100057    214.0   2299.0
D13633_at            72.0     98.763889     95.496847    -26.0    488.0
D13634_at            72.0    153.111111     64.180545     31.0    303.0
D13635_at            72.0     -3.236111     71.741023   -159.0    276.0
D13636_at            72.0    111.597222    241.536027   -655.0   1066.0
D13637_at            72.0    -12.680556    166.497035   -535.0    432.0
D13639_at            72.0   1574.125000   1554.867160    -44.0   7650.0
D13640_at            72.0    915.555556    668.225185    -34.0   3819.0
D13641_at            72.0    915.958333    636.719175    171.0   4643.0
D13642_at            72.0     88.888889    128.371880   -238.0    372.0
D13643_at            72.0   -448.500000    378.871973  -1661.0    824.0
D13644_at            72.0     39.902778     45.588533    -39.0    178.0
D13645_at            72.0    -32.138889    156.003820   -374.0    724.0
D13748_at            72.0   5804.513889   2320.174447    328.0  11217.0
D13789_at            72.0   -710.958333    328.644610  -1725.0    217.0
D13897_rna2_at       72.0    406.263889    202.279335     15.0   1267.0
D13900_at            72.0   1752.111111    679.146493    704.0   4253.0
D13969_at            72.0   -150.944444    121.860794   -454.0    131.0
D13988_at            72.0   1251.694444    706.200858    100.0   3556.0
D14043_at            72.0   1092.875000   1019.419580    151.0   7309.0
D14134_at            72.0   -112.805556     63.982973   -341.0     29.0
D14446_at            72.0    146.111111     71.117351    -34.0    371.0
D14497_at            72.0      5.500000     37.561593    -99.0     87.0
D14520_at            72.0     15.375000     72.691018   -223.0    160.0
D14530_at            72.0  17229.791667   2732.141398  10739.0  26343.0
D14533_at            72.0   -198.222222    154.812856   -594.0    317.0
D14657_at            72.0   1096.055556    895.252170     74.0   4514.0
D14658_at            72.0    758.361111    513.264512    166.0   3110.0
D14659_at            72.0     47.125000     50.401469    -63.0    163.0
D14660_at            72.0     -6.541667     56.757437   -184.0    144.0
D14661_at            72.0    461.555556    274.868516     41.0   1383.0
D14662_at            72.0    726.680556    382.973791    221.0   2303.0
D14663_at            72.0    586.597222    308.975803    110.0   1605.0
D14664_at            72.0    142.222222    181.593589   -132.0    819.0
D14678_at            72.0    -67.902778    177.567298   -868.0    252.0
D14686_at            72.0    341.166667    255.445592   -247.0   1434.0
D14689_at            72.0    702.680556    378.682030    -43.0   1542.0
D14694_at            72.0   1762.402778    925.458678    732.0   7834.0
D14695_at            72.0    275.541667    260.555849   -172.0   1477.0
D14710_at            72.0   4564.027778   2219.133691   1470.0  13742.0
D14811_at            72.0    341.555556    203.040819    -83.0    838.0
D14812_at            72.0   2553.569444   1170.946082    846.0   7252.0
D14822_at            72.0      9.125000     41.520379   -121.0    100.0
D14823_at            72.0     22.513889     48.197362    -71.0    174.0
D14827_at            72.0     26.333333    222.128880   -409.0    961.0
D14838_at            72.0    -22.555556    155.909950   -247.0    930.0
D14874_at            72.0    169.888889    131.026022   -106.0    770.0
D14878_at            72.0    528.527778    262.353808    136.0   1563.0
D14889_at            72.0    443.111111    163.965434    111.0    848.0
D15049_at            72.0     34.361111    173.354014   -569.0    434.0
D15050_at            72.0    902.597222    619.944629    157.0   3392.0
D15057_at            72.0    778.722222    835.722294      9.0   4655.0
D16181_at            72.0     51.027778     52.321857   -105.0    187.0
D16217_at            72.0    661.166667    335.339937    248.0   1862.0
D16227_at            72.0   -152.513889    208.740353   -662.0    355.0
D16294_at            72.0    269.875000    184.471528    -64.0    747.0
D16350_at            72.0     20.736111     67.435936    -90.0    293.0
D16469_at            72.0    900.513889    650.919956    -46.0   3697.0
D16532_at            72.0     43.819444    126.605890    -83.0    835.0
D16562_at            72.0   2798.861111   1338.857073    887.0   8736.0
D16581_at            72.0   1044.013889    451.358154    179.0   2426.0
D16583_at            72.0   -532.097222    372.093512  -1480.0   1603.0
D16593_at            72.0    413.486111    364.661178   -276.0   2395.0
D16626_at            72.0    -72.833333    132.752125   -444.0    468.0
D16815_at            72.0     46.208333     99.197049   -413.0    245.0
D17357_at            72.0     35.277778    104.452863   -602.0    235.0
D17390_at            72.0  -1031.708333    411.607205  -2373.0   -380.0
D17391_at            72.0    -55.777778     51.424832   -176.0     54.0
D17400_at            72.0     16.305556    157.771330   -263.0    590.0
D17461_at            72.0   -265.861111    215.297456   -925.0    221.0
D17516_at            72.0     75.736111    141.879536   -240.0    600.0
D17525_at            72.0    512.263889    321.387178   -196.0   1390.0
D17716_at            72.0    461.319444    278.252233   -174.0   1393.0
D21063_at            72.0    858.319444    723.360795   -146.0   2793.0
D21089_at            72.0    666.819444    263.623629    290.0   1653.0
D21090_at            72.0    193.597222    118.181724    -12.0    649.0
D21163_at            72.0     21.013889    153.740177   -538.0    365.0
D21205_at            72.0   -535.569444    234.546781  -1485.0    204.0
D21239_at            72.0    -82.930556     99.737730   -300.0    168.0
D21255_at            72.0    -20.444444    132.116774   -155.0    618.0
D21260_at            72.0   1434.597222   1964.472847    207.0  15646.0
D21261_at            72.0   8183.291667   4230.321199   1779.0  18941.0
D21262_at            72.0    160.625000    226.099843    -80.0   1398.0
D21267_at            72.0     32.097222     58.526065   -202.0    164.0
D21337_at            72.0     26.180556     73.033530   -113.0    205.0
D21851_at            72.0    115.791667     55.677881      8.0    253.0
D21852_at            72.0    444.430556    281.292581     64.0   1882.0
D21853_at            72.0    792.888889    329.180568    164.0   1923.0
D21878_at            72.0    -97.444444     97.514302   -336.0    235.0
D23660_at            72.0  14836.416667   3209.355579   7902.0  23144.0
D23662_at            72.0   1682.194444    702.924868    611.0   4157.0
D23673_at            72.0   2103.513889    883.859861    796.0   6308.0
D25215_at            72.0    -67.291667     92.338696   -384.0    142.0
D25216_at            72.0   1167.736111    447.285018    268.0   2359.0
D25217_at            72.0    551.388889    394.501131   -253.0   1537.0
D25218_at            72.0    374.166667    169.646941     26.0   1097.0
D25248_at            72.0    339.458333    149.205118     29.0    749.0
D25274_at            72.0    912.375000    633.348811    -92.0   3903.0
D25278_at            72.0    442.666667    193.524683    108.0   1309.0
D25303_at            72.0    175.541667    144.996643   -128.0    499.0
D25328_at            72.0    200.486111    348.659485   -286.0   1714.0
D25538_at            72.0    251.777778    249.557480    -79.0   1325.0
D25539_at            72.0    119.930556    155.838516   -129.0    522.0
D25547_at            72.0    520.319444    287.574011    -29.0   1247.0
D26018_at            72.0     13.861111    124.062036   -252.0    330.0
D26067_at            72.0    199.819444    120.007902     -6.0    553.0
D26068_at            72.0   3342.347222   1341.677436   1521.0   8467.0
D26069_at            72.0    239.611111    125.037296     41.0    666.0
D26129_at            72.0    114.861111    787.699508   -309.0   6559.0
D26135_at            72.0   -227.583333     96.369119   -563.0    -52.0
D26308_at            72.0   1344.277778   1475.318139    213.0   8703.0
D26350_at            72.0    -62.958333     62.062993   -266.0    154.0
D26361_at            72.0    142.944444    100.227894   -505.0    324.0
D26362_at            72.0    664.291667    237.333748    293.0   1623.0
D26443_at            72.0      4.222222     58.291937   -105.0    252.0
D26528_at            72.0    124.152778     61.233715     -2.0    292.0
D26561_cds1_at       72.0      9.972222     39.643116   -100.0    142.0
D26561_cds2_at       72.0     44.430556     77.429082   -204.0    302.0
D26561_cds3_at       72.0      9.319444     45.501223    -73.0    144.0
D26579_at            72.0    430.194444    386.799531     57.0   2474.0
D26598_at            72.0   1888.763889    636.447900    849.0   4399.0
D26599_at            72.0   1846.125000    814.452152    746.0   4808.0
D26600_at            72.0   1559.930556    641.607693    590.0   3509.0
D28114_at            72.0    316.138889    144.449641     89.0    707.0
D28118_at            72.0    390.652778    288.431121     31.0   2102.0
D28124_at            72.0    821.208333    336.201521    256.0   2195.0
D28137_at            72.0    805.541667    560.581663     87.0   3732.0
D28364_at            72.0    180.236111    149.928104      0.0    751.0
D28383_at            72.0    205.791667    165.575219    -80.0    654.0
D28416_at            72.0   1603.055556    617.100373    328.0   3612.0
D28423_at            72.0   1571.680556   1026.506736    -41.0   4919.0
D28476_at            72.0    731.541667    425.843023    199.0   2881.0
D28483_at            72.0    209.125000    122.142371     11.0    558.0

In [18]:
# Categorical Feature Statistics
cat_stats

                  value  count    pct
column       rank
LeukemiaType 1      ALL     47  65.28
             2      AML     25  34.72

In [19]:
# Target Distribution
target_df

              count    pct
LeukemiaType
ALL              47  65.28
AML              25  34.72

## Task Curation

In [20]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=20, n_splits=3, test_size=None

In [21]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [22]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to leukemia_allaml/019d9d0f-09f2-7aca-8924-fd2db0f15985
019d9d0f-09f2-7aca-8924-fd2db0f15985
113ad398e937622ebdd161b3dea296ed37c5e7b6b91d560bb4ab53dfe69cdb7a