### Dataset and Task Metadata

In [82]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="lymphoma9",
    dataset_year="2017",
    domain_str="business & marketing",
    # Data Source
    dataset_source="GOV Website",
    original_dataset_source_download_link="https://llmpp.ccr.cancer.gov/lymphoma/data.shtml",
    download_description="""
Download from UCI and uzip data to a predefined folder.
mkdir -p local-data-warehouse/lymphoma9/ && wget -P local-data-warehouse/lymphoma9/ https://llmpp.ccr.cancer.gov/lymphoma/data/figure1/figure1.cdt 
""",
    # References
    academic_reference_bibtex="""@article{alizadeh2000lymphoma9,
  title={Distinct types of diffuse large B-cell lymphoma identified by gene expression profiling},
  author={Alizadeh, Ash A and Eisen, Michael B and Davis, R Eric and Ma, Chi and Lossos, Izidore S and Rosenwald, Andreas and Boldrick, Jennifer C and Sabet, Hajeer and Tran, Truc and Yu, Xin and others},
  journal={Nature},
  volume={403},
  number={6769},
  pages={503--511},
  year={2000},
  publisher={Nature Publishing Group UK London}
}
""",
    academic_reference_bibtex_key="alizadeh2000lymphoma9",
    license="Public Domain",
    data_tags=["IID"],
    curation_comments="""
- We transposed the dataset, so that every gene is a feature
- We dropped the AID column, which is just an identifier and not a relevant feature
- Anomaly: we can't find the "class" column that is used on OpenML as a target (https://www.openml.org/search?type=data&sort=runs&id=45095&status=active) in the original data mentioned in the cited paper (https://llmpp.ccr.cancer.gov/lymphoma/data/figure1/figure1.cdt). There is no valid target.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="",
    problem_type="multiclass_classification",
    objective_metric_name="log_loss",
    stratify_on="",
)

## Preprocessing

In [83]:
import pandas as pd

df = pd.read_csv(f"{dataset_mold.path}/figure1.cdt", sep="\t", encoding="latin-1", header=0)

df = df.set_index('GID')
df = df.T

df.drop(columns="AID", inplace=True)
feature_names = df.columns
cat_features = ["GENE1835X"]
num_features = [col for col in df.columns if col not in cat_features]

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

df[cat_features] = df[cat_features].astype("category")
df[num_features] = df[num_features].apply(pd.to_numeric, errors='coerce').astype('float64')

In [84]:
# Use if needed to get see all cols of pandas dataframes
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
df.head()

GID GENE1835X  GENE1836X  GENE1865X  GENE1380X  GENE1933X  GENE1932X  \
0       -0.01       0.01       0.27       0.10       0.42       0.99
1        0.42       0.03      -0.76       0.31       0.14      -0.10
2       -0.03      -0.38       0.01       0.29      -0.11      -0.13
3        0.38       0.21       0.33      -0.02      -0.11      -0.05
4        0.34        NaN       0.36       0.11       0.15       0.19

GID  GENE1931X  GENE1930X  GENE3129X  GENE3126X  GENE0X  GENE3115X  GENE3116X  \
0         0.62       0.19       0.39       0.42    0.00       0.11      -0.20
1        -0.35      -0.36       0.10       0.60    0.28       0.03      -0.07
2        -0.36       0.46       0.19      -0.05   -0.18       0.14      -0.56
3        -0.37      -0.54      -0.18      -0.72   -0.13       0.25       0.00
4        -0.11       0.27       0.59       0.55   -0.11       0.31      -0.25

GID  GENE3117X  GENE3118X  GENE3073X  GENE3072X  GENE3067X  GENE3068X  \
0        -0.31      -0.29       0.17      -0.16       1.73       0.05
1        -0.08      -0.42       0.80      -0.04      -1.16      -1.70
2          NaN        NaN       0.00      -0.22      -0.89        NaN
3        -0.34       0.35      -0.60       0.60      -0.08      -0.82
4         1.04       0.90       0.15       0.68       0.13       0.90

GID  GENE3069X  GENE2584X  GENE3070X  GENE1843X  GENE3166X  GENE3165X  \
0        -0.04      -0.32      -0.15      -0.56      -0.22      -0.66
1        -0.97       0.16      -0.49      -0.66       0.21      -0.23
2        -2.08       0.71       0.18       0.75       0.00        NaN
3        -1.93      -0.35      -0.36      -0.49      -0.39      -0.49
4         0.86        NaN       0.20       0.04       0.58        NaN

GID  GENE1885X  GENE3385X  GENE3384X  GENE1110X  GENE1109X  GENE1108X  \
0         0.16      -0.51      -0.83       0.06       0.69       0.35
1        -0.46      -0.41      -0.28      -0.53      -0.28       0.12
2        -0.97      -1.25      -1.13      -1.53       1.15       0.45
3         0.44       0.27       0.23       0.40       0.76       0.15
4          NaN      -0.78      -0.48       0.61       0.19       0.60

GID  GENE1107X  GENE4005X  GENE4006X  GENE4007X  GENE4008X  GENE4009X  \
0         0.80       1.66       2.08       2.13       1.38      -0.49
1         0.14      -1.19      -0.34      -0.49      -0.28      -0.55
2        -0.72      -0.42      -1.01      -0.74      -0.96       0.12
3         0.33       0.29      -1.83      -2.18      -2.12      -1.85
4          NaN       0.11      -0.08      -0.06       0.00       0.67

GID  GENE4010X  GENE4011X  GENE4012X  GENE4013X  GENE4014X  GENE4015X  \
0        -0.01       0.47      -1.12        NaN      -0.05      -0.01
1        -0.44      -0.62      -0.94      -1.21      -0.72      -0.14
2          NaN        NaN      -1.24      -0.49      -0.98      -0.73
3         0.20       0.45       1.01       1.16       1.51       1.25
4          NaN        NaN        NaN        NaN        NaN        NaN

GID  GENE4016X  GENE3884X  GENE3885X  GENE3886X  GENE3887X  GENE3888X  \
0        -1.33      -1.09      -0.16      -0.57      -0.28      -0.67
1         0.14      -0.52      -1.31      -1.46      -0.97      -0.76
2        -0.83      -0.35       0.58       0.50       0.38       0.50
3        -0.22      -0.85      -1.37      -1.01      -1.26      -1.92
4        -1.35       0.14       0.04       0.06        NaN        NaN

GID  GENE3889X  GENE3890X  GENE1114X  GENE1115X  GENE3936X  GENE3937X  \
0        -0.36      -0.56      -0.28      -0.44       0.14       0.03
1        -1.31      -0.40       0.15       0.34      -0.39      -1.07
2        -0.22      -0.91       0.39       0.93      -0.01       0.27
3        -0.44       0.55      -0.12       0.24      -0.57      -0.38
4          NaN       0.85       0.10       0.16        NaN        NaN

GID  GENE3992X  GENE3991X  GENE3963X  GENE3994X  GENE1140X  GENE1141X  \
0        -1.65      -0.76      -1.36      -0.59      -1.43      -0.07
1        -0.11      -0.14       0.05      -0.75       0.15       0.28
2         0.23      -0.41       0.13       1.29       1.98       1.59
3        -1.54      -1.22      -0.15      -0.25       0.30       0.31
4         0.70       0.17       0.73       0.63       1.27       0.85

GID  GENE3952X  GENE3981X  GENE3940X  GENE3951X  GENE3950X  GENE3949X  \
0         0.02      -0.10      -0.28      -0.18      -0.87      -0.41
1        -0.28       0.72      -0.47      -0.16      -0.12       0.00
2         0.59       1.11       0.94       0.67       1.20       1.93
3        -0.12      -0.26       2.45       0.73       1.00      -0.08
4          NaN       0.09       0.68      -0.24       0.77       0.74

GID  GENE3948X  GENE3806X  GENE3807X  GENE3944X  GENE3943X  GENE3942X  \
0        -0.37      -0.60      -1.21      -0.92      -0.49      -0.57
1         0.11      -0.65       0.50      -0.63       0.38       0.47
2         1.78       0.28       0.09       1.27       1.13       0.85
3         0.00       0.50       0.31       1.29       0.36       0.05
4         0.64       0.50       0.92      -0.55      -0.07       0.38

GID  GENE3941X  GENE3939X  GENE3946X  GENE3945X  GENE3947X  GENE3954X  \
0        -0.07      -0.16      -0.40      -0.64      -0.63      -1.26
1         0.38       0.00       0.59       0.69       0.95      -0.77
2        -0.33       0.79       0.15       0.26      -0.85       0.70
3        -0.93      -1.54      -1.44      -1.39      -1.74       0.00
4         0.52       0.38      -0.34      -0.48       1.54       0.52

GID  GENE3953X  GENE2531X  GENE2532X  GENE2533X  GENE2534X  GENE2535X  \
0        -0.80      -0.58      -0.94      -0.63      -0.08       0.31
1        -1.25      -1.28       0.14      -0.04      -0.17        NaN
2         0.70       1.93       1.16       1.08       1.29       1.55
3        -0.19      -0.05       0.63       0.04      -0.15       0.50
4         0.20       0.78       1.92      -0.11       0.31       1.12

GID  GENE2536X  GENE2537X  GENE2538X  GENE2539X  GENE2540X  GENE2541X  \
0        -0.87      -1.53      -1.04      -0.20      -1.45      -1.29
1        -1.62      -1.88      -1.70      -1.32      -0.78      -0.48
2         1.86       1.95       1.72       0.70       1.86       1.92
3        -0.98      -0.71      -0.98      -0.19       0.01      -0.15
4         1.20       2.14       1.88       0.75       0.71       0.99

GID  GENE2542X  GENE2543X  GENE3959X  GENE3960X  GENE3879X  GENE3880X  \
0        -1.12      -1.55      -1.24      -0.10      -0.75      -0.74
1        -0.77      -0.41      -0.02      -0.04       0.45      -0.18
2         1.61       1.40       0.49       0.61      -0.77      -0.25
3         0.20      -0.41      -0.12      -0.19       0.12       0.25
4         1.02       1.23       0.12      -0.34      -0.73      -0.07

GID  GENE3881X  GENE3882X  GENE3861X  GENE3860X  GENE3863X  GENE3862X  \
0        -0.61      -0.92      -2.56      -2.44       0.00      -0.63
1        -0.24      -0.09      -0.77      -0.87      -0.39      -0.06
2        -0.31      -0.53        NaN        NaN      -0.84      -1.87
3         0.08      -0.01      -0.57      -0.89      -0.50      -0.31
4        -0.36       0.24        NaN        NaN        NaN        NaN

GID  GENE3864X  GENE3865X  GENE3866X  GENE3867X  GENE3868X  GENE3869X  \
0        -0.64      -1.28      -0.78      -0.97      -0.05       0.61
1         0.53       0.80       1.12       0.15      -0.19       0.28
2        -1.35        NaN      -1.47      -0.71       0.26      -2.60
3         1.05      -0.04       0.17       0.51       0.07       0.01
4          NaN      -0.40      -0.36      -0.09      -0.34       0.69

GID  GENE3870X  GENE3871X  GENE3872X  GENE2592X  GENE2591X  GENE166X  \
0        -0.52       0.38      -0.28      -1.17      -0.61     -1.50
1         0.40      -0.33      -0.31      -0.08       0.06      0.10
2        -1.33        NaN      -0.61       0.08       0.16      0.58
3         0.48       0.35       0.30       0.71       0.04      0.90
4        -0.09        NaN       0.44      -1.04      -0.10      0.52

GID  GENE3438X  GENE3439X  GENE3441X  GENE3440X  GENE3444X  GENE3442X  \
0        -0.94      -1.15      -1.73        NaN      -0.83      -1.47
1         0.47      -0.03      -0.12      -0.13      -0.87       0.00
2         0.47        NaN       0.10       0.57      -0.11       0.41
3        -0.52       0.58       0.17       0.46       1.01       0.21
4        -1.32        NaN       0.00       0.46        NaN      -0.41

GID  GENE3443X  GENE3446X  GENE3445X  GENE3447X  GENE3448X  GENE3449X  \
0        -1.63      -1.59      -1.82      -0.78      -0.95      -0.66
1         0.32       0.13       0.21       0.30       0.40      -0.08
2         0.72      -0.02      -0.10      -0.45      -0.23       0.00
3         0.17      -0.26      -0.34      -0.19      -0.14      -0.02
4        -0.72      -0.82      -1.34      -0.29      -0.23       0.27

GID  GENE1501X  GENE3404X  GENE3403X  GENE3401X  GENE3402X  GENE3399X  \
0        -0.88      -0.26      -0.94      -0.80      -0.62       0.08
1         0.28       0.01      -0.26       0.42       0.49       0.29
2        -1.01      -0.13      -0.83      -0.30       0.09      -0.63
3         0.67       0.02       0.85       0.24      -0.06       0.41
4         0.14       0.35       0.34       0.51       0.53      -0.07

GID  GENE3400X  GENE816X  GENE3406X  GENE3405X  GENE213X  GENE3892X  \
0        -0.38     -0.08      -0.51      -0.75     -1.18      -1.20
1         0.19      0.10       0.10      -0.02     -0.11       0.11
2        -0.21     -0.23      -0.33      -0.49       NaN      -0.06
3         0.51      1.12       0.26       0.44     -0.12      -0.43
4        -0.34     -0.55      -0.38      -0.11      0.21      -0.31

GID  GENE3876X  GENE3875X  GENE3874X  GENE167X  GENE3450X  GENE3451X  \
0          NaN      -1.96      -1.34     -0.68      -0.67      -0.83
1         0.01       0.55       0.74      0.29       0.32       0.08
2        -0.26      -0.50      -0.06       NaN       0.39      -0.03
3         0.96       1.28       1.49      0.07       0.11       0.07
4        -0.91        NaN       0.29       NaN       0.23      -0.03

GID  GENE3452X  GENE3453X  GENE3454X  GENE3878X  GENE3437X  GENE3436X  \
0        -0.85      -0.67      -0.96      -0.42      -0.36      -0.54
1        -0.15       0.03       0.23       0.40       0.30       0.07
2         0.39       0.42      -0.03       0.00      -0.29      -0.54
3         0.28       0.14      -0.22       0.08      -0.09      -0.12
4         0.04       0.50       0.42      -0.11      -1.07      -0.72

GID  GENE3435X  GENE3470X  GENE3832X  GENE3831X  GENE3830X  GENE394X  \
0        -0.92      -1.40      -1.81      -0.78      -0.68     -0.67
1        -0.18       0.35       1.64       1.77       1.06      0.25
2         0.16       0.42        NaN      -0.31      -0.14     -0.47
3         0.14      -0.35        NaN       0.28       1.42      0.54
4         0.08      -0.09      -0.22       0.62       0.01     -0.52

GID  GENE3531X  GENE3530X  GENE918X  GENE3483X  GENE3520X  GENE3519X  \
0        -1.32      -0.67     -1.08      -0.15      -1.00      -1.93
1         0.37       0.59      0.20       0.31      -0.22      -0.17
2         0.09       0.09      0.26       0.42       1.59       1.35
3         0.42       0.19     -0.62      -0.10      -0.18      -0.03
4        -0.18       0.08     -0.22        NaN       1.51       1.23

GID  GENE3518X  GENE3517X  GENE3516X  GENE3515X  GENE3514X  GENE3503X  \
0        -1.11      -1.10      -1.33      -1.75      -0.99      -1.11
1         0.65       0.17       0.44       0.66       0.44       0.21
2         0.25       0.53       0.62       0.19       0.19      -0.03
3        -0.35      -0.85       0.09      -0.13      -0.10       0.17
4        -0.53      -0.58       0.04      -0.16      -0.10       0.83

GID  GENE3502X  GENE3504X  GENE3511X  GENE3505X  GENE3506X  GENE3507X  \
0        -0.79      -0.51      -0.63      -0.75      -0.98      -0.39
1         0.32       0.39       0.00       0.34       0.32       0.36
2         0.56      -0.09       0.32       0.11       0.13       0.02
3         0.26      -0.33      -0.26      -0.66      -0.36       0.00
4         0.47      -0.71       0.56       0.00       0.47       0.39

GID  GENE3508X  GENE3509X  GENE3510X  GENE3501X  GENE3500X  GENE3499X  \
0        -0.90      -0.86      -0.10      -0.87      -0.80      -0.89
1         0.65       0.50       0.64      -0.14      -0.15      -0.08
2         0.47       0.05      -0.10       1.35       1.35       0.85
3         0.42       0.95       0.97      -0.72      -0.53      -0.51
4         0.88       0.57       0.78       1.40       1.64       0.07

GID  GENE3498X  GENE3497X  GENE3496X  GENE3495X  GENE3490X  GENE3489X  \
0        -1.04      -1.04      -1.38      -1.19      -0.61      -0.94
1         0.05       0.29      -0.14      -0.14      -0.04       0.30
2         0.72       1.25       0.64       0.52       0.72       0.29
3         0.18       0.05      -0.03       0.07       1.50       0.66
4         0.52       0.94       0.08       0.34       0.68       0.86

GID  GENE3492X  GENE3491X  GENE3493X  GENE3494X  GENE3521X  GENE3522X  \
0        -1.33      -0.98      -0.18      -0.48      -0.97      -1.15
1         0.00       0.70      -0.29      -0.95       0.27       0.25
2         0.44      -0.46       0.28       0.61       0.43      -0.07
3        -0.48       0.29      -0.04      -0.66      -0.28      -0.23
4         0.78       0.68       0.88       1.27       0.36       0.41

GID  GENE3488X  GENE3604X  GENE3603X  GENE3602X  GENE3812X  GENE3484X  \
0        -1.21      -1.17      -1.76      -1.59      -1.79      -2.11
1        -0.28       0.23       0.29       0.13       0.53       0.49
2        -0.52      -0.31       0.24       0.18       0.76      -1.40
3         0.42       0.19       0.27       0.87       0.19       0.37
4        -0.07       0.38       0.22       0.68       1.07       0.12

GID  GENE3485X  GENE3486X  GENE3487X  GENE3526X  GENE3525X  GENE3524X  \
0        -0.81      -1.48      -1.74      -1.09      -1.79      -1.43
1        -0.18      -0.41      -0.01       0.53       0.54       0.06
2         0.76       0.21      -0.32      -0.02       0.80       0.61
3        -0.04      -0.07       0.10       0.30      -0.03       0.19
4        -0.06       0.17       0.25       0.01       0.44       0.16

GID  GENE3523X  GENE3280X  GENE3281X  GENE3282X  GENE3527X  GENE3529X  \
0        -0.99      -1.41      -1.64      -1.41      -0.86      -0.67
1         0.36       0.40       0.51       0.41       0.11       0.19
2         0.14       0.50       0.13       0.71       0.58       0.54
3        -0.19      -0.25      -1.13      -0.75      -0.57       0.53
4         0.16       0.16      -0.46       0.18       0.48       0.79

GID  GENE3528X  GENE3512X  GENE2544X  GENE3843X  GENE3842X  GENE3480X  \
0        -0.94      -0.83      -0.63       0.67       0.80      -0.94
1         0.00      -0.26      -0.50       0.44       0.23       0.61
2        -0.01       0.63       0.52      -0.10       0.16       1.13
3         0.35      -0.83      -1.39      -0.30      -0.18       0.75
4         0.51       0.40       1.13       0.28       0.27      -0.45

GID  GENE3802X  GENE3801X  GENE3533X  GENE3534X  GENE3540X  GENE3558X  \
0        -1.42      -1.70      -0.82      -0.81      -1.51      -1.06
1        -0.55      -0.55       0.07       0.09       0.11       0.31
2         0.70       0.67       0.19       0.48      -0.10       0.19
3         0.00       0.15      -0.59      -0.38      -0.23       0.57
4         1.05       1.10       1.57       1.03       0.33      -0.16

GID  GENE3811X  GENE3291X  GENE2447X  GENE3810X  GENE3809X  GENE3808X  \
0        -0.62      -0.16      -0.88      -0.46      -0.82      -1.00
1        -0.28      -0.14       0.45      -0.28      -0.32       0.49
2         0.15      -0.24       1.00       0.32       1.45      -0.05
3         0.48      -0.09      -0.46      -0.26       0.43      -0.23
4         0.27       0.96       1.70       0.46       1.05        NaN

GID  GENE3826X  GENE3825X  GENE3799X  GENE3798X  GENE3797X  GENE3796X  \
0        -1.08      -0.86      -1.49      -0.56      -1.75        NaN
1         0.64       0.04       0.26       0.52      -0.69       0.06
2        -0.48       0.05       1.11       1.81       0.84       1.55
3         0.27       0.00       0.29       0.28       0.95       0.98
4         1.42       1.57        NaN       1.87       1.57       1.25

GID  GENE3795X  GENE3794X  GENE3687X  GENE3790X  GENE3789X  GENE3788X  \
0        -1.65      -1.91      -0.32      -0.50      -1.71      -2.08
1        -0.07       0.61      -0.04       0.05      -0.05      -0.28
2         1.14       1.09      -0.61       0.11       0.75       0.74
3         0.97       0.79       0.15       1.07       1.83       1.77
4         1.18       0.86      -0.68       0.73       0.90       0.35

GID  GENE3787X  GENE3786X  GENE3785X  GENE3784X  GENE3693X  GENE3692X  \
0        -1.62      -1.02      -0.85      -1.25      -2.54      -2.54
1        -0.28      -0.10       0.16       0.08      -0.23      -0.40
2         0.45       0.18       0.61       1.03       1.30       1.24
3         1.91       1.92       0.28       0.22       1.57       1.46
4         0.57       1.01       1.22       1.08       0.49       0.35

GID  GENE3698X  GENE3699X  GENE3700X  GENE3729X  GENE3728X  GENE3783X  \
0        -1.85      -2.42      -0.79      -2.93      -1.62        NaN
1        -0.09       0.26      -0.12       0.74       0.22      -0.01
2        -0.06      -0.31      -0.09      -0.05       0.40       0.45
3         0.06      -0.04       0.12      -0.43      -0.20      -0.50
4        -0.13      -0.45       0.45       0.16      -0.34       0.05

GID  GENE3782X  GENE3781X  GENE3780X  GENE3779X  GENE3778X  GENE3777X  \
0        -1.59      -1.71        NaN        NaN      -2.72      -3.03
1         0.47       0.57       0.31      -0.13       0.16       0.51
2         0.63       0.72       0.87       0.44       1.01       1.26
3        -0.82      -0.62      -0.45       0.30       0.36       0.07
4         0.33       0.62       0.56       0.71       0.28       0.99

GID  GENE3776X  GENE3775X  GENE3774X  GENE3773X  GENE3772X  GENE3771X  \
0        -2.91      -2.46      -1.97      -2.27      -2.44      -3.71
1         0.35      -0.09       0.07       0.28       0.21       0.64
2         0.58       0.29       0.54       0.19      -0.08      -0.05
3        -0.10      -0.13       0.13       0.33       0.18       0.16
4         1.21       1.15       0.87       1.03       1.12      -0.61

GID  GENE3770X  GENE3769X  GENE3768X  GENE3767X  GENE3766X  GENE3765X  \
0        -4.65      -2.82      -2.71      -2.34      -2.53      -2.72
1         0.73       0.09       0.64       0.18       0.09       0.05
2         0.12      -0.23      -0.22       0.08      -0.05      -0.30
3         0.05       0.39       0.46       0.79       0.83       0.35
4        -0.41      -0.35      -0.64        NaN      -0.70      -1.13

GID  GENE3764X  GENE3763X  GENE3762X  GENE3761X  GENE3760X  GENE3759X  \
0        -3.05      -3.53      -4.02      -3.03      -1.48      -2.02
1         0.05       0.14       0.29       0.37       0.49      -0.11
2        -0.45      -0.80      -0.98      -1.11      -0.44       0.23
3         0.57       0.17      -0.13       0.05       0.13       0.03
4        -1.31      -1.07      -1.06      -0.25      -0.90      -0.16

GID  GENE3758X  GENE3757X  GENE3756X  GENE3755X  GENE3754X  GENE3753X  \
0        -2.48      -2.80      -1.99      -2.46      -3.14      -2.93
1         0.81       0.68       0.85       0.59       0.76       0.42
2        -0.90      -1.20      -1.10       1.09       0.94       0.59
3        -0.10      -0.01       0.14       0.90       0.72       0.63
4        -0.83      -0.76      -0.22       0.73       0.37       0.50


## Data Checks

In [85]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

ValueError: target_feature '' is not in the DataFrame.

In [73]:
# Sample Rows
df_head

GID GENE1835X  GENE1836X  GENE1865X  GENE1380X  GENE1933X  GENE1932X  \
0       -0.01       0.01       0.27       0.10       0.42       0.99
1        0.42       0.03      -0.76       0.31       0.14      -0.10
2       -0.03      -0.38       0.01       0.29      -0.11      -0.13
3        0.38       0.21       0.33      -0.02      -0.11      -0.05
4        0.34        NaN       0.36       0.11       0.15       0.19

GID  GENE1931X  GENE1930X  GENE3129X  GENE3126X  GENE0X  GENE3115X  GENE3116X  \
0         0.62       0.19       0.39       0.42    0.00       0.11      -0.20
1        -0.35      -0.36       0.10       0.60    0.28       0.03      -0.07
2        -0.36       0.46       0.19      -0.05   -0.18       0.14      -0.56
3        -0.37      -0.54      -0.18      -0.72   -0.13       0.25       0.00
4        -0.11       0.27       0.59       0.55   -0.11       0.31      -0.25

GID  GENE3117X  GENE3118X  GENE3073X  GENE3072X  GENE3067X  GENE3068X  \
0        -0.31      -0.29       0.17      -0.16       1.73       0.05
1        -0.08      -0.42       0.80      -0.04      -1.16      -1.70
2          NaN        NaN       0.00      -0.22      -0.89        NaN
3        -0.34       0.35      -0.60       0.60      -0.08      -0.82
4         1.04       0.90       0.15       0.68       0.13       0.90

GID  GENE3069X  GENE2584X  GENE3070X  GENE1843X  GENE3166X  GENE3165X  \
0        -0.04      -0.32      -0.15      -0.56      -0.22      -0.66
1        -0.97       0.16      -0.49      -0.66       0.21      -0.23
2        -2.08       0.71       0.18       0.75       0.00        NaN
3        -1.93      -0.35      -0.36      -0.49      -0.39      -0.49
4         0.86        NaN       0.20       0.04       0.58        NaN

GID  GENE1885X  GENE3385X  GENE3384X  GENE1110X  GENE1109X  GENE1108X  \
0         0.16      -0.51      -0.83       0.06       0.69       0.35
1        -0.46      -0.41      -0.28      -0.53      -0.28       0.12
2        -0.97      -1.25      -1.13      -1.53       1.15       0.45
3         0.44       0.27       0.23       0.40       0.76       0.15
4          NaN      -0.78      -0.48       0.61       0.19       0.60

GID  GENE1107X  GENE4005X  GENE4006X  GENE4007X  GENE4008X  GENE4009X  \
0         0.80       1.66       2.08       2.13       1.38      -0.49
1         0.14      -1.19      -0.34      -0.49      -0.28      -0.55
2        -0.72      -0.42      -1.01      -0.74      -0.96       0.12
3         0.33       0.29      -1.83      -2.18      -2.12      -1.85
4          NaN       0.11      -0.08      -0.06       0.00       0.67

GID  GENE4010X  GENE4011X  GENE4012X  GENE4013X  GENE4014X  GENE4015X  \
0        -0.01       0.47      -1.12        NaN      -0.05      -0.01
1        -0.44      -0.62      -0.94      -1.21      -0.72      -0.14
2          NaN        NaN      -1.24      -0.49      -0.98      -0.73
3         0.20       0.45       1.01       1.16       1.51       1.25
4          NaN        NaN        NaN        NaN        NaN        NaN

GID  GENE4016X  GENE3884X  GENE3885X  GENE3886X  GENE3887X  GENE3888X  \
0        -1.33      -1.09      -0.16      -0.57      -0.28      -0.67
1         0.14      -0.52      -1.31      -1.46      -0.97      -0.76
2        -0.83      -0.35       0.58       0.50       0.38       0.50
3        -0.22      -0.85      -1.37      -1.01      -1.26      -1.92
4        -1.35       0.14       0.04       0.06        NaN        NaN

GID  GENE3889X  GENE3890X  GENE1114X  GENE1115X  GENE3936X  GENE3937X  \
0        -0.36      -0.56      -0.28      -0.44       0.14       0.03
1        -1.31      -0.40       0.15       0.34      -0.39      -1.07
2        -0.22      -0.91       0.39       0.93      -0.01       0.27
3        -0.44       0.55      -0.12       0.24      -0.57      -0.38
4          NaN       0.85       0.10       0.16        NaN        NaN

GID  GENE3992X  GENE3991X  GENE3963X  GENE3994X  GENE1140X  GENE1141X  \
0        -1.65      -0.76      -1.36      -0.59      -1.43      -0.07
1        -0.11      -0.14       0.05      -0.75       0.15       0.28
2         0.23      -0.41       0.13       1.29       1.98       1.59
3        -1.54      -1.22      -0.15      -0.25       0.30       0.31
4         0.70       0.17       0.73       0.63       1.27       0.85

GID  GENE3952X  GENE3981X  GENE3940X  GENE3951X  GENE3950X  GENE3949X  \
0         0.02      -0.10      -0.28      -0.18      -0.87      -0.41
1        -0.28       0.72      -0.47      -0.16      -0.12       0.00
2         0.59       1.11       0.94       0.67       1.20       1.93
3        -0.12      -0.26       2.45       0.73       1.00      -0.08
4          NaN       0.09       0.68      -0.24       0.77       0.74

GID  GENE3948X  GENE3806X  GENE3807X  GENE3944X  GENE3943X  GENE3942X  \
0        -0.37      -0.60      -1.21      -0.92      -0.49      -0.57
1         0.11      -0.65       0.50      -0.63       0.38       0.47
2         1.78       0.28       0.09       1.27       1.13       0.85
3         0.00       0.50       0.31       1.29       0.36       0.05
4         0.64       0.50       0.92      -0.55      -0.07       0.38

GID  GENE3941X  GENE3939X  GENE3946X  GENE3945X  GENE3947X  GENE3954X  \
0        -0.07      -0.16      -0.40      -0.64      -0.63      -1.26
1         0.38       0.00       0.59       0.69       0.95      -0.77
2        -0.33       0.79       0.15       0.26      -0.85       0.70
3        -0.93      -1.54      -1.44      -1.39      -1.74       0.00
4         0.52       0.38      -0.34      -0.48       1.54       0.52

GID  GENE3953X  GENE2531X  GENE2532X  GENE2533X  GENE2534X  GENE2535X  \
0        -0.80      -0.58      -0.94      -0.63      -0.08       0.31
1        -1.25      -1.28       0.14      -0.04      -0.17        NaN
2         0.70       1.93       1.16       1.08       1.29       1.55
3        -0.19      -0.05       0.63       0.04      -0.15       0.50
4         0.20       0.78       1.92      -0.11       0.31       1.12

GID  GENE2536X  GENE2537X  GENE2538X  GENE2539X  GENE2540X  GENE2541X  \
0        -0.87      -1.53      -1.04      -0.20      -1.45      -1.29
1        -1.62      -1.88      -1.70      -1.32      -0.78      -0.48
2         1.86       1.95       1.72       0.70       1.86       1.92
3        -0.98      -0.71      -0.98      -0.19       0.01      -0.15
4         1.20       2.14       1.88       0.75       0.71       0.99

GID  GENE2542X  GENE2543X  GENE3959X  GENE3960X  GENE3879X  GENE3880X  \
0        -1.12      -1.55      -1.24      -0.10      -0.75      -0.74
1        -0.77      -0.41      -0.02      -0.04       0.45      -0.18
2         1.61       1.40       0.49       0.61      -0.77      -0.25
3         0.20      -0.41      -0.12      -0.19       0.12       0.25
4         1.02       1.23       0.12      -0.34      -0.73      -0.07

GID  GENE3881X  GENE3882X  GENE3861X  GENE3860X  GENE3863X  GENE3862X  \
0        -0.61      -0.92      -2.56      -2.44       0.00      -0.63
1        -0.24      -0.09      -0.77      -0.87      -0.39      -0.06
2        -0.31      -0.53        NaN        NaN      -0.84      -1.87
3         0.08      -0.01      -0.57      -0.89      -0.50      -0.31
4        -0.36       0.24        NaN        NaN        NaN        NaN

GID  GENE3864X  GENE3865X  GENE3866X  GENE3867X  GENE3868X  GENE3869X  \
0        -0.64      -1.28      -0.78      -0.97      -0.05       0.61
1         0.53       0.80       1.12       0.15      -0.19       0.28
2        -1.35        NaN      -1.47      -0.71       0.26      -2.60
3         1.05      -0.04       0.17       0.51       0.07       0.01
4          NaN      -0.40      -0.36      -0.09      -0.34       0.69

GID  GENE3870X  GENE3871X  GENE3872X  GENE2592X  GENE2591X  GENE166X  \
0        -0.52       0.38      -0.28      -1.17      -0.61     -1.50
1         0.40      -0.33      -0.31      -0.08       0.06      0.10
2        -1.33        NaN      -0.61       0.08       0.16      0.58
3         0.48       0.35       0.30       0.71       0.04      0.90
4        -0.09        NaN       0.44      -1.04      -0.10      0.52

GID  GENE3438X  GENE3439X  GENE3441X  GENE3440X  GENE3444X  GENE3442X  \
0        -0.94      -1.15      -1.73        NaN      -0.83      -1.47
1         0.47      -0.03      -0.12      -0.13      -0.87       0.00
2         0.47        NaN       0.10       0.57      -0.11       0.41
3        -0.52       0.58       0.17       0.46       1.01       0.21
4        -1.32        NaN       0.00       0.46        NaN      -0.41

GID  GENE3443X  GENE3446X  GENE3445X  GENE3447X  GENE3448X  GENE3449X  \
0        -1.63      -1.59      -1.82      -0.78      -0.95      -0.66
1         0.32       0.13       0.21       0.30       0.40      -0.08
2         0.72      -0.02      -0.10      -0.45      -0.23       0.00
3         0.17      -0.26      -0.34      -0.19      -0.14      -0.02
4        -0.72      -0.82      -1.34      -0.29      -0.23       0.27

GID  GENE1501X  GENE3404X  GENE3403X  GENE3401X  GENE3402X  GENE3399X  \
0        -0.88      -0.26      -0.94      -0.80      -0.62       0.08
1         0.28       0.01      -0.26       0.42       0.49       0.29
2        -1.01      -0.13      -0.83      -0.30       0.09      -0.63
3         0.67       0.02       0.85       0.24      -0.06       0.41
4         0.14       0.35       0.34       0.51       0.53      -0.07

GID  GENE3400X  GENE816X  GENE3406X  GENE3405X  GENE213X  GENE3892X  \
0        -0.38     -0.08      -0.51      -0.75     -1.18      -1.20
1         0.19      0.10       0.10      -0.02     -0.11       0.11
2        -0.21     -0.23      -0.33      -0.49       NaN      -0.06
3         0.51      1.12       0.26       0.44     -0.12      -0.43
4        -0.34     -0.55      -0.38      -0.11      0.21      -0.31

GID  GENE3876X  GENE3875X  GENE3874X  GENE167X  GENE3450X  GENE3451X  \
0          NaN      -1.96      -1.34     -0.68      -0.67      -0.83
1         0.01       0.55       0.74      0.29       0.32       0.08
2        -0.26      -0.50      -0.06       NaN       0.39      -0.03
3         0.96       1.28       1.49      0.07       0.11       0.07
4        -0.91        NaN       0.29       NaN       0.23      -0.03

GID  GENE3452X  GENE3453X  GENE3454X  GENE3878X  GENE3437X  GENE3436X  \
0        -0.85      -0.67      -0.96      -0.42      -0.36      -0.54
1        -0.15       0.03       0.23       0.40       0.30       0.07
2         0.39       0.42      -0.03       0.00      -0.29      -0.54
3         0.28       0.14      -0.22       0.08      -0.09      -0.12
4         0.04       0.50       0.42      -0.11      -1.07      -0.72

GID  GENE3435X  GENE3470X  GENE3832X  GENE3831X  GENE3830X  GENE394X  \
0        -0.92      -1.40      -1.81      -0.78      -0.68     -0.67
1        -0.18       0.35       1.64       1.77       1.06      0.25
2         0.16       0.42        NaN      -0.31      -0.14     -0.47
3         0.14      -0.35        NaN       0.28       1.42      0.54
4         0.08      -0.09      -0.22       0.62       0.01     -0.52

GID  GENE3531X  GENE3530X  GENE918X  GENE3483X  GENE3520X  GENE3519X  \
0        -1.32      -0.67     -1.08      -0.15      -1.00      -1.93
1         0.37       0.59      0.20       0.31      -0.22      -0.17
2         0.09       0.09      0.26       0.42       1.59       1.35
3         0.42       0.19     -0.62      -0.10      -0.18      -0.03
4        -0.18       0.08     -0.22        NaN       1.51       1.23

GID  GENE3518X  GENE3517X  GENE3516X  GENE3515X  GENE3514X  GENE3503X  \
0        -1.11      -1.10      -1.33      -1.75      -0.99      -1.11
1         0.65       0.17       0.44       0.66       0.44       0.21
2         0.25       0.53       0.62       0.19       0.19      -0.03
3        -0.35      -0.85       0.09      -0.13      -0.10       0.17
4        -0.53      -0.58       0.04      -0.16      -0.10       0.83

GID  GENE3502X  GENE3504X  GENE3511X  GENE3505X  GENE3506X  GENE3507X  \
0        -0.79      -0.51      -0.63      -0.75      -0.98      -0.39
1         0.32       0.39       0.00       0.34       0.32       0.36
2         0.56      -0.09       0.32       0.11       0.13       0.02
3         0.26      -0.33      -0.26      -0.66      -0.36       0.00
4         0.47      -0.71       0.56       0.00       0.47       0.39

GID  GENE3508X  GENE3509X  GENE3510X  GENE3501X  GENE3500X  GENE3499X  \
0        -0.90      -0.86      -0.10      -0.87      -0.80      -0.89
1         0.65       0.50       0.64      -0.14      -0.15      -0.08
2         0.47       0.05      -0.10       1.35       1.35       0.85
3         0.42       0.95       0.97      -0.72      -0.53      -0.51
4         0.88       0.57       0.78       1.40       1.64       0.07

GID  GENE3498X  GENE3497X  GENE3496X  GENE3495X  GENE3490X  GENE3489X  \
0        -1.04      -1.04      -1.38      -1.19      -0.61      -0.94
1         0.05       0.29      -0.14      -0.14      -0.04       0.30
2         0.72       1.25       0.64       0.52       0.72       0.29
3         0.18       0.05      -0.03       0.07       1.50       0.66
4         0.52       0.94       0.08       0.34       0.68       0.86

GID  GENE3492X  GENE3491X  GENE3493X  GENE3494X  GENE3521X  GENE3522X  \
0        -1.33      -0.98      -0.18      -0.48      -0.97      -1.15
1         0.00       0.70      -0.29      -0.95       0.27       0.25
2         0.44      -0.46       0.28       0.61       0.43      -0.07
3        -0.48       0.29      -0.04      -0.66      -0.28      -0.23
4         0.78       0.68       0.88       1.27       0.36       0.41

GID  GENE3488X  GENE3604X  GENE3603X  GENE3602X  GENE3812X  GENE3484X  \
0        -1.21      -1.17      -1.76      -1.59      -1.79      -2.11
1        -0.28       0.23       0.29       0.13       0.53       0.49
2        -0.52      -0.31       0.24       0.18       0.76      -1.40
3         0.42       0.19       0.27       0.87       0.19       0.37
4        -0.07       0.38       0.22       0.68       1.07       0.12

GID  GENE3485X  GENE3486X  GENE3487X  GENE3526X  GENE3525X  GENE3524X  \
0        -0.81      -1.48      -1.74      -1.09      -1.79      -1.43
1        -0.18      -0.41      -0.01       0.53       0.54       0.06
2         0.76       0.21      -0.32      -0.02       0.80       0.61
3        -0.04      -0.07       0.10       0.30      -0.03       0.19
4        -0.06       0.17       0.25       0.01       0.44       0.16

GID  GENE3523X  GENE3280X  GENE3281X  GENE3282X  GENE3527X  GENE3529X  \
0        -0.99      -1.41      -1.64      -1.41      -0.86      -0.67
1         0.36       0.40       0.51       0.41       0.11       0.19
2         0.14       0.50       0.13       0.71       0.58       0.54
3        -0.19      -0.25      -1.13      -0.75      -0.57       0.53
4         0.16       0.16      -0.46       0.18       0.48       0.79

GID  GENE3528X  GENE3512X  GENE2544X  GENE3843X  GENE3842X  GENE3480X  \
0        -0.94      -0.83      -0.63       0.67       0.80      -0.94
1         0.00      -0.26      -0.50       0.44       0.23       0.61
2        -0.01       0.63       0.52      -0.10       0.16       1.13
3         0.35      -0.83      -1.39      -0.30      -0.18       0.75
4         0.51       0.40       1.13       0.28       0.27      -0.45

GID  GENE3802X  GENE3801X  GENE3533X  GENE3534X  GENE3540X  GENE3558X  \
0        -1.42      -1.70      -0.82      -0.81      -1.51      -1.06
1        -0.55      -0.55       0.07       0.09       0.11       0.31
2         0.70       0.67       0.19       0.48      -0.10       0.19
3         0.00       0.15      -0.59      -0.38      -0.23       0.57
4         1.05       1.10       1.57       1.03       0.33      -0.16

GID  GENE3811X  GENE3291X  GENE2447X  GENE3810X  GENE3809X  GENE3808X  \
0        -0.62      -0.16      -0.88      -0.46      -0.82      -1.00
1        -0.28      -0.14       0.45      -0.28      -0.32       0.49
2         0.15      -0.24       1.00       0.32       1.45      -0.05
3         0.48      -0.09      -0.46      -0.26       0.43      -0.23
4         0.27       0.96       1.70       0.46       1.05        NaN

GID  GENE3826X  GENE3825X  GENE3799X  GENE3798X  GENE3797X  GENE3796X  \
0        -1.08      -0.86      -1.49      -0.56      -1.75        NaN
1         0.64       0.04       0.26       0.52      -0.69       0.06
2        -0.48       0.05       1.11       1.81       0.84       1.55
3         0.27       0.00       0.29       0.28       0.95       0.98
4         1.42       1.57        NaN       1.87       1.57       1.25

GID  GENE3795X  GENE3794X  GENE3687X  GENE3790X  GENE3789X  GENE3788X  \
0        -1.65      -1.91      -0.32      -0.50      -1.71      -2.08
1        -0.07       0.61      -0.04       0.05      -0.05      -0.28
2         1.14       1.09      -0.61       0.11       0.75       0.74
3         0.97       0.79       0.15       1.07       1.83       1.77
4         1.18       0.86      -0.68       0.73       0.90       0.35

GID  GENE3787X  GENE3786X  GENE3785X  GENE3784X  GENE3693X  GENE3692X  \
0        -1.62      -1.02      -0.85      -1.25      -2.54      -2.54
1        -0.28      -0.10       0.16       0.08      -0.23      -0.40
2         0.45       0.18       0.61       1.03       1.30       1.24
3         1.91       1.92       0.28       0.22       1.57       1.46
4         0.57       1.01       1.22       1.08       0.49       0.35

GID  GENE3698X  GENE3699X  GENE3700X  GENE3729X  GENE3728X  GENE3783X  \
0        -1.85      -2.42      -0.79      -2.93      -1.62        NaN
1        -0.09       0.26      -0.12       0.74       0.22      -0.01
2        -0.06      -0.31      -0.09      -0.05       0.40       0.45
3         0.06      -0.04       0.12      -0.43      -0.20      -0.50
4        -0.13      -0.45       0.45       0.16      -0.34       0.05

GID  GENE3782X  GENE3781X  GENE3780X  GENE3779X  GENE3778X  GENE3777X  \
0        -1.59      -1.71        NaN        NaN      -2.72      -3.03
1         0.47       0.57       0.31      -0.13       0.16       0.51
2         0.63       0.72       0.87       0.44       1.01       1.26
3        -0.82      -0.62      -0.45       0.30       0.36       0.07
4         0.33       0.62       0.56       0.71       0.28       0.99

GID  GENE3776X  GENE3775X  GENE3774X  GENE3773X  GENE3772X  GENE3771X  \
0        -2.91      -2.46      -1.97      -2.27      -2.44      -3.71
1         0.35      -0.09       0.07       0.28       0.21       0.64
2         0.58       0.29       0.54       0.19      -0.08      -0.05
3        -0.10      -0.13       0.13       0.33       0.18       0.16
4         1.21       1.15       0.87       1.03       1.12      -0.61

GID  GENE3770X  GENE3769X  GENE3768X  GENE3767X  GENE3766X  GENE3765X  \
0        -4.65      -2.82      -2.71      -2.34      -2.53      -2.72
1         0.73       0.09       0.64       0.18       0.09       0.05
2         0.12      -0.23      -0.22       0.08      -0.05      -0.30
3         0.05       0.39       0.46       0.79       0.83       0.35
4        -0.41      -0.35      -0.64        NaN      -0.70      -1.13

GID  GENE3764X  GENE3763X  GENE3762X  GENE3761X  GENE3760X  GENE3759X  \
0        -3.05      -3.53      -4.02      -3.03      -1.48      -2.02
1         0.05       0.14       0.29       0.37       0.49      -0.11
2        -0.45      -0.80      -0.98      -1.11      -0.44       0.23
3         0.57       0.17      -0.13       0.05       0.13       0.03
4        -1.31      -1.07      -1.06      -0.25      -0.90      -0.16

GID  GENE3758X  GENE3757X  GENE3756X  GENE3755X  GENE3754X  GENE3753X  \
0        -2.48      -2.80      -1.99      -2.46      -3.14      -2.93
1         0.81       0.68       0.85       0.59       0.76       0.42
2        -0.90      -1.20      -1.10       1.09       0.94       0.59
3        -0.10      -0.01       0.14       0.90       0.72       0.63
4        -0.83      -0.76      -0.22       0.73       0.37       0.50


In [74]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,GENE1835X,category,3.0,3.03,74.0,"0.02, -0.13, 0.28, -0.01, -0.36, 0.04, 0.05, 0.06, 0.1, -0.78"
1,GENE3661X,float64,20.0,20.20,65.0,"-0.22, -0.54, 0.46, 1.03, -0.08, -0.32, 1.23, -0.25, 0.04, 0.24"
2,GENE3651X,float64,20.0,20.20,74.0,"0.3, -0.96, -1.9, -0.4, -0.34, -0.39, -2.65, -0.48, 1.27, -1.11"
3,GENE1903X,float64,20.0,20.20,64.0,"-0.03, 0.61, -0.16, 1.0, -0.25, -0.41, -0.04, -0.42, 0.98, -0.08"
4,GENE347X,float64,20.0,20.20,65.0,"0.12, 0.05, -0.26, -0.51, -0.09, -0.59, -0.7, -0.44, 1.0, -0.25"
5,GENE1386X,float64,20.0,20.20,70.0,"0.53, 0.0, 0.29, -0.08, -0.23, 0.52, -0.73, 0.25, -0.04, -1.4"
6,GENE1664X,float64,20.0,20.20,69.0,"1.0, -0.38, -0.2, 2.56, -1.2, 0.05, 1.13, 0.0, 2.0, 1.83"
7,GENE1810X,float64,20.0,20.20,75.0,"-0.12, 0.1, 0.27, 0.38, -0.64, -0.35, -0.65, -0.94, 2.07, -0.24"
8,GENE3538X,float64,19.0,19.19,61.0,"-0.25, 0.47, -0.05, 0.4, 0.56, -0.44, -0.46, 0.28, 0.25, 0.01"
9,GENE2562X,float64,19.0,19.19,64.0,"0.36, 0.16, -0.82, -0.78, 0.56, 0.0, 0.34, 0.43, -0.53, -0.19"
10,GENE1920X,float64,19.0,19.19,62.0,"-0.51, 0.47, -0.16, -0.12, 0.1, -0.09, -0.35, 0.78, 0.05, 0.42"
11,GENE2445X,float64,19.0,19.19,68.0,"-0.65, -0.1, 0.57, 0.0, 0.09, -0.45, -0.38, 0.33, 0.62, 0.16"
12,GENE1876X,float64,19.0,19.19,69.0,"-0.13, -0.35, -0.49, 0.76, 0.46, -0.51, -0.06, -0.34, 0.54, 1.97"
13,GENE3267X,float64,19.0,19.19,71.0,"-0.25, -0.71, -0.4, -0.75, -0.68, 0.09, -0.45, 0.08, 4.64, 0.53"
14,GENE3347X,float64,19.0,19.19,73.0,"-1.0, 0.12, -0.1, 0.0, 0.22, -0.51, 0.58, 0.87, 0.8, -0.41"
15,GENE3246X,float64,19.0,19.19,69.0,"-0.15, -0.04, 0.44, 0.51, 0.0, 0.23, -0.71, 0.45, 0.83, -0.12"
16,GENE1092X,float64,19.0,19.19,65.0,"0.15, -0.11, -0.12, 0.56, 0.93, -0.31, 0.06, 0.2, 0.35, -0.07"
17,GENE1921X,float64,19.0,19.19,69.0,"0.22, -0.22, 0.01, -0.63, 0.2, -0.43, -0.41, -0.08, -0.18, 0.55"
18,GENE2910X,float64,19.0,19.19,65.0,"-0.13, 0.5, 0.23, -0.29, 0.13, 0.31, -0.69, 0.4, -0.19, -0.25"
19,GENE2597X,float64,19.0,19.19,61.0,"-0.29, 0.2, 0.08, 0.31, -0.22, -0.12, 1.0, -0.47, -0.09, -0.19"
20,GENE148X,float64,19.0,19.19,66.0,"0.14, -0.19, -0.88, 0.85, 0.38, -0.83, 0.06, -0.46, -0.52, 0.3"
21,GENE1372X,float64,19.0,19.19,71.0,"-0.43, 0.14, -0.01, -0.47, 0.05, -0.35, -0.29, 0.0, 0.83, 0.71"
22,GENE724X,float64,19.0,19.19,68.0,"0.2, 0.91, 0.23, 0.14, -0.05, -0.01, 0.17, -0.59, -1.45, -0.52"
23,GENE672X,float64,19.0,19.19,72.0,"0.36, -0.09, 0.07, -0.26, -0.92, -0.25, 0.4, 0.46, -0.47, 1.74"
24,GENE413X,float64,19.0,19.19,69.0,"-0.22, -0.16, 0.43, 0.0, 0.21, -0.41, 0.61, -0.63, -0.14, -0.64"
25,GENE414X,float64,19.0,19.19,61.0,"-0.32, 0.05, 0.0, -0.14, 0.31, 0.65, 0.79, -0.02, 0.72, -0.2"
26,GENE195X,float64,19.0,19.19,68.0,"-0.16, 0.14, -0.75, 0.74, 0.05, 0.44, 0.58, 0.37, -0.24, -0.22"
27,GENE1471X,float64,19.0,19.19,70.0,"-0.08, -0.09, 0.15, 0.08, -0.06, 0.44, 0.26, 0.41, -0.35, -0.45"
28,GENE1263X,float64,19.0,19.19,69.0,"-0.54, 0.19, -0.4, -0.19, -0.29, 0.75, 0.17, -0.18, -0.02, -0.63"
29,GENE1266X,float64,19.0,19.19,59.0,"0.08, 0.35, 0.13, -0.16, -0.22, -0.32, -0.37, -0.15, -0.01, -0.24"
30,GENE3827X,float64,19.0,19.19,71.0,"-0.16, 0.18, 0.1, 0.69, 0.17, 0.73, 0.07, -1.56, 0.32, 1.17"
31,GENE1397X,float64,19.0,19.19,65.0,"-0.08, -0.09, -0.03, 0.11, -0.2, -0.14, -0.05, 0.31, -0.02, 0.03"
32,GENE1414X,float64,19.0,19.19,67.0,"0.34, -0.47, -0.26, 0.19, -0.14, -0.54, -0.11, 0.86, -0.7, 0.17"
33,GENE1415X,float64,19.0,19.19,65.0,"-0.23, -0.34, -0.12, 0.82, -0.44, 0.85, -0.14, -0.28, -0.39, 0.04"
34,GENE3914X,float64,19.0,19.19,65.0,"0.13, 0.03, -0.2, 1.12, -0.19, -0.3, 0.19, -0.28, 0.0, 0.41"
35,GENE1703X,float64,19.0,19.19,67.0,"-0.6, 0.61, 0.45, 0.85, 0.27, -0.94, 0.51, -0.28, 0.3, 1.6"
36,GENE1790X,float64,19.0,19.19,61.0,"-0.47, -0.57, -0.03, -0.18, 0.08, 0.0, 0.11, 0.23, 0.06, 0.44"
37,GENE1508X,float64,19.0,19.19,66.0,"-0.13, 0.2, -0.18, 0.65, -0.06, -0.37, 0.0, -0.27, 0.35, 0.22"
38,GENE387X,float64,19.0,19.19,67.0,"0.0, 0.69, -0.08, -0.07, 0.3, 0.12, -0.4, 0.35, -0.33, 0.36"
39,GENE1598X,float64,19.0,19.19,73.0,"0.0, -0.2, -0.05, -0.75, -0.39, 0.71, -0.53, 1.11, -0.46, -0.47"
40,GENE1667X,float64,19.0,19.19,76.0,"1.35, -0.51, -0.26, 1.38, -0.31, 1.27, -0.88, 0.18, -1.1, 0.08"
41,GENE1654X,float64,19.0,19.19,70.0,"-0.4, -0.49, 0.21, -0.21, 0.56, -0.52, -0.29, -0.71, -0.62, -0.26"
42,GENE1686X,float64,19.0,19.19,72.0,"-0.54, 0.14, 1.6, 0.15, -0.7, 1.16, 0.95, -0.3, -0.52, -0.23"
43,GENE1702X,float64,19.0,19.19,76.0,"-3.31, 2.77, -0.38, 1.02, -3.24, 0.34, -2.67, -2.9, -3.67, -1.84"
44,GENE237X,float64,19.0,19.19,69.0,"-0.01, -0.2, -0.11, 0.17, 0.37, 0.15, -0.23, -0.59, 0.31, -0.04"
45,GENE1854X,float64,19.0,19.19,70.0,"-0.21, 0.31, -0.04, -0.06, -0.31, -0.57, 0.96, -0.01, 0.78, -0.1"
46,GENE4005X,float64,18.0,18.18,72.0,"-0.28, 1.36, 0.25, 0.29, -0.1, 0.49, 0.31, -0.09, -1.7, -0.07"
47,GENE3936X,float64,18.0,18.18,68.0,"-0.22, 0.14, 0.24, -0.39, -0.45, 0.05, -0.55, -0.34, 0.54, 0.51"
48,GENE3832X,float64,18.0,18.18,70.0,"-0.22, -1.81, -0.87, -0.4, 0.35, -1.15, 0.06, 0.64, 0.18, 0.14"
49,GENE3681X,float64,18.0,18.18,69.0,"0.29, 0.31, -1.19, 0.39, 0.08, 0.73, 0.35, 0.18, 0.15, -0.1"
50,GENE3659X,float64,18.0,18.18,75.0,"1.02, 0.5, -1.02, 1.0, -0.1, 0.49, -0.17, -0.87, 0.34, 0.48"
51,GENE3077X,float64,18.0,18.18,70.0,"0.15, -0.57, 0.08, -0.08, 1.03, -0.4, -0.61, -0.55, -0.77, -0.07"
52,GENE1919X,float64,18.0,18.18,65.0,"-0.15, 0.09, 0.2, -0.34, 0.08, -0.14, 0.43, -0.18, 0.0, -0.65"
53,GENE2444X,float64,18.0,18.18,72.0,"-0.86, -1.53, -0.34, 0.65, 0.52, 0.28, 0.38, 0.06, -0.41, -0.14"
54,GENE2137X,float64,18.0,18.18,68.0,"-0.42, -0.29, 0.19, 0.41, 0.48, -0.07, 0.12, -0.1, -0.37, -0.46"
55,GENE2222X,float64,18.0,18.18,65.0,"-0.34, 0.0, 0.12, -0.13, 0.68, 0.1, 0.01, -0.81, 0.37, -0.11"
56,GENE2731X,float64,18.0,18.18,67.0,"0.0, 1.0, -0.04, -0.24, -0.38, 0.16, 0.09, 0.41, -0.42, 0.43"
57,GENE2042X,float64,18.0,18.18,60.0,"-0.17, -0.09, 0.0, -0.56, 0.34, 0.21, -0.5, 0.01, 0.74, 0.14"
58,GENE2612X,float64,18.0,18.18,65.0,"0.28, -0.13, 0.06, -0.34, 0.21, 1.0, -0.32, 0.11, 0.15, 0.56"
59,GENE1926X,float64,18.0,18.18,66.0,"0.17, -0.16, -0.03, 1.15, -0.06, -0.14, -0.31, 0.51, -0.49, -0.04"
60,GENE1851X,float64,18.0,18.18,68.0,"0.38, -0.17, -0.1, 0.03, 0.21, 0.68, -0.54, -0.53, 0.15, 0.42"
61,GENE1852X,float64,18.0,18.18,67.0,"-0.6, -0.17, -0.21, 0.41, 1.0, -0.39, 0.19, 0.66, 0.1, -0.28"
62,GENE3365X,float64,18.0,18.18,73.0,"-0.57, 0.74, -0.22, 0.16, -0.58, 0.88, 1.31, 0.29, -1.22, -0.32"
63,GENE3927X,float64,18.0,18.18,70.0,"0.54, -0.56, 0.64, -0.38, 0.12, 0.0, -1.0, 0.36, 0.14, -1.31"
64,GENE3999X,float64,18.0,18.18,61.0,"0.0, 0.12, -0.25, 0.07, -0.53, -0.4, 0.06, 0.26, 0.3, 0.64"
65,GENE1031X,float64,18.0,18.18,67.0,"0.35, -0.08, -0.17, -0.46, 0.14, 0.49, 0.09, -0.36, -0.09, 0.17"
66,GENE3055X,float64,18.0,18.18,67.0,"0.46, 0.49, -0.52, -1.22, -0.7, 0.0, -0.59, 0.1, 1.0, -0.3"
67,GENE3061X,float64,18.0,18.18,69.0,"-0.53, -0.17, -0.28, 0.83, 0.07, 0.3, 0.1, 0.0, -0.04, 0.28"
68,GENE299X,float64,18.0,18.18,64.0,"0.12, -0.43, 0.26, -0.14, 0.31, 0.81, 0.17, -0.02, -0.18, -0.16"
69,GENE209X,float64,18.0,18.18,61.0,"-0.05, 0.46, -0.25, 0.21, 0.15, 0.25, -0.44, 0.14, 0.0, 0.26"
70,GENE2001X,float64,18.0,18.18,74.0,"-0.76, -0.18, 0.26, -0.59, -0.58, 0.75, 0.67, -1.1, 0.84, -0.31"
71,GENE1330X,float64,18.0,18.18,71.0,"0.48, -0.7, -0.47, 0.23, -0.77, -0.5, -0.56, -0.42, -0.33, -0.27"
72,GENE2015X,float64,18.0,18.18,72.0,"0.47, 0.04, -0.1, 0.0, 0.37, 0.16, -0.16, -0.09, 0.12, 0.41"
73,GENE1191X,float64,18.0,18.18,67.0,"-0.13, 1.76, -0.52, 0.82, -0.72, -0.65, 1.55, -1.09, -0.23, -0.75"
74,GENE1298X,float64,18.0,18.18,75.0,"-0.51, 0.34, 0.44, -0.09, 0.67, 1.65, -0.55, -0.23, 0.19, -0.63"
75,GENE1855X,float64,18.0,18.18,70.0,"0.21, 0.37, -0.87, 0.13, -0.61, 0.3, -0.11, 0.22, 0.0, -0.1"
76,GENE941X,float64,18.0,18.18,64.0,"-0.22, -0.17, -0.41, 0.0, 0.26, -0.1, 0.27, -0.04, 0.02, -0.12"
77,GENE3622X,float64,18.0,18.18,74.0,"0.41, 0.39, 0.57, 0.08, 0.25, 1.0, 2.05, 0.21, -1.6, -0.58"
78,GENE697X,float64,18.0,18.18,76.0,"0.3, -0.22, 0.49, 0.55, -0.71, 0.48, -1.32, -1.25, -1.03, 1.1"
79,GENE798X,float64,18.0,18.18,66.0,"0.17, -0.53, 0.31, -0.38, 0.29, -0.4, 0.35, -0.02, 0.89, -0.19"
80,GENE424X,float64,18.0,18.18,73.0,"0.5, -0.38, 0.46, 0.01, -0.04, 0.08, 0.0, 0.93, 0.53, 2.52"
81,GENE205X,float64,18.0,18.18,63.0,"0.44, 0.33, 0.22, 1.18, -0.17, 0.48, -0.07, -0.08, -0.24, 0.84"
82,GENE69X,float64,18.0,18.18,67.0,"0.04, -0.19, -0.03, -0.6, -0.12, -0.37, 0.18, 0.33, -0.15, 0.23"
83,GENE1866X,float64,18.0,18.18,71.0,"-0.05, 0.17, 0.54, -0.4, -0.13, -0.47, 0.24, -0.35, -0.27, 0.99"
84,GENE1861X,float64,18.0,18.18,67.0,"-0.28, 0.83, -0.2, -0.15, 0.17, 0.48, 0.8, 0.46, -0.45, 0.01"
85,GENE1462X,float64,18.0,18.18,64.0,"-0.12, -0.16, 0.22, -0.28, 0.43, 0.17, -0.24, 0.26, -0.34, -0.47"
86,GENE3177X,float64,18.0,18.18,63.0,"-0.08, 0.04, 0.05, 0.15, -0.35, -0.26, -0.23, 0.13, -0.21, -0.47"
87,GENE1482X,float64,18.0,18.18,66.0,"0.16, 0.14, -0.44, -0.05, -0.22, 0.05, 0.04, -0.16, -0.5, 0.37"
88,GENE1793X,float64,18.0,18.18,63.0,"-0.28, 0.1, -0.16, 0.0, -0.55, -0.07, 0.23, -0.41, 0.08, 0.01"
89,GENE3464X,float64,18.0,18.18,66.0,"-0.05, 0.22, 0.56, -0.07, -0.45, 0.28, 0.01, -0.41, 0.45, -0.32"
90,GENE1564X,float64,18.0,18.18,68.0,"-0.08, -0.19, 0.0, -0.29, -0.57, 0.62, 0.44, 0.37, 0.9, -0.61"
91,GENE1742X,float64,18.0,18.18,71.0,"1.73, -0.11, -0.5, -0.42, -0.65, -0.03, -0.52, -0.81, 0.37, -1.15"
92,GENE1594X,float64,18.0,18.18,73.0,"-0.39, 0.01, 0.43, -0.01, 0.93, -0.02, 0.57, -0.87, -1.17, -1.37"
93,GENE1626X,float64,18.0,18.18,77.0,"-0.89, -0.62, -0.3, 1.15, 0.55, -0.18, -0.15, 2.88, -0.14, 2.06"
94,GENE1640X,float64,18.0,18.18,75.0,"-1.63, -1.5, -1.68, 1.46, 0.0, 3.11, 3.03, -2.39, -1.88, 1.56"
95,GENE1679X,float64,18.0,18.18,69.0,"1.26, -0.27, 1.45, -0.35, -1.07, 0.06, 2.2, 0.13, 0.0, -0.17"
96,GENE1678X,float64,18.0,18.18,68.0,"1.29, 0.0, -0.28, -0.38, 0.19, 0.32, -0.14, -0.66, -0.43, -0.62"
97,GENE1758X,float64,18.0,18.18,68.0,"-0.12, 0.2, -0.58, -0.39, -0.56, 1.09, -0.19, 0.41, -0.16, -0.71"
98,GENE1770X,float64,18.0,18.18,66.0,"-0.03, -0.57, -0.2, -0.32, 0.34, 0.26, -0.37, 0.21, -0.01, -0.28"
99,GENE1771X,float64,18.0,18.18,67.0,"-0.08, 0.0, -0.23, 0.03, 0.11, 0.8, 0.16, 0.04, -0.59, 0.23"
100,GENE1495X,float64,18.0,18.18,72.0,"-0.41, 0.22, -0.67, -0.64, -0.09, 0.7, -0.4, 0.35, -0.25, -0.61"
101,GENE1374X,float64,18.0,18.18,70.0,"0.56, 0.09, -0.55, 0.33, -0.28, 0.19, -0.69, -0.1, 0.34, -0.08"
102,GENE3119X,float64,18.0,18.18,63.0,"-0.86, -0.02, 1.0, -0.12, 0.19, -0.03, 0.56, -0.31, 0.3, -0.25"
103,GENE1836X,float64,17.0,17.17,66.0,"0.16, 0.04, 0.01, 0.33, 0.19, -0.18, -0.02, -0.63, 0.12, -0.4"
104,GENE3118X,float64,17.0,17.17,66.0,"-0.29, 0.35, 0.29, -0.13, -0.02, 0.1, -0.35, -0.5, -0.08, 0.5"
105,GENE4010X,float64,17.0,17.17,74.0,"0.58, -0.71, -0.14, 0.44, -0.7, -1.1, -0.25, 0.39, -0.01, 2.1"
106,GENE3863X,float64,17.0,17.17,67.0,"0.0, 0.18, 0.1, 0.42, -0.81, 0.26, -0.73, -0.84, 0.49, -0.39"
107,GENE3439X,float64,17.0,17.17,66.0,"0.38, 0.07, 0.54, -0.03, -0.06, 0.58, -0.87, 0.15, 0.34, 0.55"
108,GENE3783X,float64,17.0,17.17,72.0,"-0.5, 0.04, 0.05, -1.13, -0.56, 0.12, 0.26, 0.29, 0.8, -0.01"
109,GENE3671X,float64,17.0,17.17,75.0,"0.7, -0.05, 0.71, 0.42, 0.4, 0.68, -3.15, -6.74, 0.32, -0.67"
110,GENE3548X,float64,17.0,17.17,77.0,"0.71, 0.8, 0.57, 0.24, -0.24, -2.08, 1.09, 0.22, -0.6, -1.45"
111,GENE3537X,float64,17.0,17.17,75.0,"0.63, 0.81, 0.16, -0.18, -0.48, -0.17, -0.11, 0.35, 0.26, 0.17"
112,GENE2561X,float64,17.0,17.17,73.0,"0.13, 0.61, 0.36, -0.41, 1.0, 0.09, -0.31, -0.82, 0.56, -0.83"
113,GENE4X,float64,17.0,17.17,59.0,"-0.03, -0.1, 0.29, -0.2, 0.01, 0.12, -0.52, 0.33, -0.12, 0.46"
114,GENE1929X,float64,17.0,17.17,74.0,"-0.1, -1.25, -0.9, -0.77, -0.33, 0.23, 0.58, -0.13, 1.37, 0.09"
115,GENE2688X,float64,17.0,17.17,64.0,"0.42, -0.13, 0.22, 0.23, -0.37, -0.09, -0.7, -0.96, 1.0, -0.41"
116,GENE1897X,float64,17.0,17.17,60.0,"-0.13, -0.03, -0.07, 0.41, 0.18, 0.24, -0.52, 0.31, 0.54, 0.12"
117,GENE2519X,float64,17.0,17.17,73.0,"0.17, 0.39, -1.37, -0.13, 0.35, 1.06, 0.05, 0.28, -0.76, -0.45"
118,GENE1911X,float64,17.0,17.17,64.0,"-0.64, 0.15, 0.2, 0.43, 0.78, 0.5, -0.31, -0.06, 0.06, 0.31"
119,GENE1916X,float64,17.0,17.17,75.0,"-0.31, -0.02, -0.06, -0.26, 0.35, -1.52, -0.19, -0.5, 0.67, -0.47"
120,GENE2457X,float64,17.0,17.17,69.0,"0.49, 0.32, 0.0, 0.04, -0.02, -0.11, 0.09, -0.08, -0.84, 0.07"
121,GENE2414X,float64,17.0,17.17,74.0,"0.92, 0.62, 0.54, -0.74, -0.28, 0.1, -0.61, -0.26, -0.79, 1.17"
122,GENE2381X,float64,17.0,17.17,77.0,"-0.25, -0.27, 2.85, 0.27, -0.65, -1.28, -1.59, 1.21, 2.05, -1.96"
123,GENE2376X,float64,17.0,17.17,74.0,"0.4, 0.46, -0.88, -0.43, 1.81, -0.4, -0.08, -0.53, -0.45, 1.36"
124,GENE2344X,float64,17.0,17.17,69.0,"-0.23, -0.4, -0.63, -0.25, -0.67, 0.97, -0.2, -0.12, -0.26, 0.31"
125,GENE2415X,float64,17.0,17.17,67.0,"-0.33, -0.32, -0.26, 0.64, 0.01, -0.48, 0.63, -0.17, -0.29, -0.76"
126,GENE2178X,float64,17.0,17.17,73.0,"0.27, -0.21, -0.67, -0.68, 0.1, 0.2, 0.48, -0.35, -0.44, -0.4"
127,GENE2265X,float64,17.0,17.17,70.0,"-0.34, -0.2, -0.36, 0.21, 0.63, 0.41, 0.37, -0.54, -0.28, 0.43"
128,GENE1886X,float64,17.0,17.17,66.0,"-0.33, 0.0, -0.18, 0.12, -0.54, -0.85, 0.07, -0.11, 0.23, 0.51"
129,GENE2692X,float64,17.0,17.17,70.0,"-0.28, -0.09, 0.18, 0.54, 0.44, -0.41, 0.32, -0.18, -0.31, -0.06"
130,GENE1090X,float64,17.0,17.17,64.0,"0.33, -0.01, -0.12, 0.11, -0.41, 0.09, 0.03, 0.0, -0.6, 0.5"
131,GENE3344X,float64,17.0,17.17,74.0,"-0.09, -0.07, -0.28, 0.81, -1.27, -0.05, 0.73, 0.27, 0.09, 0.92"
132,GENE3189X,float64,17.0,17.17,71.0,"-0.29, 0.08, 0.48, 0.13, -0.72, 0.19, 0.57, -0.67, 0.23, -0.2"
133,GENE2571X,float64,17.0,17.17,63.0,"0.09, -0.08, 0.6, 0.33, 0.39, 0.01, -0.04, -0.49, -0.14, -0.01"
134,GENE1475X,float64,17.0,17.17,72.0,"-0.4, -0.83, -0.12, -0.44, -0.11, -0.26, -0.52, 0.87, 0.21, -0.15"
135,GENE8X,float64,17.0,17.17,66.0,"-0.57, 0.25, 0.07, 0.15, 0.59, -0.08, -0.35, -0.47, -0.43, 0.34"
136,GENE3053X,float64,17.0,17.17,63.0,"-0.14, 0.12, 0.05, -0.24, -0.16, -0.23, 0.37, 0.07, 0.25, -0.18"
137,GENE2932X,float64,17.0,17.17,76.0,"0.17, -0.53, -0.12, 0.71, 0.47, -2.15, 0.53, 0.14, -0.57, 0.5"
138,GENE256X,float64,17.0,17.17,63.0,"-0.19, 0.59, 0.29, 0.14, -0.4, -0.43, 0.05, 0.24, 0.36, -0.2"
139,GENE2909X,float64,17.0,17.17,60.0,"0.08, 0.07, -0.14, -0.05, -0.4, 0.01, -0.33, -0.09, -0.26, 0.0"
140,GENE2959X,float64,17.0,17.17,70.0,"0.0, -0.26, -0.52, 0.29, -0.16, -0.44, 0.1, 0.34, -0.34, 1.16"
141,GENE2726X,float64,17.0,17.17,67.0,"0.08, 0.02, 0.17, 0.24, -0.51, -0.15, -0.82, 0.12, -0.48, 0.3"
142,GENE2874X,float64,17.0,17.17,63.0,"-0.49, 0.25, 0.0, 0.54, -0.25, -0.42, 0.21, 0.31, -0.08, -0.8"
143,GENE3004X,float64,17.0,17.17,69.0,"-0.4, 0.0, 0.59, -0.97, 0.39, -0.55, -0.31, -0.43, -0.02, 0.08"
144,GENE2803X,float64,17.0,17.17,74.0,"-0.08, 0.0, -0.22, -0.56, 0.61, -1.4, 0.24, -1.09, 0.52, 0.34"
145,GENE2787X,float64,17.0,17.17,74.0,"0.1, -0.4, -0.04, -0.19, -0.6, 0.07, -0.28, 1.12, 0.41, -0.49"
146,GENE280X,float64,17.0,17.17,72.0,"-0.3, 0.72, 0.31, 0.0, -0.53, -0.44, -1.1, -0.95, -0.07, 1.2"
147,GENE2944X,float64,17.0,17.17,64.0,"-0.17, 0.03, -0.28, -0.05, 0.06, 0.26, -0.2, 0.02, -0.48, 0.09"
148,GENE2990X,float64,17.0,17.17,64.0,"-0.02, 0.18, 0.34, -0.37, 0.22, -0.3, 0.08, -0.1, 0.65, -0.22"
149,GENE345X,float64,17.0,17.17,69.0,"0.01, -0.27, 0.02, -0.66, 0.52, -0.63, 0.1, -1.12, 0.67, -0.19"
150,GENE2621X,float64,17.0,17.17,66.0,"0.31, -0.14, -0.1, 0.04, 0.15, -0.27, -0.03, 0.73, -0.25, 0.4"
151,GENE3024X,float64,17.0,17.17,68.0,"0.37, 0.0, -0.61, -0.13, -0.29, 0.35, -0.46, 0.48, -0.08, 0.07"
152,GENE2030X,float64,17.0,17.17,66.0,"-0.32, -0.02, -0.37, 0.16, -0.03, 0.15, -0.42, 0.4, 0.03, -0.55"
153,GENE1288X,float64,17.0,17.17,73.0,"0.04, -0.91, -0.12, 0.75, 0.0, 0.66, -0.32, 0.38, 0.4, -0.06"
154,GENE1981X,float64,17.0,17.17,63.0,"-0.5, -0.07, 0.27, 0.0, -0.13, -0.32, -0.44, 0.83, -0.34, -0.26"
155,GENE1995X,float64,17.0,17.17,67.0,"0.0, 0.16, 0.47, -0.28, -0.99, 0.11, 1.35, -0.36, 0.37, -0.38"
156,GENE1998X,float64,17.0,17.17,68.0,"-0.36, -0.38, -0.44, 0.26, 0.45, -0.24, 0.4, -0.48, -0.28, 0.38"
157,GENE1275X,float64,17.0,17.17,69.0,"0.0, -0.27, -0.2, 0.19, 0.05, 0.27, 0.44, -0.44, 0.25, -0.07"
158,GENE1361X,float64,17.0,17.17,73.0,"1.12, -0.38, -1.39, -0.69, -0.64, 1.0, -0.62, -1.16, 0.05, 0.0"
159,GENE1262X,float64,17.0,17.17,71.0,"-0.6, 0.08, -0.03, -0.13, -0.06, 0.38, 0.62, 0.51, 0.4, -0.66"
160,GENE1834X,float64,17.0,17.17,66.0,"-0.19, 0.08, 0.05, -0.2, -0.82, 0.55, -0.73, -0.21, 0.48, -0.06"
161,GENE3990X,float64,17.0,17.17,71.0,"0.13, 0.54, 0.34, 0.0, 0.31, 0.17, -0.1, -0.54, 0.03, 0.51"
162,GENE4021X,float64,17.0,17.17,75.0,"-0.18, -0.31, -1.05, 0.0, 0.88, -0.51, 0.62, 0.69, 3.55, -1.94"
163,GENE861X,float64,17.0,17.17,67.0,"-0.5, 0.01, -0.09, -0.22, -0.02, 0.13, 0.08, -0.83, -0.34, 0.0"
164,GENE680X,float64,17.0,17.17,74.0,"-0.33, -0.28, -0.15, 0.35, 0.0, 0.49, -0.49, 0.66, -0.42, 0.01"
165,GENE679X,float64,17.0,17.17,75.0,"0.53, 0.83, -0.74, -0.34, 0.18, 0.42, -1.98, -0.66, -0.07, -0.49"
166,GENE606X,float64,17.0,17.17,79.0,"-0.09, 0.61, -0.05, 1.22, -1.21, -4.25, 1.18, 2.02, 1.9, 0.91"
167,GENE790X,float64,17.0,17.17,68.0,"-0.46, 0.17, -0.34, -0.75, -0.09, 0.42, 0.0, 0.28, 0.24, 0.37"
168,GENE503X,float64,17.0,17.17,63.0,"-0.32, 0.25, -0.62, -0.03, 0.38, 0.32, 0.74, -0.35, -0.14, -0.2"
169,GENE398X,float64,17.0,17.17,72.0,"-0.31, -0.53, -1.01, -1.34, 0.46, 0.34, 0.1, 0.27, 0.12, 0.95"
170,GENE204X,float64,17.0,17.17,66.0,"-0.12, 0.16, -0.45, -0.26, -0.34, -0.84, 0.0, 0.52, 0.09, -0.22"
171,GENE752X,float64,17.0,17.17,74.0,"0.3, -0.31, -0.89, -0.61, -0.1, 0.16, -0.58, 0.84, 0.1, -0.82"
172,GENE361X,float64,17.0,17.17,68.0,"0.67, -0.26, 0.05, -0.17, -0.18, 0.14, -0.55, -0.35, 0.18, -0.08"
173,GENE1500X,float64,17.0,17.17,63.0,"-0.22, 0.08, -0.15, -0.16, 0.19, 0.07, 0.2, 0.56, -0.4, 0.27"
174,GENE71X,float64,17.0,17.17,62.0,"-0.02, -0.34, 0.19, 0.05, 0.12, -0.49, 0.24, 0.01, 0.43, -0.39"
175,GENE3201X,float64,17.0,17.17,67.0,"-0.25, 0.3, -0.51, -0.37, -0.13, 1.0, 0.31, -0.92, 0.49, -0.09"
176,GENE1463X,float64,17.0,17.17,66.0,"-0.07, 0.13, -0.21, -0.08, -0.18, 0.11, 0.51, -0.56, 0.16, -0.62"
177,GENE1461X,float64,17.0,17.17,68.0,"-0.31, 0.22, -0.28, -0.56, 0.2, 0.08, 0.03, -0.99, -0.25, -0.13"
178,GENE1455X,float64,17.0,17.17,68.0,"0.33, -0.4, 0.41, 0.15, -0.02, 0.09, 0.34, -0.44, 0.23, 0.29"
179,GENE1426X,float64,17.0,17.17,68.0,"0.03, 0.05, -0.15, 0.81, -0.09, 0.64, -0.07, -0.71, -0.02, -0.12"
180,GENE3463X,float64,17.0,17.17,63.0,"-0.14, 0.37, 0.35, 0.13, 0.34, -0.1, -0.21, -0.18, 0.02, 0.16"
181,GENE3460X,float64,17.0,17.17,68.0,"-0.2, 0.0, 0.21, -0.91, -0.08, 0.05, 0.4, 0.28, -0.02, -0.14"
182,GENE1480X,float64,17.0,17.17,74.0,"0.07, -1.12, -1.06, 1.2, -0.34, 0.05, 0.92, -1.02, -0.92, 2.28"
183,GENE1552X,float64,17.0,17.17,75.0,"1.0, 0.9, -1.1, 2.02, -0.61, -0.48, -1.76, -0.91, 1.64, -0.72"
184,GENE1527X,float64,17.0,17.17,73.0,"0.25, -0.6, 0.23, -1.41, 0.39, 0.33, 0.55, 1.3, 0.82, -1.27"
185,GENE1528X,float64,17.0,17.17,71.0,"-0.38, 1.0, -0.83, -0.08, 0.85, -0.03, -0.61, -0.06, -0.98, 0.0"
186,GENE3599X,float64,17.0,17.17,62.0,"0.12, 0.21, -0.38, -0.23, 0.06, -0.04, -0.79, -0.15, 0.09, -0.28"
187,GENE1616X,float64,17.0,17.17,78.0,"0.47, -0.5, 0.62, 1.75, -1.15, 0.24, -0.04, -0.28, 1.26, -1.94"
188,GENE1627X,float64,17.0,17.17,69.0,"-1.19, -0.59, 1.0, -0.2, -0.96, -0.33, 0.17, -0.21, 1.17, -0.91"
189,GENE1651X,float64,17.0,17.17,79.0,"2.5, -1.43, -1.57, -0.01, -1.29, -1.74, 0.4, -2.31, 1.85, -0.78"
190,GENE1650X,float64,17.0,17.17,74.0,"-0.88, -1.4, 1.13, -1.33, 0.86, 1.89, -1.78, -1.8, 0.0, -1.25"
191,GENE1649X,float64,17.0,17.17,75.0,"-0.85, 1.45, 3.04, -0.98, 1.87, -1.17, -1.46, 17226.0, -0.77, 2.07"
192,GENE1645X,float64,17.0,17.17,74.0,"-2.03, -1.98, -2.16, 0.77, 2.89, -1.8, 0.37, -2.1, 1.48, 1.78"
193,GENE1641X,float64,17.0,17.17,75.0,"-1.94, -2.23, -2.11, 1.6, 3.99, -2.2, 2.93, 0.53, -1.55, -2.89"
194,GENE1680X,float64,17.0,17.17,71.0,"-0.13, -0.05, 0.0, 0.07, -0.08, -0.37, 1.0, -0.79, 0.25, -1.04"

In [75]:
# Numeric Feature Statistics
numeric_stats

           count        mean          std   min      max
GENE1836X   82.0  193.106463  1749.242604 -1.49  15840.0
GENE1865X   96.0  155.586250  1524.398927 -1.80  14936.0
GENE1380X   91.0  163.160110  1556.281887 -0.80  14846.0
GENE1933X   86.0  173.935000  1612.853052 -1.15  14957.0
GENE1932X   96.0  142.379479  1394.468363 -1.17  13663.0
GENE1931X   94.0  145.474255  1410.573339 -1.20  13676.0
GENE1930X   98.0  139.444184  1380.066790 -0.89  13662.0
GENE3129X   98.0  177.871122  1761.408928 -1.15  17437.0
GENE3126X   97.0  176.453608  1737.558839 -1.62  17113.0
GENE0X      91.0  163.662857  1560.786305 -0.71  14889.0
GENE3115X   91.0  171.364835  1634.377205 -0.78  15591.0
GENE3116X   95.0  183.609895  1788.888392 -1.63  17436.0
GENE3117X   84.0  208.567143  1910.816398 -1.50  17513.0
GENE3118X   82.0  165.696707  1499.091654 -2.18  13575.0
GENE3073X   97.0  213.261134  2099.626677 -1.44  20679.0
GENE3072X   89.0  183.351124  1729.382680 -1.34  16315.0
GENE3067X   84.0  168.709762  1545.188543 -2.06  14162.0
GENE3068X   91.0  211.870110  2023.531129 -2.70  19303.0
GENE3069X   83.0  168.468795  1537.945297 -3.30  14011.0
GENE2584X   84.0  253.663690  2325.004253 -4.18  21309.0
GENE3070X   98.0  150.090714  1485.527387 -1.02  14706.0
GENE1843X   96.0  218.825104  2143.811495 -0.74  21005.0
GENE3166X   87.0  212.385632  1980.724765 -0.65  18475.0
GENE3165X   83.0  167.598193  1526.486771 -1.13  13907.0
GENE1885X   84.0  169.264881  1551.973304 -2.51  14224.0
GENE3385X   98.0  188.781939  1870.618811 -2.60  18518.0
GENE3384X   96.0  165.249375  1620.247543 -2.70  15875.0
GENE1110X   88.0  185.113523  1736.843461 -2.08  16293.0
GENE1109X   97.0  176.590825  1741.033091 -4.54  17147.0
GENE1108X   95.0  192.892947  1880.313040 -2.35  18327.0
GENE1107X   91.0  222.031099  2118.165797 -2.20  20206.0
GENE4005X   81.0  158.948272  1429.881041 -1.70  12869.0
GENE4006X   97.0  209.419691  2062.267166 -4.42  20311.0
GENE4007X   98.0  197.819082  1958.179860 -3.70  19385.0
GENE4008X   96.0  212.490521  2080.726832 -3.13  20387.0
GENE4009X   91.0  156.567363  1494.126844 -1.97  14253.0
GENE4010X   82.0   50.439878   455.516137 -2.27   4125.0
GENE4011X   85.0   48.458471   445.013772 -2.03   4103.0
GENE4012X   83.0  203.725181  1854.226766 -2.50  16893.0
GENE4013X   88.0  172.561364  1615.168543 -2.55  15152.0
GENE4014X   86.0  206.108605  1906.099372 -2.33  17677.0
GENE4015X   89.0   46.524382   434.766477 -1.66   4102.0
GENE4016X   98.0  197.518469  1955.046491 -1.79  19354.0
GENE3884X   87.0  171.877931  1602.370336 -1.62  14946.0
GENE3885X   95.0  218.334316  2127.462560 -1.95  20736.0
GENE3886X   94.0  219.707234  2129.465231 -1.46  20646.0
GENE3887X   84.0  248.290952  2275.906947 -1.98  20859.0
GENE3888X   87.0  241.898276  2257.345328 -2.26  21055.0
GENE3889X   89.0  152.714607  1440.856922 -1.66  13593.0
GENE3890X   92.0  168.641630  1617.761531 -3.02  15517.0
GENE1114X   98.0  215.542755  2133.336837 -1.41  21119.0
GENE1115X   98.0  166.472959  1648.370831 -1.83  16318.0
GENE3936X   81.0  261.478642  2353.446222 -1.48  21181.0
GENE3937X   87.0  247.217701  2306.225147 -1.36  21511.0
GENE3992X   87.0  246.377011  2298.073589 -2.39  21435.0
GENE3991X   95.0  223.352105  2177.127837 -1.96  21220.0
GENE3963X   98.0  214.059388  2119.506494 -1.45  20982.0
GENE3994X   97.0  140.363608  1382.598875 -2.41  13617.0
GENE1140X   94.0  219.148085  2125.040812 -2.52  20603.0
GENE1141X   94.0  170.981170  1656.970307 -1.36  16065.0
GENE3952X   85.0  165.184000  1522.631597 -1.76  14038.0
GENE3981X   96.0  167.969479  1644.513338 -1.35  16113.0
GENE3940X   96.0  167.276458  1636.643564 -1.57  16036.0
GENE3951X   95.0  155.673684  1516.075292 -1.61  14777.0
GENE3950X   98.0  197.126633  1951.004338 -2.55  19314.0
GENE3949X   94.0  166.481277  1612.611594 -2.26  15635.0
GENE3948X   97.0  178.742268  1759.586654 -1.48  17330.0
GENE3806X   88.0  209.529886  1966.035929 -2.58  18443.0
GENE3807X   92.0  180.787935  1733.267695 -1.66  16625.0
GENE3944X   98.0  197.631224  1954.422952 -2.48  19348.0
GENE3943X   98.0  197.000510  1950.302696 -2.17  19307.0
GENE3942X   91.0  212.144835  2024.137785 -1.84  19309.0
GENE3941X   98.0  196.581633  1945.854932 -2.03  19263.0
GENE3939X   95.0  154.407474  1505.215522 -2.36  14671.0
GENE3946X   97.0  174.657216  1720.712984 -2.26  16947.0
GENE3945X   98.0  196.342653  1942.919762 -2.15  19234.0
GENE3947X   96.0  200.241250  1962.351912 -2.20  19227.0
GENE3954X   84.0  153.642143  1408.050042 -2.61  12905.0
GENE3953X   94.0  159.577447  1547.340359 -2.97  15002.0
GENE2531X   95.0  139.905158  1363.317122 -2.25  13288.0
GENE2532X   90.0  241.155778  2286.310329 -1.45  21690.0
GENE2533X   91.0  203.240989  1938.167039 -2.06  18489.0
GENE2534X   95.0  185.847158  1810.327491 -2.09  17645.0
GENE2535X   83.0  179.312169  1633.622001 -2.87  14883.0
GENE2536X   98.0  180.149898  1782.506558 -3.00  17646.0
GENE2537X   96.0  141.865729  1388.333751 -3.77  13603.0
GENE2538X   92.0  182.645870  1750.358130 -2.73  16789.0
GENE2539X   92.0  147.829348  1417.054519 -1.32  13592.0
GENE2540X   98.0  149.782041  1481.885021 -2.65  14670.0
GENE2541X   98.0  215.695204  2134.239922 -3.58  21128.0
GENE2542X   94.0  224.397021  2175.159599 -1.87  21089.0
GENE2543X   96.0  150.414896  1473.054765 -2.79  14433.0
GENE3959X   94.0  168.829043  1636.969936 -1.31  15871.0
GENE3960X   98.0  208.260510  2061.313676 -1.14  20406.0
GENE3879X   98.0  180.203878  1783.725372 -1.11  17658.0
GENE3880X   98.0  188.050306  1860.895902 -1.65  18422.0
GENE3881X   97.0  181.724124  1789.237575 -1.82  17622.0
GENE3882X   95.0  175.757579  1712.661444 -1.69  16693.0
GENE3861X   87.0  240.258851  2243.098334 -3.21  20922.0
GENE3860X   85.0  251.959529  2325.195705 -2.88  21437.0
GENE3863X   82.0  172.449634  1562.059746 -2.05  14145.0
GENE3862X   88.0  166.237841  1558.917841 -1.96  14624.0
GENE3864X   83.0  200.690964  1828.454075 -2.01  16658.0
GENE3865X   92.0  172.578043  1655.291641 -1.85  15877.0
GENE3866X   97.0  189.562680  1867.942501 -2.32  18397.0
GENE3867X   92.0  147.845543  1418.106924 -2.04  13602.0
GENE3868X   92.0   44.072391   423.290946 -2.32   4060.0
GENE3869X   94.0  188.084574  1824.282745 -2.82  17687.0
GENE3870X   95.0  203.769158  1985.985239 -1.58  19357.0
GENE3871X   84.0  207.399167  1901.228043 -2.36  17425.0
GENE3872X   88.0  157.810455  1480.143249 -1.68  13885.0
GENE2592X   94.0  216.003617  2094.301670 -1.49  20305.0
GENE2591X   92.0  181.634348  1741.821377 -1.29  16707.0
GENE166X    97.0  219.630722  2162.990796 -2.22  21303.0
GENE3438X   98.0  207.907959  2058.594121 -1.32  20379.0
GENE3439X   82.0  173.671829  1572.878925 -2.02  14243.0
GENE3441X   85.0  151.899882  1401.162353 -2.07  12918.0
GENE3440X   93.0  150.938925  1455.359173 -1.65  14035.0
GENE3444X   90.0  179.525222  1702.990580 -2.38  16156.0
GENE3442X   98.0  181.825408  1800.297203 -1.70  17822.0
GENE3443X   97.0  171.014330  1684.563708 -1.77  16591.0
GENE3446X   94.0  216.847128  2101.615630 -2.47  20376.0
GENE3445X   98.0  179.994592  1782.318024 -2.36  17644.0
GENE3447X   98.0  212.092245  2099.704123 -1.16  20786.0
GENE3448X   95.0  219.069579  2135.162918 -1.02  20811.0
GENE3449X   98.0  189.471837  1875.344853 -0.86  18565.0
GENE1501X   91.0  229.219560  2186.829422 -1.50  20861.0
GENE3404X   91.0  193.685495  1847.389623 -0.75  17623.0
GENE3403X   92.0  151.395543  1452.410224 -1.40  13931.0
GENE3401X   97.0  217.465773  2141.873650 -1.16  21095.0
GENE3402X   97.0  165.912165  1633.996140 -1.15  16093.0
GENE3399X   97.0  215.940515  2127.051649 -1.11  20949.0
GENE3400X   94.0  227.290638  2203.839672 -1.01  21367.0
GENE816X    96.0  185.513854  1817.416874 -0.88  17807.0
GENE3406X   96.0  218.576354  2141.877560 -1.46  20986.0
GENE3405X   98.0  199.017959  1970.099747 -0.97  19503.0
GENE213X    89.0  152.838202  1441.701252 -1.20  13601.0
GENE3892X   91.0  235.804286  2249.515416 -1.20  21459.0
GENE3876X   92.0  162.344348  1557.396925 -1.51  14938.0
GENE3875X   92.0  175.720000  1686.370714 -3.07  16175.0
GENE3874X   89.0  181.548427  1713.281168 -3.14  16163.0
GENE167X    87.0  242.598161  2263.126076 -1.22  21109.0
GENE3450X   98.0  164.115612  1623.913705 -1.79  16076.0
GENE3451X   98.0  164.077449  1623.713476 -1.65  16074.0
GENE3452X   98.0  189.374796  1874.436302 -1.60  18556.0
GENE3453X   96.0  212.488333  2081.758160 -1.73  20397.0
GENE3454X   95.0  169.141368  1649.267458 -1.48  16075.0
GENE3878X   93.0  197.906452  1909.138253 -2.22  18411.0
GENE3437X   97.0  189.197010  1863.260646 -1.68  18351.0
GENE3436X   98.0  168.142245  1664.223339 -1.72  16475.0
GENE3435X   98.0  188.985408  1871.006152 -3.08  18522.0
GENE3470X   98.0  175.891429  1741.709985 -1.71  17242.0
GENE3832X   81.0  259.768519  2339.688758 -2.82  21057.0
GENE3831X   98.0  197.568469  1955.959940 -2.38  19363.0
GENE3830X   98.0  198.151633  1961.615443 -1.35  19419.0
GENE394X    98.0  216.012347  2138.697924 -1.47  21172.0
GENE3531X   96.0  167.094063  1636.765203 -1.56  16037.0
GENE3530X   98.0  207.010408  2048.786202 -0.91  20282.0
GENE918X    98.0  216.998571  2147.986496 -1.52  21264.0
GENE3483X   97.0  209.008660  2058.307867 -1.39  20272.0
GENE3520X   98.0  189.569286  1876.457666 -1.41  18576.0
GENE3519X   97.0  165.402474  1628.611188 -1.93  16040.0
GENE3518X   98.0  167.569388  1659.076928 -1.59  16424.0
GENE3517X   98.0  157.326633  1557.453273 -1.17  15418.0
GENE3516X   98.0  155.835102  1542.501131 -1.69  15270.0
GENE3515X   98.0  208.242143  2061.927908 -1.75  20412.0
GENE3514X   97.0  178.824742  1761.424718 -2.25  17348.0
GENE3503X   97.0  207.943299  2048.260572 -1.50  20173.0
GENE3502X   97.0  182.862680  1801.329272 -1.93  17741.0
GENE3504X   98.0  216.251429  2141.122866 -1.16  21196.0
GENE3511X   97.0  175.149897  1724.663330 -1.06  16986.0
GENE3505X   98.0  141.023571  1395.622353 -1.28  13816.0
GENE3506X   98.0  219.792041  2175.869044 -1.18  21540.0
GENE3507X   96.0  217.050625  2126.770732 -1.22  20838.0
GENE3508X   98.0  171.303673  1695.640319 -1.82  16786.0
GENE3509X   98.0  211.961939  2098.288654 -1.96  20772.0
GENE3510X   97.0  143.722062  1415.596742 -1.60  13942.0
GENE3501X   98.0  164.424592  1627.964491 -1.50  16116.0
GENE3500X   97.0  210.172577  2069.884050 -1.66  20386.0
GENE3499X   98.0  136.334592  1348.950766 -1.28  13354.0
GENE3498X   97.0  162.779897  1603.232101 -1.25  15790.0
GENE3497X   98.0  172.735816  1709.680062 -1.56  16925.0
GENE3496X   97.0  174.044433  1714.927901 -1.38  16890.0
GENE3495X   95.0  186.074000  1813.414624 -1.48  17675.0
GENE3490X   98.0  216.918469  2146.667998 -1.51  21251.0
GENE3489X   97.0  145.100722  1428.689755 -1.65  14071.0
GENE3492X   98.0  134.551327  1331.476961 -1.83  13181.0
GENE3491X   95.0  227.445368  2217.142235 -1.85  21610.0
GENE3493X   96.0  175.150104  1715.761939 -1.34  16811.0
GENE3494X   96.0  183.960000  1802.313055 -2.54  17659.0
GENE3521X   98.0  217.207959  2150.822785 -3.05  21292.0
GENE3522X   97.0  137.762268  1356.704628 -1.17  13362.0
GENE3488X   95.0  222.292421  2166.557701 -1.28  21117.0
GENE3604X   90.0  194.668333  1846.450268 -1.50  17517.0
GENE3603X   98.0  213.603265  2114.552241 -1.76  20933.0
GENE3602X   96.0  153.600000  1505.317227 -1.59  14749.0
GENE3812X   87.0  205.762759  1919.188324 -2.02  17901.0
GENE3484X   97.0  160.380412  1579.369393 -2.55  15555.0
GENE3485X   96.0  222.964583  2184.123523 -1.72  21400.0
GENE3486X   98.0  214.806122  2126.472258 -2.26  21051.0
GENE3487X   98.0  186.172449  1842.819416 -2.59  18243.0
GENE3526X   86.0  214.932093  1993.071709 -1.09  18483.0
GENE3525X   90.0  205.780111  1951.859447 -1.79  18517.0
GENE3524X   97.0  173.678557  1710.759121 -1.67  16849.0
GENE3523X   98.0  189.931224  1879.890522 -0.99  18610.0
GENE3280X   97.0  169.527526  1669.019684 -3.10  16438.0
GENE3281X   98.0  187.839184  1860.305125 -2.15  18416.0
GENE3282X   95.0  167.720421  1634.690987 -2.01  15933.0
GENE3527X   97.0  136.374639  1343.304816 -1.17  13230.0
GENE3529X   94.0  148.905532  1442.950480 -0.88  13990.0
GENE3528X   98.0  189.536020  1875.848591 -1.12  18570.0
GENE3512X   98.0  180.691633  1788.880477 -0.91  17709.0
GENE2544X   88.0  210.507614  1974.125162 -1.39  18519.0
GENE3843X   97.0  163.879278  1614.507004 -1.72  15901.0
GENE3842X   92.0  198.293043  1902.175145 -1.12  18245.0
GENE3480X   98.0  145.943469  1443.291213 -3.18  14288.0
GENE3802X   98.0  196.456224  1945.561608 -3.24  19260.0
GENE3801X   97.0  177.963608  1753.716270 -3.85  17272.0
GENE3533X   92.0  185.254130  1777.909415 -3.70  17053.0
GENE3534X   95.0  192.527895  1877.240362 -3.23  18297.0
GENE3540X   83.0  157.633976  1437.600592 -2.59  13097.0
GENE3558X   98.0  176.040204  1742.307085 -1.32  17248.0
GENE3811X   94.0  225.004468  2181.872543 -1.72  21154.0
GENE3291X   98.0  141.702245  1403.207409 -2.60  13891.0
GENE2447X   98.0  209.970816  2077.876460 -2.10  20570.0
GENE3810X   91.0  161.009670  1536.795108 -1.36  14660.0
GENE3809X   95.0  163.794421  1597.251503 -2.18  15568.0
GENE3808X   84.0  182.194643  1670.575952 -1.64  15311.0
GENE3826X   96.0  208.744688  2045.324600 -2.00  20040.0
GENE3825X   90.0  151.473111  1437.791312 -2.36  13640.0
GENE3799X   94.0  167.872021  1628.729672 -2.70  15791.0
GENE3798X   95.0  222.706526  2169.625519 -1.58  21147.0
GENE3797X   94.0  165.351064  1604.180965 -3.58  15553.0
GENE3796X   92.0  186.326630  1789.707118 -4.20  17166.0
GENE3795X   98.0  195.790408  1939.914507 -3.29  19204.0
GENE3794X   96.0  180.912917  1776.534288 -4.66  17406.0
GENE3687X   96.0  219.369167  2149.840566 -2.45  21064.0
GENE3790X   92.0  157.759130  1513.400330 -2.69  14516.0
GENE3789X   96.0  200.979375  1971.558053 -4.67  19317.0
GENE3788X   95.0  146.134000  1426.543907 -3.81  13904.0
GENE3787X   96.0  200.933229  1970.325088 -2.65  19305.0
GENE3786X   97.0  198.364536  1954.653329 -3.54  19251.0
GENE3785X   95.0  194.637474  1897.344583 -2.29  18493.0
GENE3784X   96.0  182.058333  1784.047829 -2.51  17480.0
GENE3693X   97.0  166.469485  1641.223397 -4.35  16164.0
GENE3692X   97.0  160.970515  1587.413709 -4.89  15634.0
GENE3698X   98.0  150.909796  1493.506644 -3.06  14785.0
GENE3699X   98.0  186.357041  1845.352196 -3.30  18268.0
GENE3700X   98.0  195.883571  1940.210892 -1.40  19207.0
GENE3729X   96.0  175.435938  1719.858019 -2.93  16851.0
GENE3728X   98.0  161.171837  1595.434218 -2.94  15794.0
GENE3783X   82.0  186.490366  1689.613094 -1.68  15300.0
GENE3782X   98.0  196.768061  1950.224349 -2.51  19306.0
GENE3781X   98.0  210.389592  2084.671622 -3.44  20637.0
GENE3780X   93.0  170.833118  1648.977179 -2.70  15902.0
GENE3779X   87.0  163.812644  1529.385346 -3.52  14265.0
GENE3778X   97.0   44.915361   444.132200 -4.03   4374.0
GENE3777X   96.0  174.865521  1714.244529 -3.87  16796.0
GENE3776X   98.0  189.825918  1880.820020 -3.61  18619.0
GENE3775X   97.0  180.520722  1779.204562 -3.05  17523.0
GENE3774X   98.0  155.605816  1542.116519 -3.13  15266.0
GENE3773X   95.0  160.458842  1566.594441 -3.43  15269.0
GENE3772X   96.0  219.999167  2157.304628 -3.81  21137.0
GENE3771X   97.0  188.131649  1856.496733 -4.83  18284.0
GENE3770X   98.0  164.355510  1631.237861 -5.11  16148.0
GENE3769X   98.0  178.063571  1765.369965 -4.17  17476.0
GENE3768X   98.0  160.179898  1587.983719 -4.21  15720.0
GENE3767X   97.0  188.303814  1856.376526 -4.40  18283.0
GENE3766X   96.0  219.513229  2150.960591 -6.01  21075.0
GENE3765X   97.0  216.381134  2134.496368 -6.69  21022.0
GENE3764X   98.0  145.099490  1438.887534 -6.20  14244.0
GENE3763X   98.0  160.904796  1596.074262 -4.61  15800.0
GENE3762X   96.0  180.495208  1771.833030 -5.15  17360.0
GENE3761X   88.0  203.370227  1910.631077 -4.59  17923.0
GENE3760X   98.0  216.028163  2139.512918 -3.08  21180.0
GENE3759X   98.0  137.800918  1365.334607 -3.48  13516.0
GENE3758X   98.0  196.586735  1948.201908 -3.45  19286.0
GENE3757X   98.0  169.906939  1684.761105 -3.75  16678.0
GENE3756X   98.0  143.953776  1426.859242 -4.57  14125.0
GENE3755X   97.0  205.744948  2027.968012 -3.79  19973.0
GENE3754X   96.0  151.542917  1485.830869 -3.30  14558.0
GENE3753X   98.0  196.377347  1945.773996 -3.21  19262.0
GENE3752X   97.0  138.000000  1361.502837 -4.13  13409.0
GENE3751X   96.0  152.170208  1493.914071 -3.97  14637.0
GENE3750X   93.0  144.139247  1390.558068 -1.79  13410.0
GENE3749X   96.0  141.492188  1386.102917 -3.26  13581.0
GENE3748X   95.0  155.839579  1520.827982 -3.70  14823.0
GENE3747X   98.0  217.104388  2151.241673 -3.99  21296.0
GENE3746X   97.0  215.845155  2127.984983 -3.50  20958.0
GENE3745X   96.0  217.633333  2134.446071 -3.91  20913.0
GENE3744X   98.0  214.431735  2124.775660 -3.63  21034.0
GENE3743X   97.0  180.277629  1777.075055 -3.41  17502.0
GENE3742X   98.0  145.197041  1438.468693 -3.63  14240.0
GENE3741X   85.0  153.002706  1412.456152 -2.71  13022.0
GENE3740X   96.0  192.803021  1889.479465 -1.64  18513.0
GENE3739X   98.0  146.342755  1449.884114 -2.31  14353.0
GENE3738X   95.0  153.680947  1501.143640 -4.32  14631.0
GENE3737X   96.0  212.045521  2080.463261 -3.12  20384.0
GENE3736X   91.0  160.676593  1535.134765 -3.76  14644.0
GENE3732X   96.0  185.788542  1820.379597 -2.38  17836.0
GENE3733X   98.0  189.371837  1875.457229 -2.61  18566.0
GENE3734X   98.0  175.897347  1742.526033 -3.56  17250.0
GENE3735X   97.0  189.056289  1864.506414 -3.33  18363.0
GENE3570X   97.0  165.621753  1631.666430 -2.04  16070.0
GENE3731X   97.0  216.627629  2134.367909 -1.92  21021.0
GENE3730X   97.0  170.408763  1680.317153 -2.66  16549.0
GENE3701X   98.0  196.246939  1943.950133 -4.19  19244.0
GENE3702X   96.0  156.522708  1533.997412 -3.07  15030.0
GENE3706X   87.0  206.002529  1921.331664 -2.91  17921.0
GENE3707X   95.0  184.210526  1795.566187 -2.88  17501.0
GENE3708X   98.0  204.229184  2021.923149 -2.48  20016.0
GENE3709X   98.0  205.575306  2034.644887 -2.78  20142.0
GENE3710X   94.0  157.938830  1531.873536 -3.12  14852.0
GENE3711X   95.0  142.009789  1385.081025 -3.37  13500.0
GENE3712X   96.0  142.630833  1398.464972 -3.07  13702.0
GENE3713X   96.0  162.123958  1589.525876 -3.70  15574.0
GENE3714X   97.0  158.959485  1564.946733 -1.47  15413.0
GENE3715X   95.0  162.072211  1580.113945 -1.94  15401.0
GENE3716X   97.0  184.554433  1819.725317 -4.26  17922.0
GENE3717X   97.0  156.091546  1539.798598 -4.27  15165.0
GENE3718X   96.0  202.735937  1987.259756 -2.61  19471.0
GENE3719X   91.0  166.446154  1588.473578 -1.90  15153.0
GENE3720X   96.0  221.071146  2166.373107 -4.10  21226.0
GENE3721X   96.0  142.253854  1393.862609 -3.21  13657.0
GENE3722X   92.0  234.926522  2253.732534 -3.41  21617.0
GENE3723X   95.0  140.434211  1369.172491 -3.73  13345.0
GENE3724X   97.0  206.718351  2036.896083 -3.42  20061.0
GENE3725X   97.0  166.645361  1642.128696 -3.88  16173.0
GENE3726X   98.0  187.784694  1859.902678 -3.76  18412.0
GENE3727X   96.0  186.698542  1830.393327 -3.62  17934.0
GENE2364X   94.0  152.616702  1479.990433 -3.76  14349.0
GENE2363X   95.0  156.950105  1530.874900 -3.73  14921.0
GENE2362X   98.0  189.913061  1880.504800 -1.78  18616.0
GENE2361X   98.0  167.699490  1659.573998 -2.02  16429.0
GENE3697X   97.0  169.944227  1675.235213 -4.12  16499.0
GENE3696X   98.0  210.791327  2087.794312 -2.48  20668.0
GENE3694X   91.0  172.342088  1644.237345 -2.62  15685.0
GENE3695X   89.0  186.046517  1759.111402 -4.21  16595.0
GENE3691X   92.0  151.765543  1458.801140 -4.02  13992.0
GENE3690X   97.0  198.236804  1956.924061 -4.01  19273.0
GENE3689X   98.0  167.896429  1668.434113 -4.57  16516.0
GENE3688X   98.0  159.926837  1588.418740 -4.68  15724.0
GENE3686X   97.0  198.301649  1959.174495 -4.68  19295.0
GENE3684X   92.0   44.424022   428.210402 -4.66   4107.0
GENE3685X   93.0  182.177419  1759.214768 -4.56  16965.0
GENE3683X   98.0  189.867449  1880.407416 -2.01  18615.0
GENE3682X   98.0  180.928469  1791.816096 -2.23  17738.0
GENE3681X   81.0  159.485185  1437.358242 -2.94  12936.0
GENE3678X   98.0  197.434796  1956.381840 -4.29  19367.0

In [76]:
# Categorical Feature Statistics
cat_stats

                value  count   pct
column    rank
GENE1835X 1      0.02      4  4.04
          2     -0.13      3  3.03
          3      0.28      3  3.03
          4      <NA>      3  3.03
          5      0.25      2  2.02

In [77]:
# Target Distribution
target_df

                          count   pct
GENE1835X
0.02                          4  4.04
-0.13                         3  3.03
0.28                          3  3.03
NaN                           3  3.03
0.25                          2  2.02
0.06                          2  2.02
-0.36                         2  2.02
0.22                          2  2.02
0.1                           2  2.02
-0.78                         2  2.02
0.2                           2  2.02
0.42                          2  2.02
0.05                          2  2.02
0.04                          2  2.02
-0.18                         2  2.02
-0.16                         2  2.02
-0.01                         2  2.02
-0.07                         2  2.02
0                             2  2.02
0.14                          1  1.01
0.15                          1  1.01
0.09                          1  1.01
0.13                          1  1.01
0.12                          1  1.01
0.17                          1  1.01
0.07                          1  1.01
0.16                          1  1.01
0.77                          1  1.01
0.19                          1  1.01
0.21                          1  1.01
0.66                          1  1.01
0.81                          1  1.01
0.31                          1  1.01
0.34                          1  1.01
0.37                          1  1.01
0.38                          1  1.01
0.39                          1  1.01
0.4                           1  1.01
0.44                          1  1.01
0.46                          1  1.01
0.3                           1  1.01
1.0                           1  1.01
-1.55                         1  1.01
-0.51                         1  1.01
(Unknown; Clone=1357915)      1  1.01
-0.03                         1  1.01
-0.06                         1  1.01
-0.19                         1  1.01
-0.21                         1  1.01
-0.23                         1  1.01
-0.27                         1  1.01
-0.28                         1  1.01
-0.31                         1  1.01
-0.32                         1  1.01
-0.33                         1  1.01
-0.41                         1  1.01
-0.43                         1  1.01
-0.48                         1  1.01
-0.52                         1  1.01
-1.29                         1  1.01
-0.53                         1  1.01
-0.58                         1  1.01
-0.72                         1  1.01
-0.74                         1  1.01
-0.77                         1  1.01
-0.8                          1  1.01
-0.84                         1  1.01
-0.86                         1  1.01
-0.98                         1  1.01
-1.05                         1  1.01
-1.09                         1  1.01
-1.18                         1  1.01
14913.0                       1  1.01
-1.27                         1  1.01
-1.26                         1  1.01

## Task Curation

In [78]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(dataset=df)
print(f"Recommended IID splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended IID splits: n_repeats=20, n_splits=3, test_size=None

In [79]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry.curation_recommendations import get_recommended_iid_splits

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits for IID data.",
    splits=get_recommended_iid_splits(
        dataset=df,
        n_repeats=n_repeats,
        n_splits=n_splits,
        test_size=none_or_test_size,
        stratify_on=task_mold.stratify_on,
    ),
)

Using Stratified IID splits.

ValueError: Input contains NaN

## Export

In [80]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

NameError: name 'splits_mold' is not defined