### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="parkinsons_biomedical_voice_measurements",
    dataset_year="2007",
    domain_str="medical & healthcare",
    # Data Source
    dataset_source="UCI",
    original_dataset_source_download_link="https://doi.org/10.24432/C59C74",
    download_description="""
We get the 2007 data from the UCI repository.

wget https://archive.ics.uci.edu/static/public/174/parkinsons.zip && unzip parkinsons.zip parkinsons.data && rm parkinsons.zip && mkdir -p local-data-warehouse/parkinsons_biomedical_voice_measurements && mv parkinsons.data local-data-warehouse/parkinsons_biomedical_voice_measurements/
""",
    # References
    academic_reference_bibtex="""@article{little2007exploiting,
  title={Exploiting nonlinear recurrence and fractal scaling properties for voice disorder detection},
  author={Little, Max and Mcsharry, Patrick and Roberts, Stephen and Costello, Declan and Moroz, Irene},
  journal={Nature Precedings},
  pages={1--1},
  year={2007},
  publisher={Nature Publishing Group UK London}
}
""",
    academic_reference_bibtex_key="little2007exploiting",
    license="CC BY 4.0",
    data_tags=["Non-IID", "Grouped", "WrongDomain"], # Maybe also temporal but not of importance for the task.
    curation_comments="""
We start with the data from UCI.

- We decode the group ID and session ID (time index per patient) from the name column.
""",
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="status",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="status",
    group_on="patient_id",
    group_time_on="session_number",
    group_labels="per_group",
)

## Preprocessing

In [2]:
import pandas as pd

df = pd.read_csv(dataset_mold.path / "parkinsons.data")

# Split session number from patient ID, split on the last _
df[["patient_id", "session_number"]] = df["name"].str.rsplit("_", n=1, expand=True)
df["session_number"] = df["session_number"].astype(int)
df = df.drop(columns=["name"])

as_cat_type = ["status", "patient_id"]
df[as_cat_type] = df[as_cat_type].astype("category")
print("Loaded data shape:", df.shape)

df = df.sample(frac=1, random_state=42).sort_values(by=["patient_id", "session_number"]).reset_index(drop=True)

Loaded data shape: (195, 25)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 195
Columns: 25
Use sampling: False (sample size: 195)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['MDVP:Fo(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Fhi(Hz)', 'HNR', 'RPDE', 'D2', 'PPE', 'DFA', 'spread1', 'spread2']
Rows remaining as candidates after top-10 filter: 0 (of 195)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),Shimmer:APQ3,Shimmer:APQ5,MDVP:APQ,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE,patient_id,session_number
0,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,0.426,0.02182,0.03130,0.02971,0.06545,0.02211,21.033,1,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654,phon_R01_S01,1
1,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,0.626,0.03134,0.04518,0.04368,0.09403,0.01929,19.085,1,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674,phon_R01_S01,2
2,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,0.482,0.02757,0.03858,0.03590,0.08270,0.01309,20.651,1,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634,phon_R01_S01,3
3,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,0.517,0.02924,0.04005,0.03772,0.08771,0.01353,20.644,1,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975,phon_R01_S01,4
4,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,0.584,0.03490,0.04825,0.04465,0.10470,0.01767,19.649,1,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335,phon_R01_S01,5

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,status,category,0.0,0.0,2.0,"1, 0"
1,patient_id,category,0.0,0.0,32.0,"phon_R01_S21, phon_R01_S27, phon_R01_S35, phon_R01_S01, phon_R01_S06, phon_R01_S07, phon_R01_S04, phon_R01_S02, phon_R01_S10, phon_R01_S13"
2,MDVP:Fo(Hz),float64,0.0,0.0,195.0,"119.992, 122.4, 116.682, 116.676, 116.014, 120.552, 120.267, 107.332, 95.73, 95.056"
3,MDVP:Fhi(Hz),float64,0.0,0.0,195.0,"157.302, 148.65, 131.111, 137.871, 141.781, 131.162, 137.244, 113.84, 132.068, 120.103"
4,MDVP:Flo(Hz),float64,0.0,0.0,195.0,"74.997, 113.819, 111.555, 111.366, 110.655, 113.787, 114.82, 104.315, 91.754, 91.226"
5,MDVP:Jitter(%),float64,0.0,0.0,173.0,"0.0037, 0.0074, 0.0069, 0.0097, 0.0054, 0.0026, 0.003, 0.005, 0.005, 0.0048"
6,MDVP:Jitter(Abs),float64,0.0,0.0,19.0,"0.0, 0.0, 0.0, 0.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0"
7,MDVP:RAP,float64,0.0,0.0,155.0,"0.0017, 0.0016, 0.0025, 0.0043, 0.0016, 0.0013, 0.0032, 0.0027, 0.0037, 0.0022"
8,MDVP:PPQ,float64,0.0,0.0,165.0,"0.0033, 0.0018, 0.002, 0.0028, 0.0015, 0.0014, 0.0022, 0.0039, 0.0026, 0.0034"
9,Jitter:DDP,float64,0.0,0.0,180.0,"0.0051, 0.0111, 0.0129, 0.005, 0.007, 0.0062, 0.004, 0.005, 0.0075, 0.0035"
10,MDVP:Shimmer,float64,0.0,0.0,188.0,"0.0161, 0.015, 0.0229, 0.0245, 0.0327, 0.0173, 0.0145, 0.0157, 0.0549, 0.0643"
11,MDVP:Shimmer(dB),float64,0.0,0.0,149.0,"0.154, 0.197, 0.126, 0.255, 0.307, 0.155, 0.129, 0.145, 0.228, 0.134"
12,Shimmer:APQ3,float64,0.0,0.0,184.0,"0.0083, 0.0144, 0.0073, 0.0077, 0.0047, 0.0052, 0.0128, 0.0128, 0.0063, 0.0148"
13,Shimmer:APQ5,float64,0.0,0.0,189.0,"0.0097, 0.0114, 0.0122, 0.0116, 0.0102, 0.0075, 0.0353, 0.0095, 0.0094, 0.0173"
14,MDVP:APQ,float64,0.0,0.0,189.0,"0.0377, 0.0114, 0.0113, 0.0123, 0.0149, 0.009, 0.0447, 0.0126, 0.0324, 0.0172"
15,Shimmer:DDA,float64,0.0,0.0,189.0,"0.0218, 0.019, 0.0157, 0.0445, 0.0383, 0.0474, 0.0698, 0.0249, 0.0234, 0.094"
16,NHR,float64,0.0,0.0,185.0,"0.0084, 0.0048, 0.0048, 0.0023, 0.0068, 0.0034, 0.0062, 0.0722, 0.0042, 0.0105"
17,HNR,float64,0.0,0.0,195.0,"21.033, 19.085, 20.651, 20.644, 19.649, 21.378, 24.886, 26.892, 21.812, 21.862"
18,RPDE,float64,0.0,0.0,195.0,"0.4148, 0.4584, 0.4299, 0.435, 0.4174, 0.4156, 0.596, 0.6374, 0.6156, 0.547"
19,DFA,float64,0.0,0.0,195.0,"0.8153, 0.8195, 0.8253, 0.8192, 0.8235, 0.8251, 0.7641, 0.7633, 0.7736, 0.7985"
20,spread1,float64,0.0,0.0,195.0,"-4.813, -4.0752, -4.4432, -4.1175, -3.7478, -4.2429, -5.6343, -6.1676, -5.4987, -5.0119"
21,spread2,float64,0.0,0.0,194.0,"0.2103, 0.2665, 0.3356, 0.3112, 0.2345, 0.3341, 0.2577, 0.1837, 0.3278, 0.2991"
22,D2,float64,0.0,0.0,195.0,"2.3014, 2.4869, 2.3423, 2.4056, 2.3322, 2.1876, 1.8548, 2.0647, 2.3225, 2.4328"
23,PPE,float64,0.0,0.0,195.0,"0.2847, 0.3687, 0.3326, 0.369, 0.4103, 0.3578, 0.2118, 0.1638, 0.2316, 0.2714"
24,session_number,int64,0.0,0.0,7.0,"1, 2, 3, 4, 5, 6, 7"

In [6]:
# Numeric Feature Statistics
numeric_stats

                  count        mean        std         min         max
MDVP:Fo(Hz)       195.0  154.228641  41.390065   88.333000  260.105000
MDVP:Fhi(Hz)      195.0  197.104918  91.491548  102.145000  592.030000
MDVP:Flo(Hz)      195.0  116.324631  43.521413   65.476000  239.170000
MDVP:Jitter(%)    195.0    0.006220   0.004848    0.001680    0.033160
MDVP:Jitter(Abs)  195.0    0.000044   0.000035    0.000007    0.000260
MDVP:RAP          195.0    0.003306   0.002968    0.000680    0.021440
MDVP:PPQ          195.0    0.003446   0.002759    0.000920    0.019580
Jitter:DDP        195.0    0.009920   0.008903    0.002040    0.064330
MDVP:Shimmer      195.0    0.029709   0.018857    0.009540    0.119080
MDVP:Shimmer(dB)  195.0    0.282251   0.194877    0.085000    1.302000
Shimmer:APQ3      195.0    0.015664   0.010153    0.004550    0.056470
Shimmer:APQ5      195.0    0.017878   0.012024    0.005700    0.079400
MDVP:APQ          195.0    0.024081   0.016947    0.007190    0.137780
Shimmer:DDA       195.0    0.046993   0.030459    0.013640    0.169420
NHR               195.0    0.024847   0.040418    0.000650    0.314820
HNR               195.0   21.885974   4.425764    8.441000   33.047000
RPDE              195.0    0.498536   0.103942    0.256570    0.685151
DFA               195.0    0.718099   0.055336    0.574282    0.825288
spread1           195.0   -5.684397   1.090208   -7.964984   -2.434031
spread2           195.0    0.226510   0.083406    0.006274    0.450493
D2                195.0    2.381826   0.382799    1.423287    3.671155
PPE               195.0    0.206552   0.090119    0.044539    0.527367
session_number    195.0    3.553846   1.753031    1.000000    7.000000

In [7]:
# Categorical Feature Statistics
cat_stats

                        value  count    pct
column     rank
patient_id 1     phon_R01_S21      7   3.59
           2     phon_R01_S27      7   3.59
           3     phon_R01_S35      7   3.59
           4     phon_R01_S01      6   3.08
           5     phon_R01_S06      6   3.08
status     1                1    147  75.38
           2                0     48  24.62

In [8]:
# Target Distribution
target_df

        count    pct
status
1         147  75.38
0          48  24.62

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
    group_labels=task_mold.group_labels,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Providing recommendations based on number of groups (32).
Recommended splits: n_repeats=20, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_grouped_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    group_on=task_mold.group_on,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
    group_labels=task_mold.group_labels,
    show_splits=True,
    target_on=task_mold.target_column_name,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="We create a default grouped split with label-per-group to judge if model can learn to predict the state of a patient given a set of recordings.",
    splits=splits,
)

Using Stratified Grouped splits.
Using label-per-group grouped splits.
Creating index-based splits for 32 groups

Using Stratified IID splits.
Repeat 0, Fold 0:
            Train N: 127, Test N: 68
            Target Distribution:
            	Train target distribution: {1: 0.7637795275590551, 0: 0.23622047244094488}
            	Test target distribution: {1: 0.7352941176470589, 0: 0.2647058823529412}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 0, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 0, Fold 2:
            Train N: 135, Test N: 60
            Target Distribution:
            	Train target distribution: {1: 0.7333333333333333, 0: 0.26666666666666666}
            	Test target distribution: {1: 0.8, 0: 0.2}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 1, Fold 0:
            Train N: 129, Test N: 66
            Target Distribution:
            	Train target distribution: {1: 0.7674418604651163, 0: 0.23255813953488372}
            	Test target distribution: {1: 0.7272727272727273, 0: 0.2727272727272727}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 1, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 1, Fold 2:
            Train N: 133, Test N: 62
            Target Distribution:
            	Train target distribution: {1: 0.7293233082706767, 0: 0.2706766917293233}
            	Test target distribution: {1: 0.8064516129032258, 0: 0.1935483870967742}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 2, Fold 0:
            Train N: 129, Test N: 66
            Target Distribution:
            	Train target distribution: {1: 0.7674418604651163, 0: 0.23255813953488372}
            	Test target distribution: {1: 0.7272727272727273, 0: 0.2727272727272727}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 2, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 2, Fold 2:
            Train N: 133, Test N: 62
            Target Distribution:
            	Train target distribution: {1: 0.7293233082706767, 0: 0.2706766917293233}
            	Test target distribution: {1: 0.8064516129032258, 0: 0.1935483870967742}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 3, Fold 0:
            Train N: 127, Test N: 68
            Target Distribution:
            	Train target distribution: {1: 0.7637795275590551, 0: 0.23622047244094488}
            	Test target distribution: {1: 0.7352941176470589, 0: 0.2647058823529412}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 3, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 3, Fold 2:
            Train N: 135, Test N: 60
            Target Distribution:
            	Train target distribution: {1: 0.7333333333333333, 0: 0.26666666666666666}
            	Test target distribution: {1: 0.8, 0: 0.2}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 4, Fold 0:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 4, Fold 1:
            Train N: 129, Test N: 66
            Target Distribution:
            	Train target distribution: {1: 0.7674418604651163, 0: 0.23255813953488372}
            	Test target distribution: {1: 0.7272727272727273, 0: 0.2727272727272727}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 4, Fold 2:
            Train N: 133, Test N: 62
            Target Distribution:
            	Train target distribution: {1: 0.7293233082706767, 0: 0.2706766917293233}
            	Test target distribution: {1: 0.8064516129032258, 0: 0.1935483870967742}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 5, Fold 0:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 5, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 5, Fold 2:
            Train N: 134, Test N: 61
            Target Distribution:
            	Train target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            	Test target distribution: {1: 0.8032786885245902, 0: 0.19672131147540983}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 6, Fold 0:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 6, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 6, Fold 2:
            Train N: 134, Test N: 61
            Target Distribution:
            	Train target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            	Test target distribution: {1: 0.8032786885245902, 0: 0.19672131147540983}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 7, Fold 0:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 7, Fold 1:
            Train N: 127, Test N: 68
            Target Distribution:
            	Train target distribution: {1: 0.7637795275590551, 0: 0.23622047244094488}
            	Test target distribution: {1: 0.7352941176470589, 0: 0.2647058823529412}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 7, Fold 2:
            Train N: 135, Test N: 60
            Target Distribution:
            	Train target distribution: {1: 0.7333333333333333, 0: 0.26666666666666666}
            	Test target distribution: {1: 0.8, 0: 0.2}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 8, Fold 0:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 8, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 8, Fold 2:
            Train N: 134, Test N: 61
            Target Distribution:
            	Train target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            	Test target distribution: {1: 0.8032786885245902, 0: 0.19672131147540983}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 9, Fold 0:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 9, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 9, Fold 2:
            Train N: 134, Test N: 61
            Target Distribution:
            	Train target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            	Test target distribution: {1: 0.8032786885245902, 0: 0.19672131147540983}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 10, Fold 0:
            Train N: 127, Test N: 68
            Target Distribution:
            	Train target distribution: {1: 0.7637795275590551, 0: 0.23622047244094488}
            	Test target distribution: {1: 0.7352941176470589, 0: 0.2647058823529412}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 10, Fold 1:
            Train N: 129, Test N: 66
            Target Distribution:
            	Train target distribution: {1: 0.7674418604651163, 0: 0.23255813953488372}
            	Test target distribution: {1: 0.7272727272727273, 0: 0.2727272727272727}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 10, Fold 2:
            Train N: 134, Test N: 61
            Target Distribution:
            	Train target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            	Test target distribution: {1: 0.8032786885245902, 0: 0.19672131147540983}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 11, Fold 0:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 11, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 11, Fold 2:
            Train N: 134, Test N: 61
            Target Distribution:
            	Train target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            	Test target distribution: {1: 0.8032786885245902, 0: 0.19672131147540983}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 12, Fold 0:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 12, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 12, Fold 2:
            Train N: 134, Test N: 61
            Target Distribution:
            	Train target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            	Test target distribution: {1: 0.8032786885245902, 0: 0.19672131147540983}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 13, Fold 0:
            Train N: 129, Test N: 66
            Target Distribution:
            	Train target distribution: {1: 0.7674418604651163, 0: 0.23255813953488372}
            	Test target distribution: {1: 0.7272727272727273, 0: 0.2727272727272727}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 13, Fold 1:
            Train N: 129, Test N: 66
            Target Distribution:
            	Train target distribution: {1: 0.7674418604651163, 0: 0.23255813953488372}
            	Test target distribution: {1: 0.7272727272727273, 0: 0.2727272727272727}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 13, Fold 2:
            Train N: 132, Test N: 63
            Target Distribution:
            	Train target distribution: {1: 0.7272727272727273, 0: 0.2727272727272727}
            	Test target distribution: {1: 0.8095238095238095, 0: 0.19047619047619047}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 14, Fold 0:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 14, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 14, Fold 2:
            Train N: 134, Test N: 61
            Target Distribution:
            	Train target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            	Test target distribution: {1: 0.8032786885245902, 0: 0.19672131147540983}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 15, Fold 0:
            Train N: 127, Test N: 68
            Target Distribution:
            	Train target distribution: {1: 0.7637795275590551, 0: 0.23622047244094488}
            	Test target distribution: {1: 0.7352941176470589, 0: 0.2647058823529412}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 15, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 15, Fold 2:
            Train N: 135, Test N: 60
            Target Distribution:
            	Train target distribution: {1: 0.7333333333333333, 0: 0.26666666666666666}
            	Test target distribution: {1: 0.8, 0: 0.2}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 16, Fold 0:
            Train N: 127, Test N: 68
            Target Distribution:
            	Train target distribution: {1: 0.7637795275590551, 0: 0.23622047244094488}
            	Test target distribution: {1: 0.7352941176470589, 0: 0.2647058823529412}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 16, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 16, Fold 2:
            Train N: 135, Test N: 60
            Target Distribution:
            	Train target distribution: {1: 0.7333333333333333, 0: 0.26666666666666666}
            	Test target distribution: {1: 0.8, 0: 0.2}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 17, Fold 0:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 17, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 17, Fold 2:
            Train N: 134, Test N: 61
            Target Distribution:
            	Train target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            	Test target distribution: {1: 0.8032786885245902, 0: 0.19672131147540983}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 18, Fold 0:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 18, Fold 1:
            Train N: 127, Test N: 68
            Target Distribution:
            	Train target distribution: {1: 0.7637795275590551, 0: 0.23622047244094488}
            	Test target distribution: {1: 0.7352941176470589, 0: 0.2647058823529412}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 18, Fold 2:
            Train N: 135, Test N: 60
            Target Distribution:
            	Train target distribution: {1: 0.7333333333333333, 0: 0.26666666666666666}
            	Test target distribution: {1: 0.8, 0: 0.2}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

Repeat 19, Fold 0:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 19, Fold 1:
            Train N: 128, Test N: 67
            Target Distribution:
            	Train target distribution: {1: 0.765625, 0: 0.234375}
            	Test target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            Group Distribution patient_id:
            	Train: 21
            	Test: 11

Repeat 19, Fold 2:
            Train N: 134, Test N: 61
            Target Distribution:
            	Train target distribution: {1: 0.7313432835820896, 0: 0.26865671641791045}
            	Test target distribution: {1: 0.8032786885245902, 0: 0.19672131147540983}
            Group Distribution patient_id:
            	Train: 22
            	Test: 10

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to parkinsons_biomedical_voice_measurements/019d738d-db39-7b5b-83dc-664e66da1854

019d738d-db39-7b5b-83dc-664e66da1854
c4908b24e28983026c388d101a00a06845d48aefa666d3dcd393be90657e875b