### Dataset and Task Metadata

In [1]:
from data_foundry.schema import DatasetMetadata, PredictiveMLTaskMetadata

dataset_mold = DatasetMetadata(
    unique_name="nci_pancreatic_cancer",
    dataset_year="2003",
    domain_str="medical & healthcare",
    # Data Source
    dataset_source="GOV Website",
    original_dataset_source_download_link="https://home.ccr.cancer.gov/ncifdaproteomics/ppatterns.asp",
    download_description="""
We download the data to a predefined folder.

mkdir -p local-data-warehouse/nci_pancreatic_cancer && \
wget -P local-data-warehouse/nci_pancreatic_cancer https://home.ccr.cancer.gov/ncifdaproteomics/CancerCellPanINDataBinned.zip && \
unzip local-data-warehouse/nci_pancreatic_cancer/CancerCellPanINDataBinned.zip -d local-data-warehouse/nci_pancreatic_cancer/ && \
rm local-data-warehouse/nci_pancreatic_cancer/CancerCellPanINDataBinned.zip && \
mv local-data-warehouse/nci_pancreatic_cancer/CancerCellPanINDataBinned/02-Control/PanINCTL local-data-warehouse/nci_pancreatic_cancer/ && \
mv local-data-warehouse/nci_pancreatic_cancer/CancerCellPanINDataBinned/03-PanIN local-data-warehouse/nci_pancreatic_cancer && \
rm -r local-data-warehouse/nci_pancreatic_cancer/CancerCellPanINDataBinned
""",
    # References
    academic_reference_bibtex="""@article{Hingorani2003PreinvasiveAI,
  title={Preinvasive and invasive ductal pancreatic cancer and its early detection in the mouse},
  author={Sunil R. Hingorani and Emanuel F. Petricoin and Anirban Maitra and Vinodh Rajapakse and Cynthia King and Michael A. Jacobetz and Sarah Ross and Thomas P. Conrads and Timothy D. Veenstra and Ben A. Hitt and Yoshiya Kawaguchi and David Johann and Lance A. Liotta and Howard C. Crawford and Mary E. Putt and Tyler Jacks and Christopher V. Wright and Ralph H. Hruban and Andrew M. Lowy and David A. Tuveson},
  journal={Cancer Cell},
  year={2003},
  volume={4},
  number={6},
  pages={437-450},
  doi={10.1016/s1535-6108(03)00309-x},
  url={https://doi.org/10.1016/s1535-6108(03)00309-x}
}
""",
    academic_reference_bibtex_key="Hingorani2003PreinvasiveAI",
    license="Public Domain",
    data_tags=["IID"],
    curation_comments="""
        - We merge all samples located in the .csv files into one DataFrame.
        - We label the samples based on name of the folder they are located in: "PanINCTL" translates to healthy patient cases while "03-PanIN" to individuals with a pancreatic cancer.
        - We shuffle the data since it is concatenated in the folders order.
    """,
)
task_mold = PredictiveMLTaskMetadata(
    target_column_name="HasCancer",
    problem_type="binary_classification",
    objective_metric_name="roc_auc",
    stratify_on="HasCancer",
)

## Preprocessing

In [2]:
import os
import pandas as pd

valid_labels = {
    "PanINCTL",
    "03-PanIN"
}

def csv_to_dataframe(file, label):
    """
    Convert each sample from the .csv file to a DataFrame with a label based on the name of the folder it is located in. 
    """
    label_map = {
        "PanINCTL": "No",
        "03-PanIN": "Yes",
    }

    df = pd.read_csv(file).T
    df.reset_index(drop=True, inplace=True)
    df.drop(0, inplace=True)

    target_feature = "HasCancer"
    df.columns = [f"Attribute {i+1}" for i in range(len(df.columns) - 1)] + [target_feature]
    df[target_feature] = label_map.get(label, label)

    return df

r = {}
subdirs = [dirs[0] for dirs in os.walk(dataset_mold.path)][1:]
for subdir in subdirs:
    label = subdir.split("/")[-1]
    _, _, files = next(os.walk(subdir))
    r[label] = [os.path.join(subdir, name) for name in files]

df = pd.concat(
        [csv_to_dataframe(filepath, label) for label in r if label in valid_labels for filepath in r[label]], 
        ignore_index=True
    )
df["HasCancer"] = df["HasCancer"].astype("category")
df = df.sample(frac=1, random_state=99).reset_index(drop=True)

## Data Checks

In [3]:
from data_foundry import dataset_checks
df_head, summary, numeric_stats, cat_stats, target_df = dataset_checks.run_all_checks(
    data=df,
    classification=task_mold.is_classification,
    target_feature=task_mold.target_column_name,
    print_report=False, # In notebook...
)

#### Dataset Overview
Rows: 181
Columns: 6771
Use sampling: False (sample size: 181)
Get row duplicates (staged, merged)...
Using top-10 columns for initial filtering: ['Attribute 5822', 'Attribute 4084', 'Attribute 6016', 'Attribute 5797', 'Attribute 5818', 'Attribute 5806', 'Attribute 5812', 'Attribute 5783', 'Attribute 5784', 'Attribute 5817']
Rows remaining as candidates after top-10 filter: 0 (of 181)

#### Duplicate Report
Total duplicate rows: 0 (0.00% of dataset)
Duplicate rows ignoring target: 0 (0.00% of dataset)
Get column duplicates...
Duplicate columns: 0 (0.00% of columns)

Data quality checks completed.

In [4]:
# Sample Rows
df_head

   Attribute 1  Attribute 2  Attribute 3  Attribute 4  Attribute 5  \
0        468.0        530.0        229.0        483.0        995.0
1         83.0        112.0         73.0        100.0        158.0
2         98.0        178.0         65.0        143.0        239.0
3         60.0         67.0         23.0         61.0         99.0
4        216.0        295.0        127.0        407.0        727.0

   Attribute 6  Attribute 7  Attribute 8  Attribute 9  Attribute 10  \
0        415.0        322.0        676.0        441.0        1345.0
1         80.0         76.0        135.0         76.0         127.0
2         96.0         89.0        171.0         83.0         127.0
3         28.0         47.0         79.0         37.0          59.0
4        178.0        263.0        413.0        236.0         371.0

   Attribute 11  Attribute 12  Attribute 13  Attribute 14  Attribute 15  \
0        1134.0         371.0         483.0        1037.0         373.0
1         131.0          63.0          60.0         153.0          91.0
2         186.0          82.0          66.0         164.0         127.0
3          65.0          38.0          39.0          81.0          34.0
4         386.0         228.0         209.0         338.0         189.0

   Attribute 16  Attribute 17  Attribute 18  Attribute 19  Attribute 20  \
0         226.0         619.0         426.0         175.0         488.0
1          43.0          89.0         110.0          46.0         109.0
2          60.0         129.0         148.0          69.0         113.0
3          33.0          44.0          35.0          37.0          67.0
4         131.0         326.0         221.0         127.0         257.0

   Attribute 21  Attribute 22  Attribute 23  Attribute 24  Attribute 25  \
0         625.0         200.0         428.0         592.0         180.0
1         185.0          51.0          77.0         169.0          50.0
2         230.0          61.0         107.0         207.0          70.0
3          49.0          29.0          68.0          39.0          20.0
4         362.0         115.0         239.0         309.0         121.0

   Attribute 26  Attribute 27  Attribute 28  Attribute 29  Attribute 30  \
0         349.0         581.0         242.0         364.0         590.0
1          73.0         176.0          54.0          82.0         170.0
2          89.0         194.0          59.0         103.0         194.0
3          55.0          71.0          19.0          46.0          81.0
4         224.0         323.0         130.0         200.0         386.0

   Attribute 31  Attribute 32  Attribute 33  Attribute 34  Attribute 35  \
0         274.0         301.0         580.0         323.0         332.0
1          72.0          59.0         169.0          75.0          76.0
2          69.0          85.0         186.0          91.0          99.0
3          24.0          35.0          68.0          25.0          45.0
4         153.0         187.0         342.0         171.0         199.0

   Attribute 36  Attribute 37  Attribute 38  Attribute 39  Attribute 40  \
0         618.0         286.0         283.0         599.0         307.0
1         139.0          66.0          55.0         131.0          69.0
2         187.0          73.0          80.0         151.0          87.0
3          81.0          20.0          31.0          65.0          22.0
4         327.0         157.0         164.0         320.0         171.0

   Attribute 41  Attribute 42  Attribute 43  Attribute 44  Attribute 45  \
0         374.0         522.0         332.0         253.0         525.0
1          73.0         113.0          81.0          57.0         126.0
2          90.0         158.0          93.0          74.0         169.0
3          43.0          60.0          30.0          34.0          63.0
4         178.0         289.0         158.0         149.0         362.0

   Attribute 46  Attribute 47  Attribute 48  Attribute 49  Attribute 50  \
0         341.0         273.0         558.0         376.0         215.0
1          78.0          53.0         108.0         104.0          60.0
2          89.0          66.0         178.0         126.0          51.0
3          35.0          34.0          62.0          33.0          36.0
4         179.0         182.0         303.0         225.0         129.0

   Attribute 51  Attribute 52  Attribute 53  Attribute 54  Attribute 55  \
0         547.0         419.0         256.0         664.0         468.0
1         112.0          99.0          63.0         122.0         102.0
2         145.0         116.0         102.0         165.0         128.0
3          75.0          37.0          45.0          62.0          50.0
4         292.0         220.0         224.0         388.0         239.0

   Attribute 56  Attribute 57  Attribute 58  Attribute 59  Attribute 60  \
0         213.0         560.0         412.0         204.0         538.0
1          48.0         101.0         101.0          62.0         101.0
2          65.0         131.0         116.0          61.0         123.0
3          27.0          62.0          39.0          23.0          51.0
4         163.0         295.0         256.0         171.0         263.0

   Attribute 61  Attribute 62  Attribute 63  Attribute 64  Attribute 65  \
0         408.0         177.0         470.0         411.0         247.0
1         105.0          42.0          87.0         109.0          47.0
2         129.0          61.0         104.0         136.0          63.0
3          38.0          19.0          53.0          47.0          18.0
4         225.0         131.0         223.0         286.0         150.0

   Attribute 66  Attribute 67  Attribute 68  Attribute 69  Attribute 70  \
0         542.0         454.0         184.0         419.0         399.0
1         101.0         125.0          45.0          67.0         123.0
2         119.0         151.0          65.0          95.0         149.0
3          48.0          48.0          18.0          55.0          44.0
4         220.0         233.0         131.0         251.0         239.0

   Attribute 71  Attribute 72  Attribute 73  Attribute 74  Attribute 75  \
0         234.0        1052.0         459.0         243.0         810.0
1          49.0         126.0         103.0          53.0          92.0
2          71.0         187.0         149.0          67.0         134.0
3          24.0          65.0          65.0          24.0          39.0
4         164.0         488.0         309.0         158.0         334.0

   Attribute 76  Attribute 77  Attribute 78  Attribute 79  Attribute 80  \
0         544.0        1055.0       22437.0        1134.0         529.0
1         129.0         119.0        1278.0         131.0          63.0
2         159.0         107.0        1230.0         189.0          82.0
3          55.0          49.0         364.0          56.0          29.0
4         271.0         432.0        4676.0         413.0         293.0

   Attribute 81  Attribute 82  Attribute 83  Attribute 84  Attribute 85  \
0        9540.0         817.0         319.0        2685.0         605.0
1         589.0         135.0          57.0         248.0         139.0
2         570.0         160.0          59.0         243.0         167.0
3         170.0          62.0          39.0          77.0          49.0
4        2146.0         355.0         165.0         775.0         278.0

   Attribute 86  Attribute 87  Attribute 88  Attribute 89  Attribute 90  \
0         220.0         778.0         479.0         202.0         361.0
1          49.0          94.0         144.0          42.0          70.0
2          65.0         102.0         167.0          60.0         102.0
3          30.0          56.0          50.0          27.0          43.0
4         139.0         307.0         254.0         135.0         175.0

   Attribute 91  Attribute 92  Attribute 93  Attribute 94  Attribute 95  \
0         443.0         161.0         284.0         438.0         211.0
1         117.0          39.0          81.0         125.0          49.0
2         163.0          61.0          85.0         175.0          77.0
3          45.0          29.0          42.0          68.0          26.0
4         275.0         135.0         176.0         323.0         140.0

   Attribute 96  Attribute 97  Attribute 98  Attribute 99  Attribute 100  \
0         312.0         493.0         171.0         271.0          465.0
1          86.0         108.0          55.0          75.0          128.0
2          86.0         147.0          60.0          83.0          157.0
3          39.0          42.0          23.0          34.0           69.0
4         203.0         303.0         163.0         209.0          264.0

   Attribute 101  Attribute 102  Attribute 103  Attribute 104  Attribute 105  \
0          217.0          296.0          487.0          222.0          325.0
1           68.0           74.0          114.0           41.0           60.0
2           71.0           94.0          147.0           55.0           80.0
3           26.0           36.0           48.0           24.0           40.0
4          143.0          219.0          335.0          148.0          214.0

   Attribute 106  Attribute 107  Attribute 108  Attribute 109  Attribute 110  \
0          513.0          287.0          354.0          475.0          242.0
1          140.0           65.0           76.0          101.0           55.0
2          159.0           71.0           90.0          187.0           78.0
3           45.0           18.0           38.0           55.0           27.0
4          352.0          167.0          224.0          289.0          157.0

   Attribute 111  Attribute 112  Attribute 113  Attribute 114  Attribute 115  \
0          385.0          532.0          215.0          523.0          566.0
1           73.0          146.0           51.0           84.0          131.0
2           89.0          183.0           63.0           84.0          171.0
3           48.0           61.0           22.0           49.0           68.0
4          237.0          307.0          147.0          273.0          324.0

   Attribute 116  Attribute 117  Attribute 118  Attribute 119  Attribute 120  \
0          204.0          400.0          488.0          223.0         1211.0
1           55.0           82.0          134.0           57.0          249.0
2           59.0           97.0          168.0           72.0          334.0
3           23.0           42.0           48.0           16.0           93.0
4          166.0          256.0          301.0          225.0          993.0

   Attribute 121  Attribute 122  Attribute 123  Attribute 124  Attribute 125  \
0          596.0          234.0          729.0          567.0          412.0
1          146.0           54.0          165.0          129.0           75.0
2          152.0           62.0          213.0          163.0           80.0
3           60.0           34.0           67.0           42.0           41.0
4          366.0          157.0          506.0          359.0          272.0

   Attribute 126  Attribute 127  Attribute 128  Attribute 129  Attribute 130  \
0         5538.0          610.0          323.0         2506.0          565.0
1          322.0          116.0           58.0          156.0          166.0
2          310.0          167.0           85.0          190.0          190.0
3           98.0           73.0           21.0           65.0           77.0
4         1249.0          316.0          169.0          622.0          313.0

   Attribute 131  Attribute 132  Attribute 133  Attribute 134  Attribute 135  \
0          244.0         1386.0          473.0          225.0          649.0
1           60.0          114.0          146.0           61.0           82.0
2           63.0          141.0          160.0           78.0           98.0
3           28.0           51.0           48.0           22.0           51.0
4          157.0          447.0          286.0          151.0          294.0

   Attribute 136  Attribute 137  Attribute 138  Attribute 139  Attribute 140  \
0          423.0          252.0         1401.0          930.0          286.0
1          118.0           69.0          279.0          159.0           75.0
2          153.0           98.0          403.0          219.0           99.0
3           56.0           31.0          105.0           88.0           31.0
4          280.0          359.0         1412.0          633.0          280.0

   Attribute 141  Attribute 142  Attribute 143  Attribute 144  Attribute 145  \
0          927.0          607.0          233.0          753.0          435.0
1          160.0          138.0           76.0          125.0          111.0
2          255.0          162.0           70.0          207.0          130.0
3           57.0           55.0           24.0           57.0           46.0
4          876.0          423.0          272.0          567.0          300.0

   Attribute 146  Attribute 147  Attribute 148  Attribute 149  Attribute 150  \
0          187.0          526.0          350.0          176.0          427.0
1           59.0           93.0           91.0           47.0          101.0
2           61.0          127.0          109.0           73.0          116.0
3           37.0           43.0           57.0           27.0           58.0
4          208.0          365.0          260.0          175.0          272.0

   Attribute 151  Attribute 152  Attribute 153  Attribute 154  Attribute 155  \
0          384.0          178.0          377.0          338.0          176.0
1          105.0           50.0           82.0           80.0           50.0
2          139.0           79.0          128.0          112.0           51.0
3           38.0           23.0           51.0           42.0           28.0
4          234.0          160.0          229.0          252.0          156.0

   Attribute 156  Attribute 157  Attribute 158  Attribute 159  Attribute 160  \
0          439.0          323.0          160.0          423.0          281.0
1           85.0           89.0           46.0          118.0           73.0
2          117.0          104.0           57.0          148.0           90.0
3           49.0           31.0           29.0           54.0           35.0
4          259.0          218.0          154.0          304.0          234.0

   Attribute 161  Attribute 162  Attribute 163  Attribute 164  Attribute 165  \
0          238.0          441.0          280.0          204.0          466.0
1           50.0          113.0           70.0           38.0          113.0
2           60.0          151.0           90.0           65.0          137.0
3           34.0           43.0           24.0           45.0           56.0
4          197.0          309.0          190.0          181.0          349.0

   Attribute 166  Attribute 167  Attribute 168  Attribute 169  Attribute 170  \
0          248.0          730.0          568.0          198.0          478.0
1           79.0          190.0          127.0           58.0          131.0
2           73.0          253.0          176.0           79.0          163.0
3           44.0           72.0           71.0           27.0           59.0
4          215.0          532.0          385.0          194.0          343.0

   Attribute 171  Attribute 172  Attribute 173  Attribute 174  Attribute 175  \
0          503.0          234.0          793.0          459.0          232.0
1          110.0           57.0          122.0           95.0           49.0
2          160.0           73.0          124.0          173.0           46.0
3           52.0           24.0           64.0           67.0           28.0
4          357.0          185.0          325.0          330.0          155.0

   Attribute 176  Attribute 177  Attribute 178  Attribute 179  Attribute 180  \
0          541.0          510.0          220.0          577.0          430.0
1          102.0          133.0           60.0          116.0          111.0
2           97.0          166.0           75.0          121.0          175.0
3           47.0           71.0           31.0           59.0           51.0
4          297.0          311.0          170.0          338.0          258.0

   Attribute 181  Attribute 182  Attribute 183  Attribute 184  Attribute 185  \
0          167.0          448.0          438.0          537.0         1789.0
1           71.0           83.0          142.0          292.0          564.0
2           71.0          111.0          140.0          435.0          876.0
3           23.0           45.0           47.0          142.0          151.0
4          161.0          259.0          284.0         1325.0         2132.0

   Attribute 186  Attribute 187  Attribute 188  Attribute 189  Attribute 190  \
0          531.0          473.0          898.0          377.0          412.0
1          111.0          202.0          235.0          108.0          130.0
2          146.0          290.0          345.0          165.0          180.0
3           49.0           95.0           68.0           42.0           53.0
4          342.0          857.0          888.0          282.0          510.0

   Attribute 191  Attribute 192  Attribute 193  Attribute 194  Attribute 195  \
0          654.0          302.0          353.0          448.0          295.0
1          117.0           99.0          103.0          112.0           80.0
2          178.0          125.0          115.0          134.0           97.0
3           59.0           31.0           32.0           52.0           22.0
4          363.0          246.0          253.0          315.0          204.0

   Attribute 196  Attribute 197  Attribute 198  Attribute 199  Attribute 200  \
0          328.0          457.0          275.0          244.0          474.0
1           76.0          107.0           70.0           66.0          135.0
2          105.0          141.0           85.0           56.0          185.0
3           44.0           71.0           42.0           32.0           71.0
4          259.0          331.0          173.0          200.0          310.0

   Attribute 201  Attribute 202  Attribute 203  Attribute 204  Attribute 205  \
0          220.0          611.0          491.0          194.0          374.0
1           60.0          127.0          123.0           48.0           91.0
2           55.0          179.0          150.0           65.0          118.0
3           29.0           69.0           54.0           25.0           49.0
4          186.0          492.0          277.0          145.0          330.0

   Attribute 206  Attribute 207  Attribute 208  Attribute 209  Attribute 210  \
0          422.0          189.0          320.0          392.0          158.0
1          111.0           44.0           73.0           99.0           44.0
2          133.0           59.0          101.0          116.0           58.0
3           35.0           27.0           54.0           31.0           36.0
4          261.0          171.0          240.0          268.0          163.0

   Attribute 211  Attribute 212  Attribute 213  Attribute 214  Attribute 215  \
0          354.0          356.0          187.0          408.0          278.0
1           66.0           96.0           65.0           64.0           71.0
2           92.0          130.0           72.0          125.0           99.0
3           49.0           41.0           26.0           41.0           42.0
4          206.0          245.0          161.0          253.0          199.0

   Attribute 216  Attribute 217  Attribute 218  Attribute 219  Attribute 220  \
0          184.0          362.0          291.0          255.0          442.0
1           53.0           93.0           61.0           86.0          108.0
2           60.0          132.0           85.0           92.0          171.0
3           27.0           48.0           39.0           50.0           55.0
4          158.0          287.0          182.0          177.0          290.0

   Attribute 221  Attribute 222  Attribute 223  Attribute 224  Attribute 225  \

In [5]:
# Feature Summary
summary

,index,dtype,n_missing,pct_missing,n_unique,examples
0,HasCancer,category,0.0,0.0,2.0,"No, Yes"
1,Attribute 1,float64,0.0,0.0,151.0,"96.0, 321.0, 141.0, 233.0, 221.0, 182.0, 105.0, 187.0, 151.0, 134.0"
2,Attribute 2,float64,0.0,0.0,151.0,"313.0, 165.0, 404.0, 572.0, 172.0, 234.0, 273.0, 463.0, 671.0, 395.0"
3,Attribute 3,float64,0.0,0.0,137.0,"61.0, 50.0, 139.0, 226.0, 105.0, 163.0, 73.0, 43.0, 202.0, 270.0"
4,Attribute 4,float64,0.0,0.0,156.0,"171.0, 259.0, 306.0, 453.0, 205.0, 561.0, 769.0, 518.0, 475.0, 699.0"
5,Attribute 5,float64,0.0,0.0,169.0,"716.0, 340.0, 234.0, 481.0, 295.0, 683.0, 413.0, 642.0, 250.0, 300.0"
6,Attribute 6,float64,0.0,0.0,155.0,"77.0, 139.0, 316.0, 67.0, 78.0, 434.0, 148.0, 43.0, 85.0, 134.0"
7,Attribute 7,float64,0.0,0.0,149.0,"342.0, 146.0, 293.0, 134.0, 111.0, 442.0, 119.0, 129.0, 154.0, 144.0"
8,Attribute 8,float64,0.0,0.0,162.0,"518.0, 206.0, 203.0, 264.0, 658.0, 284.0, 342.0, 442.0, 249.0, 152.0"
9,Attribute 9,float64,0.0,0.0,151.0,"72.0, 62.0, 79.0, 164.0, 179.0, 148.0, 139.0, 96.0, 321.0, 249.0"
10,Attribute 10,float64,0.0,0.0,163.0,"266.0, 167.0, 466.0, 211.0, 369.0, 375.0, 213.0, 233.0, 483.0, 226.0"
11,Attribute 11,float64,0.0,0.0,160.0,"258.0, 219.0, 260.0, 278.0, 176.0, 406.0, 558.0, 1000.0, 508.0, 782.0"
12,Attribute 12,float64,0.0,0.0,145.0,"82.0, 423.0, 167.0, 288.0, 169.0, 333.0, 371.0, 141.0, 139.0, 155.0"
13,Attribute 13,float64,0.0,0.0,146.0,"101.0, 62.0, 368.0, 86.0, 212.0, 326.0, 203.0, 166.0, 289.0, 142.0"
14,Attribute 14,float64,0.0,0.0,158.0,"342.0, 250.0, 199.0, 181.0, 201.0, 488.0, 399.0, 480.0, 173.0, 171.0"
15,Attribute 15,float64,0.0,0.0,153.0,"96.0, 126.0, 80.0, 275.0, 86.0, 270.0, 88.0, 408.0, 359.0, 262.0"
16,Attribute 16,float64,0.0,0.0,135.0,"211.0, 68.0, 110.0, 92.0, 84.0, 146.0, 164.0, 226.0, 83.0, 139.0"
17,Attribute 17,float64,0.0,0.0,155.0,"557.0, 193.0, 247.0, 450.0, 468.0, 201.0, 473.0, 150.0, 199.0, 210.0"
18,Attribute 18,float64,0.0,0.0,158.0,"119.0, 109.0, 127.0, 275.0, 437.0, 133.0, 188.0, 513.0, 122.0, 93.0"
19,Attribute 19,float64,0.0,0.0,116.0,"163.0, 66.0, 181.0, 150.0, 74.0, 50.0, 89.0, 45.0, 86.0, 164.0"
20,Attribute 20,float64,0.0,0.0,154.0,"151.0, 149.0, 556.0, 240.0, 202.0, 195.0, 192.0, 155.0, 486.0, 246.0"
21,Attribute 21,float64,0.0,0.0,164.0,"720.0, 120.0, 254.0, 157.0, 125.0, 343.0, 196.0, 551.0, 166.0, 188.0"
22,Attribute 22,float64,0.0,0.0,128.0,"42.0, 56.0, 229.0, 68.0, 106.0, 108.0, 77.0, 167.0, 195.0, 182.0"
23,Attribute 23,float64,0.0,0.0,150.0,"385.0, 168.0, 380.0, 462.0, 226.0, 181.0, 426.0, 270.0, 144.0, 330.0"
24,Attribute 24,float64,0.0,0.0,174.0,"140.0, 122.0, 519.0, 355.0, 385.0, 183.0, 110.0, 831.0, 92.0, 833.0"
25,Attribute 25,float64,0.0,0.0,123.0,"109.0, 191.0, 180.0, 210.0, 132.0, 108.0, 52.0, 48.0, 55.0, 115.0"
26,Attribute 26,float64,0.0,0.0,137.0,"113.0, 159.0, 307.0, 101.0, 172.0, 175.0, 132.0, 151.0, 142.0, 204.0"
27,Attribute 27,float64,0.0,0.0,158.0,"139.0, 194.0, 539.0, 134.0, 335.0, 298.0, 162.0, 140.0, 117.0, 824.0"
28,Attribute 28,float64,0.0,0.0,140.0,"175.0, 61.0, 48.0, 54.0, 51.0, 47.0, 254.0, 64.0, 220.0, 240.0"
29,Attribute 29,float64,0.0,0.0,153.0,"136.0, 98.0, 113.0, 219.0, 312.0, 370.0, 99.0, 263.0, 474.0, 469.0"
30,Attribute 30,float64,0.0,0.0,159.0,"137.0, 273.0, 673.0, 212.0, 419.0, 232.0, 216.0, 497.0, 180.0, 808.0"
31,Attribute 31,float64,0.0,0.0,135.0,"153.0, 70.0, 71.0, 63.0, 58.0, 28.0, 182.0, 274.0, 285.0, 214.0"
32,Attribute 32,float64,0.0,0.0,142.0,"138.0, 115.0, 367.0, 241.0, 112.0, 121.0, 231.0, 83.0, 132.0, 266.0"
33,Attribute 33,float64,0.0,0.0,163.0,"129.0, 187.0, 432.0, 191.0, 271.0, 710.0, 308.0, 157.0, 209.0, 95.0"
34,Attribute 34,float64,0.0,0.0,147.0,"82.0, 71.0, 468.0, 159.0, 74.0, 118.0, 192.0, 94.0, 234.0, 154.0"
35,Attribute 35,float64,0.0,0.0,142.0,"161.0, 283.0, 99.0, 121.0, 139.0, 119.0, 438.0, 341.0, 277.0, 178.0"
36,Attribute 36,float64,0.0,0.0,157.0,"222.0, 188.0, 326.0, 223.0, 166.0, 266.0, 407.0, 406.0, 126.0, 281.0"
37,Attribute 37,float64,0.0,0.0,140.0,"63.0, 143.0, 73.0, 207.0, 58.0, 281.0, 132.0, 54.0, 55.0, 346.0"
38,Attribute 38,float64,0.0,0.0,132.0,"94.0, 213.0, 124.0, 90.0, 148.0, 60.0, 84.0, 113.0, 246.0, 138.0"
39,Attribute 39,float64,0.0,0.0,160.0,"171.0, 163.0, 577.0, 474.0, 394.0, 255.0, 292.0, 415.0, 576.0, 79.0"
40,Attribute 40,float64,0.0,0.0,145.0,"60.0, 97.0, 136.0, 147.0, 156.0, 53.0, 138.0, 160.0, 295.0, 344.0"
41,Attribute 41,float64,0.0,0.0,139.0,"248.0, 85.0, 126.0, 260.0, 157.0, 124.0, 152.0, 154.0, 374.0, 104.0"
42,Attribute 42,float64,0.0,0.0,148.0,"299.0, 200.0, 190.0, 560.0, 269.0, 152.0, 377.0, 231.0, 281.0, 202.0"
43,Attribute 43,float64,0.0,0.0,140.0,"132.0, 74.0, 76.0, 67.0, 65.0, 155.0, 182.0, 73.0, 219.0, 77.0"
44,Attribute 44,float64,0.0,0.0,131.0,"99.0, 201.0, 84.0, 210.0, 91.0, 181.0, 68.0, 59.0, 113.0, 160.0"
45,Attribute 45,float64,0.0,0.0,152.0,"169.0, 172.0, 193.0, 154.0, 146.0, 270.0, 196.0, 265.0, 173.0, 544.0"
46,Attribute 46,float64,0.0,0.0,149.0,"77.0, 85.0, 146.0, 149.0, 75.0, 76.0, 152.0, 167.0, 454.0, 233.0"
47,Attribute 47,float64,0.0,0.0,134.0,"65.0, 109.0, 90.0, 197.0, 136.0, 116.0, 53.0, 242.0, 333.0, 113.0"
48,Attribute 48,float64,0.0,0.0,150.0,"161.0, 176.0, 181.0, 536.0, 224.0, 602.0, 308.0, 204.0, 208.0, 189.0"
49,Attribute 49,float64,0.0,0.0,145.0,"219.0, 303.0, 103.0, 234.0, 84.0, 402.0, 107.0, 87.0, 112.0, 427.0"
50,Attribute 50,float64,0.0,0.0,123.0,"101.0, 87.0, 50.0, 55.0, 90.0, 117.0, 167.0, 84.0, 112.0, 89.0"
51,Attribute 51,float64,0.0,0.0,147.0,"164.0, 172.0, 415.0, 234.0, 421.0, 379.0, 352.0, 186.0, 628.0, 453.0"
52,Attribute 52,float64,0.0,0.0,152.0,"111.0, 338.0, 332.0, 112.0, 255.0, 219.0, 57.0, 193.0, 419.0, 179.0"
53,Attribute 53,float64,0.0,0.0,148.0,"276.0, 175.0, 142.0, 172.0, 130.0, 258.0, 199.0, 98.0, 144.0, 230.0"
54,Attribute 54,float64,0.0,0.0,168.0,"222.0, 664.0, 307.0, 554.0, 273.0, 317.0, 226.0, 394.0, 293.0, 341.0"
55,Attribute 55,float64,0.0,0.0,149.0,"128.0, 116.0, 126.0, 179.0, 139.0, 102.0, 402.0, 143.0, 133.0, 214.0"
56,Attribute 56,float64,0.0,0.0,139.0,"81.0, 108.0, 65.0, 172.0, 185.0, 125.0, 180.0, 71.0, 186.0, 97.0"
57,Attribute 57,float64,0.0,0.0,160.0,"451.0, 142.0, 101.0, 257.0, 145.0, 290.0, 641.0, 314.0, 398.0, 297.0"
58,Attribute 58,float64,0.0,0.0,151.0,"118.0, 116.0, 115.0, 380.0, 177.0, 96.0, 192.0, 119.0, 207.0, 60.0"
59,Attribute 59,float64,0.0,0.0,125.0,"175.0, 135.0, 82.0, 243.0, 189.0, 196.0, 106.0, 88.0, 109.0, 97.0"
60,Attribute 60,float64,0.0,0.0,152.0,"211.0, 123.0, 234.0, 382.0, 225.0, 538.0, 308.0, 54.0, 406.0, 110.0"
61,Attribute 61,float64,0.0,0.0,145.0,"122.0, 104.0, 202.0, 119.0, 345.0, 180.0, 201.0, 106.0, 296.0, 127.0"
62,Attribute 62,float64,0.0,0.0,119.0,"74.0, 61.0, 131.0, 66.0, 85.0, 177.0, 60.0, 195.0, 88.0, 126.0"
63,Attribute 63,float64,0.0,0.0,147.0,"129.0, 123.0, 134.0, 155.0, 95.0, 307.0, 223.0, 191.0, 141.0, 200.0"
64,Attribute 64,float64,0.0,0.0,152.0,"123.0, 108.0, 101.0, 411.0, 444.0, 497.0, 364.0, 114.0, 237.0, 216.0"
65,Attribute 65,float64,0.0,0.0,130.0,"141.0, 61.0, 226.0, 56.0, 74.0, 108.0, 69.0, 174.0, 122.0, 66.0"
66,Attribute 66,float64,0.0,0.0,151.0,"319.0, 151.0, 370.0, 280.0, 122.0, 384.0, 214.0, 577.0, 160.0, 535.0"
67,Attribute 67,float64,0.0,0.0,144.0,"131.0, 108.0, 157.0, 152.0, 366.0, 228.0, 334.0, 170.0, 396.0, 134.0"
68,Attribute 68,float64,0.0,0.0,129.0,"163.0, 40.0, 81.0, 54.0, 70.0, 219.0, 67.0, 89.0, 78.0, 172.0"
69,Attribute 69,float64,0.0,0.0,154.0,"185.0, 323.0, 175.0, 98.0, 226.0, 117.0, 166.0, 290.0, 150.0, 370.0"
70,Attribute 70,float64,0.0,0.0,144.0,"113.0, 221.0, 134.0, 149.0, 241.0, 200.0, 177.0, 159.0, 314.0, 293.0"
71,Attribute 71,float64,0.0,0.0,130.0,"81.0, 86.0, 71.0, 99.0, 192.0, 184.0, 240.0, 49.0, 221.0, 218.0"
72,Attribute 72,float64,0.0,0.0,170.0,"69.0, 120.0, 273.0, 338.0, 268.0, 213.0, 308.0, 934.0, 289.0, 311.0"
73,Attribute 73,float64,0.0,0.0,155.0,"233.0, 139.0, 382.0, 234.0, 225.0, 342.0, 179.0, 281.0, 203.0, 147.0"
74,Attribute 74,float64,0.0,0.0,135.0,"62.0, 63.0, 115.0, 184.0, 162.0, 53.0, 136.0, 71.0, 125.0, 67.0"
75,Attribute 75,float64,0.0,0.0,161.0,"128.0, 541.0, 177.0, 203.0, 597.0, 474.0, 199.0, 265.0, 208.0, 226.0"
76,Attribute 76,float64,0.0,0.0,155.0,"271.0, 157.0, 396.0, 451.0, 175.0, 129.0, 142.0, 449.0, 119.0, 531.0"
77,Attribute 77,float64,0.0,0.0,162.0,"139.0, 454.0, 202.0, 317.0, 241.0, 417.0, 203.0, 340.0, 154.0, 120.0"
78,Attribute 78,float64,0.0,0.0,181.0,"22437.0, 451.0, 6027.0, 2003.0, 7285.0, 10121.0, 5487.0, 17228.0, 1430.0, 2591.0"
79,Attribute 79,float64,0.0,0.0,161.0,"386.0, 581.0, 262.0, 284.0, 535.0, 209.0, 254.0, 345.0, 198.0, 320.0"
80,Attribute 80,float64,0.0,0.0,153.0,"250.0, 148.0, 310.0, 158.0, 126.0, 498.0, 132.0, 285.0, 147.0, 223.0"
81,Attribute 81,float64,0.0,0.0,178.0,"7695.0, 170.0, 1820.0, 9540.0, 2599.0, 1037.0, 3171.0, 4384.0, 2456.0, 7428.0"
82,Attribute 82,float64,0.0,0.0,157.0,"257.0, 160.0, 446.0, 301.0, 159.0, 498.0, 220.0, 513.0, 139.0, 278.0"
83,Attribute 83,float64,0.0,0.0,134.0,"101.0, 136.0, 44.0, 104.0, 219.0, 80.0, 224.0, 166.0, 92.0, 223.0"
84,Attribute 84,float64,0.0,0.0,174.0,"243.0, 407.0, 1369.0, 679.0, 636.0, 340.0, 5004.0, 556.0, 858.0, 366.0"
85,Attribute 85,float64,0.0,0.0,157.0,"212.0, 220.0, 250.0, 501.0, 244.0, 164.0, 291.0, 208.0, 267.0, 236.0"
86,Attribute 86,float64,0.0,0.0,132.0,"58.0, 156.0, 65.0, 109.0, 94.0, 64.0, 82.0, 110.0, 95.0, 138.0"
87,Attribute 87,float64,0.0,0.0,163.0,"205.0, 166.0, 180.0, 152.0, 297.0, 331.0, 117.0, 539.0, 225.0, 489.0"
88,Attribute 88,float64,0.0,0.0,150.0,"126.0, 756.0, 121.0, 177.0, 583.0, 343.0, 150.0, 231.0, 262.0, 285.0"
89,Attribute 89,float64,0.0,0.0,129.0,"59.0, 50.0, 42.0, 79.0, 122.0, 193.0, 135.0, 45.0, 273.0, 241.0"
90,Attribute 90,float64,0.0,0.0,147.0,"110.0, 102.0, 137.0, 91.0, 220.0, 59.0, 215.0, 259.0, 104.0, 111.0"
91,Attribute 91,float64,0.0,0.0,154.0,"500.0, 127.0, 146.0, 170.0, 540.0, 266.0, 317.0, 214.0, 228.0, 313.0"
92,Attribute 92,float64,0.0,0.0,123.0,"92.0, 73.0, 48.0, 154.0, 80.0, 54.0, 115.0, 39.0, 53.0, 128.0"
93,Attribute 93,float64,0.0,0.0,143.0,"109.0, 254.0, 93.0, 219.0, 49.0, 117.0, 209.0, 224.0, 150.0, 300.0"
94,Attribute 94,float64,0.0,0.0,149.0,"479.0, 501.0, 349.0, 164.0, 636.0, 169.0, 389.0, 173.0, 227.0, 265.0"
95,Attribute 95,float64,0.0,0.0,125.0,"49.0, 77.0, 211.0, 96.0, 99.0, 50.0, 120.0, 53.0, 153.0, 203.0"
96,Attribute 96,float64,0.0,0.0,141.0,"345.0, 132.0, 178.0, 393.0, 322.0, 251.0, 248.0, 273.0, 122.0, 259.0"
97,Attribute 97,float64,0.0,0.0,150.0,"183.0, 192.0, 181.0, 166.0, 148.0, 152.0, 231.0, 313.0, 354.0, 312.0"
98,Attribute 98,float64,0.0,0.0,127.0,"42.0, 196.0, 67.0, 92.0, 60.0, 183.0, 44.0, 89.0, 39.0, 78.0"
99,Attribute 99,float64,0.0,0.0,146.0,"153.0, 103.0, 111.0, 139.0, 75.0, 84.0, 330.0, 279.0, 268.0, 242.0"
100,Attribute 100,float64,0.0,0.0,159.0,"193.0, 121.0, 363.0, 163.0, 515.0, 161.0, 181.0, 406.0, 160.0, 346.0"
101,Attribute 101,float64,0.0,0.0,142.0,"56.0, 104.0, 50.0, 126.0, 73.0, 171.0, 88.0, 85.0, 115.0, 54.0"
102,Attribute 102,float64,0.0,0.0,147.0,"108.0, 162.0, 268.0, 184.0, 307.0, 154.0, 171.0, 288.0, 408.0, 191.0"
103,Attribute 103,float64,0.0,0.0,158.0,"249.0, 485.0, 532.0, 165.0, 488.0, 415.0, 186.0, 179.0, 400.0, 231.0"
104,Attribute 104,float64,0.0,0.0,130.0,"222.0, 85.0, 47.0, 78.0, 81.0, 92.0, 183.0, 59.0, 54.0, 52.0"
105,Attribute 105,float64,0.0,0.0,137.0,"276.0, 117.0, 241.0, 115.0, 123.0, 126.0, 57.0, 266.0, 162.0, 171.0"
106,Attribute 106,float64,0.0,0.0,157.0,"183.0, 165.0, 178.0, 607.0, 197.0, 589.0, 233.0, 488.0, 234.0, 264.0"
107,Attribute 107,float64,0.0,0.0,141.0,"71.0, 112.0, 66.0, 318.0, 287.0, 184.0, 50.0, 80.0, 363.0, 48.0"
108,Attribute 108,float64,0.0,0.0,148.0,"116.0, 232.0, 121.0, 340.0, 126.0, 269.0, 124.0, 175.0, 177.0, 85.0"
109,Attribute 109,float64,0.0,0.0,150.0,"208.0, 224.0, 260.0, 145.0, 475.0, 446.0, 172.0, 444.0, 593.0, 313.0"
110,Attribute 110,float64,0.0,0.0,131.0,"169.0, 78.0, 282.0, 51.0, 100.0, 87.0, 75.0, 160.0, 252.0, 42.0"
111,Attribute 111,float64,0.0,0.0,140.0,"129.0, 120.0, 270.0, 93.0, 245.0, 151.0, 153.0, 145.0, 60.0, 126.0"
112,Attribute 112,float64,0.0,0.0,160.0,"179.0, 477.0, 149.0, 422.0, 511.0, 599.0, 415.0, 529.0, 208.0, 219.0"
113,Attribute 113,float64,0.0,0.0,121.0,"63.0, 53.0, 51.0, 92.0, 257.0, 100.0, 74.0, 59.0, 158.0, 234.0"
114,Attribute 114,float64,0.0,0.0,150.0,"211.0, 183.0, 179.0, 186.0, 167.0, 137.0, 156.0, 253.0, 165.0, 151.0"
115,Attribute 115,float64,0.0,0.0,158.0,"220.0, 137.0, 230.0, 334.0, 361.0, 187.0, 122.0, 194.0, 153.0, 160.0"
116,Attribute 116,float64,0.0,0.0,125.0,"61.0, 50.0, 93.0, 87.0, 102.0, 68.0, 209.0, 192.0, 53.0, 65.0"
117,Attribute 117,float64,0.0,0.0,147.0,"89.0, 180.0, 137.0, 96.0, 101.0, 167.0, 134.0, 120.0, 295.0, 59.0"
118,Attribute 118,float64,0.0,0.0,152.0,"214.0, 478.0, 158.0, 194.0, 298.0, 176.0, 558.0, 145.0, 295.0, 402.0"
119,Attribute 119,float64,0.0,0.0,139.0,"89.0, 271.0, 72.0, 213.0, 57.0, 144.0, 223.0, 119.0, 84.0, 254.0"
120,Attribute 120,float64,0.0,0.0,177.0,"895.0, 93.0, 583.0, 1606.0, 726.0, 1008.0, 528.0, 939.0, 2633.0, 786.0"
121,Attribute 121,float64,0.0,0.0,155.0,"323.0, 150.0, 146.0, 195.0, 161.0, 125.0, 173.0, 155.0, 167.0, 339.0"
122,Attribute 122,float64,0.0,0.0,132.0,"54.0, 86.0, 77.0, 69.0, 61.0, 78.0, 189.0, 138.0, 102.0, 133.0"
123,Attribute 123,float64,0.0,0.0,166.0,"425.0, 727.0, 277.0, 385.0, 599.0, 319.0, 1599.0, 1023.0, 525.0, 413.0"
124,Attribute 124,float64,0.0,0.0,158.0,"166.0, 158.0, 305.0, 244.0, 345.0, 209.0, 200.0, 164.0, 105.0, 142.0"
125,Attribute 125,float64,0.0,0.0,145.0,"87.0, 93.0, 149.0, 154.0, 77.0, 148.0, 412.0, 122.0, 94.0, 166.0"
126,Attribute 126,float64,0.0,0.0,175.0,"514.0, 1329.0, 458.0, 260.0, 1687.0, 1284.0, 2108.0, 1193.0, 4113.0, 372.0"
127,Attribute 127,float64,0.0,0.0,159.0,"210.0, 400.0, 219.0, 426.0, 166.0, 351.0, 399.0, 137.0, 465.0, 142.0"
128,Attribute 128,float64,0.0,0.0,132.0,"89.0, 125.0, 77.0, 70.0, 120.0, 201.0, 65.0, 132.0, 204.0, 119.0"
129,Attribute 129,float64,0.0,0.0,172.0,"288.0, 254.0, 162.0, 534.0, 328.0, 91.0, 545.0, 343.0, 189.0, 991.0"
130,Attribute 130,float64,0.0,0.0,158.0,"215.0, 166.0, 221.0, 78.0, 232.0, 152.0, 247.0, 504.0, 266.0, 475.0"
131,Attribute 131,float64,0.0,0.0,140.0,"115.0, 186.0, 138.0, 200.0, 85.0, 82.0, 99.0, 62.0, 95.0, 69.0"
132,Attribute 132,float64,0.0,0.0,165.0,"215.0, 429.0, 541.0, 322.0, 590.0, 382.0, 218.0, 287.0, 138.0, 775.0"
133,Attribute 133,float64,0.0,0.0,150.0,"183.0, 240.0, 374.0, 174.0, 205.0, 399.0, 446.0, 190.0, 370.0, 195.0"
134,Attribute 134,float64,0.0,0.0,132.0,"61.0, 162.0, 67.0, 108.0, 58.0, 63.0, 70.0, 80.0, 52.0, 94.0"
135,Attribute 135,float64,0.0,0.0,154.0,"156.0, 169.0, 334.0, 193.0, 181.0, 281.0, 58.0, 125.0, 200.0, 387.0"
136,Attribute 136,float64,0.0,0.0,157.0,"150.0, 118.0, 234.0, 147.0, 260.0, 426.0, 354.0, 119.0, 435.0, 226.0"
137,Attribute 137,float64,0.0,0.0,153.0,"428.0, 79.0, 404.0, 537.0, 151.0, 642.0, 311.0, 140.0, 206.0, 110.0"
138,Attribute 138,float64,0.0,0.0,174.0,"659.0, 976.0, 272.0, 2203.0, 274.0, 371.0, 653.0, 225.0, 2201.0, 479.0"
139,Attribute 139,float64,0.0,0.0,168.0,"219.0, 338.0, 606.0, 815.0, 224.0, 257.0, 155.0, 169.0, 286.0, 693.0"
140,Attribute 140,float64,0.0,0.0,153.0,"85.0, 170.0, 84.0, 191.0, 379.0, 78.0, 51.0, 241.0, 143.0, 87.0"
141,Attribute 141,float64,0.0,0.0,175.0,"196.0, 276.0, 374.0, 210.0, 394.0, 600.0, 604.0, 322.0, 440.0, 2805.0"
142,Attribute 142,float64,0.0,0.0,167.0,"163.0, 178.0, 490.0, 273.0, 336.0, 401.0, 421.0, 93.0, 243.0, 138.0"
143,Attribute 143,float64,0.0,0.0,147.0,"115.0, 214.0, 122.0, 67.0, 61.0, 367.0, 212.0, 105.0, 172.0, 210.0"
144,Attribute 144,float64,0.0,0.0,169.0,"478.0, 860.0, 276.0, 365.0, 502.0, 863.0, 220.0, 804.0, 187.0, 137.0"
145,Attribute 145,float64,0.0,0.0,151.0,"145.0, 195.0, 473.0, 256.0, 162.0, 175.0, 113.0, 155.0, 197.0, 322.0"
146,Attribute 146,float64,0.0,0.0,140.0,"86.0, 156.0, 61.0, 208.0, 161.0, 59.0, 106.0, 187.0, 67.0, 190.0"
147,Attribute 147,float64,0.0,0.0,163.0,"149.0, 199.0, 162.0, 626.0, 574.0, 259.0, 508.0, 218.0, 156.0, 183.0"
148,Attribute 148,float64,0.0,0.0,149.0,"186.0, 109.0, 296.0, 132.0, 117.0, 90.0, 183.0, 257.0, 479.0, 314.0"
149,Attribute 149,float64,0.0,0.0,124.0,"73.0, 119.0, 132.0, 149.0, 175.0, 64.0, 93.0, 67.0, 163.0, 56.0"
150,Attribute 150,float64,0.0,0.0,153.0,"105.0, 127.0, 139.0, 168.0, 427.0, 307.0, 145.0, 247.0, 124.0, 219.0"
151,Attribute 151,float64,0.0,0.0,152.0,"75.0, 397.0, 184.0, 194.0, 100.0, 182.0, 163.0, 333.0, 105.0, 126.0"
152,Attribute 152,float64,0.0,0.0,126.0,"56.0, 97.0, 44.0, 74.0, 120.0, 55.0, 80.0, 72.0, 53.0, 96.0"
153,Attribute 153,float64,0.0,0.0,156.0,"182.0, 161.0, 448.0, 157.0, 135.0, 108.0, 132.0, 235.0, 185.0, 124.0"
154,Attribute 154,float64,0.0,0.0,147.0,"183.0, 142.0, 164.0, 376.0, 370.0, 166.0, 108.0, 172.0, 104.0, 92.0"
155,Attribute 155,float64,0.0,0.0,121.0,"169.0, 88.0, 116.0, 87.0, 124.0, 102.0, 67.0, 135.0, 81.0, 80.0"
156,Attribute 156,float64,0.0,0.0,142.0,"185.0, 228.0, 117.0, 127.0, 226.0, 160.0, 198.0, 554.0, 360.0, 191.0"
157,Attribute 157,float64,0.0,0.0,137.0,"89.0, 101.0, 87.0, 242.0, 221.0, 93.0, 115.0, 76.0, 146.0, 393.0"
158,Attribute 158,float64,0.0,0.0,115.0,"75.0, 61.0, 73.0, 203.0, 131.0, 159.0, 109.0, 70.0, 72.0, 89.0"
159,Attribute 159,float64,0.0,0.0,151.0,"143.0, 204.0, 419.0, 157.0, 372.0, 325.0, 136.0, 122.0, 116.0, 175.0"
160,Attribute 160,float64,0.0,0.0,140.0,"72.0, 86.0, 84.0, 87.0, 68.0, 182.0, 158.0, 104.0, 250.0, 269.0"
161,Attribute 161,float64,0.0,0.0,128.0,"105.0, 71.0, 98.0, 47.0, 173.0, 195.0, 126.0, 53.0, 121.0, 197.0"
162,Attribute 162,float64,0.0,0.0,152.0,"167.0, 160.0, 159.0, 212.0, 188.0, 307.0, 181.0, 353.0, 495.0, 129.0"
163,Attribute 163,float64,0.0,0.0,142.0,"153.0, 152.0, 99.0, 230.0, 261.0, 97.0, 179.0, 271.0, 81.0, 129.0"
164,Attribute 164,float64,0.0,0.0,124.0,"77.0, 84.0, 125.0, 183.0, 79.0, 98.0, 118.0, 82.0, 244.0, 114.0"
165,Attribute 165,float64,0.0,0.0,157.0,"367.0, 220.0, 115.0, 158.0, 196.0, 488.0, 321.0, 174.0, 172.0, 383.0"
166,Attribute 166,float64,0.0,0.0,142.0,"69.0, 78.0, 215.0, 240.0, 144.0, 129.0, 77.0, 260.0, 146.0, 85.0"
167,Attribute 167,float64,0.0,0.0,172.0,"671.0, 510.0, 1013.0, 632.0, 764.0, 578.0, 370.0, 292.0, 183.0, 2209.0"
168,Attribute 168,float64,0.0,0.0,154.0,"188.0, 181.0, 206.0, 626.0, 432.0, 88.0, 239.0, 345.0, 243.0, 246.0"
169,Attribute 169,float64,0.0,0.0,123.0,"57.0, 61.0, 217.0, 116.0, 65.0, 188.0, 111.0, 168.0, 104.0, 58.0"
170,Attribute 170,float64,0.0,0.0,161.0,"178.0, 402.0, 304.0, 405.0, 301.0, 132.0, 257.0, 278.0, 622.0, 409.0"
171,Attribute 171,float64,0.0,0.0,149.0,"383.0, 181.0, 422.0, 117.0, 518.0, 372.0, 170.0, 442.0, 312.0, 190.0"
172,Attribute 172,float64,0.0,0.0,137.0,"246.0, 100.0, 85.0, 263.0, 185.0, 84.0, 67.0, 62.0, 307.0, 104.0"
173,Attribute 173,float64,0.0,0.0,165.0,"206.0, 316.0, 793.0, 239.0, 71.0, 519.0, 399.0, 290.0, 531.0, 205.0"
174,Attribute 174,float64,0.0,0.0,155.0,"370.0, 181.0, 204.0, 380.0, 194.0, 262.0, 192.0, 185.0, 159.0, 103.0"
175,Attribute 175,float64,0.0,0.0,134.0,"205.0, 104.0, 54.0, 89.0, 167.0, 87.0, 68.0, 59.0, 102.0, 187.0"
176,Attribute 176,float64,0.0,0.0,162.0,"354.0, 456.0, 112.0, 249.0, 198.0, 433.0, 234.0, 186.0, 446.0, 519.0"
177,Attribute 177,float64,0.0,0.0,146.0,"166.0, 269.0, 517.0, 171.0, 484.0, 361.0, 300.0, 371.0, 595.0, 145.0"
178,Attribute 178,float64,0.0,0.0,126.0,"99.0, 93.0, 184.0, 53.0, 128.0, 106.0, 132.0, 75.0, 43.0, 182.0"
179,Attribute 179,float64,0.0,0.0,150.0,"150.0, 210.0, 241.0, 374.0, 215.0, 192.0, 191.0, 243.0, 405.0, 279.0"
180,Attribute 180,float64,0.0,0.0,151.0,"158.0, 142.0, 160.0, 251.0, 166.0, 278.0, 143.0, 206.0, 397.0, 351.0"
181,Attribute 181,float64,0.0,0.0,126.0,"71.0, 83.0, 155.0, 129.0, 47.0, 41.0, 110.0, 95.0, 60.0, 167.0"
182,Attribute 182,float64,0.0,0.0,153.0,"219.0, 210.0, 169.0, 152.0, 141.0, 161.0, 147.0, 195.0, 344.0, 130.0"
183,Attribute 183,float64,0.0,0.0,158.0,"369.0, 218.0, 136.0, 381.0, 221.0, 152.0, 252.0, 190.0, 396.0, 163.0"
184,Attribute 184,float64,0.0,0.0,178.0,"346.0, 296.0, 1117.0, 1795.0, 2764.0, 495.0, 1252.0, 2140.0, 478.0, 932.0"

In [6]:
# Numeric Feature Statistics
numeric_stats

                count          mean           std     min       max
Attribute 1     181.0    271.823204    173.239628    42.0     952.0
Attribute 2     181.0    330.320442    162.949471    66.0     709.0
Attribute 3     181.0    154.635359     88.926247    23.0     358.0
Attribute 4     181.0    426.602210    295.474979    57.0    1549.0
Attribute 5     181.0    629.889503    421.679247    99.0    2460.0
Attribute 6     181.0    224.370166    149.471294    28.0     926.0
Attribute 7     181.0    252.767956    152.178555    47.0     721.0
Attribute 8     181.0    415.635359    230.182801    79.0    1157.0
Attribute 9     181.0    242.160221    156.342579    29.0     791.0
Attribute 10    181.0    510.906077    396.665598    52.0    1909.0
Attribute 11    181.0    462.972376    303.582396    65.0    1558.0
Attribute 12    181.0    216.723757    125.059146    29.0     587.0
Attribute 13    181.0    224.414365    131.909226    39.0     593.0
Attribute 14    181.0    432.187845    277.533978    63.0    1270.0
Attribute 15    181.0    264.353591    169.881354    34.0     724.0
Attribute 16    181.0    140.856354     72.040585    26.0     319.0
Attribute 17    181.0    349.917127    209.201707    44.0    1161.0
Attribute 18    181.0    266.629834    146.850949    35.0     591.0
Attribute 19    181.0    120.038674     53.280116    30.0     238.0
Attribute 20    181.0    305.044199    166.658927    67.0     843.0
Attribute 21    181.0    507.751381    446.434877    47.0    3791.0
Attribute 22    181.0    132.044199     69.344937    29.0     295.0
Attribute 23    181.0    266.823204    135.772734    56.0     620.0
Attribute 24    181.0    398.270718    269.288834    39.0    1756.0
Attribute 25    181.0    122.563536     63.021183    20.0     267.0
Attribute 26    181.0    228.994475    120.492116    40.0     530.0
Attribute 27    181.0    559.403315    444.403593    71.0    1982.0
Attribute 28    181.0    177.762431    126.650586    19.0     703.0
Attribute 29    181.0    231.944751    125.176974    46.0     549.0
Attribute 30    181.0    412.519337    225.747317    81.0     978.0
Attribute 31    181.0    199.116022    141.575197    24.0     765.0
Attribute 32    181.0    195.519337    101.802510    35.0     422.0
Attribute 33    181.0    377.773481    200.703093    68.0     888.0
Attribute 34    181.0    248.839779    193.804460    23.0    1379.0
Attribute 35    181.0    220.171271    112.870469    43.0     488.0
Attribute 36    181.0    340.911602    180.249651    74.0     799.0
Attribute 37    181.0    191.640884    127.008741    20.0     780.0
Attribute 38    181.0    180.558011     90.258907    31.0     417.0
Attribute 39    181.0    337.944751    172.016689    65.0     745.0
Attribute 40    181.0    208.403315    136.629295    14.0     872.0
Attribute 41    181.0    196.475138    110.283603    43.0     558.0
Attribute 42    181.0    316.364641    159.886000    60.0     730.0
Attribute 43    181.0    190.370166    113.039280    20.0     473.0
Attribute 44    181.0    152.453039     79.319566    33.0     363.0
Attribute 45    181.0    306.469613    155.089814    53.0     717.0
Attribute 46    181.0    215.149171    139.981963    25.0    1108.0
Attribute 47    181.0    172.127072     95.663359    34.0     522.0
Attribute 48    181.0    330.403315    165.496787    62.0     752.0
Attribute 49    181.0    249.447514    143.804511    33.0    1014.0
Attribute 50    181.0    134.596685     66.792280    34.0     325.0
Attribute 51    181.0    302.176796    151.343655    68.0     664.0
Attribute 52    181.0    238.392265    126.423696    27.0     580.0
Attribute 53    181.0    229.176796    120.764057    45.0     738.0
Attribute 54    181.0    443.359116    253.099735    61.0    1185.0
Attribute 55    181.0    253.491713    135.722782    47.0     694.0
Attribute 56    181.0    146.812155     67.878798    27.0     328.0
Attribute 57    181.0    348.475138    188.550599    53.0     856.0
Attribute 58    181.0    247.237569    134.384208    39.0     662.0
Attribute 59    181.0    138.176796     63.680118    20.0     286.0
Attribute 60    181.0    318.839779    182.667067    51.0     883.0
Attribute 61    181.0    243.116022    126.820182    38.0     607.0
Attribute 62    181.0    112.817680     53.163949    19.0     267.0
Attribute 63    181.0    265.149171    146.453727    52.0     684.0
Attribute 64    181.0    272.027624    169.963997    44.0    1675.0
Attribute 65    181.0    140.353591     74.128918    18.0     361.0
Attribute 66    181.0    294.331492    172.320762    48.0     837.0
Attribute 67    181.0    278.535912    148.515675    41.0     949.0
Attribute 68    181.0    124.138122     63.747747    13.0     290.0
Attribute 69    181.0    247.027624    135.426997    41.0     582.0
Attribute 70    181.0    284.955801    334.215031    44.0    4370.0
Attribute 71    181.0    155.298343     87.506568    24.0     408.0
Attribute 72    181.0    765.823204    703.567301    65.0    3648.0
Attribute 73    181.0    300.740331    201.742751    61.0    1989.0
Attribute 74    181.0    143.187845     77.479016    23.0     338.0
Attribute 75    181.0    541.160221    459.771238    39.0    2286.0
Attribute 76    181.0    335.425414    186.349347    55.0    1298.0
Attribute 77    181.0    521.331492    480.103982    49.0    3109.0
Attribute 78    181.0   7970.651934   9311.143828   362.0   54715.0
Attribute 79    181.0    515.359116    394.916627    56.0    2395.0
Attribute 80    181.0    267.077348    197.407910    29.0    1228.0
Attribute 81    181.0   3521.287293   4103.773163   170.0   26027.0
Attribute 82    181.0    418.696133    285.917784    62.0    1626.0
Attribute 83    181.0    178.198895    115.272162    27.0     562.0
Attribute 84    181.0   1091.977901   1097.884273    77.0    6727.0
Attribute 85    181.0    336.613260    187.568046    49.0     972.0
Attribute 86    181.0    138.370166     77.745961    20.0     370.0
Attribute 87    181.0    369.243094    288.647722    49.0    1655.0
Attribute 88    181.0    342.408840    202.080563    50.0    1006.0
Attribute 89    181.0    146.342541     99.885344    23.0     946.0
Attribute 90    181.0    219.939227    127.500726    41.0     614.0
Attribute 91    181.0    316.226519    161.584029    45.0     668.0
Attribute 92    181.0    133.618785     77.678064    29.0     577.0
Attribute 93    181.0    179.795580     91.940241    31.0     412.0
Attribute 94    181.0    317.806630    153.863616    68.0     672.0
Attribute 95    181.0    129.348066     70.330216    21.0     384.0
Attribute 96    181.0    192.215470     95.674175    39.0     423.0
Attribute 97    181.0    287.817680    141.546203    42.0     644.0
Attribute 98    181.0    126.049724     65.277891    23.0     309.0
Attribute 99    181.0    186.751381     91.730699    34.0     403.0
Attribute 100   181.0    309.541436    158.968357    66.0     664.0
Attribute 101   181.0    152.414365     91.668422    23.0     416.0
Attribute 102   181.0    220.867403    108.122328    36.0     496.0
Attribute 103   181.0    305.038674    150.216043    48.0     674.0
Attribute 104   181.0    139.049724     76.737958    24.0     353.0
Attribute 105   181.0    206.541436    105.325763    39.0     463.0
Attribute 106   181.0    342.950276    183.106140    45.0     848.0
Attribute 107   181.0    195.077348    132.411415    18.0     732.0
Attribute 108   181.0    221.104972    113.151791    38.0     568.0
Attribute 109   181.0    311.436464    157.069385    55.0     687.0
Attribute 110   181.0    167.414365    103.666236    15.0     520.0
Attribute 111   181.0    212.022099    109.828450    47.0     509.0
Attribute 112   181.0    313.541436    155.497284    61.0     719.0
Attribute 113   181.0    151.845304     85.226550    22.0     428.0
Attribute 114   181.0    272.580110    145.520332    49.0     680.0
Attribute 115   181.0    314.955801    170.682773    65.0     845.0
Attribute 116   181.0    134.099448     73.298409    20.0     326.0
Attribute 117   181.0    233.182320    124.862569    42.0     597.0
Attribute 118   181.0    290.972376    149.772399    48.0     731.0
Attribute 119   181.0    180.906077     96.599787    16.0     491.0
Attribute 120   181.0   1356.491713   1091.134230    93.0    6256.0
Attribute 121   181.0    346.099448    207.175854    52.0    1062.0
Attribute 122   181.0    155.464088     83.038713    31.0     362.0
Attribute 123   181.0    728.458564    543.381475    67.0    2991.0
Attribute 124   181.0    336.618785    178.415662    42.0     841.0
Attribute 125   181.0    242.674033    184.670333    37.0    1110.0
Attribute 126   181.0   1916.845304   2513.480212    98.0   17554.0
Attribute 127   181.0    340.215470    199.292256    66.0    1118.0
Attribute 128   181.0    181.762431    119.659349    21.0     665.0
Attribute 129   181.0    912.530387   1093.330851    65.0    7641.0
Attribute 130   181.0    346.928177    177.314254    75.0     898.0
Attribute 131   181.0    166.480663     99.848418    28.0     492.0
Attribute 132   181.0    590.127072    583.213274    51.0    3739.0
Attribute 133   181.0    292.878453    143.356884    48.0     651.0
Attribute 134   181.0    137.480663     75.474911    22.0     352.0
Attribute 135   181.0    329.712707    245.465036    51.0    1464.0
Attribute 136   181.0    285.668508    139.362559    55.0     678.0
Attribute 137   181.0    308.878453    250.344378    31.0    1198.0
Attribute 138   181.0   1996.883978   2218.850279    99.0   10949.0
Attribute 139   181.0    569.237569    396.874587    88.0    2119.0
Attribute 140   181.0    274.939227    215.587110    31.0    1053.0
Attribute 141   181.0   1140.983425   1190.929662    57.0    5772.0
Attribute 142   181.0    390.685083    239.505985    55.0    1235.0
Attribute 143   181.0    231.044199    166.930286    24.0     818.0
Attribute 144   181.0    741.475138    726.080555    57.0    3706.0
Attribute 145   181.0    285.773481    155.608478    46.0     803.0
Attribute 146   181.0    170.541436    108.381757    23.0     546.0
Attribute 147   181.0    405.292818    308.840605    43.0    1477.0
Attribute 148   181.0    248.016575    131.704065    42.0     656.0
Attribute 149   181.0    136.977901     71.831126    27.0     324.0
Attribute 150   181.0    287.530387    168.820336    52.0     793.0
Attribute 151   181.0    238.497238    121.355613    38.0     586.0
Attribute 152   181.0    128.839779     64.487396    23.0     317.0
Attribute 153   181.0    264.767956    141.852511    47.0     621.0
Attribute 154   181.0    232.806630    239.699467    39.0    3095.0
Attribute 155   181.0    128.370166     60.530626    24.0     303.0
Attribute 156   181.0    261.596685    131.577091    49.0     584.0
Attribute 157   181.0    202.513812    138.202292    26.0    1472.0
Attribute 158   181.0    123.215470     57.076878    29.0     281.0
Attribute 159   181.0    267.066298    129.219907    54.0     606.0
Attribute 160   181.0    204.143646    118.514422    30.0     964.0
Attribute 161   181.0    143.972376     70.343240    34.0     358.0
Attribute 162   181.0    285.933702    140.696940    43.0     640.0
Attribute 163   181.0    183.386740     95.098514    24.0     531.0
Attribute 164   181.0    149.662983     72.700926    34.0     350.0
Attribute 165   181.0    284.497238    142.467720    56.0     651.0
Attribute 166   181.0    178.204420    126.237770    23.0    1420.0
Attribute 167   181.0    718.232044    476.225987    72.0    2562.0
Attribute 168   181.0    325.386740    170.610162    54.0     817.0
Attribute 169   181.0    150.950276     90.771341    27.0     836.0
Attribute 170   181.0    418.546961    254.911323    59.0    1302.0
Attribute 171   181.0    328.104972    173.677591    52.0     751.0
Attribute 172   181.0    180.624309    115.408272    24.0     816.0
Attribute 173   181.0    528.154696    424.132564    64.0    2117.0
Attribute 174   181.0    319.834254    164.072528    67.0     741.0
Attribute 175   181.0    150.320442     85.482663    28.0     387.0
Attribute 176   181.0    352.966851    244.184241    47.0    1215.0
Attribute 177   181.0    323.337017    156.173843    56.0     710.0
Attribute 178   181.0    142.878453     80.900121    31.0     659.0
Attribute 179   181.0    359.524862    234.495785    59.0    1107.0
Attribute 180   181.0    296.618785    149.586183    44.0     871.0
Attribute 181   181.0    133.027624     69.629690    23.0     328.0
Attribute 182   181.0    275.685083    160.217128    45.0     778.0
Attribute 183   181.0    276.955801    134.901850    47.0     611.0
Attribute 184   181.0   1177.160221    923.740766   141.0    4676.0
Attribute 185   181.0   2884.928177   2608.330963   151.0   13093.0
Attribute 186   181.0    350.751381    188.813897    49.0     914.0
Attribute 187   181.0    830.977901    625.057188    95.0    3115.0
Attribute 188   181.0   1185.729282   1029.073013    68.0    5172.0
Attribute 189   181.0    280.839779    148.731532    42.0     751.0
Attribute 190   181.0    514.143646    374.885659    53.0    1783.0
Attribute 191   181.0    507.220994    374.231607    59.0    1931.0
Attribute 192   181.0    226.806630    116.660720    29.0     560.0
Attribute 193   181.0    287.917127    192.407377    32.0     963.0
Attribute 194   181.0    306.049724    165.222721    52.0     838.0
Attribute 195   181.0    194.381215    121.723382    22.0    1156.0
Attribute 196   181.0    266.944751    169.072165    37.0     814.0
Attribute 197   181.0    293.773481    145.813003    71.0     662.0
Attribute 198   181.0    175.922652     91.383955    35.0     492.0
Attribute 199   181.0    194.138122    107.984144    32.0     508.0
Attribute 200   181.0    323.618785    242.143973    71.0    2810.0
Attribute 201   181.0    149.143646    102.749487    22.0    1129.0
Attribute 202   181.0    447.795580    289.056487    69.0    1602.0
Attribute 203   181.0    304.204420    181.611084    54.0    1583.0
Attribute 204   181.0    132.066298     69.518151    20.0     432.0
Attribute 205   181.0    292.160221    173.352537    47.0     903.0
Attribute 206   181.0    267.541436    141.915564    35.0     935.0
Attribute 207   181.0    120.674033     62.236813    20.0     397.0
Attribute 208   181.0    236.165746    133.092053    51.0     720.0
Attribute 209   181.0    237.077348    118.922592    31.0     627.0
Attribute 210   181.0    113.591160     53.432083    24.0     252.0
Attribute 211   181.0    209.762431    109.275564    43.0     507.0
Attribute 212   181.0    228.491713    125.239620    40.0     921.0
Attribute 213   181.0    146.784530     75.513303    26.0     453.0
Attribute 214   181.0    232.657459    124.321956    41.0     598.0
Attribute 215   181.0    190.497238     96.669921    30.0     579.0
Attribute 216   181.0    134.082873     65.951487    23.0     344.0
Attribute 217   181.0    237.381215    117.711764    46.0     541.0
Attribute 218   181.0    186.149171    137.050659    29.0    1540.0
Attribute 219   181.0    268.530387    187.870243    50.0    1235.0
Attribute 220   181.0    283.734807    136.057653    49.0     659.0
Attribute 221   181.0    157.464088     94.020418    22.0     824.0
Attribute 222   181.0    209.331492    119.691040    27.0     758.0
Attribute 223   181.0    293.977901    135.664986    60.0     664.0
Attribute 224   181.0    137.486188     75.138140    24.0     481.0
Attribute 225   181.0    199.441989    107.189206    35.0     572.0
Attribute 226   181.0    270.464088    124.631212    49.0     629.0
Attribute 227   181.0    121.563536     59.744945    17.0     273.0
Attribute 228   181.0    215.674033    114.287400    39.0     537.0
Attribute 229   181.0    314.165746    152.232626    50.0     649.0
Attribute 230   181.0    372.795580    249.200426    54.0    1195.0
Attribute 231   181.0    709.209945    584.525487    64.0    3150.0
Attribute 232   181.0    298.154696    147.990008    51.0     686.0
Attribute 233   181.0    334.204420    221.058884    43.0    1040.0
Attribute 234   181.0    367.740331    246.048423    43.0    1352.0
Attribute 235   181.0    226.337017    112.353026    33.0     533.0
Attribute 236   181.0    301.546961    206.050868    34.0     962.0
Attribute 237   181.0    287.441989    154.239112    54.0     753.0
Attribute 238   181.0    178.066298     93.441402    27.0     463.0
Attribute 239   181.0    213.734807    130.134616    24.0     608.0
Attribute 240   181.0    316.055249    153.772080    72.0     680.0
Attribute 241   181.0    156.535912     83.050688    26.0     503.0
Attribute 242   181.0    219.033149    125.384338    40.0     595.0
Attribute 243   181.0    276.817680    135.154582    48.0     677.0
Attribute 244   181.0    120.662983     61.969995    24.0     364.0
Attribute 245   181.0    219.668508    141.494525    36.0     852.0
Attribute 246   181.0    268.563536    137.147903    43.0     632.0
Attribute 247   181.0    141.535912     68.001675    31.0     321.0
Attribute 248   181.0    309.453039    198.103352    51.0    1138.0
Attribute 249   181.0    245.099448    119.991995    41.0     574.0
Attribute 250   181.0    131.193370     62.456751    28.0     308.0
Attribute 251   181.0    246.812155    136.982270    48.0     691.0
Attribute 252   181.0    223.629834    125.139660    33.0    1130.0
Attribute 253   181.0    148.127072     78.768510    24.0     426.0
Attribute 254   181.0    243.872928    123.419926    58.0     582.0
Attribute 255   181.0    181.287293     97.527519    33.0     786.0
Attribute 256   181.0    138.651934     71.820419    35.0     340.0
Attribute 257   181.0    246.994475    115.879223    47.0     565.0
Attribute 258   181.0    138.541436     78.458515    26.0     678.0
Attribute 259   181.0    162.386740     84.864890    31.0     409.0
Attribute 260   181.0    267.116022    126.864025    56.0     615.0
Attribute 261   181.0    113.718232     56.670913    28.0     350.0
Attribute 262   181.0    176.099448     92.393007    42.0     419.0
Attribute 263   181.0    245.685083    118.075518    28.0     571.0
Attribute 264   181.0    128.657459     60.563684    25.0     286.0
Attribute 265   181.0    246.292818    135.903141    39.0     679.0
Attribute 266   181.0    401.850829    275.493224    59.0    1532.0
Attribute 267   181.0    127.790055     61.588059    20.0     315.0
Attribute 268   181.0    241.066298    123.931236    50.0     587.0
Attribute 269   181.0    329.149171    200.459209    42.0    1036.0
Attribute 270   181.0    137.640884     69.557636    29.0     364.0
Attribute 271   181.0    265.530387    129.118272    50.0     578.0
Attribute 272   181.0    195.342541    106.933956    28.0     479.0
Attribute 273   181.0    141.375691     68.457791    31.0     307.0
Attribute 274   181.0    299.569061    139.994174    59.0     647.0
Attribute 275   181.0    141.790055     72.284777    24.0     347.0
Attribute 276   181.0    224.425414    134.749113    43.0     706.0
Attribute 277   181.0    277.635359    123.310942    42.0     586.0
Attribute 278   181.0    119.215470     56.660519    21.0     274.0
Attribute 279   181.0    218.817680    110.595132    40.0     549.0
Attribute 280   181.0    257.082873    203.546333    51.0    2551.0
Attribute 281   181.0    155.806630     75.447709    36.0     403.0
Attribute 282   181.0    248.033149    121.718797    49.0     548.0
Attribute 283   181.0    197.270718    118.627843    38.0    1204.0
Attribute 284   181.0    147.718232     72.296789    26.0     377.0
Attribute 285   181.0    251.342541    124.839959    45.0     543.0
Attribute 286   181.0    140.635359     79.485286    25.0     692.0
Attribute 287   181.0    160.779006     80.121545    19.0     372.0
Attribute 288   181.0    257.160221    128.135309    34.0     543.0
Attribute 289   181.0    112.895028     57.610233    20.0     336.0
Attribute 290   181.0    183.359116     98.284441    31.0     458.0
Attribute 291   181.0    264.342541    141.493399    34.0     929.0
Attribute 292   181.0    127.232044     69.646818    22.0     671.0
Attribute 293   181.0    233.917127    128.317310    47.0     660.0

In [7]:
# Categorical Feature Statistics
cat_stats

               value  count   pct
column    rank
HasCancer 1       No    101  55.8
          2      Yes     80  44.2

In [8]:
# Target Distribution
target_df

           count   pct
HasCancer
No           101  55.8
Yes           80  44.2

## Task Curation

In [9]:
from data_foundry.curation_recommendations import get_recommended_splits_dimensions

n_repeats, n_splits, none_or_test_size = get_recommended_splits_dimensions(
    dataset=df,
    group_on=task_mold.group_on,
    time_on=task_mold.time_on,
)
print(f"Recommended splits: n_repeats={n_repeats}, n_splits={n_splits}, test_size={none_or_test_size}")

Recommended splits: n_repeats=20, n_splits=3, test_size=None

In [10]:
from data_foundry.schema import PredictiveMLSplitsMetadata
from data_foundry import curation_recommendations

splits = curation_recommendations.get_recommended_iid_splits(
    dataset=df,
    n_repeats=n_repeats,
    n_splits=n_splits,
    test_size=none_or_test_size,
    stratify_on=task_mold.stratify_on,
)

splits_mold = PredictiveMLSplitsMetadata(
    splits_comment="Default splits.",
    splits=splits,
)

Using Stratified IID splits.

## Export

In [11]:
from data_foundry.curation_container import CuratedContainer
curated_data = CuratedContainer(
    dataset=df,
    dataset_metadata=dataset_mold,
    task_metadata=task_mold,
    experiment_metadata=splits_mold,
 )
curated_data.save()
print(curated_data.uuid)
print(curated_data.checksum)

Calculating checksum for curated container...
Saving curated container to nci_pancreatic_cancer/019d9d23-4ace-71c9-b3c3-06491168b970
019d9d23-4ace-71c9-b3c3-06491168b970
7dcf4c9d989f18d89e79fd5cb39207664e5bb05a0b1dd6c2fece483bb052ded9